### ISSUE TITLE
Support TLS client authentication

### ISSUE THREAD

**Issue by acabarbaye** [jfrog/jfrog-cli#100]
I was wondering whether it could be possible to implement TLS  client authentication in such a way that client certificate and key could be passed to the CLI or stored in .jfrog/security.
Currently, I think the only way to perform such authentication is to use 'curl --key client.key --cert client.crt' and artifactory REST APIs. It would be great if jfrog CLI could be used instead, especially when used as part of Maven or Gradle Builds.

**Comment by lukasHD** [comment]
I could also benefit from such a change.

**Comment by eyalbe4** [comment]
Thanks for sharing this requirement @acabarbaye and @lukasHD.
A few questions:
1. Currently, with JFrog CLI, if you add the certificate file to the $JFROG_CLI_HOME/security directory, does the CLI authenticate with Artifactory successfully?
2. Can you share some more information about the use case? Why do you need to use different certificates when  running different CLI commands?

**Comment by acabarbaye** [comment]
I can try to elaborate about my use case.
I am using Circle CI as a build system and trying to push artifacts to a local instance of artifactory after every build. To connect to this instance, we have a reverse proxy which requires TLS client authentication. jfrog CLI does not have such a capability at the moment and hence, I have to use Curl and artifactory REST APIs instead.

**Comment by eyalbe4** [comment]
Thanks @acabarbaye.
If you place the certificate in the *~/.jfrog/security* directory, does the CLI manage to authenticate with Artifactory successfully?

**Comment by eyalbe4** [comment]
@acabarbaye,
I'm closing this issue gor now, but do let me know if you need further assistance with this,

**Comment by janbernloehr** [comment]
In our corporate environment we are using user+apikey and _in addition_ client certificates. We would like to use jfro cli but currently have to revert to curl

```
curl --cert ~/path/to/client_cert.pem -H 'X-JFrog-Art-Api: MyApiKey' -O https://file/to/download
```
