### ISSUE TITLE
Unpacking (explode) in non-interactive shell fails due to incorrect path

### ISSUE THREAD

**Issue by Mindavi** [jfrog/jfrog-cli#1002]
**Describe the bug**

I'm trying to download a file (zip archive) from artifactory and let the JFrog CLI unpack it. The JFrog CLI downloads the file successfully, but fails to unpack it (unless I run it again with the archive in place). Since I want to automate it (downloading resources from artifactory), I'm running the CLI from C++ code using the tiny-process-library. When running the CLI interactively, the same steps do seem to succeed.

As can be seen in the logging below, the path that the archive should be extracted to is somehow duplicated:

`[Info] [Thread 2] Extracting archive: C:\Users\example\AppData\Local\Temp\ui4l4f25.y54\windows\deployment\windows\deployment\Server-2016.zip to C:\Users\example\AppData\Local\Temp\ui4l4f25.y54\windows\deployment\`.

It should, as far as my goal was, unpack to `windows/deployment`, and places the zip archive in that folder first. However, it somehow then assumes it placed it in `windows/deployment/windows/deployment`. I don't understand why it would think that's the case.

What's also strange is that when I run the application twice, it will first download and fail to unpack the archive. However, when it's run for the second time, it will detect that the archive is already present, and succeed in unpacking the archive. I think it's checksumming the archive to compare with the server though, so running the tool twice is quite slow (archive is >5GB).

It might be that what I'm trying to do is not supported, but it appears to work ok (for non-zipped files).

**To Reproduce**

Download zip archive from artifactory repository using non-interactive command line usage (e.g. in CI) and try to put it in a directory.

Command lines to reproduce are shown in logging below.

Environment variables set are as follows:

- JFROG_CLI_OFFER_CONFIG: false
- CI: true
- JFROG_CLI_LOG_LEVEL: DEBUG

I did try turning CI off to see if that helps, but it doesn't seem to make any difference.

**Expected behavior**

I expected the CLI to unpack the files in the expected folder, which is given in the command line. I expect the CLI to do this in 1 time, instead of having to deal with a fail first, rerunning and the tool succeeding the second time around.

I expect consistent(ish) behavior between running interactively and non-interactively.

**Logging**

<details><summary>Results with debug logging turned on</summary>

## Request 1

Command line: ./jfrog.exe rt download --url https://artifactory.example.com/artifactory --access-token *** --flat --explode my-artifactory-repo/example/images/windows/Server-2016.zip windows/deployment/

### JFrog output

stdout: {
  "status": "failure",
  "totals": {
    "success": 0,
    "failure": 1
  }
}
stderr: [Debug] Usage Report: Sending info...
[Info] Searching items to download...
[Debug] Searching Artifactory using AQL query:
 items.find({"path":{"$ne":"."},"$or":[{"$and":[{"repo":"my-artifactory-repo","path":"example/images/windows","name":"Server-2016.zip"}]}]}).include("name","repo","path","actual_md5","actual_sha1","size","type","modified","created","property")
[Debug] Sending HTTP POST request to: https://artifactory.example.com/artifactory/api/search/aql
[Debug] Sending HTTP GET request to: https://artifactory.example.com/artifactory/api/system/version
[Debug] Artifactory response:  200 OK
[Debug] Streaming data to file...
[Debug] Finish streaming data successfully.
[Info] [Thread 2] Downloading my-artifactory-repo/example/images/windows/Server-2016.zip
[Debug] Sending HTTP HEAD request to: https://artifactory.example.com/artifactory/my-artifactory-repo/example/images/windows/Server-2016.zip
[Debug] Sending HTTP GET request to: https://artifactory.example.com/artifactory/my-artifactory-repo/example/images/windows/Server-2016.zip
[Debug] Sending HTTP GET request to: https://artifactory.example.com/artifactory/my-artifactory-repo/example/images/windows/Server-2016.zip
[Debug] Sending HTTP GET request to: https://artifactory.example.com/artifactory/my-artifactory-repo/example/images/windows/Server-2016.zip
[Debug] The Artifactory version is: 7.11.5
[Debug] Sending HTTP POST request to: https://artifactory.example.com/artifactory/api/system/usage
[Info] [Thread 2] [1]: 206 Partial Content...
[Info] [Thread 2] [2]: 206 Partial Content...
[Info] [Thread 2] [0]: 206 Partial Content...
[Debug] Usage Report: Artifactory response: 200 OK
[Debug] Usage Report: Usage info sent successfully.
**[Info] [Thread 2] Extracting archive: C:\Users\example\AppData\Local\Temp\ui4l4f25.y54\windows\deployment\windows\deployment\Server-2016.zip to C:\Users\example\AppData\Local\Temp\ui4l4f25.y54\windows\deployment\
[Error] [Thread 2]  Received an error: opening source file: open C:\Users\example\AppData\Local\Temp\ui4l4f25.y54\windows\deployment\windows\deployment\Server-2016.zip: The system cannot find the path specified.
[Error] opening source file: open C:\Users\example\AppData\Local\Temp\ui4l4f25.y54\windows\deployment\windows\deployment\Server-2016.zip: The system cannot find the path specified.**
[Error] Download finished with errors, please review the logs.

exit status: 1

## Request 2

Command line: ./jfrog.exe rt download --url https://artifactory.example.com/artifactory --access-token *** --flat --explode my-artifactory-repo/example/images/windows/Server-2016.zip windows/deployment/

### JFrog output

stdout: {
  "status": "success",
  "totals": {
    "success": 1,
    "failure": 0
  }
}
stderr: [Debug] Usage Report: Sending info...
[Info] Searching items to download...
[Debug] Searching Artifactory using AQL query:
 items.find({"path":{"$ne":"."},"$or":[{"$and":[{"repo":"my-artifactory-repo","path":"example/images/windows","name":"Server-2016.zip"}]}]}).include("name","repo","path","actual_md5","actual_sha1","size","type","modified","created","property")
[Debug] Sending HTTP POST request to: https://artifactory.example.com/artifactory/api/search/aql
[Debug] Sending HTTP GET request to: https://artifactory.example.com/artifactory/api/system/version
[Debug] Artifactory response:  200 OK
[Debug] Streaming data to file...
[Debug] Finish streaming data successfully.
[Info] [Thread 2] Downloading my-artifactory-repo/example/images/windows/Server-2016.zip
[Debug] The Artifactory version is: 7.11.5
[Debug] Sending HTTP POST request to: https://artifactory.example.com/artifactory/api/system/usage
[Debug] Usage Report: Artifactory response: 200 OK
[Debug] Usage Report: Usage info sent successfully.
[Debug] [Thread 2]  File already exists locally.
[Info] [Thread 2] Extracting archive: C:\Users\example\AppData\Local\Temp\ui4l4f25.y54\windows\deployment\Server-2016.zip to C:\Users\example\AppData\Local\Temp\ui4l4f25.y54\windows\deployment\
[Debug] Downloaded 1 artifacts.

exit status: 0

</details>

**Versions**
- JFrog CLI version: 1.44.0
- JFrog CLI operating system: Windows 10 Enterprise, 10.0.17763 Build 17763
- Artifactory Version: CommercialX license 7.11.5 rev 71105900

**Comment by ZeroMotorcyclesEugeneS** [comment]
I see same issue. Definitely would be nice to have it fixed.

**Comment by Mindavi** [comment]
I made a dev build and this issue is fixed using the latest dev branch.

Can be closed when new version is released (or now, whatever is preferred).

**Comment by eyalbe4** [comment]
Thanks for letting us know this issue is fixed in the dev branch @Mindavi. Version 1.46.1 may also include it.

**Comment by ZeroMotorcyclesEugeneS** [comment]
It seems like it is not included in 1.46.1. When is next release?

**Comment by RudiMT** [comment]
Setting --min-split=-1 worked for us

**Comment by eyalbe4** [comment]
This fix is released with version 1.46.2 of JFrog CLI. 
We'd appreciate your feedback for it.

**Comment by RudiMT** [comment]
@eyalbe4 1.46.2 works, only remaining corner case is when --spec-vars=D:/my/path/ *with a trailing (forward) slash*  is used, producing a `//` in the file, and --min-split=5120 is smaller than the largest of the ZIP files.
```
[Debug] Replacing '${location}' with 'd:/try001/'
[Debug] The reformatted content is:
{
  "files": [
    {
      "pattern": "generic-local/02-Externals/01-Libs/FileSize10000k.zip",
      "target": "d:/try001//02-Externals/01-Libs/",
      "flat": "true",
      "explode": "true"
    },
...
```

As before, --min-split=-1 works in this case.

**Comment by Mindavi** [comment]
Thanks for solving this! I confirmed this now works as expected in 1.46.3.

@RudiMT I think it's better to open a new issue for that particular use case.
