### ISSUE TITLE
Regression in jfrog config add in 1.45.1

### ISSUE THREAD

**Issue by tanguydelignieresaccenture** [jfrog/jfrog-cli#1004]
**Describe the bug**
Regression in the last jfrog-cli version (1.45.1) running `config add` command.

**To Reproduce**
```shell
$ curl -fL https://getcli.jfrog.io | sh
...
Downloading the latest version of JFrog CLI...
...

$ ./jfrog config add --artifactory-url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USERNAME --password=$ARTIFACTORY_TOKEN --interactive=false
./jfrog: line 5: syntax error near unexpected token `]'
./jfrog: line 5: ` }​ ]'
```

**Expected behavior**
```shell
$ curl -fL https://getcli.jfrog.io | sh
...
Downloading the latest version of JFrog CLI...
...
$ ./jfrog config add --artifactory-url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USERNAME --password=$ARTIFACTORY_TOKEN --interactive=false
[Info] Encrypting password...
```

**Screenshots**
N/A

**Versions**
- JFrog CLI version: 1.45.1
- JFrog CLI operating system: linux amd64
- Artifactory Version: 7.11.5 rev 71105900

**Additional context**
No problem with previous version `1.45.0`:
```shell
$ curl -fL https://getcli.jfrog.io | sh -s 1.45.0
...
Downloading version 1.45.0 of JFrog CLI...
...
$ ./jfrog config add --artifactory-url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USERNAME --password=$ARTIFACTORY_TOKEN --interactive=false
[Info] Encrypting password...
```

**Comment by eyalbe4** [comment]
Thanks for reporting this @tanguydelignieresaccenture!
We're working on resolving this now.
I'll share an update here soon.

**Comment by amalucelli** [comment]
In case this blocks any CircleCI workflow/job, I opened this PR in the official orb allowing a version to be installed instead of always using the latest one: https://github.com/jfrog/artifactory-orb/pull/9

**Comment by eyalbe4** [comment]
All - the issue should be resolved now.
We're terribly sorry for the inconvenience caused by this issue.

**Comment by tanguydelignieresaccenture** [comment]
Thanks for your reactivity.
So did you released a new version or fixed the 1.45.1 one?

**Comment by eyalbe4** [comment]
@tanguydelignieresaccenture,
We didn't need to release a new JFrog CLI version. The root cause of the issue wasn't in the code of JFrog CLI.
The cUrl installation uses a bash script, which downloads the JFrog CLI binary from a repository hosted on http://releases.jfrog.io/artifactory
Due to a configuration issue on that server, the download of the latest release failed. We fixed the config issue, which seems to have resolved the issue.
Thanks again for reporting the issue.

**Comment by tanguydelignieresaccenture** [comment]
Thanks for the explanation, you're welcome .

**Comment by tanguydelignieresaccenture** [comment]
Fix confirm, closing the issue.
Thanks
