### ISSUE TITLE
Where to pull CLI image from after bintray sunset?

### ISSUE THREAD

**Issue by rittneje** [jfrog/jfrog-cli#1006]
According to https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ bintray will be taken down on May 1. However, your README still says to download the CLI docker image from bintray. https://github.com/jfrog/jfrog-cli#using-jfrog-cli-docker-image Is there somewhere else we should be pulling from?

**Comment by eyalbe4** [comment]
Sure @rittneje,

The README and the [Get CLI](https://jfrog.com/getcli/) pages will be soon updated with the new docker images. See below. 

In addition to the "slim" JFrog CLI docker image, which includes only JFrog CLI, we added a new "full" docker image. The new image includes, in addition to JFrog CLI, all the tools and package managers JFrog CLI supports, such as curl, maven, gradle, npm, pip, and more.
Here's how you fetch the images - 
```
docker run releases-docker.jfrog.io/jfrog/jfrog-cli jfrog -v

docker run releases-docker.jfrog.io/jfrog/jfrog-cli-full jfrog -v
```
Please let me know if this helps.

**Comment by rittneje** [comment]
Perfect, thanks!
