### ISSUE TITLE
jfrog rt dotnet restore frequently and inconsistently fails with nuget.org connection timeout.

### ISSUE THREAD

**Issue by ri-paul** [jfrog/jfrog-cli#1011]
**Describe the bug**
When running jfrog rt dotnet restore from GHA or developer machine frequently fails with `error : The feed 'JFrogCli [https://***.jfrog.io/***/api/nuget/***]' lists package 'package' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again. `

**To Reproduce**
Unable to provide code to reproduce as we experience this as part of our Cloud Artifactory setup. Our configuration is:
* A local nuget repository - default configuration
* A remote nuget repository - default configuration pointing to nuget.org
* A virtual nuget repository that includes the above two repositories
* All repos set for private (auth) access

When running the following in GHA
```
jfrog rt dotnet-config --repo-resolve "${{ env.NUGET_JFROG_REPO }}" --server-id-resolve "${{ secrets.JFROG_SERVER }}"
jfrog rt dotnet restore $SLN_NAME
```
Consistently fails with the following error (although not always the same package)
```
Error : The feed 'JFrogCli [https://***.jfrog.io/***/api/nuget/***]' lists package 'Microsoft.AspNetCore.Hosting.2.2.7' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again. 
```

Artifactory Service Log shows (sample - multiple timeout exceptions present):
`2021-03-16T08:26:10.648Z [jfrt ] [WARN ] [e6edd6ff677f9b80] [o.a.r.RemoteRepoBase:505      ] [p-nio-8081-exec-5788] - nuget-remote: Error in getting information for 'System.Reflection.Metadata.1.6.0.nupkg' (Failed retrieving resource from https://www.nuget.org/api/v2/package/System.Reflection.Metadata/1.6.0: Connect to globalcdn.nuget.org:443 [globalcdn.nuget.org/152.199.23.209] failed: connect timed out).`

Artifactory Request Log shows 404:
`2021-03-16T08:26:10.649Z|***|20.186.104.***|***-user|GET|/api/nuget/***/Download/System.Reflection.Metadata/1.6.0|404|-1|0|30842|NuGet .NET Core MSBuild Task/5.7.0 (Linux 5.4.0-1040-azure #42-Ubuntu SMP Fri Feb 5 15:39:06 UTC 2021)`

Have also experimented with remote caching on/off and increased socket timeout to 60000ms, no change in outcome.

`dotnet restore` works as expected in GHA and on developer machine.

**Expected behavior**
`jfrog rt dotnet restore` to complete without error.

**Screenshots**

**Versions**
- JFrog CLI version: 1.39.7 (from jfrog/setup-jfrog-cli@v1)
- JFrog CLI operating system: Ubuntu 20.04.2 LTS
- Artifactory Version: Cloud / SaaS Artifactory 

**Additional context**

**Comment by eyalbe4** [comment]
@ri-paul,
Thanks for reporting this issue and for the detailed description.
For the information you provided, it looks like the root cause of the issue lies on the cloud server side and not in JFrog CLI's code base. The fact this issue occurs inconsistently and frequently, leads us to believe that it is best to get JFrog Support involved, so that they can investigate the issue.
I suggest you open a ticket with JFrog Support and also share with them this GitHub issue.

**Comment by ri-paul** [comment]
Thank you @eyalbe4, I have reported it here because `dotnet restore` pointing at the same repo on the same Artifactory server works/succeeds consistently. 

I must say that I'm at a loss to explain the issue myself. Happy to take this up with JFrog Support and report back if there are any relevant findings.

**Comment by ri-paul** [comment]
The suggestion from support is to alter some configurations to use nuget-v3 (which has a better CDN apparently). Logs indicate that nuget-v2 is being used. Our Artifactory nuget remotes are all v3 compatible, so that points at the client config being incorrect. I have used the basic `jfrog rt dotnet config` method, I need to inspect configs to understand further the differences between `nuget config` and `jfrog rt dotnet config`.

Can anyone point me towards where  `jfrog rt dotnet config` stores the config file?

**Comment by ri-paul** [comment]
Further update, not resolved, CLI issue:

I have spoken with jfrog support and followed instructions to ensure that my nuget repos allow v3 nuget protocol (which it was, so no config changes).

*Testing With dotnet Client*
I have configured the `dotnet nuget` and `nuget` cli to to use v3 and tested. I can confirm that this works correctly. Logs show the v3 endpoint being used - this confirms that artifactory cloud is configured correctly:

```
OK https://***.jfrog.io/artifactory/api/nuget/v3/***/registration-semver2/Download/system.windows.extensions/4.7.0 880ms
GET https://***.jfrog.io/artifactory/api/nuget/v3/***/registration-semver2/system.drawing.common/index.json
OK https://***.jfrog.io/artifactory/api/nuget/v3/***/registration-semver2/system.drawing.common/index.json 800ms
```

For jfrog cli, I want to ensure that the jfrog cli config uses the v3 feeds. I configure jfrog cli as follows, using the same virtual repo as used in the above example:

```
# configure jfrog cli
jfrog rt c --apikey "myapikey" --user "me@tld.com" --interactive=false --url "https://***.jfrog.io/artifactory" myServer
# configure dotnet resolver
jfrog rt dotnetc --repo-resolve "***" --server-id-resolve myServer
# perform restore with verbose logging
jfrog rt dotnet restore -v d
```

inspecting the logs, I can see the temporary config file that jfrog produces:
```
Build started 29/03/2021 19:35:59.
     0>Process = "/usr/local/share/dotnet/dotnet"
       MSBuild executable path = "/usr/local/share/dotnet/sdk/3.1.301/MSBuild.dll"
       Command line arguments = "/usr/local/share/dotnet/sdk/3.1.301/MSBuild.dll -maxcpucount -verbosity:m -nologo -target:Restore -verbosity:d -property:RestoreConfigFile=/var/folders/f7/jhs_nlp55xx9yssp3bmwmn6c0000gn/T/jfrog.cli.temp.-1617006958-411042117/jfrog.cli.nuget.811985376 -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/usr/local/share/dotnet/sdk/3.1.301/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/usr/local/share/dotnet/sdk/3.1.301/dotnet.dll"```

inspecting the config file 
```
cat /var/folders/f7/jhs_nlp55xx9yssp3bmwmn6c0000gn/T/jfrog.cli.temp.-1617006958-411042117/jfrog.cli.nuget.811985376
```

yields an incorrect v2 config
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="JFrogCli" value="https://***.jfrog.io/artifactory/api/nuget/***" />
  </packageSources>
  <packageSourceCredentials>
    <JFrogCli>
      <add key="Username" value="me@tld" />
      <add key="ClearTextPassword" value="myapikey" />
    </JFrogCli>
  </packageSourceCredentials>
</configuration>```


the *correct* configuration should look like this, wit a v3 url and the protocolVersion specified:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="JFrogCli" value="https://***.jfrog.io/artifactory/api/nuget/v3/***" protocolVersion="3"/>
  </packageSources>
  <packageSourceCredentials>
    <JFrogCli>
      <add key="Username" value="me@tld" />
      <add key="ClearTextPassword" value="myapikey" />
    </JFrogCli>
  </packageSourceCredentials>
</configuration>```


From this, I suspect that the parsing of the `.jfrog/projects/dotnet.yaml` and the jfrog config file is yielding a 'v2 by default' config file. 

I haven't had the time to look at the cli code as yet. Can anyone tell me if I'm missing anything? The docs certainly seem to suggest that jfrog-cli is nuget-v3 by default [see --nuget-v2 flag](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-BuildingNuGetPackages)

**Comment by ri-paul** [comment]
@eyalbe4 - I have done further digging on the construction of the nuget file and I believe I've found the issue.

In https://github.com/jfrog/jfrog-cli-core/blob/636772089d4406cebcab7e0580b7b5acfe0fd83e/artifactory/commands/dotnet/dotnetcommand.go#L260, the code builds the source url, taking account of a v3 (default) or v2 nuget feed set via flag. This part works well, but an additional attribute is required for a v3 feed in the nuget source spec, and that is the protocolVersion. It isn't enough just to set the correct sourceUrl. 

The difficulty here is that the native nuget cli (first branch in code below) doesn't support specifying protocolVersion. The config file has to be edited after the fact. As such it may be better to remove the 'nuget cli' branch, and inject the protocolVersion into code using a formatted string. Modifying the constant dotnet.ConfigFileFormat to explicitly include the protocol version string, then setting it to 2 or 3 depending on the dc.useNugetV2 value. 

```
	if dc.useNugetAddSource {
		err = dc.AddNugetAuthToConfig(dc.toolchainType, configFile, sourceUrl, user, password)
	} else {
		_, err = fmt.Fprintf(configFile, dotnet.ConfigFileFormat, sourceUrl, user, password)
	}
```

**Comment by ri-paul** [comment]
Cross posting issue to jfrog-cli-core repo and closing this issue.
