### ISSUE TITLE
jfrog rt ping can't recognize --url

### ISSUE THREAD

**Issue by akunszt** [jfrog/jfrog-cli#1017]
In the latest version `1.45.2` at the moment the `jfrog rt ping` can't recognize the `--url` option in the command line.

```
~ # docker run --rm -it --net host releases-docker.jfrog.io/jfrog/jfrog-cli-go:1.45.2 jfrog rt ping --url http://127.0.0.1:8081/artifactory
[Error] the --url option is mandatory
```

This regression was introduced in `1.45.0`.
```
~ # docker run --rm -it --net host releases-docker.jfrog.io/jfrog/jfrog-cli-go:1.44.0 jfrog rt ping --url http://127.0.0.1:8081/artifactory
OK
~ # docker run --rm -it --net host releases-docker.jfrog.io/jfrog/jfrog-cli-go:1.45.0 jfrog rt ping --url http://127.0.0.1:8081/artifactory
[Error] the --url option is mandatory
```

**Comment by yahavi** [comment]
@akunszt,
Thanks for reporting this issue! We created #1018 to resolve this issue.
We'll keep you updated.

**Comment by wichert** [comment]
This impacts other commands as well, for example download:

```
❯ jfrog rt dl --url https://artifactory-example.com/ /repo/some-file /usr/local/bin/some-file
[Error] the --url option is mandatory
```

**Comment by yahavi** [comment]
@wichert,
Thanks for the information. 
The fix should resolve the issue for all anonymous access commands that include the `--url` flag.

**Comment by yahavi** [comment]
@akunszt @wichert 
JFrog CLI 1.46.1 is released. This version includes a fix for this issue.
We'd appreciate your feedback on that.

**Comment by akunszt** [comment]
@yahavi Thanks, I can confirm that it's working now for me.
