### ISSUE TITLE
Setting properties on folders using --include-dirs and --recursive not working

### ISSUE THREAD

**Issue by akashkrkashyap** [jfrog/jfrog-cli#1019]
**Describe the bug**
We have a folder in the artifactory and few files inside it. When we are trying to add a property recursively it is only adding the property inside to the root folder and not the subfolders/files. 

**To Reproduce**
Example: https://artifactory.*****:4**/artifactory/example-artifacts/builds/app/test/378
Inside this folder, we have two files.

I am running the below command to update the property.
./jfrog.exe rt sp "example-artifacts/builds/app/test/378" "Version=PROMOTION_READY" --recursive --include-dirs=true

**Expected behavior**
example-artifacts/builds/app/test/378 should have the property as Version=PROMOTION_READY and also the subfolders and files. 
But only the parent folder i.e. example-artifacts/builds/app/test/378 has the property. 

**Versions**
- JFrog CLI version: jfrog version 1.41.1
- JFrog CLI operating system: Windows 10 Enterprise 64 Bit
- artifactory.version=7.7.3

**Additional context**
If I am adding extra "/" after the main folder it is creating the property to the subfolders and files as well. 

Hence to make it work I have to run the command 2 times i.e. one with / and one without /. 
Example: 
./jfrog.exe rt sp "example-artifacts/builds/app/test/378" "Version=PROMOTION_READY" --recursive --include-dirs=true

./jfrog.exe rt sp "example-artifacts/builds/app/test/378/" "Version=PROMOTION_READY" --recursive --include-dirs=true

**Comment by talarian1** [comment]
Hi,
This behavior is consist with other CLI commands like the following search command:
`jfrog rt s "example-artifacts/builds/app/test/378" --recursive=true --include-dirs`
that returns a single result (the directory itself).
Adding a "/" will apply the command(s) on the folder content.
You may use a file spec in order to avoid 2 separate commands.
Please see the following [thread](https://github.com/jfrog/jfrog-cli/issues/887#event-4036033440).

**Comment by talarian1** [comment]
Sorry for closing this.
Please let me know what you think.

**Comment by akashkrkashyap** [comment]
This worked. 
 jfrog rt s "example-artifacts/builds/app/test/378*" --recursive=true --include-dirs
Thanks for the info. I believe this info should be updated to the official documentation.
