### ISSUE TITLE
npm: ENOWORKSPACES error

### ISSUE THREAD

**Issue by cyberox** [jfrog/jfrog-cli#1030]
**Describe the bug**
After upgrading the npm package from 7.6.3 to 7.7.0, the command `jfrog rt npm-install` is erroring with the error: 
```
npm ERR! code ENOWORKSPACES
npm ERR! This command does not support workspaces.
```

**To Reproduce**
Upgrade npm to version 7.7.0 or later

**Expected behavior**
install package dependencies

**Screenshots**

**Versions**
- JFrog CLI version: 1.45.2
- JFrog CLI operating system: MacOS 10.15
- Artifactory Version: hosted

**Comment by gerrnot** [comment]
same issue, pump!

**Comment by Mazorius** [comment]
I am looking forward to the release with this fix.
Thanks in advance!

**Comment by asafgabai** [comment]
@cyberox
Thanks for reporting this issue.
We're on it!

**Comment by asafgabai** [comment]
@cyberox
Fixed and released in JFrog CLI 1.46.4.
Please let us know if you still face the issue after updating.

**Comment by Mazorius** [comment]
Create a PR in [homebrew-core](https://github.com/Homebrew/homebrew-core/pull/75489) to upgrade JFrog CLI.

**Comment by Mazorius** [comment]
PR was merged. I upgraded the CLI locally.
No I do not face the issue anymore.

Thanks for the fix!

**Comment by eyalbe4** [comment]
Thanks for confirming @Mazorius!
