### ISSUE TITLE
Provide a fish completion

### ISSUE THREAD

**Issue by Mazorius** [jfrog/jfrog-cli#1059]
**Is your feature request related to a problem? Please describe.**

I really like to have a cli completion for JFrog to not check the manual,  every time.

**Describe the solution you'd like to see**

Add in addition to the bash and zsh a fish completion file.

**Describe alternatives you've considered**

—

**Additional context**

I am using macOS BigSur together with homebrew.
I using the fish shell as shell environment and using for the ProX variant the JFrog CLI for integration.

**Comment by yahavi** [comment]
@Mazorius 
JFrog CLI 2.9.0 includes the fish completion.
Installation is straightforward:
```sh
jf completion fish
```
We'd appreciate your feedback on that.
