### ISSUE TITLE
jfrog.exe rt download can crash when --min-split is smaller than the largest ZIP file

### ISSUE THREAD

**Issue by RudiMT** [jfrog/jfrog-cli#1060]
After jfrog.exe 1.46.2 fixed most of #1002, only remaining corner case is when --spec-vars=D:/my/path/ *with a trailing (forward) slash*  is used, producing a `//` in the file, and --min-split=5120 is *smaller* than the largest of the ZIP files. This cannot always be controlled by the end user.

`jfrog1.46.2-dev.exe rt dl --spec=D:/try001/repro.json --spec-vars="location=d:/try001/" --min-split=5120`
```
[Debug] Replacing '${location}' with 'd:/try001/'
[Debug] The reformatted content is:
{
  "files": [
    {
      "pattern": "generic-local/02-Externals/01-Libs/FileSize10000k.zip",
      "target": "d:/try001//02-Externals/01-Libs/",
      "flat": "true",
      "explode": "true"
    },
...
```

Setting --min-split=-1 (or --min-split=11000, which is larger than file FileSize10000k.zip in the example) works in this case.

_Originally posted by @RudiMT in https://github.com/jfrog/jfrog-cli/issues/1002#issuecomment-820960267_

**Comment by RudiMT** [comment]
#1002, new issue as suggested by @Mindavi

**Comment by asafgabai** [comment]
Hi @RudiMT,
Thanks for reporting this issue.
I opened a PR for fixing this [here](https://github.com/jfrog/jfrog-client-go/pull/399), and it'll be released soon.

**Comment by asafgabai** [comment]
@RudiMT
JFrog CLI 2.2.0 and 1.51.0 are released and include this fix.
We'd appreciate your feedback for it.

**Comment by RudiMT** [comment]
We looked at 1.51.0 and it works.
