### ISSUE TITLE
`jfrog config` does not replace `jfrog rt config`

### ISSUE THREAD

**Issue by rmm5t** [jfrog/jfrog-cli#1062]
**Describe the bug**
`jfrog rt config` was deprecated in favor of `jfrog config add`; however, `jfrog config add` does not replace `jfrog rt config` competely.

**To Reproduce**
Using the same credentials, the two configuration options yield different results:

```
$ jfrog rt config --url="${ARTIFACTORY_URL}" --user="${ARTIFACTORY_USER}" --password="${ARTIFACTORY_PASSWORD}" Default-Server
[Warn] The "jfrog rt config" command is deprecated. Please use "jfrog config" command instead. You can use it as follows:
	The command includes the following sub-commands - "jfrog config add", "jfrog config edit", "jfrog config show", "jfrog config remove", "jfrog config import" and "jfrog config export".
	Important: When switching to the new command, please replace "--url" with "--artifactory-url".
	For example:
	Old syntax: "jfrog rt config <server-id> --url=<artifactoryUrl>"
	New syntax: "jfrog config add <server-id> --artifactory-url=<artifactory-url>"
```

```
$ jfrog config add --artifactory-url="${ARTIFACTORY_URL}" --user="${ARTIFACTORY_USER}" --password="${ARTIFACTORY_PASSWORD}" Default-Server
[Error] The following error was received while trying to encrypt your password: Artifactory response: 401 Unauthorized 
```

**Expected behavior**
`jfrog config add` should have the same outcome as `jfrog rt config` given the same inputs.

**Versions**
- JFrog CLI version: jfrog version 1.46.4
- JFrog CLI operating system: all
- Artifactory Version: Enterprise license 7.10.2 rev

**Additional context**
The user in this scenario appears to be restricted from traditional login, but was setup for use in our CI environments for the purpose of publishing artifacts to artifactory. The user was capable of publishing artifacts using the old artifactory bitbucket pipes and can utilize `jfrog rt config` but cannot utilize `jfrog config`.

**Comment by yahavi** [comment]
@rmm5t 
Thanks for reporting this issue.

We couldn't reproduce this issue:
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/11367982/115585276-21470100-a2d4-11eb-8d92-ddf11391b958.png">

Can you please run the command with `JFROG_CLI_LOG_LEVEL=DEBUG` environment variable and share the results?

**Comment by rmm5t** [comment]
We now have it working. Our artifactory team had been mucking around with the accounts, and I can no longer reproduce the issue myself either. ¯\\\_(ツ)\_/¯
