### ISSUE TITLE
Sunset of bintray.com and  build-info-extractor-gradle plugin

### ISSUE THREAD

**Issue by pniederlag** [jfrog/jfrog-cli#1067]
We are using the jfrog cli as wrapper in our build-process to integrate with our in-house licensed artifactory server.

We have seen an outage yesterday for our gradle builds:

```
+ jfrog rt gradle build
[Info] Downloading bintray/jcenter/org/jfrog/buildinfo/build-info-extractor-gradle/4.18.0/build-info-extractor-gradle-4.18.0-uber.jar
[Error] 403 Forbidden 
```

We assume this is related to the announced sunsetting of bintray-services https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

What do we have to do in order to make the jfrog-cli fetch the plugin from the proper location?

```
jfrog rt gradle --use-wrapper true --uses-plugin false
```

**Comment by RobiNino** [comment]
Hi @pniederlag ,
What version of the CLI are you using?
As of version 1.46.0, the extractors should be downloaded from [https://oss.jfrog.org/artifactory/](https://oss.jfrog.org/artifactory/) by default.
If you are using the extractors environment variables, see their replacements [here](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-DownloadingtheMavenandGradleExtractorJARs).
Thanks

**Comment by pniederlag** [comment]
@RobiNino thx for your feedback, didn't spot this on the changelog. We have now updated and the plugin is fetched from the mentioned site. Thx for your help.
