### ISSUE TITLE
Poor handling of absolute windows paths in jfrog rt dl command 

### ISSUE THREAD

**Issue by testworksau** [jfrog/jfrog-cli#1072]
**Describe the bug**
On Windows, when specifying an absolute directory as the target pattern, the jfrog CLI attempts to call mkdir and fails, unless the path is specified in a Unix style format. 

The documentation for the CLI makes no mention of the need to supply paths in Unix style format so the expectation is that regular Windows path formats should just work.

**To Reproduce**
These will cause an issue:
```
jfrog rt dl --server-id=artifactory "my-repo/Python/" "D:\Temp\folder\python\"
jfrog rt dl --server-id=artifactory "my-repo/Python/" "D:\\Temp\\folder\\python\\"
```

When the download fails, the log file shows something like this:

```
[Info] Searching items to download...
[Info] [Thread 1] Downloading my-repo/Python/python-3.6.8.exe
[Info] [Thread 2] Downloading my-repo/Python/python-3.6.8-amd64.exe
[Info] [Thread 0] Downloading my-repo/Python/python-3.7.9-amd64.exe
[Info] [Thread 0] [0]: 206 Partial Content...
[Info] [Thread 2] [2]: 206 Partial Content...
[Info] [Thread 1] [1]: 206 Partial Content...
[Info] [Thread 0] [2]: 206 Partial Content...
[Info] [Thread 1] [0]: 206 Partial Content...
[Info] [Thread 1] [2]: 206 Partial Content...
[Info] [Thread 2] [0]: 206 Partial Content...
[Info] [Thread 2] [1]: 206 Partial Content...
[Info] [Thread 0] [1]: 206 Partial Content...
[Error] [Thread 0]  Received an error: mkdir D:: The system cannot find the path specified.
[Info] [Thread 0] Downloading my-repo/Python/python-3.7.9.exe
[Info] [Thread 0] [1]: 206 Partial Content...
[Info] [Thread 0] [2]: 206 Partial Content...
[Info] [Thread 0] [0]: 206 Partial Content...
[Error] [Thread 1]  Received an error: mkdir D:: The system cannot find the path specified.
[Info] [Thread 1] Downloading my-repo/Python/python-3.8.7-amd64.exe
[Info] [Thread 1] [0]: 206 Partial Content...
```

This target path format works:
```
jfrog rt dl --server-id=artifactory "my-repo/Python/" "/D/Temp/folder/python/"
```

**Expected behavior**
Ideally, the folders should be created and the download should succeed.
Alternatively, appropriate documentation and an error message about the target pattern requirements (and please - not hidden in a log file) would be useful.

**Versions**
- JFrog CLI version: 1.47.1
- JFrog CLI operating system: Windows 10
- Artifactory Version: 6.20.0

**Comment by sverdlov93** [comment]
Thanks for reporting this @testworksau.
So about , he first line you wrote :
`jfrog rt dl --server-id=artifactory "my-repo/Python/" "D:\Temp\folder\python\"`
It's not working on windows because the trailing backslash is escaping, so the cli turns D:\Temp\folder\python\"` to D:\Temp\folder\python".

You can use :
- "D:\Temp\folder\python\\"  (with double \ )
- D:\Temp\folder\python\       (without "" around the target)

About the second line : 
`jfrog rt dl --server-id=artifactory "my-repo/Python/" "D:\\Temp\\folder\\python\\"`
It works fine on my cli so maybe tell me more details.

**Comment by testworksau** [comment]
Hi @sverdlov93 - embarrassingly, it appears I'm a victim of my own context switching.

I was working on a machine that had a D:\ drive, and copied and used the command not remembering my new laptop has no D:\ drive. 

The reason this command worked:
`jfrog rt dl --server-id=artifactory "my-repo/Python/" "/D/Temp/folder/python/"`

was because it created a folder named `D` in my `C` drive 🤦🏼 

As you correctly pointed out, the second command works fine for me when using the correct drive letter. Sorry for wasting your time here.
