### ISSUE TITLE
jfrog rt u --ant --exclusions does not include directories, even with --include-dirs flag

### ISSUE THREAD

**Issue by sophietait** [jfrog/jfrog-cli#1076]
**Describe the bug**
When running a `jfrog rt u` command with the `--ant --exclusions` and `--include-dirs` flags, directories are not excluded even if they meet the exclusion ANT pattern.

**To Reproduce**
I created the `days` directory with the following structure:
```
days
  └── monday
	├──monday.txt
	└── tuesday
	    ├──tuesday.txt
	    └── wednesday
 		  └──wednesday.txt
```
I tested the `jfrog rt u` command to collect all files located under the `days/monday` directory, excluding the `**/tuesday/**` ANT pattern, including directories, and upload them to the `test-local` repository in the `days.zip` file. This command uploaded the `days/monday` directory, excluding the `tuesday.txt` file in the `tuesday` directory based on the exclude pattern. However, the `tuesday `directory was included and its contents even though directories were included. 

```
sophiet-mac:jfrog-cli sophiet$ ./jfrog rt u "**/days/monday/" test-local/days.zip --flat=false --ant --archive=zip --exclusions="**/tuesday/**" --include-dirs=true
 Log path: /Users/sophiet/.jfrog/logs/jfrog-cli.2021-05-07.08-49-24.67385.log
{
  "status": "success",
  "totals": {
    "success": 1,
    "failure": 0
  }
}
```

**Expected behavior**
According to [ant.apache.org](https://ant.apache.org/manual/dirtasks.html), 
`**/test/**	Matches all files that have a test element in their path, including test as a filename.`

Therefore, the `tuesday` directory matches the ANT pattern and should be excluded.

**Screenshots**
![Screen Shot 2021-05-07 at 8 49 41 AM](https://user-images.githubusercontent.com/16872799/117718056-728a3800-b190-11eb-8493-bdf03f05a4f7.png)

**Versions**
- JFrog CLI version: 1.47.2
- JFrog CLI operating system: Mac OS
- Artifactory Version: 6.20.0

**Comment by gailazar300** [comment]
Thanks for reporting this! @sophietait 
Pull request for fixing this issue:
https://github.com/jfrog/jfrog-client-go/pull/348

**Comment by gailazar300** [comment]
@sophietait 
JFrog CLI 1.47.3 is now released and includes this fix.
We'd appreciate your feedback for it.
