### ISSUE TITLE
Show progress bar 

### ISSUE THREAD

**Issue by kucabpet** [jfrog/jfrog-cli#112]
It would be good show some progress bar during upload/download/copy files etc.

**Comment by eyalbe4** [comment]
@kucabpet,
JFrog CLI 1.26.0 has been released and includes a progress bar for the *jfrog rt upload* and *jfrog rt download* commands.

**Comment by zork456** [comment]
Can you please tell me what the command to show the progress bar is for jfrog rt download? I couldn't find it in the jfrog documentation.

**Comment by eyalbe4** [comment]
@zork456,
The `jf rt download` command displays a progress bar if the `CI` environment variable isn't set to `true`.

**Comment by zork456** [comment]
@eyalbe4 
"export CI=FALSE" before the jf rt download should work? It didn't work.

**Comment by eyalbe4** [comment]
@zork456,
Are you using the latest JFrog CLI release?
Could it be you're not running the command in a terminal? Will you be able to run the command from your local machine's terminal?

**Comment by zork456** [comment]
I tried it running a batch script not using the command directly in my terminal. Is this not possible? I am not sure how I can find out the CLI release, but I know which version of JFrog I am using.
