### ISSUE TITLE
The build-docker-create command fails to collect fat-manifest's build-info 

### ISSUE THREAD

**Issue by Or-Geva** [jfrog/jfrog-cli#1182]
**Describe the bug**
Running the command `jfrog rt build-docker-create ...` on fat-manifest returns an error"
```
[Error] exec: "kaniko": executable file not found in $PATH
```

**To Reproduce**
1. Push fat-manifest to Artifactory.
2. Run `jfrog rt build-docker-create ...` with a file that contains the fat-manifest  tag & digest diegest

**Expected behavior**
It should be able to add these image(s) just like none fat-manifest images.

**Versions**
- JFrog CLI version: 1.49
- Artifactory Version: 7.21.3

**Additional context**
JFrog CLI command ```build-docker-create``` does not support fat-manifest and therefore fails.
The root cause of this bug happens when JFrog CLI needs to choose which image inside the fat-manifest needs to be added to build-info. Choosing the right image uses the command `inspect`, a valid command for Docker/Podman CLIs, but not for Kaniko.

While this logic makes sense for docker pull, `build-docker-create` does not necessarily aim at a single image. Therefore, a different approach is probably needed here.

**Comment by lmcpare** [comment]
You refer to a "fat-manifest". Can you describe what it is?

**Comment by Or-Geva** [comment]
Sure @lmcpare, [here](https://docs.docker.com/registry/spec/manifest-v2-2/) you can find more info on "fat-manifest".

**Comment by Or-Geva** [comment]
The https://github.com/jfrog/jfrog-cli/pull/1364 fix has resolved this issue.
