### ISSUE TITLE
JFrog CLI is searching for package.json as a suffix instead of package.json

### ISSUE THREAD

**Issue by amithkm** [jfrog/jfrog-cli#1198]
**Description**
When we have a package.json as a suffix (example-package.json) then JFrog CLI thinks this is the actual package.json and will publish the package name as mentioned in example-package.json instead of considering the package name in the package.json file.

**To Reproduce**
Create a sample npm project with package.json and example-package.json file or any file which ends with package.json.
and perform the below steps.
#jfrog rt npmc
#jfrog rt npm-install --verbose
#jfrog rt npm-publish --verbose
and we will be able to see the following output  from the JFrog CLI while publishing
[Info] [Thread 2] Uploading artifact: /Users/examplekm/Downloads/npmpipelineprivate/npmpipelineprivate/projects/angular-reusable-components/angular-reusable-components-0.0.1.tgz
[Debug] Sending HTTP PUT request to: **https://example.jfrog.io/artifactory/npm-npm//-/-.tgz;**

[Debug] [Thread 2]  Artifactory response: 201 Created  (Checksum deploy)
[Debug] Uploaded 1 artifacts.

**Expected behavior**
JFrog CLI should be able to detect the package.json file and not with suffix.

**Source of the problem**
https://github.com/jfrog/jfrog-cli-core/blob/6338f12dcd0c4be906f45f3e6be61f6b7e8d9fc1/artifactory/commands/npm/publish.go#L386

**Versions**
- JFrog CLI version: can be reproduced with JFrog CLI 1.51.0 and 2.2.0 
- JFrog CLI operating system:NA
- Artifactory Version: reproduced with Artifactory latest

**Comment by yahavi** [comment]
Fix is included in JFrog CLI 1.51.1 and 2.30.0
