### ISSUE TITLE
Error download index-app

### ISSUE THREAD

**Issue by gjhofmann** [jfrog/jfrog-cli#1201]
**Describe the bug**
When I start an Xray scan, I get the following error message:
[Error] read ... /.jfrog/dependencies/xray-indexer/temp: is a directory
indexer-app is in the directory ./jfrog/dependencies/xray-indexer/temp
and an additional artifact is created: ./jfrog/dependencies/xray-indexer/3.29.0
when I rename the temp-directory to 3.29.0 everything works fine

**To Reproduce**
./jfrog xr s jar-file

**Expected behavior**
indexer-app should be downloaded in the directory ./jfrog/dependencies/xray-indexer/3.29.0

**Screenshots**

**Versions**
- JFrog CLI version: 2.2.0
- JFrog CLI operating system: Ubuntu 18.04.5 LTS
- Artifactory Version: 7.21.8

**Additional context**

**Comment by asafgabai** [comment]
@gjhofmann
Thanks for reporting this issue.
I just [opened a PR](https://github.com/jfrog/jfrog-cli-core/pull/213) for fixing it.
I'll update here when it's released.

**Comment by eyalbe4** [comment]
@gjhofmann -
JFrog CLI 2.2.1 with this fix has just been released.
Looking forward to your feedback for the fix.

**Comment by gjhofmann** [comment]
@eyalbe4 
Version 2.2.1 solved the problem - the download behaves now as expected - Thanks.

**Comment by eyalbe4** [comment]
Thanks for confirming this @gjhofmann and thanks @asafgabai for adding the fix.
