### ISSUE TITLE
Download urls not working on https://jfrog.com/getcli/

### ISSUE THREAD

**Issue by oyarzun** [jfrog/jfrog-cli#1221]
Not sure this is the place to report this issue, but the urls to download the latest jfrog-cli executables are not working.

https://releases.jfrog.io/artifactory/jfrog-cli/v2/[RELEASE]/jfrog-cli-mac-386/jfrog
https://releases.jfrog.io/artifactory/jfrog-cli/v2/[RELEASE]/jfrog-cli-windows-amd64/jfrog.exe
https://releases.jfrog.io/artifactory/jfrog-cli/v2/[RELEASE]/jfrog-cli-linux-amd64/jfrog

e.g.
```json
{
  "errors": [
    {
      "status": 404,
      "message": "Item jfrog-cli:v2/[RELEASE]/jfrog-cli-linux-amd64/jfrog does not exist"
    }
  ]
} 
```

**Comment by testworksau** [comment]
@oyarzun they work for me (at least, they do at the moment).

**Comment by oyarzun** [comment]
Thanks, they are working properly again.
