### ISSUE TITLE
CLI --url option is mandatory

### ISSUE THREAD

**Issue by dkubicki** [jfrog/jfrog-cli#1222]
Hi, 

I'm wondering what We do wrong and why we received an error msg if we put an options URL.

```git clone https://github.com/jfrog/jfrog-cli
cd jfrog-cli
./build/build.sh
export CI=true
export JFROG_CLI_LOG_LEVEL=DEBUG

./jfrog rt c --url=https://artifactory.allegrogroup.com/artifactory --user=user_bamboo --password="${bamboo.artifactory.user.password}"```

then i got msg -> 
09-Sep-2021 15:04:38 | No help topic for 'c'
09-Sep-2021 15:04:38 | [Error] the --url option is mandatory

**Comment by yahavi** [comment]
@dkubicki, 
The `jfrog rt c` command is not supported anymore in JFrog CLI V2.
To config Artifactory server on V2, run the following command: 
`jfrog c add --artifactory-url=https://artifactory.allegrogroup.com/artifactory --user=user_bamboo --password="${bamboo.artifactory.user.password}"`

For more information see [List of changes in JFrog CLI v2](https://www.jfrog.com/confluence/display/CLI/JFrog+CLI#JFrogCLI-ListofchangesinJFrogCLIv2).

**Comment by dkubicki** [comment]
@yahavi many thx. It works properly.
