### ISSUE TITLE
does jfrog-cli-go support  POST api/docker/<repoKey>/v2/promote

### ISSUE THREAD

**Issue by rajatjindal** [jfrog/jfrog-cli#123]
I am trying to use it to promote the docker image, couldn't find an option to do this.

**Comment by eyalbe4** [comment]
@rajatjindal,
The API for docker promotion is currently not supported in JFrog CLI. We are however working on implementing build-info for docker builds, similar to the existing build-info functionality for *npm*, *maven* and *gradle*.
If you'll push your image with JFrog CLI, and publish its build-info, you'll be able to promote the whole build.

**Comment by eyalbe4** [comment]
@rajatjindal,
Version 1.14.0 which has been released a few days ago, supports a new *docker-push* command. The new command uses the docker client to push a docker image to Artifactory, while collecting and recording build-info locally. The collected build-info can be then published to Artifactory using the *build-publish* command.
The build can be then promoted using the *build-promote* command. You can read more about it [here](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-BuildingDockerImages)
If you choose to use the new docker build-info functionality, we'd appreciate your feedback for it.
