### ISSUE TITLE
Creating signed bundle fails yet exit code is 0

### ISSUE THREAD

**Issue by trriplejay** [jfrog/jfrog-cli#1251]
**Describe the bug**
when creating a release bundle with sign=true, if the release bundle is created but signing fails, the summary shows "failures: 1" but the exit code of the command is 0, making it look successful.

**To Reproduce**
- Have JFrog Distribution with a signing key that requires a passphrase
- use the CLI to create a release bundle with sign=true, but do not supply the passphrase
- observe the command completes as though successful, but the summary shows "failures: 1", and if you look in distribution, the bundle was created but not signed.

**Expected behavior**
if sign=true in the command, but the bundle could not be signed, the command itself should have a non-zero exit code.

**Screenshots**

**Versions**
- JFrog CLI version: 1.49.x
- JFrog CLI operating system: Ubuntu 18

**Comment by trriplejay** [comment]
I've run into another case of this happening where the bundle fails to be created, but the CLI exits with a 0 return code, making our CI system think that all is well when actually the bundle was never created. In this new case, it does not seem to be related to signing the bundles, since we've been able to create/sign other bundles.

So, maybe this bug is a more general issue with returning 0 from a "release-bundle-create" action despite it failing.

**Comment by yahavi** [comment]
Hi @trriplejay 
Thanks for reporting this issue!
This issue is resolved in the latest JFrog CLI 2.5.1 by https://github.com/jfrog/jfrog-cli/pull/1271. Feel free to upgrade.

We'd appreciate your feedback on that.

**Comment by trriplejay** [comment]
@yahavi any chance the 1.x version can get this fix as well? upgrading to 2.x will be quite an effort for us.

**Comment by eyalbe4** [comment]
@trriplejay,
Following your request, we released version 1.53.0 which includes the fix.
Looking forward to you r feedback.
