### ISSUE TITLE
Blank jfrog-cli.conf causes concurrency issues

### ISSUE THREAD

**Issue by el-gee** [jfrog/jfrog-cli#129]
**Summary of the Issue**
Our team has noticed a large number of errors from the cli along the lines of:
- access denied
-  can not access file because it is in use by another program
- (might be 1 more variant, but you get the idea)

These errors seem to occur more frequently when our build servers are under heavy load.  Additionally, with the blank jfrog-cli.conf we notice that the "last modified" time is updated after every single exe invocation.  

**System Information:**
OS - Windows
CLI Version - 1.13.1
A blank jfrog-cli.conf
relevant env vars:
- JFROG_CLI_OFFER_CONFIG = false
- JFROG_CLI_HOME = default

**Workaround Implemented**
We provided a valid cli config and the issues appear to have subsided.  Additionally the file is no longer updated after every invocation of the exe.  

**Root Cause Best Guess**
After poking around the source a bit it seems that if for any reason the cli pulls a partial or invalid or blank config it will attempt to write back out a blank configuration file -- even if the exact same file already exists.  While the behavior in isolation isn't particularly offensive, in an environment where the exe is being aggressively called (such as a build server) it seems to run into issues.  It seems that if the cli attempts to write out a conf file while there is already another instance of the process running an error will (rightly) be thrown.  

I could see an argument that this isn't really a bug,  it's poor behavior on the end users.  However, I would contend that as this is the "out of the box" configuration of the cli,  it should support multiple concurrent invocations without further configuration.  If it is decided that the current behavior is correct, it would be nice to update the documentation to indicate that high performance environments must be configured to avoid contention issues.

**Comment by eyalbe4** [comment]
Thank you for sharing @el-gee.
This is definitely something we want to improve. We'll try to come up with an improved approach for managing the jfrog-cli.conf file. We'll share here the details soon.

**Comment by eyalbe4** [comment]
@el-gee,
The code has been  further improved in version 1.19.0, to completely prevent this concurrency issue.
Please let us know if the latest release resolves the issue.
