### ISSUE TITLE
I use ‘jfrog xr am’ to scan source code，It can only report the dependency security issue，but it can‘t report transitive dependency security issue，but it can be found in xray，why？

### ISSUE THREAD

**Issue by liwei2151284** [jfrog/jfrog-cli#1303]
I use ‘jfrog xr am’ to scan source code，It can only report the dependency security issue，but it can‘t report transitive dependency security issue，but it can be found in xray，why？

**Comment by liwei2151284** [comment]
![image](https://user-images.githubusercontent.com/16078620/142985725-6730088c-4551-4b3d-8032-7dcef33531c9.png)

![image](https://user-images.githubusercontent.com/16078620/142985762-d1bb08d7-53a3-4406-a61a-1cd84a374e3e.png)

**Comment by eyalbe4** [comment]
@liwei2151284 - 
The ```jfrog xr am``` command scans all of your project depedencies - both direct and transitive (indirect). The command output displays only vulnerable dependencies (and allows filtering them out according to your Xtay policy).
Can you therefore ellaborate more about the issue you're seeing? Which vulnerable depedencies do you not see as part of the command output?

**Comment by liwei2151284** [comment]
@eyalbe4 Thank you for answering my question
I use “jfrog xr am” without "--watch", maybe means it can report all of the secruity issues.but I can only see the direct dependency issues.

My pom file：
![image](https://user-images.githubusercontent.com/16078620/142996549-71d6249e-7739-485b-828e-f8ee718efd64.png)
If I use 'jfrog xr am' ,my scan report:
![image](https://user-images.githubusercontent.com/16078620/142996927-8d676818-f2e5-41b1-a5af-42a92ffeff2f.png)
Dependancy tree:
![image](https://user-images.githubusercontent.com/16078620/142997124-df02619c-3e91-4f21-96d0-1df8f70182fd.png)
If I use 'jfrog xr s xxx.jar',my scan report all security issues:
![image](https://user-images.githubusercontent.com/16078620/142997590-ba7ba57c-1276-4e7c-8048-9829a6d29646.png)

My source code:
https://github.com/liwei2151284/Guestbook-microservices-k8s/tree/master/gateway-service

**Comment by eyalbe4** [comment]
@liwei2151284 - 
It looks like dependencies such as ```ch.qos.logback:logback-core``` are indeed packed inside your ```getway-service.jar```. And by running ```jfrog xr s getway-service.jar```, Xray identified these packed depedencies and their vulnerabilities.
I can see though that ```ch.qos.logback:logback-core``` is not included in the dependencies tree output yuo shared. Is it indeed not there, or you just haven't shared the entire output?
If it is not there there, could it be that these depedencies make into your ```getway-service.jar``` from somewhere else during your build? If they do, then the ```jfrog xr am``` command, which does not build the code, but just compiles it with maven to find its dependencies, can't be aware of them.
Please let us know what you think.

**Comment by liwei2151284** [comment]
@eyalbe4  Thanks for answering my question
This is all my dependency tree，you can see logback-core is in it.
![image](https://user-images.githubusercontent.com/16078620/143145235-f8921a8a-3be9-4d10-9d2b-ad8dd305225b.png)
![image](https://user-images.githubusercontent.com/16078620/143145285-da45fdbe-deb7-4bcc-826c-c2482044b58d.png)

**Comment by sverdlov93** [comment]
Hi @liwei2151284, thanks again for reporting this issue and also for the detailed logs.
We found the issue that caused the missing dependencies in maven-audit and fixed it.

We will update here as soon as the fix will be released.

**Comment by sverdlov93** [comment]
Hi @liwei2151284,
We just released JFrog CLI 2.6.2 which fixes this issue.
We'd appreciate your feedback on it.
Sorry for the inconvenience caused by this.

**Comment by liwei2151284** [comment]
Hi @sverdlov93 
Thank you very much ,I've already upgrade JFrog CLI 2.6.2, and it worked well.
