### ISSUE TITLE
jfrog/jfrog-cli-v2 Docker image size increase

### ISSUE THREAD

**Issue by santhonisz** [jfrog/jfrog-cli#1320]
Hi there,

I've noticed that when pulling the `latest` (2.7.0 release) tag of the "slim" `releases-docker.jfrog.io/jfrog/jfrog-cli-v2` Docker image, the size of the image has increased dramatically since the 2.5.0 release. Currently for `latest` the image size is ~1.28GB whereas it is a much more palatable ~50.4MB for the `2.5.0` tag.

As a result it is slowing our build pipelines down due to the increased pull time.

Is there any valid reason for the increase in size or is something amiss?

**Comment by eyalbe4** [comment]
Thanks for reporting this @santhonisz!
We're looking into this now and will report back here.

**Comment by Or-Geva** [comment]
@santhonisz, This [PR](https://github.com/jfrog/jfrog-cli/pull/1326) fixes the issue.
I will update this thread once the next release will be out.

**Comment by Or-Geva** [comment]
@santhonisz, JFrog CLI 2.8.1 was released, feel free to upgrade and share your feedback.

**Comment by santhonisz** [comment]
Hi @Or-Geva, sorry about the delayed reply. I can confirm the issue is indeed fixed in the newer releases of the Docker image - thanks for the fix!
