### ISSUE TITLE
jfrog mvn package should not upload artifacts to artifactory

### ISSUE THREAD

**Issue by tsuyo** [jfrog/jfrog-cli#1348]
**Is your feature request related to a problem? Please describe.**
Normal `mvn package` command builds artifacts, but doesn't install and/or deploy them. But currently `jfrog mvn package` automatically uploads artifacts to artifactory. So it should obey the same principle as normal `mvn package`.

**Describe the solution you'd like to see**
`jfrog mvn package` should only build artifacts, but not upload them to artifactory.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by donhui** [comment]
The issue can be solved temporarily by add `-Dartifactory.publish.artifacts=false` to the list of goals and options.

**Comment by larkoie** [comment]
This is horrible behavior that should not have been implemented first. Maven has very well documented workflows that are known by everybody for years.
Jfrog just decides to mess all the well known wording and say that 'mvn install' or 'mvn package' will actually also deploy on Artifactory.
This is straight madness to implement such things, what's the added value? It's just adding complexity on top of a simple workflow...
jfrog cli is just a wrapper to integrate with Artifactory, it should not mess with the expected workflow of the tools it's using...
