### ISSUE TITLE
Populate the issues tab in Artifactory Build Info

### ISSUE THREAD

**Issue by NasAmin** [jfrog/jfrog-cli#141]
Hi,

Is there a way to publish JIRA issues ids and their links to Artifactory via JFrog CLI as done by the Jenkins plugin?
https://www.jfrog.com/confluence/display/RTF/Build+Integration#BuildIntegration-Issues

We have started using JFrog CLI to publish build info to Artifactory using our build tool i.e. Gradle.

If it isn't supported yet, is there an ETA on when this will be done and is there a work around in the mean time?

regards,

Nasir

**Comment by NasAmin** [comment]
Anyone please? @eyalbe4 ?

**Comment by eyalbe4** [comment]
@NasAmin,
This functionality is currently not supported in JFrog CLI. It is indeed supported by the Jenkins Artifactory Plugin. The implementation in Jenkins relies on the Jira Plugin.
Jira integration for JFrog CLI is an interesting idea. We will consider adding it to our features roadmap.

**Comment by NasAmin** [comment]
Thanks @eyalbe4. It would be super helpful if this is supported. This way builds are fully traceable as well. Since the Build Info schema supports Issues, it should be relatively simple.
I was hoping you could just pass this information to Jfrog CLI so it doesn't have to fetch it directly from JIRA. This way we'll have to do the work, JFrog Cli just accepts some json.

This could be a similar task to _jfrog rt bad_ command

If you are thinking of directly integrating jira with jFrog CLI then that would be another option.

regards,

**Comment by gh-andre** [comment]
Artifactory plug-in for Jenkins doesn't support MSbuild and jfrog.exe is the only way to publish artifacts and builds in this case. Lack of integration with Jira is a significant shortcoming for C++ builds.

**Comment by NasAmin** [comment]
Hi @eyalbe4, is this still being considered?

**Comment by eyalbe4** [comment]
@NasAmi and @gh-andre,
We've recently added support for adding issues tracking information into the build-info, through the *jfrog rt build-add-git* command. You can read more about this [here](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-CollectingBuildInformation).
Looking forward to you feedback for this,

**Comment by serGrey** [comment]
Is there a way to publish custom issue IDs and their links to Artifactory via JFrog CLI?
For example, is it possible to extract issue IDs from git commit messages, make links to the issue tracker and publish with build info to the Artifactory?

I'm trying to run 
jfrog rt bag ${buildName} ${buildVersion}
as a result, I see just next content in the temp file: 
{
  "Timestamp": 1583849093065,
  "vcsUrl": "https://{url}/git/repo.git",
  "vcsRevision": "128b88815effcff2bd2d56f69e3f1a0af640efa"
}

**Comment by RobiNino** [comment]
Hi @serGrey,
This is exactly what the 'bag' command does, when you provide a config file to it using the '--config' option. 
See the [documentation](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-CollectingInformationfromGit) of the command for the config schema and extended details.

**Comment by serGrey** [comment]
Thanks @RobiNino 
I  created the config file and it's worked
Could you please explain what I should to setup in the config file to extract issue IDs from git commit messages separate for each build?

**Comment by RobiNino** [comment]
@serGrey What do you mean by "separate for each build"?
If you want to only collect issues of a specific project in the tracker, modify the regexp field accordingly.

**Comment by serGrey** [comment]
@RobiNino, thank you!

**Comment by NasAmin** [comment]
Awsome. I am going to close this issue.
