### ISSUE TITLE
getting 404 error on pipeline log

### ISSUE THREAD

**Issue by shailesh719** [jfrog/jfrog-cli#1431]
Hi 

when i am trying to Configure Artifactory instance with  jfrog cli for my gitlab pipe-line , i am getting 404 error on pipeline log , below are the error message 
"Error] The following error was received while trying to encrypt your password: Artifactory response: 404  " 

Variable declared on my pipeline
 ARTIFACTORY_BASE_URL: https://XXX.XX.XXX/artifactory
 ARTIFACTORY_SERVER_ID: XYZSERVER-ID
 ARTIFACTORY_KEY: someEncodedKEY
ARTIFACTORY_USER: XYZ_USER 
 
jfrog cli Command which i am using on gitlab pipeline :
    `./jfrog config add $ARTIFACTORY_SERVER_ID --artifactory-url="$ARTIFACTORY_BASE_URL" --user="$ARTIFACTORY_USER" --apikey="$ARTIFACTORY_KEY" --interactive=false

_Originally posted by @shailesh719 in https://github.com/jfrog/jfrog-cli/issues/441#issuecomment-1033966240_

**Comment by jdelucaa** [comment]
Hi 👋 
Did you solve this? I am getting the same.

**Comment by eyalbe4** [comment]
@jdeluc2aa,
Ensure that the URL you're providing is the JFrog Platform URL and not the Artifactory URL. In the initial message posted in this issue the URL seem to end with /artifactory, when it actually shouldn't.

**Comment by jdelucaa** [comment]
> @jdeluc2aa, Ensure that the URL you're providing is the JFrog Platform URL and not the Artifactory URL. In the initial message posted in this issue the URL seem to end with /artifactory, when it actually shouldn't. Also try using the --url command option instead of --artifactory-url.

hey, yeah, I figure that out after a few attempts 😄 
Thanks.

**Comment by eyalbe4** [comment]
Happy to hear this @jdelucaa 👍

**Comment by dallinwilcox** [comment]
> @jdeluc2aa, Ensure that the URL you're providing is the JFrog Platform URL and not the Artifactory URL. In the initial message posted in this issue the URL seem to end with /artifactory, when it actually shouldn't. Also try using the --url command option instead of --artifactory-url.

@eyalbe4 I'm confused by this since [the docs](https://jfrog.com/help/r/jfrog-cli/authenticating-with-username-and-password/api-key)  indicate the `--url` option should end with `/artifactory`

> | **Command option**  | **Description** |
> | ----------- | ----------- |
> | --url    | JFrog Artifactory API endpoint URL. It usually ends with /artifactory     |

Are the docs in need of an update, or does  `--url` behave differently than `--artifactory-url`?
