### ISSUE TITLE
Implement auto-completion script on stdout or custom destination

### ISSUE THREAD

**Issue by carlsmedstad** [jfrog/jfrog-cli#1435]
**Is your feature request related to a problem? Please describe.**
When packaging (as I am for Arch Linux) CLI-tools it's often appreciated by users to have completions automatically installed. This is not doable in the clean way with jfrog-cli, as there is no way to produce a completion script in a location different than the one in the users home directory (that I know of).

**Describe the solution you'd like to see**
The `jfrog completion` commands would take a flag that will output the completion script either on stdout or in a file with a settable location. This would allow me to install completion alongside the program in my package without touching the users home directory.

For example:

```sh
$ jfrog completion -o some_location bash
$ cat some_location
#!/bin/bash
_jfrog() {
    local cur opts base
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    opts=$( ${COMP_WORDS[@]:0:$COMP_CWORD} --generate-bash-completion )
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
}

complete -F _jfrog -o default jfrog
complete -F _jfrog -o default jf
```

Or:

```sh
$ jfrog completion --stdout bash
#!/bin/bash
_jfrog() {
    local cur opts base
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    opts=$( ${COMP_WORDS[@]:0:$COMP_CWORD} --generate-bash-completion )
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
}

complete -F _jfrog -o default jfrog
complete -F _jfrog -o default jf
```

Thanks!

**Comment by eyalbe4** [comment]
Thanks for sharing this requirement @carlsmedstad.
Can you share with us the scenario in which you wouldn't want the competition script to be stored under the user home directory. You mentioned "when packing CLI tools". Can you elaborate more about that?

**Comment by yahavi** [comment]
@carlsmedstad,
I think https://github.com/jfrog/jfrog-cli/pull/1426 should allow this by changing the default behavior of `jfrog completion ...` commands - instead of installing the completion scripts in `~/.jfrog/`, it prints the completion script to the screen.

**Comment by carlsmedstad** [comment]
Thanks for the quick response!

> Can you share with us the scenario in which you wouldn't want the competition script to be stored under the user home directory? You mentioned "when packing CLI tools". Can you elaborate more about that?

I'm maintaining a package for jfrog-cli in the AUR (Arch Linux User Repository), the definition of which can be found [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=jfrog-cli-bin). I would like to install completions as part of my package but it's bad form to touch the users home directory during installation. All installation steps should happen in an isolated directory.

So I would like to be able to add generation of the completion scripts to my package without touching the home directory of the person installing the package. The package will install the completion scripts globally to `/usr/share/bash-completion/` and the corresponding directories for the other shells.

> I think https://github.com/jfrog/jfrog-cli/pull/1426 should allow this by changing the default behavior of jfrog completion ... commands - instead of installing the completion scripts in ~/.jfrog/, it will print the completion script to the screen.

@yahavi Yes, this is precisely the change I'm looking for :+1:

**Comment by eyalbe4** [comment]
Thanks for this information @carlsmedstad!
So it looks like @yahavi's #1426 is what's needed.

**Comment by carlsmedstad** [comment]
As of the latest version, my package now installs completions so I'm closing this issue.

Thank you @yahavi & @eyalbe4! Much appreciated.
