### ISSUE TITLE
Add an rsync-like mode for upload and download

### ISSUE THREAD

**Issue by jgeorgeson** [jfrog/jfrog-cli#144]
It'd be great to have the jfrog CLI be able to delete contents from the destination if they've been deleted from the source. Similar to how `rsync` works.

**Comment by jgeorgeson** [comment]
Something like

`jfrog rt upload --rsync=true local-folder my-repo/folder/`

And anything not present in `local-folder/` would be removed from `my-repo/folder/`. Ideally this mode would be supported by both upload and download commands.

**Comment by arbourd** [comment]
This would be wonderful. 

Because the JFrog CLI doesn't allow you to pass a list of objects, and also doesn't accept a list via stdin, the only way to pass in multiple artifacts is to use a janky regex that looks like `(file1.tgz)|(completelydifferent.txt)` which isn't desirable.

**Comment by shivaprasadh** [comment]
I am looking for this option in Jfrog-Cli.  Is there any way to delete the local files if it is not present in Source?

**Comment by protenhan** [comment]
I would also appreciate this because it would speed up our up- and download operations quite a bit. :+1:

**Comment by eyalbe4** [comment]
@protenhan, @shivaprasadh, @arbourd and @jgeorgeson - 
@liron-shalom is working on adding this in https://github.com/jfrog/jfrog-cli/pull/431

**Comment by reenberg** [comment]
I guess this issue could be closed, now that #431 has been merged around 10month ago?

**Comment by jgeorgeson** [comment]
Agreed

**Comment by eyalbe4** [comment]
Thanks @reenberg.
Just as a reference, you can use the *--sync-deletes* option with the *jfrog rt download* and *jfrog rt upload* commands. Feel free to provide us with feedback for this functionality.
