### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference when running 'jf dotnet' or 'jf nuget restore' 

### ISSUE THREAD

**Issue by infestus** [jfrog/jfrog-cli#1463]
**Describe the bug**
When running either 'dotnet restore' or 'nuget restore' I see the following error: 

>  [exec] panic: runtime error: invalid memory address or nil pointer dereference
[exec] [signal 0xc0000005 code=0x1 addr=0x40 pc=0x1a24b78]
[exec] 
[exec] goroutine 1 [running]:
[exec] github.com/jfrog/jfrog-cli-core/v2/artifactory/utils/dotnet/solution.(*solution).BuildInfo(0xc0002ec000, {0x0, 0x0})
[exec]  /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.10.1/artifactory/utils/dotnet/solution/solution.go:77 +0x598
[exec] github.com/jfrog/jfrog-cli-core/v2/artifactory/commands/dotnet.(*DotnetCommand).Exec(0xc0001a8f50)
[exec]  /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.10.1/artifactory/commands/dotnet/dotnetcommand.go:133 +0x343
[exec] github.com/jfrog/jfrog-cli-core/v2/artifactory/commands/dotnet.(*DotnetCoreCliCommand).Run(0xc0000068a0)
[exec]  /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.10.1/artifactory/commands/dotnet/dotnetcorecli.go:27 +0x46
[exec] github.com/jfrog/jfrog-cli-core/v2/common/commands.Exec({0x1e35b18, 0xc0000068a0})
[exec]  /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.10.1/common/commands/command.go:26 +0xad
[exec] github.com/jfrog/jfrog-cli/buildtools.DotnetCmd(0xc0000d0dc0)
[exec]  /var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/buildtools/cli.go:571 +0x2ab
[exec] github.com/jfrog/jfrog-cli/buildtools.GetCommands.func10(0xc0000d0dc0)
[exec]  /var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/buildtools/cli.go:196 +0x19
[exec] github.com/urfave/cli.HandleAction({0x1b6fd40, 0x1d03690}, 0x6)
[exec]  /root/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0xa8
[exec] github.com/urfave/cli.Command.Run({{0x1cab70e, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1cb8acf, 0x12}, {0x1ce4f8e, ...}, ...}, ...)
[exec]  /root/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x652
[exec] github.com/urfave/cli.(*App).Run(0xc0000c4a80, {0xc0000a6000, 0x6, 0x8})
[exec]  /root/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x705
[exec] main.execMain()
[exec]  /var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/main.go:104 +0x307
[exec] main.main()
[exec]  /var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/main.go:68 +0x25

**To Reproduce**
Target Framework: .Net Core (netcoreapp3.1)
Trying to restore dependencies stored in Artifactory using either "jf dotnet restore ProjectName.sln" or "jf nuget restore ProjectName.sln" 
After a while, a lot of warnings (50+) with the following message occur

> The file C:\Users\username\\.nuget\packages\microsoft.netcore.platforms\1.1.0\microsoft.netcore.platforms.1.1.0.nupkg doesn't exist in the NuGet cache directory but it does exist as a target in the assets files. Skipping adding this dependency to the build info. This might be because the package already exists in a different NuGet cache, possibly the SDK's NuGetFallbackFolder cache. Removing the package from this cache may resolve the issue.

Followed by a single panic error (listed above), and the build then terminates. 

**Expected behavior**
Expected to have restore nuget packages from Artifactory

**Versions**
- JFrog CLI version: 2.12.1 and 2.13.0
- JFrog CLI operating system: Windows Server 2016
- Artifactory Version: 7.29.9

**Comment by talarian1** [comment]
Hi @infestus,
Thanks for reporting this issue.
Could you please share with us the test project you used as well?

**Comment by infestus** [comment]
[TestSolution.zip](https://github.com/jfrog/jfrog-cli/files/8215304/TestSolution.zip)

How to run and reproduce:

- Edit the NuGet.config to point to a proper artifactory nuget repository (v3). 
- Setup your configuration with: `jf config add --interactive=false --overwrite=true --url https://SOMEURL --access-token YOURTOKEN prod` and ` jf dotnetc --repo-resolve REPO-NAME --server-id-resolve prod`
- via Powershell go `$env:JFROG_CLI_BUILD_NAME="sdjhkfskjd"` and `$env:JFROG_CLI_BUILD_NUMBER="123123"`
- and finally `jf dotnet restore TestSolution.sln`

**Comment by infestus** [comment]
A couple of notable observations: 
- I dont see this if JFROG_CLI_BUILD_NAME/BUILD_NUMBER is not set. 
- The problem arises in solution.go (in jfrog-cli-core), when your `directDeps` is not a perfect subset of `dependencies`, so clearly a number of direct dependencies are not listed in `project.Extractor().AllDependencies()` and your code clearly assume it is without a null-check. 
- This is most likely caused by dependencies to the dotnet framework itself (like `microsoft.netcore.platforms`) , as it's probably not listed as a proper "dependency" (hence the warnings before the exception), but is clearly listed as a direct dependency.

**Comment by talarian1** [comment]
@infestus, Thanks for sharing this info with us. I will look into that and will keep you updated.

**Comment by shavitbit** [comment]
I have the same problem with Artifactory nuget extension - restore command. It seems that it finish to restore and than end with the same error 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x40 pc=0x1513658]

**Comment by yahavi** [comment]
@infestus @infestus,
Thanks for your valuable feedback.
We manage to detect the root cause of this issue. This PR should fix this issue - https://github.com/jfrog/jfrog-cli-core/pull/355.
The fix is expected to be included in the next JFrog CLI release. We'll keep you updated.

**Comment by infestus** [comment]
@yahavi , much appreciated. Looking forward to it.

**Comment by yahavi** [comment]
@infestus,
JFrog CLI 2.14.0 is released. This version includes a fix for this issue.
Feel free to upgrade - We'd appreciate your feedback on that.

**Comment by infestus** [comment]
I have verified that the new release works, @yahavi . I will close this issue now and considers it resolved.
