### ISSUE TITLE
CLI crashes when trying to create a repo with invalid package type

### ISSUE THREAD

**Issue by meirtsvi** [jfrog/jfrog-cli#1464]
Repro steps:
1. Create json file with the following content:
{"key":"RPM-wrong","packageType":"rpmaa","rclass":"local","xrayIndex":"true"}

2. jf rt repo-create <json_file>

Expected result:
The cli should return error message saying the package type is not supported/exists.

Actual result:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc28e71]

goroutine 1 [running]:
github.com/jfrog/jfrog-cli-core/v2/artifactory/commands/repository.(*RepoCommand).PerformRepoCmd(0xc0002aef60, 0x9d)
        /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.9.1/artifactory/commands/repository/repository.go:60 +0x311
github.com/jfrog/jfrog-cli-core/v2/artifactory/commands/repository.(*RepoCreateCommand).Run(0xb32708)
        /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.9.1/artifactory/commands/repository/create.go:39 +0x1d
github.com/jfrog/jfrog-cli-core/v2/common/commands.Exec({0xfcd648, 0xc0002aef60})
        /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.9.1/common/commands/command.go:26 +0xad
github.com/jfrog/jfrog-cli/artifactory.repoCreateCmd(0xc0001b51e0)
        /var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/artifactory/cli.go:1961 +0x105
github.com/jfrog/jfrog-cli/artifactory.GetCommands.func49(0xc0001b51e0)
        /var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/artifactory/cli.go:736 +0x19
github.com/urfave/cli.HandleAction({0xd19160, 0xea6938}, 0xb)
        /root/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0xa8
github.com/urfave/cli.Command.Run({{0xe57f7b, 0xb}, {0x0, 0x0}, {0xc000249640, 0x1, 0x1}, {0x0, 0x0}, {0xc000174a50, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x652
github.com/urfave/cli.(*App).RunAsSubcommand(0xc000160c40, 0xc0001b4f20)
        /root/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405 +0x9ec
github.com/urfave/cli.Command.startApp({{0xe4eb0c, 0x2}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372 +0x6e9
github.com/urfave/cli.Command.Run({{0xe4eb0c, 0x2}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102 +0x808
github.com/urfave/cli.(*App).Run(0xc000160a80, {0xc000138040, 0x4, 0x4})
        /root/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x705
main.execMain()
        /var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/main.go:104 +0x307
main.main()
        /var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/main.go:68 +0x25

**Comment by sverdlov93** [comment]
Hi @meirtsvi, Thanks for reporting this issue.
Our apologies for the inconvenience caused by this.
This https://github.com/jfrog/jfrog-cli-core/pull/348 has improved log for invalid package type / rcalss.
I will update this thread once the next release will be out.

**Comment by sverdlov93** [comment]
Hi @meirtsvi, 
JFrog CLI 2.14.0 is released and should fix the above issue.
Looking forward to your feedback on it.
