### ISSUE TITLE
Incorrect exit code for `jfrog scan` command

### ISSUE THREAD

**Issue by santhonisz** [jfrog/jfrog-cli#1469]
**Describe the bug**
When using the `jfrog scan` command and violations are returned that are set to fail the build e.g. via the use of an appropriately configured Watch, the returned exit code is not as expected. In this case the returned exit code is `1`, whereas with the `jfrog build-scan` (and legacy `jfrog rt build-scan` command) the returned exit code is `3`. 

As per the help documentation when running `jfrog scan -h`, the `--fail` argument is used to bypass this behaviour. It also indicates the exit code should be `3`.

> --fail              [Default: true] Set to false if you do not wish the command to return exit code 3, even if the 'Fail Build' rule is matched by Xray.

I'm not sure if this issue also affects the `jfrog docker scan` command as it isn't currently possible to use the `--watches` argument with it due to https://github.com/jfrog/jfrog-cli/pull/1461 

Having an exit code of `1` makes it difficult to programmatically distinguish between failures such as authentication issues etc. and when scans have completed successfully but with violations.

**To Reproduce**
Run a scan using the `jfrog scan` command with a Watch via `--watches` argument that will ensure any violations will fail the build. 

**Expected behavior**
If the scan is failed due to the violations failing the build, the exit code should be `3`.

**Screenshots**
Note the slight difference in text against the `[Error]` message

***`jfrog scan` exit code:***

![image](https://user-images.githubusercontent.com/29723862/157210218-c7a795d1-b471-4d13-b03d-a0d7fdb5191f.png)

***`jfrog build-scan` exit code:***

![image](https://user-images.githubusercontent.com/29723862/157211437-fede470f-8725-436f-a69f-d27178f91b04.png)

**Versions**
- JFrog CLI version: 2.13.0
- JFrog CLI operating system: Windows 10
- Artifactory Version:  7.33.12
- Xray Version: 3.43.1

**Additional context**
Having different exit code behaviours between the various scan commands makes it inconsistent and difficult to integrate with other systems.

**Comment by sverdlov93** [comment]
Hi @santhonisz 
Thanks for reporting this issue.
Our apologies for the inconvenience caused by this.
This PR - https://github.com/jfrog/jfrog-cli-core/pull/351 should fix it.
I will update this thread once the next release will be out.

**Comment by sverdlov93** [comment]
Hi @santhonisz, 
JFrog CLI 2.14.0 is released and should fix the above issue.
Looking forward to your feedback on it.
