### ISSUE TITLE
jf audit fails when there are conflicts in npm peer dependencies

### ISSUE THREAD

**Issue by sstephant** [jfrog/jfrog-cli#1515]
**Describe the bug**

jf audit fails when there are conflicts in peer dependencies.
In the working example below we have a simple angular@10 project.
There is also a @ngui/auto-complete dependency that has an angular@9 peer dependency

This results in errors in the `npm ls` command arguing there are peer deps missing

```console
npm ERR! peer dep missing: @angular/common@^9.0.1, required by @ngui/auto-complete@3.0.0
npm ERR! peer dep missing: @angular/core@^9.0.1, required by @ngui/auto-complete@3.0.0
npm ERR! peer dep missing: jasmine-core@>=3.8, required by karma-jasmine-html-reporter@1.7.0
npm ERR! peer dep missing: tslib@^1.10.0, required by @ngui/auto-complete@3.0.0
npm ERR! peer dep missing: tslib@^1.10.0, required by @ngui/auto-complete@3.0.0
npm ERR! peer dep missing: tslib@^1.10.0, required by @ngui/auto-complete@3.0.0
npm ERR! peer dep missing: tslib@^1.10.0, required by @ngui/auto-complete@3.0.0
npm ERR! peer dep missing: tslib@^1.10.0, required by @ngui/auto-complete@3.0.0
npm ERR! peer dep missing: tslib@^1.10.0, required by @ngui/auto-complete@3.0.0
npm ERR! peer dep missing: tslib@^1.10.0, required by @ngui/auto-complete@3.0.0
npm ERR! peer dep missing: tslib@^1.10.0, required by @ngui/auto-complete@3.0.0
npm ERR! peer dep missing: jasmine-core@>=3.8, required by karma-jasmine-html-reporter@1.7.0
``` 

So far this is expected because of the version conflicts.
However this missing information will make any jf commands relying on npm ls fail with the following error (including jf audit):
````console
[🚨Error] json: cannot unmarshal string into Go struct field legacyNpmLsDependency.PeerMissing of type []*utils.peerMissing
````

**To Reproduce**
You can use the following demonstration project:
https://github.com/sstephant/jf-peer-bug

1. clone the project
2. setup artifactory (jf config add, jf npmc)
2. jf npm i 
3. jf audit (fails)

Step 2 may require the `--legacy-peer-deps` depending of the npm version

It's probable that step 2. fails with `build-name` and `build-number` which will record deps info and trigger an `npm` ls command

**Expected behavior**

While the project present some problems I expect the jfrog cli to workaround the issue and ignore the missing peer dependdencies.

**Versions**
- Node version: 14
- npm versions 6/8
- JFrog CLI version: 2.15, 2.15.1, 2.16
- JFrog CLI operating system: tested on linux
- Artifactory Version: 7.25.6
- XrayVersion: 3.32

**Comment by sstephant** [comment]
FYI I also tried the 2.16 version that was just released since the [release notes](https://github.com/jfrog/jfrog-cli/blob/v2.16.0/RELEASE.md#2160-april-15-2022) mention:

> **Bug fix - Missing npm depedencies should not return an error**

I got the same error:

> [🚨Error] json: cannot unmarshal string into Go struct field legacyNpmLsDependency.PeerMissing of type []*utils.peerMissing

**Comment by Or-Geva** [comment]
@sstephant, JFrog-CLI 2.16.1 has been released and fixes this issue.

**Comment by sstephant** [comment]
Hi, I can confirm version 2.16.1 fixed the problem for us.
Thank you.
