### ISSUE TITLE
Update "Install a JFrog CLI plugin" help message to also include "or upgrade"

### ISSUE THREAD

**Issue by eldada** [jfrog/jfrog-cli#1521]
**Is your feature request related to a problem? Please describe.**
Not a problem, but an improvement

**Describe the solution you'd like to see**
In file [docs/plugin/install/help.go](https://github.com/jfrog/jfrog-cli/blob/v2/docs/plugin/install/help.go), update all text to also reflect the fact that the `install` command is for upgrades too.

**Examples**

Change
```
Install a JFrog CLI plugin.
```
to
```
Install or Upgrade a JFrog CLI plugin.
```

Change
```
Specifies the name and version of the JFrog CLI Plugin you wish to install from the plugins registry.
```
to
```
Specifies the name and version of the JFrog CLI Plugin you wish to install or upgrade from the plugins registry.
```

**Comment by eyalbe4** [comment]
Thanks for reporting this @eldada.
Would you like to contribute this fix through a pull request?

**Comment by eldada** [comment]
> Thanks for reporting this @eldada. Would you like to contribute this fix through a pull request?

See https://github.com/jfrog/jfrog-cli/issues/1521
