### ISSUE TITLE
Built executables for 2.16.2 are not available

### ISSUE THREAD

**Issue by carlsmedstad** [jfrog/jfrog-cli#1525]
**Describe the bug**

Built executables are not available for version 2.16.2. The folders in Artifactory are empty, for example https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/2.16.2/jfrog-cli-linux-amd64/.

Thanks!

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Versions**
- JFrog CLI version: 2.16.2
- JFrog CLI operating system: N/A
- Artifactory Version: N/A

**Additional context**
N/A

**Comment by sverdlov93** [comment]
Hi @carlsmedstad,
Thanks for reporting this issue.
Our apologies for the inconvenience caused by this bug.
We believe that the issue was fixed.
Looking forward to your feedback on it.

**Comment by carlsmedstad** [comment]
It's fixed now, thanks!
