### ISSUE TITLE
Build Info Truncating VCS Branch Names with Slashes

### ISSUE THREAD

**Issue by daykjfrog** [jfrog/jfrog-cli#1553]
**Describe the bug**
When the branch name has "/" in it, then in the build info file, the branch name becomes the name after the last slash.

**To Reproduce**
I have a git branch as “test/branch”.
Then I run the below commands using cli:
```
jf rt build-add-git "test" 3 --server-id myserver
jf rt build-publish --server-id myserver "test" 3
```
Then my build info has my branch name as “branch” instead of “test/branch”:
```
{
    "version": "1.0.1",
    "name": "test",
    "number": "3",
    "buildAgent": {
        "name": "GENERIC",
        "version": "2.18.2"
    },
    "agent": {
        "name": "jfrog-cli-go",
        "version": "2.18.2"
    },
    "started": "2022-05-31T15:21:32.652-0700",
    "durationMillis": 0,
    "artifactoryPrincipal": "user",
    "vcs": [{
        "revision": "b07853939d54a40688d492fcc49a2f84edd7b289",
        "message": "Initial commit",
        "branch": "branch",
        "url": "https://github.com/daykjfrog/testgit.git"
    }]
}
```

**Expected behavior**
The branch name should be as it is, instead of stripping the names before the last slash

**Versions**
- JFrog CLI version: 2.18.2 (Latest)
- JFrog CLI operating system: Linux
- Artifactory Version: 7.x

**Comment by sverdlov93** [comment]
Hi @daykjfrog and @flichtenheld and @jeremycornett
Thanks for reporting this issue.
Our apologies for the inconvenience caused by this.
This PR - https://github.com/jfrog/jfrog-client-go/pull/616 should fix it.
I will update this thread once the next release will be out.

**Comment by sverdlov93** [comment]
Hi @daykjfrog and @flichtenheld and @jeremycornett
[JFrog CLI 2.22.0](https://github.com/jfrog/jfrog-cli/releases/tag/v2.22.0) is released and should fix the above issue.
Looking forward to your feedback on it.
