### ISSUE TITLE
CLI Output doesn't encodes the build URL in output

### ISSUE THREAD

**Issue by sachinzen** [jfrog/jfrog-cli#158]
When using CLI for publishing build record, the output produced doesn't seems to be encoding the final URL when its containing special characters like "#". We feel that CLI in general should always encode the URLs when it is outputting.
Below is the snippet from the Build output. Note that the URL is having "#" in it and when we copy paste or click directly its break at this position.

2018-04-18T19:35:25.4457293Z Collecting Build Environment Information
2018-04-18T19:35:25.4774653Z [Info] Collecting environment variables...
2018-04-18T19:35:25.4784682Z [Info] Collected environment variables for SoftwareServices#Artifactory-VSTS-Extension/20180418.1.
2018-04-18T19:35:25.5501416Z [Info] Deploying build info...
2018-04-18T19:35:25.6441486Z [Info] Build info successfully deployed. Browse it in Artifactory under https://<servername>/artifactory/webapp/builds/SoftwareServices#Artifactory-VSTS-Extension/20180418.1

**Comment by fdolsky321** [comment]
Still doesn't fix, is it going to be fixed? :)

**Comment by fdolsky321** [comment]
@sachinzen do you have any workaround? It's strange that this easy fix is not applied yet :X.

**Comment by eyalbe4** [comment]
@fdolsky321,
Does the build name you're publishing to Artifactory include special characters? Can you share the build name?

**Comment by fdolsky321** [comment]
@eyalbe4 
Yes, it includes. So, build name is:
`BITBUCKET/DEVOPS/dostack-pipeline-lib-it-npm/multibranch-job/develop`

Wrongly generated URL is:
`https://artifacts.merck.com/artifactory/webapp/builds/BITBUCKET/DEVOPS/dostack-pipeline-lib-it-npm/multibranch-job/develop/71`

Correct generated URL should be:
`https://${BASE_URL}/artifactory/webapp/#/builds/BITBUCKET~2FDEVOPS~2Fdostack-pipeline-lib-it-npm~2Fmultibranch-job~2Fdevelop/71/1557501043984`
Here is located the build

**Comment by staffanf** [comment]
@eyalbe4 Hello, we have also hit this now in 2021.
Isn't this something that should be regarded as a bug and fixed?

Our use case is that we have been enforcing build names separated by slashes and those using the jfrog cli are getting bad urls from he tool.

**Comment by talarian1** [comment]
Hi @sachinzen , @fdolsky321, and @staffanf  
The fix is included in [1.51.0](https://github.com/jfrog/jfrog-cli/releases/tag/v1.51.0) and in [2.2.0](https://github.com/jfrog/jfrog-cli/releases/tag/v2.2.0) releases.
We would appreciate any feedback from you.

**Comment by staffanf** [comment]
From our team I hear that the URLs are working.

**Comment by eyalbe4** [comment]
Thanks for confirming this @staffanf and thanks @talarian1 for delivering this fix.
