### ISSUE TITLE
Jfrog cli binary breaking with `syntax error near unexpected token `]'` error

### ISSUE THREAD

**Issue by raghavharness** [jfrog/jfrog-cli#1588]
**Describe the bug**
When running the jfrog binary we get the below error.
```
./jfrog: line 5: syntax error near unexpected token `]'
./jfrog: line 5: `  } ]'
```

**To Reproduce**
1. Tested on CLI Version 2.18.2
2. Run the command: `./jfrog rt u --url <actual_url> --access-token <actual_access_token> "/drone/README.md" /default-generic-local/citesting`

Output:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/103042128/176852946-1436c9eb-c6ca-405d-9087-bb51c9229031.png">

**Expected behavior**
When tested with CLI version 1.53.1 the same command works perfectly.

**Versions**
- JFrog CLI version: 2.18.2, 2.19.0
- JFrog CLI operating system: MacOS Monterey, M1 (same behaviour noticed on linux as well)
- Artifactory Version:

**Additional context**

**Comment by raghavharness** [comment]
False alarm, we just saw the binary is different for v2. But somehow we were able to download v2 binary with this command too `curl -fL https://getcli.jfrog.io | sh /dev/stdin 2.18.2`, which gives the wrong binary.

**Comment by Mohamed-E** [comment]
@raghavharness - What command are you using to download the correct binary for v2? I am also running into this issue.

**Comment by kc224** [comment]
@Mohamed-E did you ever find a solution?

**Comment by Mohamed-E** [comment]
Hey @kc224, this was quite a while ago so I am not exactly sure how we resolved it - but I believe we updated the CLI to a newer version and no longer faced this issue.
