### ISSUE TITLE
jfrog-cli-v2 version 2.20.0 fails with SIGSEGV when uploading in Ubuntu 20.04.4 LTS running under WSL2

### ISSUE THREAD

**Issue by gstorhaug** [jfrog/jfrog-cli#1595]
**Describe the bug**
jfrog (from jfrog-cli-v2) fails with the following error message after uploading:
Working ∙∙∙∙∙∙
 |…⬜⬜⬜⬜⬛⬛⬛⬛…|  Tasks: 206/413
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xa001d8]

goroutine 55 [running]:
github.com/jfrog/jfrog-client-go/utils/io/content.(*ContentWriter).Close(0xda3840)
        /root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v1.15.0/utils/io/content/contentwriter.go:164 +0x18
github.com/jfrog/jfrog-client-go/artifactory/services.(*resultsManager).finalizeResult(0xc00088c030, {0xc0004d8240, 0x60}, 0xc0003d4140)
        /root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v1.15.0/artifactory/services/upload.go:993 +0x75
github.com/jfrog/jfrog-client-go/artifactory/services.(*UploadService).CreateUploadAsZipFunc.func1(0x2)
        /root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v1.15.0/artifactory/services/upload.go:749 +0x7af
github.com/jfrog/gofrog/parallel.(*runner).addThread.func1(0x2)
        /root/go/pkg/mod/github.com/jfrog/gofrog@v1.2.0/parallel/runner.go:250 +0x19d
created by github.com/jfrog/gofrog/parallel.(*runner).addThread
        /root/go/pkg/mod/github.com/jfrog/gofrog@v1.2.0/parallel/runner.go:238 +0xcf

The jfrog command exits with the exit code 2,
However the uploaded archive appears to be OK.

**To Reproduce**
From some directory:
jfrog rt upload ./ sandbox-release/zz-test-to-be-deleted-0.0.0/something.zip --archive zip

**Expected behavior**
Exit code 0 and output like:
 Log path: /home/gas/.jfrog/logs/jfrog-cli.2022-07-07.13-17-07.2231.log
{
  "status": "success",
  "totals": {
    "success": 1,
    "failure": 0
  }
}

**Screenshots**
NA

**Versions**
- JFrog CLI version: 2.20.0
- JFrog CLI operating system: DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
running under: Linux GeirS-AuroraR11 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Artifactory Version:  7.2.1 rev 70201900 undefined

**Additional context**
Downgrading to version 2.18.2 of jfrog-cli-v2 solves the problem:
sudo apt install jfrog-cli-v2=2.18.2

**Comment by Or-Geva** [comment]
Thank you for reporting this issue, @gstorhaug.
JFrog CLI version 2.21.0 just got released, which fixes this issue.
If you have any feedback, please let us know.

**Comment by gstorhaug** [comment]
Works as expected in 2.21.0.

Thank you so much - this was fixed much faster than I had expected!
