### ISSUE TITLE
jf audit gradle error on android project

### ISSUE THREAD

**Issue by gregoryboue** [jfrog/jfrog-cli#1610]
**Describe the bug**

On android project with gradle 7.3.3 and com.android.tools.build:gradle:7.2.1, `jf audit` command produce following error :  

```
Task :app:extractModuleInfo
Error during extraction: 
org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':app:debugAndroidTestCompileClasspath'.
 at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.wrapException(ErrorHandlingConfigurationResolver.java:105)
...
Caused by: org.gradle.internal.component.AmbiguousVariantSelectionException: The consumer was configured to find an API of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.2.1'. However we cannot choose between the following variants of project :app:
- Configuration ':app:debugApiElements' variant android-base-module-metadata declares an API of a component, as well as attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.2.1', attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug':
       - Unmatched attributes:
           - Provides attribute 'artifactType' with value 'android-base-module-metadata' but the consumer didn't ask for it
           - Provides attribute 'com.android.build.gradle.internal.attributes.VariantAttr' with value 'debug' but the consumer didn't ask for it
          - Doesn't say anything about its target Java environment (preferred optimized for Android)
....
```

**To Reproduce**

- Clone the following sample project : https://github.com/jfrog/project-examples/tree/master/gradle-examples/gradle-android-example
- upgrade gradle wrapper to use 7.3.3 version
- upgrade plugin com.android.tools.build:gradle to use 7.2.1 version 
- update dependency androidx.test.ext:junit to use 1.1.3 version
- adapt /app/src/main/AndroidManifest.xml to add android:exported properties : `<activity android:name=".MainActivity" android:exported="true">`
- Launch the following commands with a jfrog cli configured to uses Artifactory platform (7.35.2) 
  - jf gradle-config...
  - jf audit

**Expected behavior**

a `jf audit` execution without errors and functionnal project dependency scan

**Versions**
- JFrog CLI version: 2.21.4
- JFrog CLI operating system: Linux (Docker)
- Artifactory Version: 7.35.2 + xray 3.43.4

**Additional context**

It seems that variant production (debug, release) is root cause, if i update modules configuration in root build.gradle as following, it works : `artifactoryPublish.dependsOn('build')` -> `artifactoryPublish.dependsOn('assembleDebug')` or `artifactoryPublish.dependsOn('assembleRelease')`.

This problem also affect `jf build scan` command because no dependency information are collected in build-info when i perform a jf gradle build.

**Comment by gregoryboue** [comment]
Hi,

Any news about this ?

**Comment by gregoryboue** [comment]
This problem was due to an artifactory publications artifact misconfiguration, i close the issue

**Comment by Larnoo** [comment]
i have the same problem. How did you work it out?

**Comment by gregoryboue** [comment]
you have to configure your publishing.publications block to publish only one buildType :

```gradle
publishing {
    publications {
        app(MavenPublication) {
            groupId = group
            artifactId = project.getName()
            version = version
// only debug apk
            artifact("$buildDir/outputs/apk/debug/${project.getName()}-debug.apk")...
}

    artifactoryPublish.dependsOn('assemble')
    artifactoryPublish {
        publications(publishing.publications.app)
    }

```

 or you can configure one publication by builldType and add this publications in artifactoryPublish 

```gradle
publishing.publications {
    android.applicationVariants.all { variant ->
         "maven${variant.name.capitalize()}Apk"(MavenPublication) {
               // artifact configurations here
          }
     }
}

artifactoryPublish.dependsOn("assemble")

artifactoryPublish {
     android.applicationVariants.all { variant ->
        if (variant.name.contains("${flavour}${currentJob.capitalize()}")) {
            publications("maven${variant.name.capitalize()}Apk")
        }
    }
}

```

**Comment by a735131232** [comment]
gradle 7.5    com.android.tools.build:gradle:7.4.1    "org.jfrog.buildinfo:build-info-extractor-gradle:latest.release"  

错误信息，请问这个错误如何解决？
![image](https://user-images.githubusercontent.com/5805214/226294743-d4352535-c57b-4ca3-b1cb-f3b7e3666c6a.png)

配置内容，多项目  app + library 在一个project下
![image](https://user-images.githubusercontent.com/5805214/226304493-a8468037-4acc-4b69-a3dd-adb4ca0df8ca.png)
