### ISSUE TITLE
'jf bs' there is no way can return the license.

### ISSUE THREAD

**Issue by mikesun666** [jfrog/jfrog-cli#1626]
**Describe the bug**
'jf bs' can not display the license, even though there are a lot of license the violations

**To Reproduce**
1. Create a policy that adds all licenses that will trigger the violation.
2. Make a maven or docker build and publish on Artifactory
3. use jf bs to scan the build.

**Expected behavior**
It should return not only the security issue but also the license issue.

**Screenshots**
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/43203674/181722433-b6adf0d2-d21c-4ab9-9ecf-29f49c75b73b.png">

<img width="1741" alt="image" src="https://user-images.githubusercontent.com/43203674/181722628-fa770995-c32c-4486-9c2d-5c206d2c1202.png">

**Versions**
- JFrog CLI version:  jf version 2.21.5
- JFrog CLI operating system: Centos7
- Artifactory Version: 7.41.6

**Additional context**
'jf bs' there is no way can return the license.

**Comment by sverdlov93** [comment]
Hi @mikesun666,
The Licenses tab you see on the Platform UI shows all found licenses on your build.
The `jf bs` returns the  Security/License **violations**.
To make a license violate a build, there should be a policy assigned to that build that catches that license, and the 'fail build' box should be selected.
![Screen Shot 2022-08-01 at 16 35 43](https://user-images.githubusercontent.com/29822394/182159887-bce05526-cd82-4e4e-ba09-db8c530629ef.png)

**Comment by mikesun666** [comment]
@sverdlov93 Thanks for the update, this is not an issue.
