### ISSUE TITLE
jf audit supposed to detect packages automatically but is not detecting

### ISSUE THREAD

**Issue by viveksamaga** [jfrog/jfrog-cli#1627]
Hi we are using xray version 3.52.4 and jf cli 2.22.0 and trying to get the vulnerabilities report for 1 of the npm project, upon running jf audit command on the project workspace it is throwing below error.
But when we run jf audit 
jf audit --npm it is generating the report.
                      
14:44:27 [🔵Info] Log path: /Users/vsamaga/.jfrog/logs/jfrog-cli.2022-07-29.14-44-27.61717.log
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/jfrog/build-info-go/build/utils.(*YarnDependency).Name(...)
        github.com/jfrog/build-info-go@v1.4.0/build/utils/yarn.go:183
github.com/jfrog/jfrog-cli-core/v2/xray/audit/yarn.getXrayDependencyId(0x19c8580?)
        github.com/jfrog/jfrog-cli-core/v2@v2.18.7/xray/audit/yarn/yarn.go:68 +0xb4
github.com/jfrog/jfrog-cli-core/v2/xray/audit/yarn.parseYarnDependenciesMap(0xc000494180?, 0x4?)
        github.com/jfrog/jfrog-cli-core/v2@v2.18.7/xray/audit/yarn/yarn.go:55 +0x105
github.com/jfrog/jfrog-cli-core/v2/xray/audit/yarn.buildYarnDependencyTree()
        github.com/jfrog/jfrog-cli-core/v2@v2.18.7/xray/audit/yarn/yarn.go:47 +0xfe
github.com/jfrog/jfrog-cli-core/v2/xray/audit/yarn.AuditYarn({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1afc65d, 0xa}, 0x0, ...}, ...)
        github.com/jfrog/jfrog-cli-core/v2@v2.18.7/xray/audit/yarn/yarn.go:19 +0x45
github.com/jfrog/jfrog-cli-core/v2/xray/commands/audit/generic.GenericAudit({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1afc65d, 0xa}, 0x0, ...}, ...)
        github.com/jfrog/jfrog-cli-core/v2@v2.18.7/xray/commands/audit/generic/auditmanager.go:56 +0x585
github.com/jfrog/jfrog-cli-core/v2/xray/commands/audit/generic.(*GenericAuditCommand).Run(0xc0004f4000)
        github.com/jfrog/jfrog-cli-core/v2@v2.18.7/xray/commands/audit/generic/generic.go:105 +0x128
github.com/jfrog/jfrog-cli-core/v2/common/commands.Exec({0x3595118?, 0xc0004f4000})
        github.com/jfrog/jfrog-cli-core/v2@v2.18.7/common/commands/command.go:26 +0xa8
github.com/jfrog/jfrog-cli/utils/progressbar.ExecWithProgress({0x1cf8d08, 0xc0004f4000})
        github.com/jfrog/jfrog-cli/utils/progressbar/filesprogressbar.go:325 +0xf2
github.com/jfrog/jfrog-cli/scan.AuditCmd(0xc0004ee160)
        github.com/jfrog/jfrog-cli/scan/cli.go:182 +0x1bd
github.com/urfave/cli.HandleAction({0x19a5340?, 0x1bb0ee8?}, 0x5?)
        github.com/urfave/cli@v1.22.9/app.go:524 +0xa8
github.com/urfave/cli.Command.Run({{0x1aeeec1, 0x5}, {0x0, 0x0}, {0xc00048e150, 0x1, 0x1}, {0x1b74793, 0x3c}, {0x0, ...}, ...}, ...)
        github.com/urfave/cli@v1.22.9/command.go:173 +0x652
github.com/urfave/cli.(*App).Run(0xc0001e0a80, {0xc0001ae000, 0x2, 0x2})
        github.com/urfave/cli@v1.22.9/app.go:277 +0x8a7
main.execMain()
        github.com/jfrog/jfrog-cli/main.go:103 +0x2fb
main.main()
        github.com/jfrog/jfrog-cli/main.go:67 +0x25

**Comment by sverdlov93** [comment]
Hi @viveksamaga,
Thanks for reporting this issue.
Our apologies for the inconvenience caused by this bug.
Looks like the Audit command mistakenly detected the project as Yarn project.
The JFrog CLI detects the technology type by the descriptor files (package.json / yarn.lock / etc..)
Can you please provide your project's root dir files list?

**Comment by viveksamaga** [comment]
Hello thanks for getting back, here are all the files
yarn.lock
webpack-overrides.js
tsconfig.json
splunk
scripts
renovate.json5
packages
package.json
lerna.json
jest.config.js
jest-preset.js
integration-tests
hosting-applications
global.d.ts
e2e-tests
docs
babel.config.js
README.md
Jenkinsfile
CONTRIBUTING.md
node_modules
package-lock.json

**Comment by sverdlov93** [comment]
Hi @viveksamaga,
So I see that it's indeed a Yarn project, so that's why we try to run Audit Yarn.
Is it Yarn 1 or 2? 
Unfortunately, JFrog CLI audit currently supports only Yarn 2.
Having said that, the error you received is wrong and we will fix it and let the users know that currently Yarn 1 is not supported.

**Comment by viveksamaga** [comment]
I just used yarn 2 to build the project and getting below errors.
jfrog audit      
16:47:10 [🔵Info] Log path: jfrog/logs/jfrog-cli.2022-08-01.16-47-10.8581.log
16:47:13 [🚨Error] invalid character 'I' looking for beginning of value
 yarn -v          
2.0.0-rc.30

**Comment by sverdlov93** [comment]
Can you add here also the log inside: jfrog/logs/jfrog-cli.2022-08-01.16-47-10.8581.log ? @viveksamaga

**Comment by viveksamaga** [comment]
I think whole project needs to be upgraded to yarn v2 for jf audit to work is that correct?
