### ISSUE TITLE
jfrog cli(2.24.0) is forcing to set environment config even though I am passing username and password in command

### ISSUE THREAD

**Issue by virendra3inarow** [jfrog/jfrog-cli#1640]
CLI is not letting me download files without CLI configuration.

jf rt dl  --url $artifactory_url --user $user --password $password folder/common.zip --recursive=false --flat=true --explode=true ./

I keep getting the message below

To avoid this message in the future, set the CI environment variable to true.
The CLI commands require the URL and authentication details
Configuring JFrog CLI with these parameters will save you from including them as command options.
You can also configure these parameters later using the 'jfrog c' command.
Configure now? (y/n) [n]?

**Comment by dan-hoeger** [comment]
that works I set CI=true and that resolved it.

**Comment by sverdlov93** [comment]
@dan-hoeger BTW are you using https://marketplace.visualstudio.com/items?itemName=JFrog.jfrog-azure-devops-extension ?
