### ISSUE TITLE
can not upload a folder that the name include ‘()’

### ISSUE THREAD

**Issue by j1an5** [jfrog/jfrog-cli#1658]
**Describe the bug**
$ ls "test(test)/"
1.txt
$ jfrog rt u "test(test)/" example-repo-local/test/ --flat=false
{
"status": "success",
"totals":

{ "success": 0, "failure": 0 }
}

**To Reproduce**
1. install jfrog cli latest
2. mkdir -p 'test(test)'
3. cd 'test(test)' && touch 1.txt  && echo 1 > 1.txt && cd ../
4. jfrog c add ... & use
5. jfrog rt u 'test(test)' example-repo-local/test/

**Expected behavior**
Really upload success.

**Screenshots**

**Versions**
- JFrog CLI version: jf version 2.21.5
- JFrog CLI operating system: Linux&windows
- Artifactory Version: 7.41.6

**Additional context**
if mv "test(test)/" "test（test）/", can succeed.

**Comment by eyalbe4** [comment]
@j1an5 - 
JFrog CLI 2.32.0 is released and includes a fix for this issue.
Looking forward to your feedback for it.

**Comment by j1an5** [comment]
@eyalbe4 hello,I can upload the folder when using such a command, with version 2.32.0 both jfrog and jf
$ jfrog rt u 'test(test)/' example-repo-local/

Thanks a lot.
