### ISSUE TITLE
jf audit times out with dotnet project 

### ISSUE THREAD

**Issue by lorenyeung** [jfrog/jfrog-cli#1679]
**Describe the bug**
dotnet projects with sln/csproj files and 300+ dependencies never complete jf audit scans (15+ minutes). It appears from the POST requests made to Xray that the size of the payload is quite large with respect to the number of dependencies.

**To Reproduce**
internal steps provided

**Expected behavior**
jf audit to return results

**Versions**
- JFrog CLI version: 2.18
- JFrog CLI operating system: mac
- Artifactory Version: 7.41.7
- Xray Version: 3.55.2

**Additional context**

**Comment by sverdlov93** [comment]
Hi @lorenyeung,
[JFrog CLI 2.25.3](https://github.com/jfrog/jfrog-cli/releases/tag/v2.25.3) is released and should fix the above issue.
Looking forward to your feedback on it.
