### ISSUE TITLE
jf docker scan crashes with sarif output format

### ISSUE THREAD

**Issue by gjasny** [jfrog/jfrog-cli#1688]
**Describe the bug**
Switching the Xray docker scan output format to sarif leads to an application crash.

**To Reproduce**
```
$ jf docker scan debian:latest --format sarif           
07:51:00 [🔵Info] Log path: /home/gregorj/.jfrog/logs/jfrog-cli.2022-09-09.07-51-00.2737833.log
07:51:16 [🔵Info] Note: no context was provided, so no policy could be determined to scan against.
You can get a list of custom violations by providing one of the command options: --watches, --repo-path or --project.
Read more about configuring Xray policies here: https://www.jfrog.com/confluence/display/JFROG/Creating+Xray+Policies+and+Rules
All vulnerabilities detected will be included in the output JSON.
07:51:17 [🚨Error] strconv.ParseFloat: parsing "": invalid syntax
```

Surprisingly if I use the exact image name with the SHA it works: `debian@sha256:d52921d97310d0bd48dab928548ef539d5c88c743165754c57cfad003031386c`.

**Expected behavior**
No parse error happening.

**Versions**
- JFrog CLI version: 2.25.3 downloaded from GitHub
- JFrog CLI operating system: Linux amd64
- Artifactory Version: EnterpriseX license 7.37.14 rev 73714900 

Thanks,
Gregor

**Comment by omerzi** [comment]
Hi @gjasny, thank you for letting us know about this issue. We will investigate this issue and let you know as soon as possible.

**Comment by omerzi** [comment]
Hey @gjasny, I've found the root cause and fixed the issue. It will be available in the coming release. I'm keeping this issue open so you can update me on wether the issue is resolved on your side. Thank you.

**Comment by yahavi** [comment]
@gjasny - JFrog CLI 2.25.4 is released.
This version includes @omerzi's fix for this issue.
Feel free to upgrade - we'd appreciate your feedback on that!

**Comment by gjasny** [comment]
Thanks the new version solves my issue.
