### ISSUE TITLE
jf audit does not post results at XRay server

### ISSUE THREAD

**Issue by tkatrichenko** [jfrog/jfrog-cli#1711]
When I run scan commands like 
`jf scan --project <proj_name>` or `jf docker scan --project <proj_name>` the jfrog cli posts results at my XRay server `https://my.jfrog.io/ui/onDemandScanning/<scan_id>?projectKey=<proj_name>`

But for `jf audit --project <proj_name>` I can't find any results at my XRay server. Is it expected or am I missing something?

**Comment by sverdlov93** [comment]
Hi @tkatrichenko,
The On-Demand scanning UI page shows only **binary scans**. (`jf scan` that scans files or directories and `docker scan` that uses `scan`  to scan docker image tar file)
`jf audit` is a **dependency scan** that scans the project's dependencies and sub-dependencies and it's not shown on the Xray UI page.
Let us know if you have more questions.

**Comment by yevhenhnes** [comment]
@sverdlov93, but regarding the info on the https://jfrog.com/help/r/jfrog-security-user-guide/developers/cli/scan-your-source-code:
_The 
`jf audit
` command enables developers to perform on-demand security scans of their source code directly from their terminal, ensuring early detection of CVEs, licenses, operational risk, [SAST](https://jfrog.com/help/r/_SD6R0PIfl9UZ1cNTXRYqw/0kVr_nMWBR4BtICtFYLk8g), [misconfigurations](https://jfrog.com/help/r/_SD6R0PIfl9UZ1cNTXRYqw/ES945o9HKMEz7uaI0nZMsw), and exposed [secrets](https://jfrog.com/help/r/_SD6R0PIfl9UZ1cNTXRYqw/eAEWRZl8fngfGC_2dmWi_w). By integrating seamlessly into the developer workflow, it helps catch security risks before code reaches production—reducing remediation costs and enhancing software integrity. **The scan results are displayed in the terminal for immediate feedback and are also available in the JFrog Platform’s On-Demand Scans pane, providing centralized visibility**._
Is it a documentation issue?
