### ISSUE TITLE
jf docker scan output to a file results in "[🚨Error] inappropriate ioctl for device"

### ISSUE THREAD

**Issue by derekscp** [jfrog/jfrog-cli#1725]
### Describe the bug

When performing an on-demand docker scan command with the jfrog cli (i.e. jf docker scan) you will receive an error when trying to redirect the output to a file.

An older version (2.15.1) does not exhibit this issue.

### Current behavior

Example:
`$ jf docker scan alpine > alpine_vuln.txt
10:28:41 [Debug] JFrog CLI version: 2.27.1
10:28:41 [Debug] OS/Arch: darwin/amd64
10:28:41 [🔵Info] Log path: /clihome/.jfrog/logs/jfrog-cli.2022-10-17.10-28-41.77904.log
10:28:52 [🚨Error] inappropriate ioctl for device`

### Reproduction steps

Download the alpine docker image from Docker hub.

Perform a jf docker scan on the image and redirect the output to a file.
$ jf docker scan alpine  > alpine_vuln.txt

Observe the error:
"[🚨Error] inappropriate ioctl for device"

### Expected behavior

We should be able to write the output to a file.

### JFrog CLI version

2.27.1

### Operating system type and version

darwin/amd64

### JFrog Artifactory version

7.47.1

### JFrog Xray version

3.59.4

**Comment by sverdlov93** [comment]
Hi @derekscp ,
Thanks for reporting this issue.
Our apologies for the inconvenience caused by this.
This PR - https://github.com/jfrog/jfrog-cli-core/pull/582 should fix it.
I will update this thread once the next release will be out.

**Comment by sverdlov93** [comment]
Hi @derekscp ,
[JFrog CLI 2.28.0](https://github.com/jfrog/jfrog-cli/releases/tag/v2.28.0) is released and should fix the above issue.
Looking forward to your feedback on it.
