### ISSUE TITLE
jf poetry audit error on poetry project

### ISSUE THREAD

**Issue by farba07** [jfrog/jfrog-cli#1756]
### Describe the bug

In a poetry project with at least one dependency, when the **jf audit --watches critical_watch_02608** command is run, the following error is obtained

### Current behavior

```
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run poetry lock [--no-update] to fix it.
 
Package operations: 45 installs, 1 update, 0 removals
 
• Installing pycparser (2.21)
 
ValueError
 
Repository "jfrog-server-1667984374870" does not exist.
 
at ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/repositories/pool.py:57 in repository
53│         lookup = self._lookup.get(name)
54│         if lookup is not None:
55│             return self._repositories[lookup]
56│ 
57│         raise ValueError(f'Repository "{name}" does not exist.')
58│ 
59│     def add_repository(
60│         self, repository: Repository, default: bool = False, secondary: bool = False
61│     ) -> Pool:
```

### Reproduction steps

- Clone the following sample project: https://github.com/jfrog/project-examples/tree/master/python-example/poetry-example
- Install project dependencies with **jf poetry install**
- Build the project with **jf poetry build**
- Run a local scan with the **jf audit** command

### Expected behavior

- No re-downloading of dependencies each time the jf poetry command is run
- a consistent poetry.lock file without having to run the command **poetry lock --no-update**
- A local scan on the project dependencies without error

### Additional context

It seems that the problem comes from the fact that the poetry.lock file is modified each time the jf poetry command is run and these lines are added with different timestamp on the _reference_ field:
```
[package.source]
type = "legacy"
url = "https://artefact-repo.apps.eul.sncf.fr/artifactory/api/pypi/pypi_02608/simple"
reference = 'jfrog-server-1667990693175'
```

This forces us to run **poetry lock --no-update** command before the local scan with **jf audit** otherwise the poetry.lock file is inconsistent with the toml.
Another problem we encountered is that if we run the jf poetry install command and then the jf poetry build command all the dependencies are redownloaded with the build command. 

### JFrog CLI version

2.31.0

### Poetry version

Poetry version 1.3.1

**Comment by gregoryboue** [comment]
Any new on this issue ?

**Comment by sverdlov93** [comment]
Hi @farba07 and @gregoryboue and @vmiko,
Thanks for reporting this issue.
Our apologies for the inconvenience caused by this.
[JFrog CLI 2.32.0](https://github.com/jfrog/jfrog-cli/releases/tag/v2.32.0) is released and should fix the above issue.
Looking forward to your feedback on it.
