### ISSUE TITLE
jfrog rt delete --dry-run=true should return exit code 1

### ISSUE THREAD

**Issue by Manisiri** [jfrog/jfrog-cli#1794]
### Describe the bug

Getting an exit code 1 for jfrog rt del --spec=specfile --dry-run=true --quiet=true

### Current behavior

NA

### JFrog CLI version

v3

### Operating system type and version

ubuntu in pipelines

**Comment by kumadee** [comment]
duplicate of https://github.com/jfrog/jfrog-cli/issues/682

**Comment by EyalDelarea** [comment]
Duplicate of https://github.com/jfrog/jfrog-cli/issues/682 and should be resolved.
