### ISSUE TITLE
Install specific version of CLI

### ISSUE THREAD

**Issue by Tobias-08** [jfrog/jfrog-cli#1795]
Hi,
how am I able to install a specific version (v2-jf, but not latest, e. g. 2.21.0) of JFrog CLI via `curl`?

`curl -fL https://install-cli.jfrog.io | sh` installs latest. We want to be able to pin the version in our build-scripts. Could you extend your install-script/url-structure to accept a version-param?

Thanks!
Tobias

**Comment by yahavi** [comment]
Hi @Tobias-08,
Thanks for using the JFrog CLI.
To use a specific version, run the following command:
```bash
curl -fL https://install-cli.jfrog.io | sh -s 2.21.0
```

Please let me know if that helped.

**Comment by Tobias-08** [comment]
@yahavi Thanks, that worked!
