### ISSUE TITLE
CLI upload status bar keep increasing a upload file more than the file count for the user who does not have deploy permission

### ISSUE THREAD

**Issue by ujwalpoovaiah** [jfrog/jfrog-cli#1812]
### Describe the bug

CLI upload status bar displays a incorrect file count as it is keep increasing a upload file count more than the actual file count. The issue occurs when the user do not have the deploy permission.

It will create confusion  when we are uploading 1000 of file at one go and status will show keep uploading without the termination the task or showing the 403 error in front.

### Current behavior

% jf rt u test/ test 

19:53:26 [🔵Info] Log path: /Users/abc/.jfrog/logs/jfrog-cli.2023-01-20.19-53-26.43122.log

 Working ●∙∙∙∙∙        

 |⬜⬜⬜⬜⬜⬜⬜⬜⬜| Tasks: 521/202

 |⬛⬛⬛⬛⬛⬛⬛⬛⬛| 0.0b/0.0b

 |⬛⬛⬛⬛⬛⬛⬛⬛⬛| 0.0b/0.0b

 |⬛⬛⬛⬛⬛⬛⬛⬛⬛| 0.0b/0.0b

 |⬛⬛⬛⬛⬛⬛⬛⬛⬛| 0.0b/0.0b

CLI Logs:

 Info] [Thread 1] Uploading: test/file-040
[Warn] [Thread 2] (Attempt 1) - Failure occurred while uploading to http://artifactory.com/artifactory/test/test/file-042: server response: 403 Forbidden
[Warn] [Thread 0] (Attempt 1) - Failure occurred while uploading to http://artifactory.com/artifactory/test/test/file-041: server response: 403 Forbidden
[Warn] [Thread 1] (Attempt 1) - Failure occurred while uploading to http://artifactory.com/artifactory/test/test/file-040: server response: 403 Forbidden
[Warn] [Thread 2] (Attempt 2) - Failure occurred while uploading to http://artifactory.com/artifactory/test/test/file-042: server response: 403 Forbidden
[Warn] [Thread 0] (Attempt 2) - Failure occurred while uploading to http://artifactory.com/artifactory/test/test/file-041: server response: 403 Forbidden
[Warn] [Thread 1] (Attempt 2) - Failure occurred while uploading to http://artifactory.com/artifactory/test/test/file-040: server response: 403 Forbidden

### Reproduction steps

-> Create folder with multiple files in it.
-> Create a user without deploy permission to the repository.
-> Try to upload this folder to Artifactory repository  
% jf rt u test/ test 
Files being uploaded count will increase.

 |⬜⬜⬜⬜⬜⬜⬜⬜⬜| Tasks: 521/202

### Expected behavior

While trying to upload a file to the repository in the Artifactory without "deploy" permission, Error should be displayed immediately and the task should terminate immediately, instead of that the progress status which misleads as files being uploaded

### JFrog CLI version

2.33.0

### Operating system type and version

linux

### JFrog Artifactory version

7.49.5

### JFrog Xray version

n/a

**Comment by greenlama** [comment]
It happens not only when user doesn't have upload permissions but also on any upload errors (no matter what was the reason of that error). A file may be uploaded during third retry but every upload retry increases the counter.

**Comment by sarao1310** [comment]
We've released a new version that would support this issue.
Please let us know if you have any more issues or questions.
And thank you for your feedback! 🐸
