### ISSUE TITLE
2.33.0 results in error 401: Props Authentication Token not found

### ISSUE THREAD

**Issue by famod** [jfrog/jfrog-cli#1814]
### Describe the bug

With `jfrog/jfrog-cli-v2-jf:latest` the following:
```
jf config add artifacts.my-company.de --artifactory-url=https://artifacts.my-company.de/artifactory --user=some-user --access-token=foobar
jf config show
jf rt ping
```

results in:
```
[Error] server response: 401 Unauthorized
{
  "errors": [
    {
      "status": 401,
      "message": "Props Authentication Token not found"
    }
  ]
}
```

When using `jfrog/jfrog-cli-v2-jf:2.32.0` everything is fine.

### Current behavior

See description

### JFrog CLI version

2.33.0

### Operating system type and version

Official docker image

### JFrog Artifactory version

EnterpriseX license 7.33.12 rev 73312900

**Comment by g3n35i5** [comment]
I can confirm this bug:

```
jf config add --user=someone@example.com --access-token=XYZ --url=https://artifactory.mycompany.com/ --artifactory-url=https://artifactory.mycompany.com/artifactory --distribution-url=https://artifactory.mycompany.com/distribution --xray-url=https://artifactory.mycompany.com/xray --interactive=false --overwrite=true

jf docker push artifactory.mycompany.com/docker-registry/image-name:image-tag

[Error] failed while attempting to get Artifactory version:
server response: 401 Unauthorized
{
  "errors": [
    {
      "status": 401,
      "message": "Props Authentication Token not found"
    }
  ]
}
```

In version 2.32 this works.

**Comment by sverdlov93** [comment]
Hi @g3n35i5 and @famod,
Thanks for reporting this issue.
Our apologies for the inconvenience caused by this.
Are you using a reference token or a full JWT token? Also, can you please test the same command without the user field?

**Comment by sverdlov93** [comment]
Hi @g3n35i5 and @famod,
[API key](https://jfrog.com/knowledge-base/platform-api-key-deprecation-and-the-new-reference-tokens/) should be used as a password and not as an access token.
To avoid breaking users that used it as access-token we made it work now with a warning.
[JFrog CLI 2.34.0](https://github.com/jfrog/jfrog-cli/releases/tag/v2.34.0)
Looking forward to your feedback on it.

**Comment by sverdlov93** [comment]
@famod 2.34 released a few minutes ago.
Glad it helped!

**Comment by mjkl-gh** [comment]
@sverdlov93 

I'm encountering the error, but 2.33 hasn't hit the apt repo yet. Any timeline when this will released?

**Comment by sverdlov93** [comment]
@mjkl-gh 
Do you mean 2.34?
Also, did you try using it as a password(as it should be used)?
`jf some command --user="your username" --password="your API key"`

**Comment by mjkl-gh** [comment]
> @mjkl-gh Do you mean 2.34? Also, did you try using it as a password(as it should be used)? `--user="your username" --password="your API key"`

Yes we changed it in our script, but I was wondering about the release of 2.34 at the same time.

**Comment by sverdlov93** [comment]
I believe it will appear soon. It sometimes takes some time for new versions to appear on some tool providers.
