### ISSUE TITLE
Formatting characters / gibberish in console on server 2012r2

### ISSUE THREAD

**Issue by brhodes-pcty** [jfrog/jfrog-cli#1815]
### Describe the bug

When using some commands of jf.exe in a windows server 2012r2 console, formatting displayed is a mess, where it appears to be displaying formatting or spacing characters. Specifically with the ADD or EDIT commands

### Current behavior

See Describe section.

### Reproduction steps

run the following to see this behavior.

jf c add target-server

If "target-server" is already configured, the below will repro as well:

jf c edit target-server

![error](https://user-images.githubusercontent.com/110056731/214344796-b8150ca1-5228-4d88-89f6-c9b26344904d.png)

### Expected behavior

Readable formatting - see screenshot of normal behavior, in this case from a Server 2019 box.

![correct](https://user-images.githubusercontent.com/110056731/214344054-c24f62ca-183d-4dcf-955e-b4611dd5cafa.png)

### JFrog CLI version

2.33.00

### Operating system type and version

Windows Server 2012r2

**Comment by sverdlov93** [comment]
Hi @brhodes-pcty, 
It looks like your terminal is not supporting colors.
We show colors on windows only when the `WT_SESSION` environment variable is not empty.
Can you please provide that env's value?

Also, a quick workaround will be to add the env: `TERM  = "dumb"` or `NO_COLOR="true"`

**Comment by brhodes-pcty** [comment]
Ty for your reply -- near as I can tell, WT_SESSION is undefined on both a "working" 2019 box, and the non-working 2012r2 box.

Additionally, I tried adding the two environment variables mentioned, and the behavior did not change in either case :/

**Comment by sverdlov93** [comment]
Hi @brhodes-pcty,
Thanks for reporting this issue.
Our apologies for the inconvenience caused by this.
This PR - https://github.com/jfrog/jfrog-cli-core/pull/679 should fix it.
I will update this thread once the next release will be out.
