### ISSUE TITLE
Flag "--watches" missing from "jf bs" command

### ISSUE THREAD

**Issue by DavidRadoorHummel** [jfrog/jfrog-cli#1816]
### Describe the bug

When invoking the command:

`jf bs buildName 1`

You get the output:

```
15:21:27 [Info] Scan of build buildNameis in progress
15:21:27 [Info] Waiting for Build Scan to complete...
15:21:28 [Info] The scan data is available at: https://REDACTED.com/ui/builds/buildName/1/REDACTED/xrayData?buildRepo=artifactory-build-info
The full scan results are available here: C:\Users\REDACTED\AppData\Local\Temp\jfrog.cli.temp.-1674656488-166575874

Note: no context was provided, so no policy could be determined to scan against.
You can get a list of custom violations by providing one of the command options: --watches, --repo-path or --project.
Read more about configuring Xray policies here: https://www.jfrog.com/confluence/display/JFROG/Creating+Xray+Policies+and+Rules
Below are all vulnerabilities detected.
```

However, from the suggested command options only `--project` is available, neither `--watches` nor `--repo-path` is available as commands.

Attempting to use `--watches` produces the following error:

```
jf bs buildName 1  --watches=Default_Watch
15:22:55 [Error] Wrong number of arguments (3). You can read the documentation at https://www.jfrog.com/confluence/display/CLI/JFrog+CLI

Name:
  jf.exe build-scan - Scan a published build-info with Xray.

Usage:
  jf.exe bs [command options] <build name> <build number>

Arguments:
  build name
    Build name.

  build number
    Build number.

Options:
  --access-token      [Optional] JFrog access token.
  --extended-table    [Default: false] Set to true if you'd like the table to include extended fields such as 'CVSS' & 'Xray Issue Id'. Ignored if provided 'format' is not 'table'.
  --fail              [Default: true] Set to false if you do not wish the command to return exit code 3, even if the 'Fail Build' rule is matched by Xray.
  --format            [Default: table] Defines the output format of the command. Acceptable values are: table, json, simple-json and sarif.
  --password          [Optional] JFrog password.
  --project           [Optional] Artifactory project key.
  --rescan            [Default: false] Set to true when scanning an already successfully scanned build, for example after adding an ignore rule.
  --server-id         [Optional] Server ID configured using the config command.
  --url               [Optional] JFrog Xray URL.
  --user              [Optional] JFrog username.
  --vuln              [Default: false] Set to true if you'd like to receive all vulnerabilities, regardless of the policy configured in Xray.


15:22:55 [Error] Wrong number of arguments (3).
```

The result is that _all_ vulnerabilities are discovered for the specified build and you cannot reduce it by providing a watch.

### Current behavior

`jf bs` does not support `--watches` argument, despite claiming so, when invoked.

### Expected behavior

`jf bs` supports the `--watches` flag to scope the scanning to a specific watch.

### JFrog CLI version

2.30.0

### Operating system type and version

Tried on Windows 10 and Ubuntu 20.04 LTS

### JFrog Artifactory version

7.49.5

### JFrog Xray version

3.59.7

**Comment by sverdlov93** [comment]
Hi @DavidRadoorHummel,
`jf bs` command does not support watches of repo path flags.
Filtering build violations should be achieved by setting watches and policies and connecting them to the specific build using the UI (and also select the build for indexing on Xray UI)
The warning above should not appear on the `jf bs` command.
Did you use the '--vuln' flag? or any other flag?
Also, can you run export `JFROG_CLI_LOG_LEVEL=TRUE` and run the command again and share the full logs received?

**Comment by DavidRadoorHummel** [comment]
Hi @sverdlov93,
Thank you for your quick reply :)
Yes, you are absolutely correct, I did notice the initial command had the "--vuln' flag.

Am I correct in assuming that JFrog CLI build scan, will automatically scan it against the policies defined for the specified build?

If that is the case, how would developers overwrite this? Let's say they want to scan their build against a different watch, than what is defined for their build.
How would they go about this?

Best regards
David

FYI I love JFrog CLI, we use it for so many things and it is super intuitive, great work on this!

**Comment by sverdlov93** [comment]
Hi @DavidRadoorHummel,
`jf bs` is automatically against policies defined by the specific build.
Adding `--vuln` flag is showing an additional table with all vulnerabilities found regardless of the policies and watches.
A Build is something that has already been published to the artifactory so it's already associated with the policies assigned to it.
For developers, we have other ["shift left" tools to scan their code before publishing it.](https://jfrog.com/blog/scanning-dependencies-in-your-sources-using-jfrog-cli-and-xray/)

**Comment by eyalbe4** [comment]
We're also super happy to hear you're enjoying JFrog CLI and that it brings value to you @DavidRadoorHummel.
Thanks so much for sharing this with us!

**Comment by DavidRadoorHummel** [comment]
Thanks for your replies, both of you!
I will go ahead and close this, as there is no issue and you clarified the situation :)
I wish you both a good day!
