### ISSUE TITLE
JFrog CLI to support scan result in the CI output  with colour code to identify/spot the critical/high vulnerabilities

### ISSUE THREAD

**Issue by janardhanajl** [jfrog/jfrog-cli#1820]
**Feature description:**

Running the JFrog CLI locally provides  output, with colours and icons. However running this in CI (GitLab)does not yield any colour/icons.

**Expectation:**

Within CI, the same results are output, however the Severity column has no styling/emojis. Hence requesting for a way to force the JFrog CLI to parse/output colour in the CI.

Example screenshot

<img width="944" alt="image" src="https://user-images.githubusercontent.com/47290578/215065692-f10e3b36-2530-4d3e-8b0c-fcc1da8c490d.png">
<img width="892" alt="image" src="https://user-images.githubusercontent.com/47290578/215065751-dc0cdc89-23d9-4413-b80a-78450a1c28da.png">

**Comment by sverdlov93** [comment]
Hi @janardhanajl, mostly CI consoles do not support colors or emojis.
Also, you can see that the above console can't even display straight lines of the table columns and rows.

**Comment by jitterjuice** [comment]
Hi @sverdlov93 , I raised this feature request - generally that is true regarding CI consoles and color/emoji support however GitLab CI does support colors and emoji for the most part, hence having a force enabled feature flag/environment variable would provide for easier viewing, especially for critical elements that should require more attention.

**Comment by eyalbe4** [comment]
Thank you @jitterjuice. This is indeed important.
Let us work on this. We'll share an update here.

**Comment by sarao1310** [comment]
Hi @janardhanajl, we fixed this issue, and it has been released!
