### ISSUE TITLE
jf docker scan: Provide an option to filter vulnerabilities by severities

### ISSUE THREAD

**Issue by harshagv** [jfrog/jfrog-cli#1836]
**Is your feature request related to a problem? Please describe.**
While performing the scan of any docker (containers) image using Jfrog Xray, we currently don't have the option to filter vulnerabilities by severities

**Describe the solution you'd like to see**
Command line option to option to filter vulnerabilities by severities
```bash
jf docker scan <IMAGE:TAG> --severity="HIGH,CRITICAL"
```

For example: trivy scanner provides an option that meets this requirement
```bash
trivy image --severity HIGH,CRITICAL httpd:latest
```

**Describe alternatives you've considered**
Currently, I am using jq filter to list only the vulnerabilities by severities and it only helps in case of `--format=json|simple-json`. But this would not help in case of  `--format=table|sarif`
e.g: 

```bash
jq -r '.[] | (.vulnerabilities[] | select(.severity == "High" or .severity == "CRITICAL"))
```

**Additional context**

**Comment by ventz** [comment]
+1 on this request!!

Also - please provide a way to filter out things that have no fix (similar to Trivy, Snyk, Orca, etc)

**Comment by sverdlov93** [comment]
Hi @harshagv and @ventz,
The above functionality can be achieved by using JFrog Xray Watches functionality.
Create a Watch on Xray (or use an existing one) and then connect a policy to it according to your requirements:
![Screenshot 2023-03-21 at 16 43 21](https://user-images.githubusercontent.com/29822394/226642297-0e916bf3-cfd6-41bd-8642-2806718b0d23.png)

Then you can run `jf docker scan / jf scan / jf audit` commands with the `--watches` flag: 

![Screenshot 2023-03-21 at 16 44 43](https://user-images.githubusercontent.com/29822394/226642732-0a66bcf0-b6f2-4a17-b67d-8acdfa058bcc.png)

For example: 
`jf docker scan alpine:latest --watches=mywatch`

**Comment by ventz** [comment]
@sverdlov93 Thank you for mentioning this!

Would it be possible to add stand alone client-side filtering -- effectively a json filter similar to @harshagv's jq select, to the binary itself?

The use case being that when this is distributed in an action to groups/teams, it would require for them to pre-create this, rather than just have a "drop in" solution to scan containers.

We are seeing most groups going with Trivy due to the "drop in" container scanning ability within GitHub Actions. The results are pulled/filtered from the json output, and then github issues are created for each.

**Comment by harshagv** [comment]
@sverdlov93 Thanks for answering! 

Yes, I was aware of [configuring xray watches](https://www.jfrog.com/confluence/display/JFROG/Configuring+Xray+Watches) along with a policy rule to fail the CI/CD build or exit CLI with non-zero status upon discovering the minimum CVE severity filter! 

For time being I am actually using JFrog xray docker scan with watches! 😄 
```bash
jf docker scan <IMAGE:TAG> --watches=<WATCH-NAME> 
```
displayed the output in default table format

Though watches is more of a 1-time configuration to be added in the JFrog console but its not flexible enough to change the severity filter in CLI during CI/CD builds (I am only able to think about this use case at this moment but there could be other use cases too!).

but this request was more about out of the box CLI option if available to filter vulnerabilities by severities while performing docker scan! As you said, I will wait for the feature available in https://github.com/jfrog/frogbot to be propagated to `jf docker scan`

**Comment by sverdlov93** [comment]
Hi @harshagv and @ventz,
Following our recent discussion we decided to implement the above requested features.
[JFrog CLI 2.37.0](https://github.com/jfrog/jfrog-cli/releases/tag/v2.37.0) has been released and includes the following 2 flags for `jf audit / jf scan / jf docker scan` commands:
 --min-severity         [Optional] Set the minimum severity of issues to display. The following values are accepted: Low, Medium, High, or Critical.
--fixable-only      [Optional] Set to true if you wish to display issues with a fixed version only.

Looking forward to your feedback on it.

**Comment by sverdlov93** [comment]
All credit goes to @omerzi 👑

**Comment by ventz** [comment]
@sverdlov93 Getting an error that the flag does not exist:

```
% jf -v                                                                     
jf version 2.37.0

% jf docker scan --min-severity High --fixable-only true --format json nginx
10:45:12 [🔵Info] Log path: /Users/user/.jfrog/logs/jfrog-cli.2023-05-03.10-45-12.22001.log
10:45:13 [🚨Error] failed running command: 'docker save --min-severity -o /var/folders/vz/f_bzz__j26q5rqbtjcym5jb40000gn/T/jfrog.cli.temp.-1683125112-3862741077/image.tar' with error: exit status 125 - unknown flag: --min-severity
See 'docker save --help'.
```

Unrelated, just FYI - there's an extra period in Options for `jf docker scan` under "fixable-only":
(and another floating period on the end of that line)

```
--fixable-only .  
```

**Comment by sverdlov93** [comment]
Hi @ventz,
Thanks for letting us know.
We actually just removed that dot already.
Regarding the first issue, please run `jf docker scan nginx --min-severity High --fixable-only true --format json` where the image name is the first one.
We will fix this order issue ASAP.

**Comment by sverdlov93** [comment]
Hi @ventz, 
Please my edit to the above comment.
