### ISSUE TITLE
File spec example 6 from docs fails with "an archive's target cannot be a directory"

### ISSUE THREAD

**Issue by flcdrg** [jfrog/jfrog-cli#1847]
### Describe the bug

Under https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-FileSpecSchemas, example 6 is:

```json
{
  "files": [
    {
      "pattern": "resources/",
      "archive": "zip",
      "target": "all-my-frogs/"
    }
  ]
}
```

### Current behavior

Fails with "[Error] an archive's target cannot be a directory"

### Expected behavior

Not fail

### JFrog CLI version

2.25.5

### Operating system type and version

Ubuntu

**Comment by RobiNino** [comment]
Fixed, thanks a lot @flcdrg !
