### ISSUE TITLE
getCli.sh and the gitlab setup for self hosted Artifactory

### ISSUE THREAD

**Issue by usinelogicielle** [jfrog/jfrog-cli#1857]
We have our self hosted version of Artifactory with a go remote repository of jfrog-cli.
We would like use the getCli.sh or extends job of Gitlab to install Jfrog-cli. But there are URLs from internet. 

We would like these scripts can be overriden with specific URL from our self hosted Artifactory.

**Comment by RobiNino** [comment]
Hi @usinelogicielle ,
This is under development will be available in the near future.
Thanks!

**Comment by RobiNino** [comment]
Hi @usinelogicielle ,
A new version of the JFrog Setup for GitLab script has been released, and includes support for downloading JFrog CLI from a remote repository ([see the instructions](https://github.com/jfrog/gitlab-templates#downloading-the-setup-jfrog-script-and-jfrog-cli-from-artifactory)).

If you already included the setup in your script, please note the include statement has slightly changed as described in #1882.

We'd appreciate your feedback for it, thanks!

**Comment by usinelogicielle** [comment]
Hi @RobiNino,

Our last configuration is to download jfrog-cli from the remote repository with a CURL and environment variables. 
Not sure if your script will add something.
Sorry to not test it.

I closed the issue
