### ISSUE TITLE
jfrog logs info on stderr

### ISSUE THREAD

**Issue by joergsesterhenn** [jfrog/jfrog-cli#1859]
### Describe the bug

Running a Buildscan jfrog cli returns info logs on the stderr while there is no error.

### Current behavior

Current behaviour - the following is printed to stderr when we run a jf build-scan

10:50:17 [🔵Info] Scan of build BUILDNAME is in progress
10:50:17 [🔵Info] Waiting for Build Scan to complete...
10:50:17 [🔵Info] The scan data is available at: URLTOBUILD

### Reproduction steps

Run a scan on any existing builds like
 
jf build-scan BUILDNAME 123

### Expected behavior

Log infos to stdout.

We currently run execute jfrog cli via npm with execSync and the infos get swallowed because there are logs on stderr even though there is no error.

### JFrog CLI version

2.34.6

### Operating system type and version

ubuntu 20.04

### JFrog Artifactory version

 7.41.13

### JFrog Xray version

3.59.7

**Comment by joergsesterhenn** [comment]
Same goes for debug logs! Please don't missuse stderr.

**Comment by eyalbe4** [comment]
This behavior is expected @joergsesterhenn.
All of jfrog-cli's log messages are added to stderr. This is a common practice among CLI utilities, and it is done to allow having the command output only added to stdout.

**Comment by joergsesterhenn** [comment]
Well in this case consider adding the link to the scan result as output.

We need that link and having to fish for it in the stderr is no fun.

I still think it is weird to write infos to an error stream. Could you point to any other cli tools that do this?

If I want to filter I can easily do this by setting the log level...

**Comment by joergsesterhenn** [comment]
Does this contain the link to the online result in Xray? That's what we need.

**Comment by sverdlov93** [comment]
Yes, `xray_data_url` is one of the parameters inside the JSON response.
