### ISSUE TITLE
Strange use of a replace in release 2.34.6

### ISSUE THREAD

**Issue by nantes44-github** [jfrog/jfrog-cli#1861]
https://github.com/jfrog/jfrog-cli/blob/801912f5aaf80722046aee22442f6058ddb6679c/go.mod#L125

Hi, is this normal to force use of a fork of jfrog-cli-core while it is a release?

best regards

**Comment by yahavi** [comment]
Thanks, @nantes44-github.
You are right. This is not normal and not according to our high standards. Our policy is to fix the replacement before merging and remove it before releasing.
@gailazar300 is from our team and therefore there is no risk of having any security issues.

We'll raise this concern in our next team meetings.
