### ISSUE TITLE
Simplify self-signed certificate use case

### ISSUE THREAD

**Issue by Karreg** [jfrog/jfrog-cli#191]
Hello,

We are working in a company that is using self signed certificates everywhere.
The issue is that it's complicated to get them, because there are copies of copies of copies. It's really hard to find the correct certificates, adn also it can't be used ins automated environment.

I could see why JFrog pushes to the ~/.jfrog/security stuff, but this is blocker for us. 

Almost every tool as an option of "insecure". Could the JFrog CLI have this option? If would be far more useful. In the current situation, we can't use JFrog CLI. It's easier for use to use cURL to communicate with our Artifactory because of that, which is both painful and ridiculous.

I hope this will change, for the best :)

But if there are strong reasons for not doing that, I'm open to have them too... It won't change the fact that JFrog CLI can't be used, but at least we will be able to communicate to our developers on why they have to use cURL...

Thanks!

**Comment by eyalbe4** [comment]
@Karreg - 
@RobiNino added support for this and pushed https://github.com/jfrog/jfrog-cli-go/commit/a4201f86e614400e0d124e002dda7ec2a2139eb1 into the dev branch.
This should be included in the upcoming release.

**Comment by eyalbe4** [comment]
@Karreg - check out the *--insecure-tls* command option.
It is available in the latest release.
Looking forward to your feedback for this.
