### ISSUE TITLE
Checksum validation on download causes error with filtered artifacts

### ISSUE THREAD

**Issue by al4** [jfrog/jfrog-cli#200]
If I download a filtered artifact, the downloaded file's checksum does not match the server's. This is expected, as the file stored on the server is not the same file that's presented to the client.

```
jfrog rt download  --url https://<company>.jfrog.io/<artifactory> \
 --apikey $apikey \
 --flat \
 /templates/foo.conf
[Info] Searching items to download...
[Info] [Thread 2] Downloading templates/foo.conf
[Error] [Thread 2]  Received an error: Checksum mismatch for foo.conf, expected: 93401a2751b6628a68393d77bf902ca78ea9b912, actual: 0e166223b3cebaaf7e248cce7080465bdd443350
[Error] Checksum mismatch for foo.conf, expected: 93401a2751b6628a68393d77bf902ca78ea9b912, actual: 0e166223b3cebaaf7e248cce7080465bdd443350
{
  "status": "failure",
  "totals": {
    "success": 0,
    "failure": 1
  }
}
[Error] Download finished with errors. Please review the logs
```

A workaround for this is to append `|| true`, or better still `|| test -f foo.conf`, but the jfrog client shouldn't error in this case. If verification of filtered artifacts is not possible, there should be an option to disable verification.

**Comment by eyalbe4** [comment]
@al4,
Can you please share some more information about the use case? This may help us decide about the best approach in such scenarios.
What is the filtered file used for? Why is it filtered and how does it get filtered?

**Comment by al4** [comment]
@eyalbe4 we're using filtered resources as per https://www.jfrog.com/confluence/display/RTF/Filtered+Resources

The immediate use case is a workstation build script that downloads maven, pip etc config files from artifactory, pre-populated (by the built-in freemarker filtering) with the user's name and api key. But I expect it would apply to any automation that shells out to jfrog-cli and downloads a filtered resource.

Personally I think the best approach would be to allow the user to disable verification, as for most use cases it is correct that jfrog-cli exits with an error when the checksum doesn't match.

**Comment by al4** [comment]
To aid in prioritisation I should add that the workaround above is an acceptable solution to us, and I'd totally understand if it was not a high priority!

I just think the behaviour is incorrect as far as Artifactory is concerned, and that it shouldn't really be an error if the checksum of the template doesn't match the downloaded resource.

**Comment by SteveNewson** [comment]
This is still an issue. The documentation suggests that this should be possible:
https://www.jfrog.com/confluence/display/JFROG/Maven+Repository#MavenRepository-ProvisioningDynamicSettingsforUsers
```
Provisioning Dynamic Settings for Users
You can deploy and provision a dynamic settings template for your users.

Once downloaded, settings are generated according to your own logic and can automatically include user authentication information.

For more details, please refer to the Provisioning Build Tool Settings under Filtered Resources.
```
The problem here is that you cannot use this through the JFrog CLI as it checks the checksum. 

See also this documentation: https://www.jfrog.com/confluence/display/JFROG/Filtered+Resources

**Comment by eyalbe4** [comment]
Thanks for sharing this requirement with us @SteveNewson.
If the `jf rt download` command included an option for disabling the checksum validation performed after the download, that would resolve the issue, right?

**Comment by SteveNewson** [comment]
Yes. I think the split of client and CLI makes this slightly harder, but
clearly not impossible. It could be just not supplying the checksum to the
http client, though that feels a little hacky.

**Comment by SteveNewson** [comment]
It's simple enough to reproduce. Create a filtered resource somewhere (we're using `/configuration-templates/gradle/gradle.properties`):
```
jfrogIoUsername=${security.getCurrentUsername()}
jfrogIoPassword=<#if security.getEscapedEncryptedPassword()??>${security.getEscapedEncryptedPassword()}<#else><!-- Insert your API key here --></#if>
```
Then issue an rt download command:
```
jfrog rt download --flat=true /configuration-templates/gradle/gradle.properties
```
That'll give you this:
```
13:52:12 [🔵Info] Log path: /Users/steve.newson/.jfrog/logs/jfrog-cli.2022-08-04.13-52-12.95777.log
13:52:13 [🚨Error] download finished with errors, please review the logs
```
The file will be downloaded successfully (and filtered), but you'll get an error exit code.

I think I'd like something like:
```
jfrog rt download --flat=true --ignore-checksum-failures=true /configuration-templates/gradle/gradle.properties
```
Which probably needs to omit the SHA1 from the file details when calling the http client (that's probably hacky though), or better still enhance the client to include a flag in the request details.

**Comment by SteveNewson** [comment]
Fixed by this: https://github.com/jfrog/jfrog-cli/pull/1660

**Comment by al4** [comment]
Closing this as it's fixed - thank you @SteveNewson!
