### ISSUE TITLE
ERROR invalid Action type. Must be `func(*Context`)` or `func(*Context) error).

### ISSUE THREAD

**Issue by jkosek** [jfrog/jfrog-cli#2046]
### Describe the bug

After following the installation guide:
```
wget -qO - https://releases.jfrog.io/artifactory/jfrog-gpg-public/jfrog_public_gpg.key | sudo apt-key add -
echo "deb https://releases.jfrog.io/artifactory/jfrog-debs xenial contrib" | sudo tee -a /etc/apt/sources.list &&    sudo apt update &&
sudo apt install -y jfrog-cli-v2-jf &&
jf intro
```

The `jf intro` intro command exit with error
```
ERROR invalid Action type. Must be `func(*Context`)` or `func(*Context) error).
```

### Current behavior

Command exit with error:
```
ERROR invalid Action type. Must be `func(*Context`)` or `func(*Context) error).
```

### Reproduction steps

```
docker run -it python:3.8 bash

wget -qO - https://releases.jfrog.io/artifactory/jfrog-gpg-public/jfrog_public_gpg.key | apt-key add -

echo "deb https://releases.jfrog.io/artifactory/jfrog-debs xenial contrib" | tee -a /etc/apt/sources.list && apt update &&
apt install -y jfrog-cli-v2-jf

jf intro
```

### JFrog CLI version

2.41.0

### Operating system type and version

Ubuntu 22.04/Debian 12

**Comment by kinderlars** [comment]
Same issue here.

**Comment by sverdlov93** [comment]
Hi @kinderlars and @jkosek 
Thanks for reporting this issue.
Our apologies for the inconvenience caused by this.
This [PR](https://github.com/jfrog/jfrog-cli/pull/2047) should fix it.
I will update this thread once the next release will be out.

**Comment by eyalbe4** [comment]
Version 2.41.1 fixes this issue.
