### ISSUE TITLE
Scan Generated SARIF file invalid

### ISSUE THREAD

**Issue by rseeton** [jfrog/jfrog-cli#2135]
### Describe the bug

SARIF files generated from the **_jf scan_** command are not Valid SARIF files and are not interoperable with other tools (i.e. GitHub Advanced Security) 

### Current behavior

Generation of a SARIF file from our package completes successfully ( [jf_scan_sarif.txt](https://github.com/jfrog/jfrog-cli/files/12352204/jf_scan_sarif.txt)):

jf s ./tangerine-release*.tar.gz --format sarif

However, the resulting SARIF file (attached) fails the SARIF file validation and cannot be loaded to the target system (GHAS in our case).

We have analyzed the resulting file using these sites, which provide notes on the validation failures:

https://sarifweb.azurewebsites.net/Validation 
https://www.jsonschemavalidator.net/

### Reproduction steps

Scan package
Save SARIF format output
Analyze SARIF output

### Expected behavior

SARIF file generated should meet the SARIF v2.1.0 specification to allow inter-operability.

### JFrog CLI version

jf version 2.45.0

### Operating system type and version

Ubuntu 20.0.4

### JFrog Artifactory version

Enterprise Plus 7.55.10 rev 75510900 

### JFrog Xray version

xray_version:3.65.2 xray_revision:bca527a

**Comment by attiasas** [comment]
Hi @rseeton, thank you for reporting this issue! 
we are currently working on fixing it so it will meet the SARIF v2.1.0 specification.
It will be available soon and we will update you as soon as possible.

**Comment by attiasas** [comment]
Hi @rseeton, v2.47.0 has been released and should fix the Sarif generation, it should be valid and contain much more information now. let us know if there are any issues left.

**Comment by attiasas** [comment]
@davidka91, thank you for bringing this issue to my attention. I have identified some of the issues that causes your output to fail.
you can follow this PR for a fix on this:
https://github.com/jfrog/jfrog-cli-core/pull/968

In addition "Sca" = "software component analysis" We will consider renaming it to "SCA" or something more descriptive.

**Comment by rseeton** [comment]
@attiasas  - Excellent, thanks for the updates.  
The generated SARIF from JFrog CLI 2.48.0 is now loading cleanly to the GHAS system. 

One outstanding issue:
Running the generated SARIF file through the JSON Validator ( https://www.jsonschemavalidator.net/ ), the system is failing on the follwing snippet:
-------------
         "locations": [
           {
             "physicalLocation": {
               "artifactLocation": {
                 **"uri": " Package Descriptor"**
               }
             }
           }
         ]


Message:
String ' Package Descriptor' does not validate against format 'uri-reference'.
Schema path:
https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json#/definitions/artifactLocation/properties/uri/format
-------------
This is not a show-stopper (the SARIF file still loads), but it would be good to have this correctly populated.

Thanks.

**Comment by attiasas** [comment]
Hi @rseeton and @davidka91 CLI v2.49.0 has been released and should fix the issues raised here.
Let me know if it is fixed or if anything else is missing or failing.

**Comment by rseeton** [comment]
Resolved in 2.50.2
