### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference is back in setup-jfrog-cli-github-action/2.4.1

### ISSUE THREAD

**Issue by AidarGatin** [jfrog/jfrog-cli#2159]
### Describe the bug

Vulnerability scan fails with error 

jf config add \
  jf config add \
  --url=https://*******.jfrog.io \
  --user=*** \
  --*** \
  --interactive=false
  jf audit --watches=ci-build-scan --fail=false --mvn
  jf docker scan ************* --watches=ci-build-scan --fail=false
  shell: /usr/bin/bash -e {0}
  env:
    PUBLISH_IMAGE: true
    SCAN_CODE: true
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.20-8/x64
    JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.20-8/x64
    JFROG_CLI_ENV_EXCLUDE: *password*;*secret*;*key*;*token*;*auth*;JF_ARTIFACTORY_*;JF_ENV_*;JF_URL;JF_USER;JF_PASSWORD;JF_ACCESS_TOKEN
    JFROG_CLI_OFFER_CONFIG: false
    JFROG_CLI_BUILD_NAME: CI
    JFROG_CLI_BUILD_NUMBER: 212
    JFROG_CLI_BUILD_URL: **********
    JFROG_CLI_USER_AGENT: setup-jfrog-cli-github-action/2.4.1

### Current behavior

Returns error : 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x130 pc=0xc8a3d6]

goroutine 1 [running]:
github.com/jfrog/jfrog-cli-core/v2/common/commands.(*ConfigCommand).resolveServerId(...)
	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.41.0/common/commands/config.go:318
github.com/jfrog/jfrog-cli-core/v2/common/commands.(*ConfigCommand).prepareConfigurationData(0xc00016c568)
	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.41.0/common/commands/config.go:287 +0x156
github.com/jfrog/jfrog-cli-core/v2/common/commands.(*ConfigCommand).config(0xc00016c568)
	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.41.0/common/commands/config.go:162 +0x25
github.com/jfrog/jfrog-cli-core/v2/common/commands.(*ConfigCommand).Run(0xc00016c568)
	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.41.0/common/commands/config.go:132 +0x271
github.com/jfrog/jfrog-cli/config.addOrEdit(0xc00027e2c0, 0x0)
	/var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/config/cli.go:139 +0x146
github.com/jfrog/jfrog-cli/config.addCmd(0xc00027e2c0)
	/var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/config/cli.go:94 +0x65
github.com/urfave/cli.HandleAction({0xf039a0?, 0x114c530?}, 0x3?)
	/root/go/pkg/mod/github.com/urfave/cli@v1.[22](https://github.com/archinsurance/aigi-dig-ds-api-policy/actions/runs/5961111428/job/16177158121#step:9:23).14/app.go:5[24](https://github.com/archinsurance/aigi-dig-ds-api-policy/actions/runs/5961111428/job/16177158121#step:9:25) +0x50
github.com/urfave/cli.Command.Run({{0x1070340, 0x3}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x10bfc7e, 0x1c}, {0x0, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/urfave/cli@v1.22.14/command.go:175 +0x67b
github.com/urfave/cli.(*App).RunAsSubcommand(0xc00064e1c0, 0xc00027e420)
	/root/go/pkg/mod/github.com/urfave/cli@v1.22.14/app.go:405 +0xe87
github.com/urfave/cli.Command.startApp({{0x1077c9c, 0x6}, {0x0, 0x0}, {0xc0003c20a0, 0x1, 0x1}, {0x109809f, 0x10}, {0x0, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/urfave/cli@v1.22.14/command.go:380 +0xb7f
github.com/urfave/cli.Command.Run({{0x1077c9c, 0x6}, {0x0, 0x0}, {0xc0003c20a0, 0x1, 0x1}, {0x109809f, 0x10}, {0x0, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/urfave/cli@v1.22.14/command.go:103 +0x845
github.com/urfave/cli.(*App).Run(0xc00017a700, {0xc000122000, 0x7, 0x7})
	/root/go/pkg/mod/github.com/urfave/cli@v1.22.14/app.go:277 +0xb87
main.execMain()
	/var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/main.go:129 +0x353
main.main()
	/var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/main.go:74 +0x[25](https://github.com/archinsurance/aigi-dig-ds-api-policy/actions/runs/5961111428/job/16177158121#step:9:26)
Error: Process completed with exit code 2.

### JFrog CLI version

setup-jfrog-cli-github-action/2.4.1

### Operating system type and version

Unix

**Comment by yahavi** [comment]
Thank you for bringing up this matter, @AidarGatin. 
This issue should be fixed in the latest release, [2.46.1](https://github.com/jfrog/jfrog-cli/releases/tag/v2.46.1), by https://github.com/jfrog/jfrog-cli-core/pull/915. 

We'd appreciate your feedback on that.

**Comment by AidarGatin** [comment]
I don't have any issues any more. Thank you
