### ISSUE TITLE
Remote repository creation completely ignores certain fields

### ISSUE THREAD

**Issue by isaac-s** [jfrog/jfrog-cli#2172]
### Describe the bug

When using the `jf rt repo-create` command to create a remote repository based on a template created using `jf rt rpt`, certain fields are ignored, such as:

`retrievalCachePeriodSecs`
`assumedOfflinePeriodSecs`
`missedRetrievalCachePeriodSecs`
`failedRetrievalCachePeriodSecs`

### Current behavior

Remote repository is created without the provided values.
No errors are reported.
However, the values set for the fields I specified, don't appear. The defaults appear instead.

### Reproduction steps

Use JSON file:

```
{
  "key": "docker-remote",
  "packageType": "docker",
  "repoLayoutRef": "simple-default",
  "description": "Smart Remote for docker-remote",
  "rclass": "remote",
  "url": "https://my.example.com/artifactory/api/docker/docker-local",
  "synchronizeProperties": "true",
  "contentSynchronisation": "true,true,true,true",
  "retrievalCachePeriodSecs": "0",
  "assumedOfflinePeriodSecs": "0",
  "missedRetrievalCachePeriodSecs": "0",
  "failedRetrievalCachePeriodSecs": "60",
  "username": "xxx",
  "password": "xxx"
}
```

As input for `jf rt repo-create`.

### Expected behavior

The cache parameters should have the specified values.

### JFrog CLI version

2.46.2

### Operating system type and version

Ubuntu 22 LTS

### JFrog Artifactory version

7.63.12

**Comment by sverdlov93** [comment]
Hi @isaac-s 
Thanks for reporting this issue.
Our apologies for the inconvenience caused by this.
This [PR](https://github.com/jfrog/jfrog-client-go/pull/834) should fix it.
I will update this thread once the next release will be out.
