### ISSUE TITLE
JFROG_CLI_RELEASES_REPO doesn't work on private Artifactory

### ISSUE THREAD

**Issue by usinelogicielle** [jfrog/jfrog-cli#2231]
### Describe the bug

Configuring the new environment variable JFROG_CLI_RELEASES_REPO, 
and trying using "jfrog mvn". 
Jfrog can't download the build-info-extractor-maven3 jar because the URL is wrong.
It seems Jfrog add repo name from JFROG Artifactory.

### Current behavior

```
export JFROG_CLI_RELEASES_REPO="token_artifactory_serverid/jfrogcli-maven-remote"
```
jfrogcli-maven-remote is the name of our remote repository pointing to "https://oss.jfrog.org/artifactory/oss-release-local"

```
$jfrog mvn-config --server-id-deploy token_artifactory_serverid --repo-deploy-snapshots testci-maven-dev --repo-deploy-releases testci-maven --server-id-resolve token_artifactory_serverid --repo-resolve-releases testci-maven --repo-resolve-snapshots testci-maven-dev

$jfrog mvn clean install -B -Dartifactory.publish.artifacts=false
14:58:37 [Debug] JFrog CLI version: 2.48.0
14:58:37 [Debug] OS/Arch: linux/amd64
14:58:39 [Debug] failed while trying to check latest JFrog CLI version: couldn't get latest JFrog CLI latest version info from GitHub API: Get "https://api.github.com/repos/jfrog/jfrog-cli/releases/latest": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
14:58:39 [Debug] Saving build general details at: /home/ad/<username>/.jfrog/builds/43f7e3bd69def55d0da30b88b42048bf646b4d44e94b9d88410956223da85394/partials
14:58:39 [Debug] Usage Report: Sending info...
14:58:39 [🔵Info] Downloading JFrog's Dependency from https://<ARTIFACTORY_HOST>/artifactory/jfrogcli-maven-remote/artifactory/oss-release-local/org/jfrog/buildinfo/build-info-extractor-maven3/2.41.5/build-info-extractor-maven3-2.41.5-uber.jar
14:58:39 [Debug] Sending HTTP GET request to: https://<ARTIFACTORY_HOST>/artifactory/api/system/version
14:58:39 [Debug] Sending HTTP HEAD request to: https://<ARTIFACTORY_HOST>/artifactory/jfrogcli-maven-remote/artifactory/oss-release-local/org/jfrog/buildinfo/build-info-extractor-maven3/2.41.5/build-info-extractor-maven3-2.41.5-uber.jar
14:58:39 [Debug] Artifactory response: 200
14:58:39 [Debug] JFrog Artifactory version is: 7.55.3
14:58:39 [Debug] Sending HTTP POST request to: https://<ARTIFACTORY_HOST>/artifactory/api/system/usage
14:58:40 [🟠Warn] Failed to get remote file details.
 Got: server response: 404
14:58:40 [Debug] Sending HTTP GET request to: https://<ARTIFACTORY_HOST>/artifactory/jfrogcli-maven-remote/artifactory/oss-release-local/org/jfrog/buildinfo/build-info-extractor-maven3/2.41.5/build-info-extractor-maven3-2.41.5-uber.jar
14:58:40 [🚨Error] server response: 404
```

The URL to download the jar is wrong

https://<ARTIFACTORY_HOST>/artifactory/jfrogcli-maven-remote/artifactory/oss-release-local/org/jfrog/buildinfo/build-info-extractor-maven3/2.41.5/build-info-extractor-maven3-2.41.5-uber.jar => https://<ARTIFACTORY_HOST>/artifactory/jfrogcli-maven-remote/org/jfrog/buildinfo/build-info-extractor-maven3/2.41.5/build-info-extractor-maven3-2.41.5-uber.jar

### Reproduction steps

Already explained in Current behavior

### Expected behavior

Construct the good URL of personnal remote repository

### JFrog CLI version

2.48.0

### Operating system type and version

OS/Arch: linux/amd64

### JFrog Artifactory version

7.55.3 rev

### JFrog Xray version

3.62.4

**Comment by evil-of-blad** [comment]
I also found the same problem，I am trying to lower the jf-cli version.

**Comment by biernatt** [comment]
same problem here, tested on [jfrog-cli-2.52.2.x86_64.rpm](https://releases.jfrog.io/artifactory/jfrog-rpms/jfrog-cli-v2-jf/jfrog-cli-2.52.2.x86_64.rpm)

**Comment by eyalbe4** [comment]
All,
Let us share an update here soon.

**Comment by eranturgeman** [comment]
Hello @usinelogicielle, thank you for reaching out!

The information regarding the jfrogcli-maven-remote repository pointing to 'https://oss.jfrog.org/artifactory/oss-release-local' is based on a legacy setup. Our current methodology employs a different approach.

By utilizing the 'jf options' command, you'll notice that the required configuration for JFROG_CLI_RELEASES_REPO is to proxy to 'https://releases.jfrog.io', not 'https://oss.jfrog.org/artifactory/oss-release-local'. 

![Screenshot 2023-12-17 at 10 51 26](https://github.com/jfrog/jfrog-cli/assets/81029514/8087b66c-9620-4c98-9264-6f268939629a)

The 'https://releases.jfrog.io' serves as a proxy from where all necessary resources for our workflows can be downloaded seamlessly. When supplying the server ID (token_artifactory_serverid) and setting JFROG_CLI_RELEASES_REPO to 'https://releases.jfrog.io', the URL will be automatically constructed as follows:

https://releases.jfrog.io/artifactory/oss-release-local/org/jfrog/buildinfo/build-info-extractor-maven3/2.41.5/build-info-extractor-maven3-2.41.5-uber.jar

Which is the correct URL for the requested resource.

We trust this solution resolves the issue you've encountered. If you have any further questions or if the solutions didn't fix your problem, please don't hesitate to let us know.

**Comment by usinelogicielle** [comment]
Hi @eranturgeman,

I understand the change. But the variable documentation would have to be modified. It says that JFROG_CLI_RELEASES_REPO corresponds to a repository. And not to an Artifactory server.
We have our own instance of Artifactory, so we need to tell our users to change this variable with our server.
And to create an oss-release-local repository in our instance, which is a remote from https://releases.jfrog.io/artifactory/oss-release-local.

I think this would work, but it distorts the naming convention to have a repository named "local" when it's a remote.

**Comment by biernatt** [comment]
We resolve the case by adding proxy repo to Jfrog oss-release-local in our Antifactory

**Comment by chkp-roniz** [comment]
We had this issue as well...

We did proxy https://releases.jfrog.io/artifactory/oss-release-local, and got the 404 failure

After adding a proxy to https://releases.jfrog.io, the issue was resolved

**Comment by KRiusd** [comment]
This solution sounds more linke a workaround as it takes all flexability structuring and naming the source repository.

I would favour setting up any mvn repository pointing to https://releases.jfrog.io/artifactory/oss-release-local and the cli not to add "artifactory/oss-release-local" to the request.

Example:
- RemoteRepo: my-oss-release-repo -> https://releases.jfrog.io/artifactory/oss-release-local
- JFROG_CLI_RELEASES_REPO=<serverId>/my-oss-release-repo
- CLI requests: https://my-artifactory/artifactory/my-oss-release-repo/org/jfrog/buildinfo/build-info-extractor-maven3/2.41.5/build-info-extractor-maven3-2.41.5-uber.jar
