### ISSUE TITLE
init.js broken with 2.49.0

### ISSUE THREAD

**Issue by mike-stock** [jfrog/jfrog-cli#2242]
### Describe the bug

When installing the npm package, the init.sh fails because of a wrong variable reference:

### Current behavior

npm install -g jfrog-cli-v2-jf

npm ERR!         node_modules/jfrog-cli-v2-jf/init.js:28
npm ERR!         host: proxyparts.hostname
npm ERR!         ReferenceError: proxyparts is not defined

This is caused by this variable name mismatch introduced with 2.49.0:
https://github.com/jfrog/jfrog-cli/blob/v2.49.0/build/npm/v2/init.js#L24

### JFrog CLI version

2.49.0 and 2.49.1

### Operating system type and version

Linux

**Comment by yahavi** [comment]
Hey @mike-stock,
Appreciate you letting us know about this problem.
We've created https://github.com/jfrog/jfrog-cli/pull/2243 to address it.
We'll make sure to keep you updated.

**Comment by mike-stock** [comment]
Thanks for the quick fix!

**Comment by yahavi** [comment]
@mike-stock 
JFrog CLI 2.49.2 has been released. This version includes https://github.com/jfrog/jfrog-cli/pull/2243.
We'd love to hear your feedback on it.

**Comment by mike-stock** [comment]
@yahavi I could successfully verify your fix.

Unfortunately, we ran into another issue with the updated jf version. We are investigating right now and should it be related to jf, we will open another bug.

**Comment by yahavi** [comment]
Thanks for the verification, @mike-stock. 
Please don't hesitate to create a [new issue](https://github.com/jfrog/jfrog-cli/issues/new/choose) if you come across any.
