### ISSUE TITLE
Windows binary is actually "AMD64" and/or "ARM-64"

### ISSUE THREAD

**Issue by Elkiwa** [jfrog/jfrog-cli#2247]
### Describe the bug

The release page indicates users are able to download Windows ARM-64 binary
![image](https://github.com/jfrog/jfrog-cli/assets/11015675/111828e2-5a6e-440a-95f3-942ae7ab98be)

1. However, the URL naming suggests that it is actually Windows "AMD-64" binary
https://releases.jfrog.io/artifactory/jfrog-cli/v2/2.1.1/jfrog-cli-windows-amd64/jfrog.exe

2. I installed it on my Windows amd64 machine and run it through PowerShell
```PowerShell
PS C:\dev> jfrog --version
jf version 2.49.2
```

### Current behavior

1. Go to https://github.com/jfrog/jfrog-cli/releases/tag/v2.49.2 page 
2. Click "Downloads JFrog CLI" 

![image](https://github.com/jfrog/jfrog-cli/assets/11015675/a0b95e87-9a13-4409-b973-0b94231e05ff)

3. Only ARM-64 is listed under Windows section

### Reproduction steps

1. Prepare a Windows AMD-64 and/or ARM-64 machine
2. Install jfrog.exe from https://releases.jfrog.io/artifactory/jfrog-cli/v2/2.1.1/jfrog-cli-windows-amd64/jfrog.exe

### Expected behavior

1. Go to https://github.com/jfrog/jfrog-cli/releases/tag/v2.49.2 page 
2. Click "Downloads JFrog CLI" 
3. AMD-64 and/or ARM-64 will be listed under Windows section

### JFrog CLI version

2.49.2

### Operating system type and version

WIndows 11 AMD-64

### JFrog Artifactory version

Not Applicable

### JFrog Xray version

Not Applicable

**Comment by yahavi** [comment]
@Elkiwa
Thanks for reporting this issue.
JFrog CLI 2.50.2 includes the fix for this issue.
