### ISSUE TITLE
Add 'jq' to the slim image

### ISSUE THREAD

**Issue by jghal** [jfrog/jfrog-cli#2251]
**Is your feature request related to a problem? Please describe.**

I like to use your 1st party images as the `image` in my GitLab Ci jobs to run API interactions with. I order to run JSON queries on the responses to `jf * curl` commands I need to either add `apk install jq` (waste of bandwidth to have to do this on every job) or use the `full` image (which is 3 GB instead of 71 MB, so even more wasteful) 

**Describe the solution you'd like to see**

Please install `jq` package in the slim Docker image.

**Describe alternatives you've considered**

Adding `apk add jq` to my pipeline script

**Comment by eyalbe4** [comment]
Thanks so much for the contribution @jghal. 
Your pull request is merged and the change will therefore be included as part of the upcoming release.

**Comment by yahavi** [comment]
Hi @jghal,
JFrog CLI version 2.50.1 is now available. Feel free to reach out if you require any additional assistance.
