### ISSUE TITLE
Bad handling of gradle CLI opts since 2.52.6

### ISSUE THREAD

**Issue by gregoryboue** [jfrog/jfrog-cli#2397]
### Describe the bug

Since 2.52.6 release and this PR : https://github.com/jfrog/jfrog-cli/pull/2357 , some properties like `-Dorg.gradle.internal.plugins.portal.url.override=https://myartifactory.org/artifactory/maven-public/` are not interpreted anymore.

In a context of a company with only access to maven repository through Artifactory, we have to use this property to download gradle plugins with artifactory because the JFrog CLI can't do that.

### Current behavior

Since 2.52.6 version, if i launch : `jf gradle clean assemble -Dorg.gradle.internal.plugins.portal.url.override=https://myartifactory.org/artifactory/maven-public/`, the plugins needed by my project is not downloaded through artifactory anymore.

### Reproduction steps

With a simple gradle project with [gradle sonarqube plugin](https://plugins.gradle.org/plugin/org.sonarqube) used in the build.gradle.

- With JFROG CLI 2.52.6+
- Use gradle wrapper 7.2 and java 11/17
- Run jf gradle-config to resolve dependency from artifactory (proxy to maven-central required)
- run `jf gradle clean assemble --info -Dorg.gradle.internal.plugins.portal.url.override=https://myartifactory.org/artifactory/maven-public/`

Then the log show that the repository https://myartifactory.org/artifactory/maven-public/ is not used to resolve gradle plugin (and the command is in error if there is no network access to `https://plugins.gradle.org/m2/`

The same command is ok with 2.52.5 version.

### Expected behavior

That the opt is well interpreted by JFrog CLI and https://myartifactory.org/artifactory/maven-public/ is used for gradle plugin resolution

### JFrog CLI version

2.52.6+

### Operating system type and version

Ubuntu

### JFrog Artifactory version

7.55.10

### JFrog Xray version

3.79.11

**Comment by omerzi** [comment]
Hey @gregoryboue, thank you for reporting this issue. We've made changes since the relevant PR you mentioned. These changes take effect in JFrog CLI [v2.52.8](https://github.com/jfrog/jfrog-cli/releases/tag/v2.52.8). Have you tried this version? Thanks.

**Comment by gregoryboue** [comment]
Hi @omerzi,

I have the same behaviour with [v2.52.8](https://github.com/jfrog/jfrog-cli/releases/tag/v2.52.8).

**Comment by omerzi** [comment]
Hi @gregoryboue, could you please attach the debug logs? To set the debug logs you need to add the `JFROG_CLI_LOG_LEVEL` environment variable and set it to `DEBUG`. It would assist us in further investigating this issue, thank you.

**Comment by gregoryboue** [comment]
Hi @omerzi You can find the logs in the following file : 
[jfgradle.log](https://github.com/jfrog/jfrog-cli/files/13830136/jfgradle.log)

**Comment by omerzi** [comment]
Hi @gregoryboue, we've released JFrog CLI [v2.52.9](https://github.com/jfrog/jfrog-cli/releases/tag/v2.52.9) with a gradle command parameter handling fix. Please let us know if this resolves your issue. Thank you.

**Comment by gregoryboue** [comment]
@omerzi , I can confirm that the issue is fixed in [v2.52.9](https://github.com/jfrog/jfrog-cli/releases/tag/v2.52.9) , thanks a lot
