### ISSUE TITLE
"jf config show" should also show the used config file

### ISSUE THREAD

**Issue by Rob3rtS** [jfrog/jfrog-cli#2421]
**Is your feature request related to a problem? Please describe.**
After using jfrog-cli for some years now and updating it from time to time to new versions, I have noticed the growing number of config files in ~/.jfrog/ next to the original jfrog-cli.conf: jfrog-cli.conf.v4, jfrog-cli.conf.v5, jfrog-cli.conf.v6
When analyzing user issues, it is often hard to determine the one config file, which really is taking effect now - especially, if users edited some file directly instead of using "jf c". Furthermore, we have implemented tools, which are also using jfrog-cli.conf - there it also became guess work, which of the config files is "in charge".

**Describe the solution you'd like to see**
"jf config show" should addtionally print a line like e.g.:
Config path:                    C:\Users\<accountName>\.jfrog\jfrog-cli.conf.v6

**Describe alternatives you've considered**
Until now, I have tried to guess and find out by deleting/renaming/trying, which config file actually takes effect.

**Comment by yahavi** [comment]
@Rob3rtS,
The `jfrog-cli.conf` file is internal to the JFrog CLI, and it's preferable not to manually read or modify it without using JFrog CLI commands. 
That being said, could you provide more details about your use case? What's prompting you to access its path?

**Comment by Rob3rtS** [comment]
My use case is: installing Debian packages from (private) Debian repositories hosted on Artifactory via apt using a script.
The script is extracting the access token from `jfrog-cli.conf` and creating the necessary sources.list files. Actually, I have other scripts as well, which are using the token for REST API calls, but that seems a bit outdated in the meanwhile, because there is `jf rt curl` (although calling a subprocess from python is not as elegant as directly issuing http requests within the script itself).

**Comment by yahavi** [comment]
Thanks for sharing this use case, @Rob3rtS. 
The challenge with relying on the `jfrog-cli.conf` is that it might become incompatible with future versions. Simply providing the path may not be effective if the structure changes. 

My recommendation is to generate a short-lived token using the `jf atc` command:
```bash
# Generate an access token for 10 minutes
jf atc --expiry 600
```
This command generates the following JSON that you can safely parse:
```json
{
  "scope": "applied-permissions/user",
  "access_token": "<the-new-token>",
  "expires_in": 600,
  "token_type": "Bearer",
  "token_id": "2e035eb6-3379-45c7-b8e5-32859e55cd38"
}
```

Another option is to store the original access token as a secret on the CI server and only expose it as an environment variable when necessary.

Please let me know if that helped.

**Comment by Rob3rtS** [comment]
Thank you @yahavi - I guess, I will go for the approach using `jf rt atc`...

**Comment by yahavi** [comment]
@Rob3rtS
Quick note: `jf rt atc` relies on an outdated API. Consider using `jf atc` instead, if possible.
