### ISSUE TITLE
404 when trying to download a release

### ISSUE THREAD

**Issue by vtc-guilherme-souza** [jfrog/jfrog-cli#2441]
### Describe the bug

When trying to download a release from https://github.com/jfrog/jfrog-cli/releases I'm receiving a 404.

### Current behavior

Example: https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/2.52.10/jfrog-cli-linux-amd64/jf

Response:
```
{
  "errors": [
    {
      "status": 404,
      "message": "Not Found"
    }
  ]
}
```

### Reproduction steps

Try to download a release from the releases page.

### Expected behavior

I expect to be able to download all releases listed in the releases page.

### JFrog CLI version

NA

### Operating system type and version

MacOS

**Comment by vaibhavdangar-woolies** [comment]
Jfrog error: Downloading: https://releases.jfrog.io/artifactory/jfrog-cli/v1/1.53.2/jfrog-cli-linux-386/jfrog
##[error]Error occurred while executing task:
Failed while attempting to download JFrog CLI from https://releases.jfrog.io/artifactory/jfrog-cli/v1/1.53.2/jfrog-cli-linux-386/jfrog. If this build agent cannot access the internet, you may use the 'Artifactory Tools Installer' task, to download JFrog CLI through an Artifactory repository, which proxies https://releases.jfrog.io/artifactory/jfrog-cli/v1/1.53.2/jfrog-cli-linux-386/jfrog. You may also manually download version 1.53.2 of JFrog CLI and place it on the agent in the following path: /__t/_jfrog/current/jfrog
**Error: certificate has expired**

**Comment by yahavi** [comment]
Thanks, @vaibhavdangar-woolies and @vtc-guilherme-souza, for flagging this problem! 
A short time after the incident yesterday, we sorted out the certificate issue, so everything should be back on track now. If you're still experiencing any trouble, just give us a heads-up.
