### ISSUE TITLE
Multipart Upload Stickiness + Visibility

### ISSUE THREAD

**Issue by idand1741** [jfrog/jfrog-cli#2467]
To enable stickiness for the multipart upload feature and recover from errors in one of the pods
we need to add the header: "X-JFrog-Route-To: *server-name*" to the status requests.

In case the pod is down during the complete phase the response will be 503 Service Unavailable.
Now we need to call the complete again without the header and change the value based on the current pod we got.

In addition, we need to add visibility for support to trace multipart uploads.
The best way will be to print somewhere the upload-id of the request.

Thanks!

**Comment by yahavi** [comment]
1 + 2 are fixed by https://github.com/jfrog/jfrog-client-go/pull/918
