### ISSUE TITLE
new jf cli 2.54 does not uploed big files (~2GB)

### ISSUE THREAD

**Issue by andboss** [jfrog/jfrog-cli#2497]
### Describe the bug

The new cli version cannot upload big files - files with some KBs worked but failed with ~2GB files.

### Current behavior

```
[Error] got unexpected server response while attempting to get JFrog Artifactory version:
server response: 404
{
 "errors": [
  { 
    "status": 404, 
    "message": "Could not find resource"
  }
  ]
[Error] Failed uploading 1 artifacts.
[Error] got unexpected server response while attempting to get JFrog Artifactory version:
server response: 404
{
  "errors": [
   { 
    "status": 404, 
    "message": "Could not find resource" 
   }
...
}
```

### Reproduction steps

call with big file
```
jf rt u --url="${ARTIFACTORY_PATH}/" --access-token="${ACCESS_TOKEN}" "${new_image_file}" "${BUILD_NAME}"
```

### Expected behavior

Should work same as with 2.53.2

### JFrog CLI version

2.54.0

### Operating system type and version

Debian 12

### JFrog Artifactory version

Enterprise Plus 7.71.10 rev 77110900

**Comment by eyalbe4** [comment]
@andboss,
Will you be able to set JFrog CLI's log level to DEBUG by setting the `JFROG_CLI_LOG_LEVEL` environment variable to `DEBUG`, run the command again, and then share the log output here?

**Comment by andboss** [comment]
@eyalbe4 see the logs below:
```
09:35:21 [Debug] JFrog CLI version: 2.54.0
09:35:21 [Debug] OS/Arch: linux/amd64
09:35:21 [Debug] Usage info is disabled.
09:35:21 [Info] [Thread 2] Uploading: vmware/spsdcvd-1.2.0-alpha.2-6-dcf6105-amd64-development.ova
09:35:30 [Debug] Sending HTTP PUT request to: https://falcon.rtf-alm.siemens.cloud/artifactory/oie_jupiter-dev-public-generic/jupiter-core/mr/625//5621/vmware/spsdcvd-1.2.0-alpha.2-6-dcf6105-amd64-development.ova;CommitId=dcf6105;CommitMessage=chore%3A+jfrog+cli+debug+log;ImageArch=amd64;ImageBuild=development;ImageFormat=ova;ImageName=spsdcvd;ImageVersion=1.2.0-alpha.2-6;PipelineId=29940253;TargetPlatform=vmware;TestStatus=+
09:35:30 [Debug] Sending HTTP GET request to: https://falcon.rtf-alm.siemens.cloud/artifactory/oie_jupiter-dev-public-generic/jupiter-core/mr/625//api/system/version
09:35:30 [Error] got unexpected server response while attempting to get JFrog Artifactory version:
server response: 404 
{
  "errors": [
    {
      "status": 404,
      "message": "Could not find resource"
    }
  ]
}
09:35:30 [Debug] Uploaded 0 artifacts.
09:35:30 [Error] Failed uploading 1 artifacts.
09:35:30 [Error] got unexpected server response while attempting to get JFrog Artifactory version:
server response: 404 
{
  "errors": [
    {
      "status": 404,
      "message": "Could not find resource"
    }
  ]
}
{
  "status": "failure",
  "totals": {
    "success": 0,
    "failure": 1
  }
}
09:35:30 [Error] upload finished with errors. Review the logs for more information
```

I'm away until 02.04.24 and may answer later.

Thanks!

**Comment by eyalbe4** [comment]
@andboss,
As you can see in the above log snippet you shared, the following call to Artifactory's `/api/system/version` API fails with 404 resource not found.
`https://falcon.rtf-alm.siemens.cloud/artifactory/oie_jupiter-dev-public-generic/jupiter-core/mr/625//api/system/version`
I recommend investigating why this specific REST endpoint in unavailable.

**Comment by anb0s** [comment]
> @andboss, As you can see in the above log snippet you shared, the following call to Artifactory's `/api/system/version` API fails with 404 resource not found. `https://falcon.rtf-alm.siemens.cloud/artifactory/oie_jupiter-dev-public-generic/jupiter-core/mr/625//api/system/version` I recommend investigating why this specific REST endpoint in unavailable.

@eyalbe4 sorry i do not get it - the only change is the new jf cli vesion - why jf cli try this in the new version as it was working or was different in the previous?
```
[Debug] Sending HTTP GET request to: https://falcon.rtf-alm.siemens.cloud/artifactory/oie_jupiter-dev-public-generic/jupiter-core/mr/625//api/system/version
```

**Comment by sverdlov93** [comment]
Hi @andboss , Can you provide the full command you used, with the real values?
Without accessToken of course.
jf rt u --url="${???}/" --access-token=XXX "${???}" "${???}"

**Comment by andboss** [comment]
@eyalbe4 thank you!

I've checked the CLI parameter help again and now understand that we used it differently, but it worked and therefore was not clear why new version of CLI is behaving differently!

We need to change many script and pipelines, but first showed it works now with both versions `< 2.54` and `>= 2.54`

closing
