### ISSUE TITLE
JFROG CLI 2.54.0 regression upon npm p execution

### ISSUE THREAD

**Issue by Thomas-Boutin** [jfrog/jfrog-cli#2499]
### Describe the bug

Hey,
Since the new version of the JFROG CLI, the command `jfrog npm p` does not build anymore but leads to a runtime error.
Everything's ok in the 2.53.2.

### Current behavior
```bash
jfrog npm p --build-name=vod-nutflix-front --build-number=0.6.0-0 vod-nutflix-front-0.6.0-0.tgz --registry <artifactory>
16:05:32  panic: runtime error: invalid memory address or nil pointer dereference
16:05:32  [signal SIGSEGV: segmentation violation code=0x1 addr=0x24 pc=0x872aeda]
16:05:32  
16:05:32  goroutine 1 [running]:
16:05:32  github.com/jfrog/jfrog-client-go/utils/io/content.(*ContentReader).NextRecord(0x0, {0x8bac6a0, 0xb87e4e0})
16:05:32  	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v1.38.0/utils/io/content/contentreader.go:66 +0x6a
16:05:32  github.com/jfrog/jfrog-client-go/artifactory/services/utils.ConvertArtifactsDetailsToBuildInfoArtifacts(0x0)
16:05:32  	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v1.38.0/artifactory/services/utils/resultutils.go:86 +0x85
16:05:32  github.com/jfrog/jfrog-cli-core/v2/artifactory/commands/npm.(*NpmPublishCommand).Run(0xba87620)
16:05:32  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.49.0/artifactory/commands/npm/publish.go:197 +0x40a
16:05:32  github.com/jfrog/jfrog-cli-core/v2/common/commands.Exec({0x8ebdaa8, 0xba87620})
16:05:32  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.49.0/common/commands/command.go:26 +0xa6
16:05:32  github.com/jfrog/jfrog-cli/buildtools.NpmPublishCmd(0xb92e420)
16:05:32  	/var/****_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/buildtools/cli.go:868 +0x26b
16:05:32  github.com/jfrog/jfrog-cli/buildtools.npmGenericCmd(0xb92e420, {0xfff397b7, 0x1}, 0x0)
16:05:32  	/var/****_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/buildtools/cli.go:830 +0x138
16:05:32  github.com/jfrog/jfrog-cli/buildtools.GetCommands.func11(0xb92e420)
16:05:32  	/var/****_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/buildtools/cli.go:331 +0x190
16:05:32  github.com/urfave/cli.HandleAction({0x8b475a0, 0x8d46618}, 0xb92e420)
16:05:32  	/root/go/pkg/mod/github.com/urfave/cli@v1.22.14/app.go:524 +0x50
16:05:32  github.com/urfave/cli.Command.Run({{0x8c7bb82, 0x3}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x8ca4ce6, 0x10}, {0x8d324f7, ...}, ...}, ...)
16:05:32  	/root/go/pkg/mod/github.com/urfave/cli@v1.22.14/command.go:175 +0x63e
16:05:32  github.com/urfave/cli.(*App).Run(0xb925340, {0xb828140, 0x8, 0x8})
16:05:32  	/root/go/pkg/mod/github.com/urfave/cli@v1.22.14/app.go:277 +0xb11
16:05:32  main.execMain()
16:05:32  	/var/****_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/main.go:139 +0x4d5
16:05:32  main.main()
16:05:32  	/var/****_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/main.go:78 +0x23
```

### Reproduction steps

- Use the latest cli version
- Run npm p using the jfrog cli

### Expected behavior

It should build

### JFrog CLI version

2.54.0

### Operating system type and version

RHEL 8 in docker

**Comment by EyalDelarea** [comment]
Hey @Thomas-Boutin,
Thank you for using JFrog CLI!

I was unsuccessful in replicating the problem. Could you kindly offer more detailed instructions on how to reproduce it?

1. Set CLI debug log level by : `export JFROG_CLI_LOG_LEVEL=DEBUG`
2. Share the package.json file.

Providing thorough steps to recreate this issue would greatly assist us in resolving it.

I made an attempt to replicate the issue by installing version `v2.54.0` of the CLI within a RHEL 8 Docker image, but the problem did not arise.

![image](https://github.com/jfrog/jfrog-cli/assets/23456142/c00b2605-5ad0-492b-ab25-ec49909f4c14)

**Comment by Thomas-Boutin** [comment]
Additional information : the above job is running with npm 10.2.4 and node 20.11.1

**Comment by EyalDelarea** [comment]
Hey @Thomas-Boutin,

Thank you for this information. 
I was able to reproduce the issue and fix it, you can track the progress in the following [PR](https://github.com/jfrog/jfrog-cli/pull/2502) 

As a temp workaround you could downgrade the cli version or use `jf npm p` without providing an already packed npm package ( the jf command will pack it for you )

Thank you for the bug report!

**Comment by Thomas-Boutin** [comment]
@EyalDelarea cheers good job!

Thanks for the fast fix. We've already downgraded the cli version. Looking forward to having this fixed :-)

Have a nice day

**Comment by EyalDelarea** [comment]
Hey @Thomas-Boutin ,
A new version of the CLI has been released and the fix is included.

Feel free to reach out if you require further assistance!

**Comment by Thomas-Boutin** [comment]
Hey @EyalDelarea I'll test this one I'll let you know

**Comment by eyalbe4** [comment]
Thanks for the update @Thomas-Boutin!
