### ISSUE TITLE
Can a password/token value be overridden when uploading artifacts?

### ISSUE THREAD

**Issue by jdknight** [jfrog/jfrog-cli#2508]
Trying to cleanup an environment which uses (GitLab) CI containers with jfrog-cli pre-configured with a server. The original setup allowed users of the container to invoke [`jt rt u <path>`](https://docs.jfrog-applications.jfrog.io/jfrog-applications/jfrog-cli/cli-for-jfrog-artifactory/generic-files#uploading-files) to upload files from a CI job. However, this design has the token embedded into the image, which is not ideal.

My goal is to tweak a Docker image to register an Artifactory server without the use of the `--password` argument here:

```
FROM alpine:latest
...
RUN curl -fL https://install-cli.jfrog.io | sh
RUN jf config add \
    my-artifactory-instance \
    --interactive=false \
    --url https://my-artifactory-home/ \
    --user my-ci-user 
```

And then at runtime, add the password/access-token inside a CI job's environment variable (e.g. `SOME_JFROG_AUTH_KEY` which can be implicitly used when uploading files:

```
jf rt u my-built-img.tar
```

Or, if needed, explicitly through a command line:

```
echo "$SOME_JFROG_AUTH_KEY" | jf rt u my-built-img.tar --[access-token/password]-from-stdin
```

The only known workaround/approach to not embed the key (aside from overriding a base image's entry point with inject some jf actions) is to have each repository using this image to manually add the configuration entry themselves (similar to what is described in ["GitLab CI and Artifactory: On Your Mark, Get Set, Build!"](https://jfrog.com/blog/gitlab-and-artifactory-on-your-mark-get-set-build/)). But having to replicate the `jf config` call across multiple repositories is not ideal.

Is there an alternative approach here?

Related:
- https://github.com/jfrog/jfrog-cli/issues/1823

**Comment by RobiNino** [comment]
Hi @jdknight ,
As discussed in the issue you referenced, providing credentials via environment variables is currently only supported explicitly for the `jf config [add/edit] --[access-token/password]-from-stdin` commands.

The alternative approach for GitLab integration is using [JFrog's GitLab Templates](https://github.com/jfrog/gitlab-templates). These templates handle the download and configuration of JFrog CLI using GitLab CI/CD variables.
See also:
[Official blog about this functionality](https://jfrog.com/blog/software-supply-chain-with-gitlab-cicd-jfrog/)
[Customer's blog about a more complex integration solution](https://medium.com/@izra.ron/how-did-we-seamlessly-integrated-jfrog-cli-into-our-gitlab-ci-pipelines-52fd1d6e3119)

Thanks

**Comment by jdknight** [comment]
@RobiNino, thanks for the information.

Tried a couple of the mentioned approaches. In the end, went with overriding the entry point for the various base images we use to auto-run a custom Artifactory script. The script will register a server configuration if select CI variables are set.
