### ISSUE TITLE
Release Bundle Create command (jf rbc) has an issue with the --project flag when using a spec file that is not "builds" but "pattern" or "aql"

### ISSUE THREAD

**Issue by derekscp** [jfrog/jfrog-cli#2535]
### Describe the bug

When utilizing the 'jf release-bundle-create' [command](https://docs.jfrog-applications.jfrog.io/jfrog-applications/jfrog-cli/cli-for-jfrog-artifactory/release-lifecycle-management#creating-a-release-bundle) it results in an error when using 'aql' or 'pattern' in the spec file while there is a --project flag. Using 'builds' does not produce the error.
Error:
[🚨Error] release bundles creation source only supports the 'exclusions', 'props', 'excludeProps' and 'recursive' fields

### Current behavior

We get this error because of the project key. If it does not have the project key it works as expected.

$ jf release-bundle-create --server-id=cloud  --project=<PROJECT_KEY> --signing-key="gpgkey1" --sync=true --spec=specfile.json Release-Bundle-Test 1.0.0
16:38:03 [Debug] JFrog CLI version: 2.56.0
16:38:03 [Debug] OS/Arch: darwin/amd64
16:38:03 [Debug] Sending HTTP GET request to: <ART_URL>/artifactory/api/system/version
16:38:03 [Debug] Usage Report: Sending info...
16:38:03 [Debug] Sending HTTP GET request to: <ART_URL>/artifactory/api/system/version
16:38:03 [Debug] Artifactory response: 200 
16:38:03 [Debug] Artifactory response: 200 
16:38:03 [Debug] JFrog Artifactory version is: 7.84.3
16:38:03 [Debug] Sending HTTP POST request to: <ART_URL>/artifactory/api/system/usage
16:38:03 [🚨Error] release bundles creation source only supports the 'exclusions', 'props', 'excludeProps' and 'recursive' fields

### Reproduction steps

1. Create a specfile, specfile.json
```
{
  "files": [
    {
      "pattern": "<REPO_NAME>/<PATH_TO_FOLDER>/*"
    }
  ]
}
``` 
2. Run the jfrog cli command to create the release bundle under a project
```
$ jf release-bundle-create --server-id=cloud --project=<PROJECT_KEY> --signing-key="gpgkey1" --sync=true --spec=specfile.json Release-Bundle-Test 1.0.0
``` 

### Expected behavior

I would expect that it should work the same as when the spec file contains a build as the parameter instead of a pattern or aql.

### JFrog CLI version

jf version 2.56.0

### Operating system type and version

OS/Arch: darwin/amd64

### JFrog Artifactory version

7.84.3

### JFrog Xray version

n/a

**Comment by yahavi** [comment]
@derekscp 
JFrog CLI version 2.56.1 is now, addressing this problem. 
Keep us posted on whether it fixes the issue for you!

**Comment by derekscp** [comment]
@yahavi Thank you. This fixes the issue for me.
