### ISSUE TITLE
The latest jf-cli has not been updated in Debian(ubuntu22), it currently still 2.59.1

### ISSUE THREAD

**Issue by kunkka-m** [jfrog/jfrog-cli#2644]
I am unable to install the latest version by using apt install on Ubuntu22, and its latest version is still 2.59.1. and I need to use version 2.61+ in Debian

 
<img width="224" alt="image" src="https://github.com/user-attachments/assets/bffe70dc-8e20-42e0-892e-a40d05ed319b">

**Comment by sverdlov93** [comment]
Hi @kunkka-m 
Thanks for reporting this issue.
Can you confirm that it's still happening with the latest 2.63 version?

**Comment by kunkka-m** [comment]
Hi @sverdlov93 
I got the rc, This may be caused by an internal JFrog configuration issue, using the official repo will works.

**Comment by sverdlov93** [comment]
So no issue here for 2.60+ versions on our side?

**Comment by kunkka-m** [comment]
Yes, thanks!
