### ISSUE TITLE
Regression in jfrog-cli 2.62.0 (Maven integration): "failed to parse build info file: unexpected end of JSON input"

### ISSUE THREAD

**Issue by rtaugerbeck** [jfrog/jfrog-cli#2648]
### Describe the bug

Executing a trivial Maven command through JFrog CLI (e.g. `jf mvn --version`) fails since 2.62.0. It works up to 2.61.2

### Current behavior

❯ jf mvn --version
15:02:05 [🔵Info] Running Mvn...
15:02:05 [🔵Info] Running mvn command: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java -classpath /opt/homebrew/Cellar/maven/3.9.8/libexec/boot/plexus-classworlds-2.8.0.jar -Dmaven.home=/opt/homebrew/Cellar/maven/3.9.8/libexec -DbuildInfoConfig.propertiesFile=/var/folders/9q/r84slt016jl2llrcqtmbsmf40000gn/T/jfrog/properties/extractorProperties265332632 -Dm3plugin.lib=/Users/john/.jfrog/dependencies/maven/2.41.21 -Dclassworlds.conf=/Users/john/.jfrog/dependencies/maven/2.41.21/classworlds.conf -Dmaven.multiModuleProjectDirectory=/Users/john/myproject -DbuildInfoConfig.artifactoryResolutionEnabled=true org.codehaus.plexus.classworlds.launcher.Launcher --version
Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)
Maven home: /opt/homebrew/Cellar/maven/3.9.8/libexec
Java version: 17.0.12, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "14.6.1", arch: "aarch64", family: "mac"
15:02:05 [🔵Info] Trace ID for JFrog Platform logs: cc868b5088d2d9e7
15:02:05 [🚨Error] failed to parse build info file: unexpected end of JSON input

### Reproduction steps

`> jf mvn-config --server-id-resolve=my-server --repo-resolve-releases=maven-releases --repo-resolve-snapshots=maven-snapshots`    # not relevant
`> jf mvn --version`

### Expected behavior

Log output from `mvn --version`

### JFrog CLI version

2.63.0

### Operating system type and version

macOS Sonoma 14.6.1

**Comment by omerzi** [comment]
Hi @rtaugerbeck,

Thank you for reporting this issue. I've opened a pull request that should resolve it: https://github.com/jfrog/jfrog-cli-core/pull/1226. Once it is merged and the JFrog CLI is released with the fix, I’ll let you know as soon as possible.

**Comment by omerzi** [comment]
Hi @rtaugerbeck,

I wanted to let you know that JFrog CLI version [v2.63.1](https://github.com/jfrog/jfrog-cli/releases/tag/v2.63.1) has been released.

Please let me know if there is anything else you need or if the issue remains unresolved. Thanks again for bringing it to our attention.

**Comment by rtaugerbeck** [comment]
JFrog CLI v2.63.1 fixes this issue. Thanks for fixing!
