### ISSUE TITLE
"invalid character 'u' looking for beginning of value" when running jf yarn install in Yarn 4 project

### ISSUE THREAD

**Issue by RobinDinkel** [jfrog/jfrog-cli#2664]
### Describe the bug

When I run "jf yarn install" in my Yarn 4 project I receive the following error:

09:47:20 [🚨Error] invalid character 'u' looking for beginning of value

### Current behavior

jf yarn install
09:47:19 [Debug] JFrog CLI version: 2.63.2
09:47:19 [Debug] OS/Arch: linux/amd64
09:47:19 [Debug] Trace ID for JFrog Platform logs: 92e835809fc8ca2a
09:47:19 [🔵Info] Running Yarn...
09:47:19 [Debug] Preparing to read the config file **redacted**/.jfrog/projects/yarn.yaml
09:47:19 [Debug] Found resolver in the config file **redacted**/.jfrog/projects/yarn.yaml
09:47:19 [Debug] Preparing prerequisites.
09:47:19 [Debug] Found Yarn executable at: /usr/bin/yarn
09:47:19 [Debug] Working directory set to: **redacted**
09:47:19 [Debug] Found Yarn executable at: /usr/bin/yarn
09:47:19 [Debug] Sending HTTP GET request to: **redacted**/artifactory/api/system/version
09:47:19 [Debug] Artifactory response: 200 
09:47:19 [Debug] JFrog Artifactory version is: 7.90.6
09:47:19 [Debug] Sending npm auth request
09:47:19 [Debug] Sending HTTP GET request to:**redacted**/artifactory/api/npm/auth
09:47:19 [Debug] Sending HTTP GET request to:**redacted**/api/repositories/**redacted**
09:47:20 [🔵Info] Trace ID for JFrog Platform logs: 92e835809fc8ca2a
09:47:20 [🚨Error] invalid character 'u' looking for beginning of value

### Reproduction steps

Create Yarn 4 project
Run jf c add
Run jf yarn-config
Run yarn install

### Expected behavior

The dependencies are downloaded.

### JFrog CLI version

2.63.2

### Operating system type and version

Ubuntu 20.04

### JFrog Artifactory version

7.90.6

### JFrog Xray version

3.88.12

**Comment by EyalDelarea** [comment]
Hi @RobinDinkel,

This issue has already been reported in our jfrog-cli-core project, where the logic for handling it resides. As I mentioned in [this issue](https://github.com/jfrog/jfrog-cli-core/issues/1166), we currently do not support Yarn v4.

We will provide updates once support is added to our roadmap and share progress as it happens.

I'm closing this issue to avoid duplication. Thank you for bringing this to our attention!
