### ISSUE TITLE
Are there any plans to start using golang `1.23.0` ?

### ISSUE THREAD

**Issue by NitinRamesh25** [jfrog/jfrog-cli#2680]
The security vulnerabilities in golang `1.22.x` prevent me from using the jfrog-cli productively.
Are there any plans to start using golang `1.23.0` ?
I'd very much appreciate it if this can be upgraded soon.

**Comment by eyalbe4** [comment]
Yes @NitinRamesh25.
See https://github.com/jfrog/jfrog-cli/pull/2688
Since this will be applied as part of the upcoming JFrog CLI release, I think you can close this issue.

**Comment by NitinRamesh25** [comment]
Thanks
