### ISSUE TITLE
How to split build info several jobs

### ISSUE THREAD

**Issue by gsemet** [jfrog/jfrog-cli#279]
Hello
We have a pipeline (on Gitlab) that generate several artifacts on various jobs, and they all upload to artifactory independently. This works great, and allow to use artifactory to be used to exchange large artifacts between pipeline.

I would like to declare the builds as artifacts so that they appear in the "Build browser" in Artifactory, however the main limitation is that `jfrog rt bp` does not see previously uploaded files, even if, on the previous steps (that run on different machines/VM/dockers) i use `jfrog rt upload` with `--build-name` and `--build-number` set with the same values accross all the jobs.

The issue seems related to the fact that {{rt upload --build...}} actually generates files on the computer, in {{/tmp/jfrog/builds/[BASE64ENCODEDBUILDNAMEANDNUMBER]/partials/temp[A-BIG-NUMBER]}}. Isn't it possible to ask the `jfrog rt bp` to fetch these information from artifactory, since all the artifacts I need has the right properties `build.name` and `build.number` ?

Where:
- BASE64ENCODEDBUILDNAMEANDNUMBER = base64(build_name + "_" + build_number)
- [A-BIG-NUMBER] = seems random

**Comment by gsemet** [comment]
Seem related to #142.

I would propose another command:
```bash
jfrog rt build-fetch-artifacts --build-name NAME --build-number NUMBER
```
that would find from artifactory all artifacts that has been previously updated with `rt upload --build-name NAME --build-number NUMBER`, and generate the right "partials" files in /tmp/jfrog, so that upcoming `rt bp` will populate them in the "builds" database in Artifactory.

**Comment by gsemet** [comment]
Hi. I have written a small python script that perform the following AQL query and generate the partials:
```python
        arti = ArtifactoryPath( "http://my-artifactory/artifactory") 
        query = {
            "$and": [
                {
                    "@build.name": self.args.build_name,
                },
                {
                    "@build.number": self.args.build_number,
                },
            ]
        }

        from path import Path
        from nestor_cli.common.anyconf import anydump

        res = arti.aql("items.find", query)
        for f in res:
            stat = (arti / f["repo"] / f["path"] / f["name"]).stat()
            creation_time = arrow.Arrow.fromdatetime(stat.ctime)
            partial_dict = {
                "Artifacts": [{
                    "name": str((Path(f["path"]) / f["name"]).basename()),
                    "sha1": stat.sha1,
                    "md5": stat.md5,
                }],
                "Timestamp":
                    creation_time.timestamp * 1000 + int(creation_time.format("SSS")),
            }
            fname = self._create_temp_partial()
            with open(fname) as f:
                f.write(json.dumps(partial_dict)
        if self.args.git_partial_from_ci:
            fname = self._create_temp_partial()
            git_partial = {
                "Timestamp": self._arrow_to_milliseconds(arrow.utcnow()),
                "vcsUrl": os.getenv("CI_PROJECT_URL"),
                "vcsRevision": os.getenv("CI_COMMIT_SHA"),
            }
            with open(fname) as f:
                f.write(json.dumps(git_partial)
```
Works pretty well. I would like to see it in jfrog-cli :)

**Comment by cschyma** [comment]
There's an issue at JFrog's JIRA tracker: https://www.jfrog.com/jira/browse/RTFACT-16374 . Vote for it!

**Comment by arvid-r** [comment]
Hi @gsemet
Still using the python script above, or did you come up with a better solution? I'm trying to figure out how to handle builds spanning over several build machines, which is an important case in our environment

**Comment by gsemet** [comment]
Hello. I actually ditched the use of "build" feature from artifactory, it makes things too complex to use. We are using properties instead, but again, due to slowness of the server the more we use it (the properties database grows a lot), but are reverting to using only cleverly design storage paths. I wonder how others use the "build" feature, on the paper it looks cool, but it is pretty much useless for us: how do we qualify several flavor of builds for a given projet (ex: branch builds, mergerequests, master, releases, daily rebuilds, weeekly or other special schedules),...
Most of the time we want something like "give me the latest builds from the 'master' branch", and on gitlab for instance, manually triggered pipelines or scheduled pipelines can still be on master, so we need other 'keys' to select the right builds. Having just a list of builds for a given project is not useful

**Comment by arvid-r** [comment]
Thanks for your update! Too bad. And I agree, the "build" feature seemed great, but I haven't figured out how to use it for any non-trivial task yet. What I really want in the end is an easy way to have several build machines, running macOS, Windows and Linux, work and upload items to the same build. And promote that build in several stages, and add more files like test results etc. to finally publish the build to customers. And also have different retention policies that keeps released builds forever, but drops nightly builds from last week etc.
I really thought this was the purpose of Artifactory, and it buggs me that it can almost be done in a clean way.
Now there is even an append command `jfrog rt ba` but what it actually does isn't really useful for any purpose I can imagine. Very strange.

**Comment by gsemet** [comment]
Yes, basically we do the same thing. There are several use cases:
- working area = "I want to fetch the right pipeline results from my CI". 
- release area = we want to organize things clearly for customers.

In both cases, we ended up with file path (same for retention policies, pipelines artifacts search -> everything is based on paths). Maybe bintray can help, but that's another product to buy

**Comment by eyalbe4** [comment]
@gsemet and @arvid-r - thanks for sharing your thoughts and requirements here.
Supporting these scenarios is something that is included in our roadmap and will be delivered in the future.

**Comment by arvid-r** [comment]
Thanks for chiming in here @eyalbe4 
Do you know if what we want to achieve is possible through the REST API?

**Comment by eyalbe4** [comment]
All - sharing here here an update -

The latest releases of jfrog-cli include a new capability, which allow the aggregation of multiple build-info's into one "master" build-info. Each build-info is published separately to Artifactory, which allows publishing them from different stages or different machines. Eventually, you can reference all of those build-info from one build-info. 
When downloading or searching the artifacts of the master build-info, all the artifacts of the referenced builds get fetched and downloaded. 
Read more about it in the [Aggregating published builds](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-AggregatingPublishedBuilds) documentation section. 
Important - this functionality requires Artifactory version 7.17.0 or above. 

We'd appreciate your feedback for this functionality.

**Comment by cschyma** [comment]
Sounds awesome! Is there also a REST API available to use this functionality? https://www.jfrog.com/confluence/display/rtf/artifactory+rest+api#ArtifactoryRESTAPI-BUILDS does not reflect this currently.

**Comment by cschyma** [comment]
Meaning the build-append command does use https://www.jfrog.com/confluence/display/rtf/artifactory+rest+api#ArtifactoryRESTAPI-BuildUpload?

**Comment by eyalbe4** [comment]
@cschyma - 
The ```build-append``` command adds the details of a published build (its build name and build number) into a local (unpublished) build-info. The unpublished build-info can be then published (like any build-info) using the ```jfrog rt build-publish``` command.
The ```jfrog rt build-publish``` command uses the above REST API.

**Comment by arvid-r** [comment]
Thanks for the update! I just try this using `frog rt dl ...` on an aggregated build, and that works as expected. Great!
It would be nice if the aggregation was also shown somehow when looking at the aggregated build in the web UI.

**Comment by eyalbe4** [comment]
Thanks for the feedback @arvid-r!
The plan is to also have Builds UI in Artifactory reflect the relationships between builds.

**Comment by kkmoslehpour** [comment]
I'm using the build aggregation to aggregate the separate builds, however, when i try to run build-promote on the aggregate build it does nothing. The artifacts in the aggregate builds are still in the same place.
