### ISSUE TITLE
Get jfrog-cli-layout from https://releases.jfrog.io/artifactory/jfrog-cli/

### ISSUE THREAD

**Issue by Vvlad1slavV** [jfrog/jfrog-cli#2792]
Hello,
I want to make a local repository of `jfrog-cli`. But can't repeat `jfrog-cli-layout` to be able to download the last release like
`https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/[RELEASE]/jfrog-cli-linux-amd64/jf` use [RELEASE] instead version.
Can you share `jfrog-cli-layout`?

**Comment by yahavi** [comment]
@Vvlad1slavV

The simplest and most convenient option is to use `https://releases.jfrog.io/artifactory/jfrog-cli` as the URL for a new "jfrog-cli-remote " remote repository. No specific layout is required in this scenario.

If you need the JFrog CLI binary to be in a local repository, you can use the following Artifact Path Pattern:
```
[orgPath]/[baseRev]/[module]/jf(.[ext])
```
Please let me know if this solution works for you.

**Comment by Vvlad1slavV** [comment]
Thanks a lot!
This option is work.

I tried to follow the documentation https://jfrog.com/help/r/jfrog-rest-apis/retrieve-latest-artifact and the phrase confused me
`
Both [folderItegRev] and [fileItegRev] have to be defined in the repository layout.
`
