### ISSUE TITLE
Publish build info from jfrog CLI to update Used By or Produce By info in tree browser in Artifactory

### ISSUE THREAD

**Issue by Rupesh-Narayan** [jfrog/jfrog-cli#324]
While publishing builds from TeamCity and checking the option of "Publish Build Info", I am able to see the "Produced By" and "Used By" entries in Artifactory. Is there any command so that I can also publish build info during local builds from jfrog CLI?

**Comment by Rupesh-Narayan** [comment]
I have tried using _jfrog rt bp_ command which does publish build-info, but it doesn't captures the info related to who used or produced the package under Build tab in tree browser of artifactory.
In case of publishing the build from TeamCity using artifactory teamcity plugin, this info is captured but not during local builds where I am trying to use JFrog CLI.

**Comment by alwaysharsha** [comment]
This would be useful feature, if we are able to get it from the JFrog-CLI.
Can we prioritize this feature development?

**Comment by barbelity** [comment]
@Rupesh-Narayan @alwaysharsha,
If I understand correctly - you are referring the views available when selecting an artifact in the '**Artifactory Repository Browser**' -> '**Builds**' tab.

The "Produced By" and "Used By" views are Artifactory features. They are calculated for artifacts stored in Artifactory, and naturally depend on published builds.
I tested this with JFrog CLI - published several builds with conjunction artifacts / dependencies, and it works for me:
![image](https://user-images.githubusercontent.com/12187591/55741440-eac42380-5a35-11e9-80b7-e1dadd48c721.png)

Can you please elaborate on your use case?

**Comment by eyalbe4** [comment]
@Rupesh-Narayan @alwaysharsha,
Did you get a chance to look into this?

**Comment by alwaysharsha** [comment]
@eyalbe4 I verified we can perform this using Jfrog CLI. You can close this bug.

**Comment by eyalbe4** [comment]
Awesome @alwaysharsha.
Thanks
