### ISSUE TITLE
Codesign Windows Binaries

### ISSUE THREAD

**Issue by megaposer** [jfrog/jfrog-cli#34]
Hi,

I was wondering if it would be possible to code-sign (Authenticode) the official Windows binaries distributed via [Bintray](https://bintray.com/jfrog/jfrog-cli-go) and [here](https://www.jfrog.com/getcli/).

If not, maybe you could at least provide some checksums for the official binaries? That would be great.

Cheers!

**Comment by eyalbe4** [comment]
@megaposer, we could probably GPG sign the JFrog CLI binaries on Bintray.
Would that be what you're looking for?

**Comment by megaposer** [comment]
Thanks for getting back to me @eyalbe4 ...

For the Windows version of the CLI binary an Authenticode code-sign signature would be required to correctly identify the publisher, integrity/authenticity and to make life easier with Smart Screening on Windows (not to mention IT/security departments frowning on unsigned binaries).

**Comment by eyalbe4** [comment]
Got it @megaposer. Thanks. We'll look into this.

**Comment by eyalbe4** [comment]
https://github.com/jfrog/jfrog-cli/pull/556 adds signing for the Windows binary of JFrog CLI.
This will be included in the upcoming release of JFrog CLI.

**Comment by jornfranke** [comment]
Could this be extended to the Linux binaries or is there is a signature somewhere I am not aware of?

**Comment by eyalbe4** [comment]
Closing this issue, since Windows binaries signing has already been addressed by #556.
As for signing the other binaries, we now have #1355 for tracking this request.
