### ISSUE TITLE
Add support for npm ci

### ISSUE THREAD

**Issue by scottrus** [jfrog/jfrog-cli#342]
Currently JFrog CLI has support for npm install via the `jfrog rt npmi` command. The `npm ci` command offers a number of advantages in automated build environments including faster build times. To continue to use JFrog CLI for collecting dependancies during NPM build, it would be good to support `npm ci`.

**Comment by scottrus** [comment]
Keeping it popping fresh.

**Comment by CC84** [comment]
I'd like to see support for this too.

**Comment by AlexeiVainshtein** [comment]
Hi @scottrus and @CC84 

I would like to update you that we have added the support for npm-ci. This is already included in our latest release (version 1.26.1). You can find the documentation regarding this [here](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-BuildingNpmPackages).

We will appreciate your feedback regarding this.

**Comment by s-geiger-si** [comment]
I can confirm that `jfrog rt npm-ci works` and runs `npm ci`. I think this issue can be closed. Note there is #705 about some cosmetic documentation issues between npm-install and npm-ci.

**Comment by scottrus** [comment]
This is resolved for me.
