### ISSUE TITLE
CLI parameter substitution for spec files

### ISSUE THREAD

**Issue by jgeorgeson** [jfrog/jfrog-cli#37]
I have a case where I want to loop over path strings and run an AQL query with a spec file. At present I have  tokenized spec file with tokens like _@@PATH@@_ and I'll have a sed command in my shell loop to copy the template spec file substituting the correct value for that loop iteration in place of the token and running the CLI command with the temp file. I'd like something like a _--spec-template_ with accompanying _--token_ argument. Ideally supporting multiple usage of _--token_ in a single command, with the value using a format like _<token>:<value>_ (since ':' is a necessary part of the spec file it's a good choice for an illegal character in a token name and therefore a good choice of character to separate token name and value on command line).

**Comment by eyalbe4** [comment]
Thanks for this requirement @jgeorgeson.
We'll include it as part of one of the next releases.

**Comment by eyalbe4** [comment]
@jgeorgeson,
The latest JFrog CLI release includes the *--spec-vars* options for all commands which support File Specs.
Did you get a chance to try this out?

**Comment by jgeorgeson** [comment]
I did not! Fantastic! I hadn't readily found release notes (I've found them now) to know what was new in 1.10.

**Comment by jgeorgeson** [comment]
Working nicely so far, issue is resolved for me. Only suggestion would be improving error messages. When supplying a parameterized spec file without a `--spec-vars` argument I am shown the usage statement with no indication what was missing or wrong. Though to be fair that's a general issue rather than specific to this feature.

**Comment by faizan002** [comment]
It is closed issue but Does --spec-vars work with "props" as well ? if props are a list of properties like key=value;key1=value1  ?
