### ISSUE TITLE
Empty folders created during rt download

### ISSUE THREAD

**Issue by shivaprasadh** [jfrog/jfrog-cli#370]
I am using the below code to download the files (Including sub-directories) from Artifactory Source, and I have some EMPTY folders in my Source Repository

`jfrog.exe rt dl --threads=10 --include-dirs=true --flat=true --recursive "Artifactory-Source-Repo/Test_Project/(*)" "Test_Project/{1}"`

The files are downloaded successfully, but after download, I see EMPTY folders are created in each and every directory with the above command.
I tried the same without "--include-dirs" in the above command and the EMPTY folders are NOT created, but by removing this option, Empty folders from Source are not created in Local.

Output of the above command:
**Source:**
reponame/path/to/my/project/dir1/file1
reponame/path/to/my/project/dir1/dir2/file1
reponame/path/to/my/project/dir1/dir2/file2

**Target:**
/dir1/file1
/dir1/dir2/file1
/dir1/dir2/file2
_/dir1/dir2/dir2_  (I don't want this directory to be created)

Can someone provide me an option for downloading all EMPTY folders and at the same time, NOT to create the duplicate EMPTY folders with the above command?  Thanks.

**Comment by eyalbe4** [comment]
@shivaprasadh,
I think that the following command should get you what you want:
```
jfrog rt dl --threads=10 --include-dirs --recursive "Artifactory-Source-Repo/Test_Project/" "Test_Project/"
```
Please let me know if this works.

**Comment by busymans** [comment]
I had exact same issue and leave a solution.
Do not enable --include-dirs option.

`jfrog rt dl --threads=10 --include-dirs=false --recursive "Artifactory-Source-Repo/Test_Project/" "Test_Project/"
or
jfrog rt dl --threads=10  --recursive "Artifactory-Source-Repo/Test_Project/" "Test_Project/"`

**Comment by eyalbe4** [comment]
Thank you for sharing @busymans!
