### ISSUE TITLE
`jfrog rt gp` doesn't publish .info file. 

### ISSUE THREAD

**Issue by edganiukov** [jfrog/jfrog-cli#372]
According to https://research.swtch.com/vgo-module#publishing, repository should contain 4 files:
* ../@v/list
* ../@v/v1.0.0.info
* ../@v/v1.0.0.mod
* ../@v/v1.0.0.zip

But it uploads only `.mod` and `.zip` so my build fails with, for example: 
```
go: github.com/user/example/v2@v2.25.0: unexpected status (https://artifactory.example.com/api/go/go-local/github.com/user/example/v2/@v/v2.25.0.info): 404 Not Found
```

Content of such .info files is, for example:
```
{"Version":"v2.5.0","Time":"2018-03-26T05:07:29Z"}
```

I believe `jfrog rt gp` should publish .info file as well.

**Comment by eyalbe4** [comment]
Thank you @edganiukov.
We intend to add this soon.

**Comment by andrewhoff** [comment]
Hey @eyalbe4 just wondering what your ETA/plan is for including this functionality?

**Comment by eyalbe4** [comment]
@andrewhoff,
Actually, version 1.26.0 has just been released and includes publishing info files.
The support for this has been added in Artifactory 6.10.0, so you'll need both the CLI and Artifactory to be at those versions for this to work.
Looking forward to your feedback for this.

**Comment by andrewhoff** [comment]
@eyalbe4 Thanks for the quick response! I've actually noticed it working fine with cli version 1.25 against a hosted artifactory instance, but it doesn't seem to work work cli version 1.25 against `docker.bintray.io/jfrog/artifactory-pro:6.10.3`. Also just curious when the 1.26 mojave package will be published to homebrew? Thanks!

**Comment by eyalbe4** [comment]
@andrewhoff,
This should work for all scenarios with JFrog CLI 1.26.0 and above and Artifactory 6.10.0 and above.
Please let us know if you see any issues with those versions.
Version 1.26.1 is available on homebrew now.

**Comment by andrewhoff** [comment]
ahhh it works great now, thanks!

**Comment by eyalbe4** [comment]
Happy to hear this @andrewhoff. Thanks :)
