### ISSUE TITLE
Go source identified using wildcards not found when building

### ISSUE THREAD

**Issue by jackwhelpton** [jfrog/jfrog-cli#373]
Attempting to run a build command such as:

`GOOS=linux GOARCH=amd64 CGO_ENABLED=0 ./jfrog rt go 'build -ldflags="-s -w" -o bin/api.linux-amd64 cmd/api/*.go' go-dev`

produces:

```
stat ./cmd/api/*.go: no such file or directory
{
  "status": "failure",
  "totals": {
    "success": 0,
    "failure": 1
  }
}
```
I've validated that those files are present in `./cmd/api` relative to the directory from which jfrog is launched; I've also tried using an absolute path, with a similar error. Listing the files individually (rather than using a wildcard) works.

**Comment by jackwhelpton** [comment]
For the second example, quoting what follows the go command:

`./jfrog rt go 'get -d ./...' go-dev`

Still struggling with ldflags, though.

**Comment by eyalbe4** [comment]
@jackwhelpton - thanks for reporting this.
We intend to modify the ```jfrog rt go``` command, so that it supports a syntax which allows setting all flags.
We'll keep this issue updated with our progress.

**Comment by eyalbe4** [comment]
@jackwhelpton,
With the latest JFrog CLI release, you can run the new **jfrog rt go-config** command, from the root directory of your go project, to save the Artifactory repositories for the project.
This allows using the **jfrog rt go** command without the need of adding quotes around the go arguments.
Looking forward to your feedback for this functionality.

**Comment by jackwhelpton** [comment]
Thanks! Is this useable in a non-interactive form, from CI pipelines for example? I tried passing it parameters, but just receive a "Wrong number of arguments" type error.

**Comment by jackwhelpton** [comment]
On the plus side, I worked around this by writing the yaml file into the home directory myself, and the "jfrog rt go" commands that result are _much_ cleaner; I can remove the parsing of build flags that I was having to do. Thanks!

Suggestions on how to automate the global configuration are welcome.

**Comment by eyalbe4** [comment]
@jackwhelpton,
The *jfrog rt go-config* command creates a **.jfrog** in the current directory (we recommend running it in the root directly of the go project).
You can then push this directory to the source control, which makes the
configuration available for anyone who pulls the sources. That's why we didn't add a non interactive option for now 
Another option is to run the command with the *--global* option, which adds
the configuration to JFrog CLI's home dir, effecting all projects. This is basically what you did when you added the confirmation to the home dir manually.
We would appreciate any feedback for the existing functionality.
Thanks

**Comment by jackwhelpton** [comment]
I may as well close this, as I've been working with the unquoted version for several months with no difficulties. The non-interactive version of the config option would enable me to use it with CI pipelines, but I'm OK generating the config file as explained above.

**Comment by davidalpert** [comment]
does this mean that the only way to pass args to the underlying `go build` command (e.g. `-ldflags`) is to first write a config file to disk?

**Comment by eyalbe4** [comment]
@davidalpert,
Using the **jfrog rt go** command without configuring the project (or machine) first is deprecated. Mixing the go falgs together with the JFrog CLi flags in one command execution can be very challenging. That's the reason why we separated the config (jfrog rt go-config) and the go execution (jfrog rt go) into two separate comands. 
The **.jfrog** directory created by the **jfrog rt go-config** command can be pushed into to the SCM and saved with the sources. This way, the **jfrog rt go-config** command won't need to be executed every time. 
We'd love to hear your feedback and your experience.
