### ISSUE TITLE
`jfrog rt c` doesn't work on Windows

### ISSUE THREAD

**Issue by BattleBrisket** [jfrog/jfrog-cli#382]
I'm getting the following output when I attempt to run the `config` command:

```
> jfrog rt c
[Error] The handle is invalid.
```

Attempted with/without several optional parameters, as well as `--interactive=false`

Help output (`jfrog h` or `jfrog rt h`) both produce output as expected, so the executable appears in good working order.

`jfrog.exe` running on Windows 10. Tried with Command Prompt and PowerShell, both as normal user and elevated admin.

Running version 1.25.0. Installed via Chocolatey (https://chocolatey.org/packages/jfrog-cli)

**Comment by BattleBrisket** [comment]
Update: eliminated Chocolatey from the equation, with similar but not identical results.

```
> jfrog.exe rt c
[Error] Lock hasn't been acquired.
```

The error returned after a long pause (>1 min).

**Comment by BattleBrisket** [comment]
Found the problem. You must set the `JFROG_CLI_HOME_DIR` environment variable. The default ` ~/.jfrog` obviously doesn't exist, and there's no Windows-based default fallback. 

I opted to set this system-wide, creating a System Variable with the location `C:\Users\Public\jfrog`

Could we add something about this requirement to the installation docs?

**Comment by eyalbe4** [comment]
@BattleBrisket, thanks for sharing this.
Here's the [code](https://github.com/jfrog/jfrog-client-go/blob/master/utils/io/fileutils/files.go) which returns the user's home dir:
```
func GetHomeDir() string {
	home := os.Getenv("HOME")
	if home != "" {
		return home
	}
	user, err := user.Current()
	if err == nil {
		return user.HomeDir
	}
	return ""
}
```
Since the *HOME* environment variable is not (usually) set on Windows, then user.Current().HomeDir should return the user home dir.
Can check again what happens when you remove the *JFROG_CLI_HOME_DIR* environment variable?
Could it be that there's no user logged in? (is it even possible on Windows?)
Can you try and see if (and where) the *.jfrog* directory is created without the *JFROG_CLI_HOME_DIR* environment variable?

**Comment by BattleBrisket** [comment]
I can reproduce the error when `JFROG_CLI_HOME_DIR` is removed, and can further confirm that `.jfrog` isn't being created in that situation.

A windows user is definitely logged in, and no I don't think it's possible to run without a login.

There are several ways to get the home directory. Using the standard command prompt (`cmd.exe`), I can call `echo %USERPROFILE%` to report my home directory. Using Windows PowerShell, I can get the same thing with `echo $HOME`.

I'm not adept enough at Go to provide constructive feedback on the CLI code, however since I'm seeing the same CLI error output when calling using both `cmd` and Windows PowerShell, I suspect the problem is in the `"os/user"` library.

**Comment by eyalbe4** [comment]
@BattleBrisket,
Which path do oy get when running ```echo %USERPROFILE%```?
We may be able to add this to the above *GetHomeDir()* function.

**Comment by BattleBrisket** [comment]
On a default Windows installation, the `USERPROFILE` env variable will point to `C:\Users\<USERNAME>`.

For cmd.exe, call `echo %USERPROFILE%`

For PowerShell, it's `echo $env:USERPROFILE`

**Comment by eyalbe4** [comment]
@BattleBrisket,
I created the above PR following your feedback.

**Comment by eyalbe4** [comment]
@BattleBrisket - 
The fix is included as part of the latest release.
Looking forward to your feedback.

**Comment by BattleBrisket** [comment]
Confirmed it works without setting `JFROG_CLI_HOME_DIR` env var.

💯

**Comment by keithel** [comment]
I received this same error on Windows 10 from a git bash shell. - Same symptom, but different problem I'm pretty sure.
Error:
```$ jfrog rt c
Artifactory server ID: server-id
Artifactory URL: https://artifact.server.foo.com/artifactory
Access token (Leave blank for username and password/API key): [Error] The handle is invalid.```

This was solved by running `jfrog rt c` from a plain Windows command prompt (I actually used a VS2017 command prompt).

Might be nice to get this working from bash shells under windows.

**Comment by Postyy** [comment]
Thanks for you feedback @keithel ,
Looks like the error you describe is related to Go according to https://github.com/golang/go/issues/34612.
I'll let you know as soon as there's an update.

**Comment by CloudDevopsEngineer02** [comment]
> echo $env:USERPROFILE

i tried in power shell (2012R2 Ver) got user profile.
