### ISSUE TITLE
 jfrog rt bdi --exclude-builds list is kept forever

### ISSUE THREAD

**Issue by glevy** [jfrog/jfrog-cli#391]
Hi,

I couldn't find a simple way to re-include previously excluded builds on the Artifactory discard old builds settings.
running the command line again with a different exclude list only accumulate them on top of the previous list.

running:
Jfrog rt bdi demo_build --max-days=0 --delete-artifacts=true --exclude-builds="43, 44, 45, 46, 47, 48"

and then with:
--exclude-builds="44, 45, 46, 47, 48, 49”

 and:
--exclude-builds="45, 46, 47, 48, 49, 50”

Will result in keeping these forever:
43, 44, 45, 46, 47, 48, 49, 50

**Comment by eyalbe4** [comment]
@glevy,
The *jfrog rt bdi* command has no "memory" of previous command. Neither does Artifactory. Every command invokes the build retention API on Artifactory, with the arguments sent (max days, max builds, as well as the builds to exclude).
Can you perhaps try discarding builds which are more than a day old with max-days=1 or try using the max-builds (just to troubleshoot this).
Please share with us what you see.

**Comment by eyalbe4** [comment]
Hey @glevy,
Just following up on this issue.

**Comment by glevy** [comment]
Hi,

Sorry for the delay...I tried using the  max-builds=1 + exclude list and it
is working as expected.

Thanks,
Gilad

**Comment by eyalbe4** [comment]
Thanks for the update @glevy.
