### ISSUE TITLE
build.number property gets set incorrectly for jfrog rt gradle command

### ISSUE THREAD

**Issue by scriptnull** [jfrog/jfrog-cli#398]
When trying to publish the jfrog sample gradle project to my artifactory ( https://github.com/jfrog/project-examples/tree/master/gradle-examples/gradle-example-minimal ), my artifact gets uploaded but the build number property is not set correctly.

```
 jfrog rt gradle "clean artifactoryPublish -b build.gradle" ./art-config --build-name=local-gradle-test --build-number=4
```

![image](https://user-images.githubusercontent.com/4211715/59515778-857d2a80-8edd-11e9-87f2-fa41cf7ca5dd.png)

I am guessing that, as a result of this, issuing a build-publish ( `jfrog rt build-publish local-gradle-test 4` ) is not able to correctly locate the artifact.
![image](https://user-images.githubusercontent.com/4211715/59516021-0cca9e00-8ede-11e9-8227-ab6b096e4aeb.png)

And as the consequence of the above facts, issuing a build-promote fails with the following error

```
vagrant@ubuntu-bionic:~/project-examples/gradle-examples/gradle-example-minimal$ jfrog rt bpr local-gradle-test 4 vishnu-local
[Info] Promoting build...
[Error] Artifactory response: 400 Bad Request
{
  "errors": [
    {
      "status": 400,
      "message": "Unable to find artifacts of build 'local-gradle-test' #4: aborting promotion."
    }
  ]
}
```

One small observation that I could make is that the value of `build.number` property seems like a timestamp value, so could it be a bug in `jfrog rt gradle` command or perhaps I am doing something wrong or missing out something. Any help on this would be much appreciated!

**Comment by yahavi** [comment]
@scriptnull,
Thanks for reporting this issue!
This [commit](https://github.com/jfrog/jfrog-cli/commit/9e13a195680801fdd0fae51b3e58e14284f464ac) resolves this issue and will be included in the next release.

**Comment by scriptnull** [comment]
Works like a charm. Thank you @yahavi for letting me know and thank you @AlexeiVainshtein for the fix.
