### ISSUE TITLE
Using explode in file spec on Jenkins job does not extract .tar.gz file 

### ISSUE THREAD

**Issue by ArthiIR** [jfrog/jfrog-cli#417]
https://www.jfrog.com/confluence/plugins/servlet/mobile?contentId=54986754#content/view/54986754

Tried to explode (per link above)a tar.gz but it created another tar.gz file. Can someone  with experience using explode to untar a file help please. 

Thank you!

**Comment by ilatypov** [comment]
Ending the `target` parameter with a slash and using it as a root of the unpacked tar ball worked for me (except `jfrog rt dl` threw an esoteric error when I attempted to use `./` in target).
```
$ cat ra.spec
{
    "files": [
        {
            "aql": {
                "items.find": {
                    "repo": {"$eq": "maven-remote-cache"},
                    "path": {"$eq": "org/flywaydb/flyway-commandline/5.2.4"},
                    "name": {"$eq": "flyway-commandline-5.2.4-macosx-x64.tar.gz"}
                }
            },
            "flat": "true",
            "target": "flyway/",
            "explode": "true"
        }
    ]
}

$ JFROG_CLI_OFFER_CONFIG=false JFROG_CLI_LOG_LEVEL=DEBUG jfrog rt dl --url=https://COMPANY.TLD/artifactory --server-id=artserver --user=USER --password=ENCRYPTED_PASSWORD --spec=ra.spec
[Info] Searching items to download...
[Debug] Searching Artifactory using AQL query:
 items.find({
                    "repo": {"$eq": "maven-remote-cache"},
                    "path": {"$eq": "org/flywaydb/flyway-commandline/5.2.4"},
                    "name": {"$eq": "flyway-commandline-5.2.4-macosx-x64.tar.gz"}
                }
            ).include("name","repo","path","actual_md5","actual_sha1","size","type","property")
[Debug] Artifactory response:  200 OK
[Info] [Thread 2] Downloading maven-remote-cache/org/flywaydb/flyway-commandline/5.2.4/flyway-commandline-5.2.4-macosx-x64.tar.gz
[Info] [Thread 2] [1]: 206 Partial Content...
[Info] [Thread 2] [0]: 206 Partial Content...
[Info] [Thread 2] [2]: 206 Partial Content...
[Info] [Thread 2] Extracting archive: flyway-commandline-5.2.4-macosx-x64.tar.gz to flyway
[Debug] Downloaded 1 artifacts.
{
  "status": "success",
  "totals": {
    "success": 1,
    "failure": 0
  }
}

$ ls -la flyway/
total 0
drwxr-xr-x   3 USER  DOM\Domain Users   96 24 Jul 21:12 .
drwxr-xr-x  19 USER  DOM\Domain Users  608 24 Jul 21:12 ..
drwxr-xr-x  12 USER  DOM\Domain Users  384 24 Jul 21:12 flyway-5.2.4
```

Too bad that jFrog's AQL in general and jFrog's Jenkins plugin in particular apply only to locally available files.  This makes the plugin useless in downloading external artifacts because their presence in the cache is not guaranteed.

https://stackoverflow.com/questions/44825224/using-jfrogcli-to-download-artifacts-from-a-smart-repo-on-artifactory

**Comment by liron-shalom** [comment]
Hi @ArthiIR ,
Unfortunately, we were unable to reproduce the issue (using cli directly and using Jenkins plugin).

Can you please provide us some steps to reproduce?
Are you using the Artifactory plugin for Jenkins or using cki directly in Jenkins? please attach your pipeline.
Which JFrog CLI/Artifactory plugin and Jenkins versions are you using? 

Thanks.  

@ilatypov - Thanks for reporting!
[This commit](https://github.com/jfrog/jfrog-client-go/commit/bd05f94a4c53f09e8b29188224c697a9b8045337) resolved this issue.
We would appreciate your feedback for it.

Thanks.

**Comment by ilatypov** [comment]
@liron-shalom it's easier to reproduce the issue than to work it around.  Ending the target parameter with a forward slash eas not enough when I wanted to unpack into the current directory with `"target": "./"`

**Comment by eyalbe4** [comment]
@ilatypov,
Can you please try this again with version 1.26.3, which has just been released?

**Comment by ArthiIR** [comment]
Thank you all. Explode: true works. Closing this issue.
