### ISSUE TITLE
Artifactory access token response doesn't include token_id

### ISSUE THREAD

**Issue by BattleBrisket** [jfrog/jfrog-cli#423]
I am [creating Artifactory access tokens](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-CreateToken), which get tossed into a secrets storage (Azure Keyvault in this case, actual tool is irrelevant). 

The response includes values for `scope`, `access_token`, `expires_in`, and `token_type`.  However `token_id` is suspiciously absent.

```
jfrog rt curl -s -XPOST /api/security/token -d "username=service-test-data" -d "scope=member-of-groups:readers" -d "expires_in=1800"
{
  "scope" : "member-of-groups:readers api:*",
  "access_token" : "eyJ2ZXIiOiIyIi [...]",
  "expires_in" : 1800,
  "token_type" : "Bearer"
}
```

As the unique, non-sensitive identifier for the key, I want to keep this value locally on hand, associated with the `access_token`, as a general best practice for data curation.

More importantly, I want to utilize this value for performing `revoke` actions on the token. The API allows me to revoke tokens via the full `access_token` value, however that requires me to pull the sensitive `access_token` from secret storage. Per the _Principle of Least Privilege_, I don't want (or need) the user/process performing a revoke action to access this sensitive info.

Currently, in order to retrieve `token_id`, I need to use the [`Get Tokens` API call](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-GetTokens), which returns every token in the system, and then parse the list for token(s) with a `subject` value matching the token's username. This process is also insufficient, as I can have multiple tokens with the same `username`. 

**Recommendation:** include `token_id` as part of the existing return data.

```
jfrog rt curl -s -XPOST /api/security/token -d "username=service-test-data" -d "scope=member-of-groups:readers" -d "expires_in=1800"
{
  "token_id": "3a9eeb48-5fdb-441f-ae56-d86f5c39c296",
  "scope" : "member-of-groups:readers api:*",
  "access_token" : "eyJ2ZXIiOiIyIi [...]",
  "expires_in" : 1800,
  "token_type" : "Bearer"
}
```

Given that the revoke action [accepts `token_id` as a parameter](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-RevokeToken), it would seem that the API architects had this workflow in mind.

**Comment by eyalbe4** [comment]
@BattleBrisket,
Since this request is not directly related to JFrog CLI or the "jfrog rt curl" command, but to the */api/security/token* REST API of Artifactory, I believe it is best to open this issue on the [Artifactory JIRA project](https://www.jfrog.com/jira/).
