### ISSUE TITLE
MAVEN_OPTS are ignored

### ISSUE THREAD

**Issue by voidengineer** [jfrog/jfrog-cli#426]
When calling `mvn` directly (without jfrog-cli) the contents of MAVEN_OPTS are passed to the JVM that will execute Maven. This is especially useful for customizing memory-sizes (-Xms, -Xmx, -XX:MaxMetaspace, etc.)

Calling `jfrog rt mvn` does not pass this values and I did not find any way to configure memory-settings in any other way.

It would be great if `jfrog rt mvn` would behave like `mvn` and pass MAVEN_OPTS to the JVM.

**Comment by liron-shalom** [comment]
@voidengineer 
Thanks for reporting this issue!
This [commit](https://github.com/jfrog/jfrog-cli/commit/8661d546823edffdc9630466a0f2f9c008b18be2) resolves this issue and will be included in the next release.

**Comment by eyalbe4** [comment]
@voidengineer, 
The latest release includes this functionality.
We'd appreciate your feedback for it.

**Comment by voidengineer** [comment]
Works like expected! :+1:
