### ISSUE TITLE
Is there any option to download artifact based on sha1 checksum

### ISSUE THREAD

**Issue by murali741** [jfrog/jfrog-cli#432]
Hi Team,

I am trying to download a artifact from my local repository based on checksum. Could you please help me with documentation to download the artifact based on the checksum value of the file.

Thanks
Murali

**Comment by eyalbe4** [comment]
@murali741.
The following File Spec will do this for you:
```
{
  "files": [
    {
      "aql": {
        "items.find": {
          "actual_sha1": "8655bd744e972bb4afe66d8e0afc116333333879"
        }
      }
    }
  ]
}
```
Please let me know if this works for you.

**Comment by eyalbe4** [comment]
@murali741,
I hope the above helped. Let me know if it didn't. 
Closing this issue.
