### ISSUE TITLE
Server ID artifactory API key authentication is not supported

### ISSUE THREAD

**Issue by xNok** [jfrog/jfrog-cli#441]
Hi,

I go the following error when i use the build integration for mavne `jfrog rt mvn`: *Server ID artifactory API key authentication is not supported*.

My script:
```
./jfrog rt config artifactory --url=$ARTIFACTORY_URL --apikey=$ARTIFACTORY_KEY --interactive=false
./jfrog rt mvn "$MVN_GOALS_AND_OPT" ${BUILD_CONF} --build-name=demo-mvn-artifactory --build-number=$BUILD_NUM
```

Why would API key authentication not work while it work for all the other Jfrog cli options

**Comment by eyalbe4** [comment]
@xNok,
JFrog CLI no longer supports the usage of an API key without a username. The config command, in its non-interactive mode, still supports adding a config with an API key without a user, but this is only for backward compatibility reasons.
Can you please try using the config with a username and an API key?

**Comment by eyalbe4** [comment]
@xNok,
I'm closing this issue for now, but do let us know if you need additional assistance with this.

**Comment by shailesh719** [comment]
Hi 

when i am trying to Configure Artifactory instance with  jfrog cli for my gitlab pipe-line , i am getting 404 error on pipeline log , below are the error message 
"Error] The following error was received while trying to encrypt your password: Artifactory response: 404  " 

Variable declared on my pipeline
 ARTIFACTORY_BASE_URL: https://XXX.XX.XXX/artifactory
 ARTIFACTORY_SERVER_ID: XYZSERVER-ID
 ARTIFACTORY_KEY: someEncodedKEY
ARTIFACTORY_USER: XYZ_USER 
 
jfrog cli Command which i am using on gitlab pipeline :
    `./jfrog config add $ARTIFACTORY_SERVER_ID --artifactory-url="$ARTIFACTORY_BASE_URL" --user="$ARTIFACTORY_USER" --apikey="$ARTIFACTORY_KEY" --interactive=false
