### ISSUE TITLE
1.28.0: Unable to build due to undefined variables

### ISSUE THREAD

**Issue by dvzrv** [jfrog/jfrog-cli#445]
Hi!

I'm currently maintaining jfrog-cli in the Arch Linux User Repository ([AUR](https://aur.archlinux.org)) (as [jfrog-cli-go](https://aur.archlinux.org/packages/jfrog-cli-go)). Midterm I would like to move this tool to the official [community](https://www.archlinux.org/packages/?sort=&repo=Community&q=&maintainer=&flagged=) repository.

When building `1.28.0` I'm running into issues with undefined variables:
```
# github.com/jfrog/jfrog-cli-go/artifactory/utils/pip/dependencies
../src/github.com/jfrog/jfrog-cli-go/artifactory/utils/pip/dependencies/dependencies.go:190:66: undefined: pipDepTreeVersion
../src/github.com/jfrog/jfrog-cli-go/artifactory/utils/pip/dependencies/dependencies.go:209:38: undefined: pipDepTreeContent
```

See here for the full build log: 
[jfrog-cli-go-1.28.0-build.log](https://github.com/jfrog/jfrog-cli/files/3563855/jfrog-cli-go-1.28.0-build.log)

My build steps are (after extracting the sources, where `$pkgname` is `jfrog-cli-go`, `$_upstream_name` is `jfrog-cli`, `$_name` is `jfrog`, `$pkgver` is `1.28.0` and `$srcdir` is the directory in which all source code operations are taking place):

```
  mv -v "${_upstream_name}-${pkgver}" "${pkgname}-${pkgver}"
  (
    cd "$pkgname-$pkgver/"
    go mod vendor
    rm -v go.mod
  )
  export GOPATH="${srcdir}"
  mkdir -vp src
  mv -v "${pkgname}-${pkgver}"/vendor/* src/
  mkdir -vp src/github.com/jfrog
  ln -rTsf "${pkgname}-${pkgver}" src/github.com/jfrog/jfrog-cli-go

  cd "$pkgname-$pkgver"
  export GOPATH="${srcdir}"
  go build -o "${_name}" \
           -ldflags="-linkmode external -extldflags ${LDFLAGS} -s -w" \
           "main.go"
```

Sorry, if this looks somewhat confusing (with all the moving/ changing dirs/ exporting variables), but the build steps take place in different functions of our [PKGBUILD](https://wiki.archlinux.org/index.php/PKGBUILD) build scripts.

On Arch Linux we're currently on:

* go 1.12.9
* glibc 2.29
* git 2.23.0

**Comment by dvzrv** [comment]
Ah, hm... investigating further in [./build.sh](https://github.com/jfrog/jfrog-cli/blob/master/build.sh#L10), I realize, that some "resources" get added: `go run ./python/addresources.go`

It would be really great, if non-standard steps like these would be properly documented or generally avoided.

**Comment by eyalbe4** [comment]
You're correct @dvzrv and my apologies for this.
We'll soon update the new build steps as part of the README and let you know when done.

**Comment by eyalbe4** [comment]
@dvzrv,
We updated the README with the new build and test instructions.
See https://github.com/jfrog/jfrog-cli/commit/b02ac0119e41bb56dc145b4ff76d7e884488211c with the changes.
Thank you for reporting this issue.

**Comment by eyalbe4** [comment]
@dvzrv,
I'm closing this issue for now.
Please let me know if you'd like to discuss this further.
