### ISSUE TITLE
Failed initializing dependency-map script

### ISSUE THREAD

**Issue by sudodevnull** [jfrog/jfrog-cli#455]
rhel7 > downloaded executable
receive the following when running jfrog commands:

panic: Failed initializing dependency-map script.

goroutine 1 [running]:
github.com/jfrog/jfrog-cli-go/artifactory/utils/pip/dependencies.init.0()
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/artifactory/utils/pip/dependencies/dependencies.go:25 +0x68

**Comment by sudodevnull** [comment]
installed by one user, attempted to be used by another is where the issue appears.

**Comment by liron-shalom** [comment]
Hi @sudodevnull,

Can you please let us know what are the permissions the file is created with?
(the file should be located under JFROG_CLI_HOME_DIR/dependencies/pip/1)
What command are you trying to run? 

Thanks.

**Comment by famod** [comment]
Same here, but with the official docker image `jfrog-cli-go:latest`.
Downgrading from `jfrog-cli-go:1.28.0` (current `latest`) to `jfrog-cli-go:1.27.0` fixes the problem!

**Comment by famod** [comment]
@liron-shalom Any news on this? There have been two releases since this issue was reported (1.29 and 1.29.1).
For me, this issue is an upgrade blocker.

**Comment by eyalbe4** [comment]
@famod,
I think that this latest release resolves this issue. Can you please check and let us know?

**Comment by famod** [comment]
@eyalbe4 confirmed.

Would be nice if @sudodevnull (which originally created this issue) could also confirm.

**Comment by sudodevnull** [comment]
I am out of pocket for a few days and will not be able to test. I will take @famod word and close. Thank you!

**Comment by eyalbe4** [comment]
Thanks @famod and @sudodevnull.
We may still have a permissions issue for people who use the new *jfrog rt pip-install* command with different OS users.
Any chance you can help us investigating this by answering @liron-shalom's question above?
Really appreciate your help with this. Thanks.
