### ISSUE TITLE
Can't go-publish private dependency on Go 1.13

### ISSUE THREAD

**Issue by perj** [jfrog/jfrog-cli#471]
I'm trying to go-publish one of my dependencies to artifactory:

```
jfrog rt go-publish --self=false --deps=go.example.org/example:v1.0.3 go-local
```

This fails on the `go mod graph` step:

```
[Info] Running 'go mod graph' in /home/perj/example
verifying go.example.org/example@v1.0.3/go.mod: go.example.org/example@v1.0.3/go.mod: reading https://sum.golang.org/lookup/go.example.org/example@v1.0.3: 410 Gone
```

This surprised me because this checksum is already in my go.sum file and `go mod graph` should pick it up from there rather than calling to `sum.golang.org`. Indeed, running `go mod graph` directly is not an issue.

So I checked with strace since I like to do that. Turns out jfrog is removing my go.sum just before it calls `go mod graph`:

```
[pid  5704] unlinkat(AT_FDCWD, "/home/perj/example/go.sum", 0) = 0
[pid  5704] write(2, "[Info] Running 'go mod graph' in /home/perj/example\n", 55[Info] Running 'go mod graph' in /home/perj/example
```

Since there's no go.sum present go falls back to the checksum database server.

I don't particulary like that, I think the local go.sum should be used if possible. I assume the jfrog cli has a good reason for removing it, perhaps related to publishing self. But if so it should be possible to still have it around when other go commands is run.

Obviously I can work around this by setting GONOSUMDB, but I'd prefer not to since checksums are a good idea.

jfrog version 1.29.1

**Comment by eyalbe4** [comment]
@perj,
I created the above PR which should fix this issue.

**Comment by eyalbe4** [comment]
@perj,
The latest release includes this fix.
Please let us know if the issue is resolved for you.

**Comment by perj** [comment]
It works fine. Thanks a lot.

**Comment by eyalbe4** [comment]
Great. Thanks @perj.
