### ISSUE TITLE
Uploading all files referenced by relative path does not work

### ISSUE THREAD

**Issue by bts-dido** [jfrog/jfrog-cli#482]
This is working. 

`jfrog rt u "/foo/bar/*" artfctry/upload`

But for some reason this is not working. Command says success, but not uploading anything. 

`jfrog rt u "/foo/baz/../bar/*" artfctry/upload`

It's working for single file referenced by relative path like

`jfrog rt u "/foo/baz/../bar/file" artfctry/upload`

But when it comes to pattern using `*`, it's not working - says success but not uploading.  

`jfrog rt u "/foo/baz/../bar/file*" artfctry/upload`

**Comment by Postyy** [comment]
Fix for this issue : https://github.com/jfrog/jfrog-client-go/pull/89

**Comment by eyalbe4** [comment]
@bts-dido,
Was the issue resolved for you? If so, feel free to close this issue.
