### ISSUE TITLE
Upload fails with missing target message when target is supplied

### ISSUE THREAD

**Issue by ryanwholey** [jfrog/jfrog-cli#487]
We have been using the jfrog cli to upload helm charts to our jfrog helm repo:

```sh
jfrog rt upload *.tgz / --url $REGISTRY --user $DOCKER_REGISTRY_USERNAME --apikey $DOCKER_REGISTRY_PASSWORD
```
Our last successful build was 25 days ago, we haven't published a new helm chart until now. 
We are now receiving this error:
```
[Error] Spec must include target.
```

1) Did the API change such that our command is no longer supported or is this a bug?
2) ~Is there a way we can pin a CLI version without building from source?~ Just found the bintray index

```sh
$ ./jfrog --version
jfrog version 1.30.1
```

installed with:
```sh
curl -fL https://getcli.jfrog.io | sh
```

Thank you for your time!

Update:
Confirmed that the provided command works with `1.30.0` but fails with `1.30.1`. I noticed that there was some [recent changes to this file](https://github.com/jfrog/jfrog-cli/pull/485) where the error is thrown.

**Comment by eyalbe4** [comment]
@ryanwholey,
It looks like your *upload* command does not include a target repository (or repository and path) to upload the files to. I'm curious how previous versions managed to work with this command structure. 
Can you please try adding this and let us know if resolves the issue?
The last release indeed included some refactoring and code improvements around the command validation.

**Comment by ryanwholey** [comment]
Ah yes that’s what I thought when I first came across this line too. I think the source pattern is *.tgz and the target pattern is /

**Comment by ryanwholey** [comment]
To elaborate a little (sorry on my phone), we have been uploading our files to the root of the repository. Adding a destination 
‘’’
jfrog rt u *.tgz /app ...
‘’’
uploads to the repository but to a sub directory /app instead of the root /.

Again, thank you for your time!

**Comment by eyalbe4** [comment]
@ryanwholey,
Does the following work for you?
**jfrog rt u *.tgz <repo name>/app/**
This is the correct syntax of the upload command. .

**Comment by ryanwholey** [comment]
sorry for the late response.

yes it seems we can resolve our issue by shifting the path from the end of the --url to the target argument.
```
jfrog rt upload *.tgz repo-name/ --url=<url>
```

instead of
```
jfrog rt upload *.tgz / --url=<url>/repo-name
```

Thanks!
