### ISSUE TITLE
Build-info result of "jfrog rt go" contains 3 dependencies with same id for each package

### ISSUE THREAD

**Issue by liron-shalom** [jfrog/jfrog-cli#520]
After running:

`jfrog rt go build --build-name=my-build-name --build-number=1`

`jfrog rt bp my-build-name 1`

build-info JSON view in Artifactoy shows 3 dependencies with same id for each package:

`"dependencies": [{`
   `"sha1": "426446d5c0af5848c16e5a6f49eca2330d68be0f",`
   `"sha256": "900b797c531f2df182e431a895ecd3109aacfedfdddab23a48f7c0a9d5a75659",`
            `"md5": "eadae478e0fc4f1fe664d469cae846d7",`
            `"id": "github.com/chzyer/readline:v0.0.0-20180603132655-2972be24d48e"`
        `}, {`
            `"sha1": "b90a4ddeea5997dd28b311396509b617985fc6e0",`
            `"sha256": "3dc842677887278fb33d25078d375ae6a7a94bb77a8d205ee2230b581b6947a6",`
            `"md5": "89f1f1f6faac284c3e72b27f832a9734",`
            `"id": "github.com/chzyer/readline:v0.0.0-20180603132655-2972be24d48e"`
        `}, {`
            `"sha1": "1667f72df01070d590a6c32d8285d2f979614388",`
            `"sha256": "b9a160b2d9d99c44f1b61380d544f63104e0fec3c4929fc6bd85de33e11215e0",`
            `"md5": "48bd506b22680c8110363dd31c63e4a0",`
            `"id": "github.com/chzyer/readline:v0.0.0-20180603132655-2972be24d48e"`
        `}`

Each dependency should have a different id according to the file type: zip, mod or info.

**Comment by Or-Gabay** [comment]
Fixed
https://github.com/jfrog/gocmd/commit/50f0d7b009ee0faeb85836bba3a09956c1edbc13
