### ISSUE TITLE
When I use "--fail-no-op=true",it doesn`t seem to work.

### ISSUE THREAD

**Issue by mosangzi** [jfrog/jfrog-cli#524]
Here is my command.
`jfrog rt dl --flat=true --fail-no-op=true --url=xxx <source_nonexist_repo_path>`
and return me like this
```
{
  "status": "success",
  "totals": {
    "success": 0,
    "failure": 0
  }
}
```
Shouldn`t it exit code 2? Or how can I catch this error in my Jenkins script

**Comment by eyalbe4** [comment]
@mosangzi,
The *fail-no-op* affects the exit code of the process. You can check the exit code by running *echo $?* after JFrog CLI command execution. Did you try this without Jenkins, from the terminal?

**Comment by mosangzi** [comment]
Thanks,it works!And Jenkins can catch this error without running `echo $?`
