### ISSUE TITLE
Using placeholder around const string end with error.

### ISSUE THREAD

**Issue by liron-shalom** [jfrog/jfrog-cli#527]
Running `jfrog rt u --spec="/tmp/cache.spec"`, using the following file-spec:
`{
    "files": [
        {
            "pattern": "/tmp/cache/download/(github.com/*)",
            "target": "go-local/{1}"
        }
    ]
}`

Ends with the flowing error:
`[Error] Path does not exist: /tmp/cache/download/(github.com`.

The result is 0 uploaded files:
`{
  "status": "failure",
  "totals": {
    "success": 0,
    "failure": 0
  }
}`

**Comment by Or-Gabay** [comment]
Fixed here : https://github.com/jfrog/jfrog-client-go/pull/111
