### ISSUE TITLE
Jfrog CLI unable to publish environment variable with string "Key" in it.  

### ISSUE THREAD

**Issue by mamidala86** [jfrog/jfrog-cli#533]
I am having an issue publishing environment variable to buildinfo with a variable which has string 'key' in it

Example: 
I can publish project, projecttest, but projectKey, key, keyy, or any other variable which has word 'key' in it jfrog cli doesnt publish it. All other variables are published fine as expected. I am unable to figure out why only variable name with key in it gets excluded. . I have no include/exclude variables set as well. Verified that env variable does exist as part of the build. Anyone has ran into similar issue ??

jfrog rt bce helloworld 1
jfrog rt bp helloworld 1

**Comment by eyalbe4** [comment]
@mamidala86,
See the **--env-exclude** option of the **frog rt bp** command. Key is one of the default exclude patterns. You can override the defaults by defining your own exclude patterns. 
Let me know if this helps.

**Comment by mamidala86** [comment]
Thats great. I completely overlooked. Thank you. It works but now the real problem is when I exclude it overrides the defaults but when I include it doesnt override the defaults. I just want to be able to include selective variables and one of them has "key" in it and default excludes are not overridden with include option. 
Any suggestions on that

**Comment by mamidala86** [comment]
Thank you very much. That really helps. I completely overlooked.
