### ISSUE TITLE
download --sync-deletes causes panic

### ISSUE THREAD

**Issue by maiteko** [jfrog/jfrog-cli#534]
Ran this command `jfrog rt dl --flat=true --recursive=false --threads=8 c2e-local/Data/Cycles/1906_6.12_20190917/J3S/ ats/C2E/src/Data/J3S/`

Was immediately presented with:

```
Sync-deletes may delete some files in your local file system. Are you sure you want to continue? (y/n): y
 Log path: C:\Users\sean.pace\.jfrog\logs\jfrog-cli.2019-12-18.15-08-30.14216.log
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xae8cd2]

goroutine 1 [running]:
github.com/jfrog/jfrog-cli-go/artifactory/commands/generic.createSyncDeletesWalkFunction.func1(0xc0000ae030, 0x2d, 0x0, 0x0, 0xeb3ae0, 0xc0001dcff0, 0xc000139ad0, 0x1)
        /var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/artifactory/commands/generic/download.go:200 +0x292
github.com/jfrog/jfrog-client-go/utils/io/fileutils.Walk(0xc0000ae030, 0x2d, 0xc0003bc9e0, 0xc0003bc900, 0x0, 0x0)
        /var/lib/jenkins/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.6.1/utils/io/fileutils/listfiles.go:86 +0x126
github.com/jfrog/jfrog-cli-go/artifactory/commands/generic.(*DownloadCommand).Run(0xc000191db0, 0x0, 0x0)
        /var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/artifactory/commands/generic/download.go:115 +0x7af
github.com/jfrog/jfrog-cli-go/artifactory/commands.Exec(0xec2b20, 0xc000191db0, 0xc0000bf2c0, 0xc0000ae000)
        /var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/artifactory/commands/command.go:26 +0x90
github.com/jfrog/jfrog-cli-go/artifactory.downloadCmd(0xc0000c4b00, 0x0, 0x0)
        /var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/artifactory/cli.go:2141 +0x3a3
github.com/jfrog/jfrog-cli-go/artifactory.GetCommands.func4(0xc0000c4b00, 0x1010100, 0xc0000c4b00)
        /var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/artifactory/cli.go:132 +0x32
github.com/codegangsta/cli.HandleAction(0xc4a8e0, 0xda61d0, 0xc0000c4b00, 0xc0000bf200, 0x0)
        /var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/app.go:490 +0xcf
github.com/codegangsta/cli.Command.Run(0xd6a9a7, 0x8, 0x0, 0x0, 0xc000143a70, 0x1, 0x1, 0xd6ea71, 0xf, 0xd9e090, ...)
        /var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/command.go:210 +0x936
github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc0000c1a00, 0xc0000c4840, 0x0, 0x0)
        /var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/app.go:379 +0x81f
github.com/codegangsta/cli.Command.startApp(0xd680a7, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd7294f, 0x14, 0x0, ...)
        /var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/command.go:298 +0x82b
github.com/codegangsta/cli.Command.Run(0xd680a7, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd7294f, 0x14, 0x0, ...)
        /var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/command.go:98 +0x120c
github.com/codegangsta/cli.(*App).Run(0xc0000c1520, 0xc0000bc000, 0x9, 0x10, 0x0, 0x0)
        /var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/app.go:255 +0x6a2
main.execMain(0xc0000adf88, 0xc000072058)
        /var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/main.go:89 +0x1b5
main.main()
        /var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/main.go:71 +0x2e
```

Log seems to show the issue:

```
[Info] Searching items to download...
[Info] Deleting:  C:\repos\C2E\c2e-local\Data\Cycles\1906_6.12_20190917\J3S
```

It's attempting to delete the path defined for the download, from the current working directory. It should be attempting to delete c:\repos\C2E\ats\C2E\src\Data\J3S. It should also, I assume, verify the folder exists before attempting to delete it :)

Side notes:

My hope was this would only delete the local files that had been removed on the server, not the whole folder and then redownload it. I'm already doing that and it's awfully slow (this is potentially a couple of gigs of tiny files, where every once in awhile ONE file is removed).

Also Forcing a confirm each time this is called is a pain from an automation standpoint.

**Comment by eyalbe4** [comment]
@maiteko,
Thanks for reporting this issue. 
We'll look into it keep your up to date with our findings. 
As for the delete confirmation message, you can disable it by adding the **--quiet ** flag to the command. The confirmation message should probably also offer the option of adding this flag.

**Comment by maiteko** [comment]
Thanks for the heads up with the quiet flag, I didn't see it, but didn't look super hard after I ran into the panic. I'll look at it tomorrow.

**Comment by liron-shalom** [comment]
@maiteko,
Can you please share with us the path you tried to sync?

**Comment by maiteko** [comment]
Sync from? Sync to? it's in the original command I believe

from: c2e-local/Data/Cycles/1906_6.12_20190917/J3S/
to: ats/C2E/src/Data/J3S/

**Comment by liron-shalom** [comment]
@maiteko,
Sorry for the unclear question - I meant to the value of the --sync-deletes flag.
The command you shared with us, doesn’t show the flag and it’s value.

In case of download --sync-deletes, the flag value should be “**Specific path in the local file system, under which to sync dependencies after the download**“.
So if you want to sync your entire target-path, your command should be:
`jfrog rt dl --flat=true --recursive=false --threads=8 --sync-deletes=ats/C2E/src/Data/J3S/ c2e-local/Data/Cycles/1906_6.12_20190917/J3S/ ats/C2E/src/Data/J3S/`
Please let us know if this command works for you.

For the panic issue, we will fix it in our next release (check if the file exists before trying to delete it  and if it doesn’t, prompt a clear message).
For you side notes - we do remove only the files that had been removed on the server.

We would appreciate additional feedback you may have for this functionality. Thanks again for reporting this issue and helping us improve.

**Comment by maiteko** [comment]
Ah, you are correct, that contains my old command (pre --sync-deletes) and that explains the problem

I apologize, I misread the command there. I assumed it was a boolean flag and would just sync delete all files in my destination by default. it was placed right before the source, so that's why it attempted to delete that path.

**Comment by maiteko** [comment]
And thank you for the clarification on the other points. I'm glad it actually does do what I expected. That log message just had me concerned :) I was really happy you guys added this, because it's something that's caused a lot of pain points for my team.

**Comment by eyalbe4** [comment]
Happy to hear this functionality brings value to you @maiteko!
@liron-shalom also fixed the functionality, so that it doesn't panic. It is included in the latest patch release.
Feel free to close this issue @maiteko.

**Comment by maiteko** [comment]
Thanks for the quick action/responses guys :)
