### ISSUE TITLE
Unable to publish to artifactory (414 Request-URI Too Large)

### ISSUE THREAD

**Issue by toonetown** [jfrog/jfrog-cli#553]
I am unable to publish to artifactory using a script which leverages Jfrog.  When using Jfrog 1.32.3 (on macOS - installed via brew), it fails with (for example):
```
[Error] [Thread 5] Artifactory response: 414 Request-URI Too Large
```

However, if I roll back and use Jfrog 1.32.1, the exact same command (to the exact same server) succeeds and uploads just fine.

The command I'm running is:
```
jfrog rt u --apikey="${ARTIFACTORY_KEYSTORE_PW}" --url="${ARTIFACTORY_URL}" \
                --build-name="${ARTIFACTORY_PROJECT}" --build-number="${VERSION}.${BUILD_NUM}" \
                --threads=10 --exclude-patterns="*.DS_Store*" \
                "${1}/(*)" \
                "${ARTIFACTORY_RELEASE_REPO}/${ARTIFACTORY_PROJECT}/${VERSION}.${BUILD_NUM}/{1}"
```

**Comment by eyalbe4** [comment]
@toonetown,
I believe that this issue was resolved in version **+.32.4**. Can you please give it try and let us know?

**Comment by toonetown** [comment]
1.32.4 appears to be working.  Thank you.
