### ISSUE TITLE
Issue with publishing artifact jfrog CLI

### ISSUE THREAD

**Issue by Arun1111** [jfrog/jfrog-cli#554]
CLI version 1.32.4 

When running:

jfrog rt mvnc

resulting config is for example:

type: maven
deployer:
  snapshotRepo: libs-snapshot
  releaseRepo: libs-release

Then mvn command jfrog rt mvn "clean install -Dartifactory.publish.buildInfo=true" fails:

[main] ERROR org.jfrog.build.extractor.maven.BuildInfoRecorder - org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded() listener has failed: 
java.lang.IllegalArgumentException: Unable to resolve Artifactory Build Info Client properties: no context URL was found.
    at org.jfrog.build.extractor.maven.BuildInfoClientBuilder.resolveClientProps (BuildInfoClientBuilder.java:36)
    at org.jfrog.build.extractor.maven.BuildInfoClientBuilder.resolveProperties (BuildInfoClientBuilder.java:26)
    at org.jfrog.build.extractor.maven.BuildDeploymentHelper.deployArtifacts (BuildDeploymentHelper.java:298)

**Comment by Or-Gabay** [comment]
@Arun1111 ,  could you share your maven.yaml & full error message?

**Comment by Arun1111** [comment]
@Or-Gabay thanks for your response.

Please find my maven.yml file and full error message attached below.

maven configuration.yml file

version: 1
type: maven
resolver:
  snapshotRepo: alpha-snapshots
  releaseRepo: alpha-release
deployer:
  snapshotRepo: alpha-snapshots
  releaseRepo: alpha-release

Error Logs:

11:18:34  [main] ERROR org.jfrog.build.extractor.maven.BuildInfoRecorder - org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded() listener has failed: 
11:18:34  java.lang.IllegalArgumentException: Unable to resolve Artifactory Build Info Client properties: no context URL was found.
11:18:34  	at org.jfrog.build.extractor.maven.BuildInfoClientBuilder.resolveClientProps(BuildInfoClientBuilder.java:36)
11:18:34  	at org.jfrog.build.extractor.maven.BuildInfoClientBuilder.resolveProperties(BuildInfoClientBuilder.java:26)
11:18:34  	at org.jfrog.build.extractor.maven.BuildDeploymentHelper.deployArtifacts(BuildDeploymentHelper.java:298)
11:18:34  	at org.jfrog.build.extractor.maven.BuildDeploymentHelper.deploy(BuildDeploymentHelper.java:104)
11:18:34  	at org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded(BuildInfoRecorder.java:173)
11:18:34  	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:64)
11:18:34  	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:42)
11:18:34  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:137)
11:18:34  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
11:18:34  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
11:18:34  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
11:18:34  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
11:18:34  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
11:18:34  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
11:18:34  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:18:34  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:18:34  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:18:34  	at java.lang.reflect.Method.invoke(Method.java:498)
11:18:34  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
11:18:34  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
11:18:34  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
11:18:34  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
11:18:34  [main] ERROR org.apache.maven.cli.MavenCli - Internal error: java.lang.RuntimeException: org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded() listener has failed: Unable to resolve Artifactory Build Info Client properties: no context URL was found. -> [Help 1]
11:18:34  org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded() listener has failed: 
11:18:34  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
11:18:34  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
11:18:34  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
11:18:34  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
11:18:34  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:18:34  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:18:34  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:18:34  	at java.lang.reflect.Method.invoke(Method.java:498)
11:18:34  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
11:18:34  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
11:18:34  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
11:18:34  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
11:18:34  Caused by: java.lang.RuntimeException: org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded() listener has failed: 
11:18:34  	at org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded(BuildInfoRecorder.java:182)
11:18:34  	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:64)
11:18:34  	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:42)
11:18:34  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:137)
11:18:34  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
11:18:34  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
11:18:34  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
11:18:34  	... 11 more
11:18:34  Caused by: java.lang.IllegalArgumentException: Unable to resolve Artifactory Build Info Client properties: no context URL was found.
11:18:34  	at org.jfrog.build.extractor.maven.BuildInfoClientBuilder.resolveClientProps(BuildInfoClientBuilder.java:36)
11:18:34  	at org.jfrog.build.extractor.maven.BuildInfoClientBuilder.resolveProperties(BuildInfoClientBuilder.java:26)
11:18:34  	at org.jfrog.build.extractor.maven.BuildDeploymentHelper.deployArtifacts(BuildDeploymentHelper.java:298)
11:18:34  	at org.jfrog.build.extractor.maven.BuildDeploymentHelper.deploy(BuildDeploymentHelper.java:104)
11:18:34  	at org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded(BuildInfoRecorder.java:173)
11:18:34  	... 17 more
11:18:34  [main] ERROR org.apache.maven.cli.MavenCli - 
11:18:34  [main] ERROR org.apache.maven.cli.MavenCli - To see the full stack trace of the errors, re-run Maven with the -e switch.
11:18:34  [main] ERROR org.apache.maven.cli.MavenCli - Re-run Maven using the -X switch to enable full debug logging.
11:18:34  [main] ERROR org.apache.maven.cli.MavenCli - 
11:18:34  [main] ERROR org.apache.maven.cli.MavenCli - For more information about the errors and possible solutions, please read the following articles:
11:18:34  [main] ERROR org.apache.maven.cli.MavenCli - [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
11:18:34  exit status 1

**Comment by Or-Gabay** [comment]
Thanks you, please try to delete maven.yaml and recreate it using jfrog-cli  1.32.4

**Comment by Arun1111** [comment]
@Or-Gabay 

still the same , I am getting the same error.

I am using the jenkins to trigger the mvn job and jfrog cli to upload the artifacts

here is the command I am using 

curl -fL https://getcli.jfrog.io | sh
            
            cat > configuration.yml <<EOL
version: 1
type: maven
resolver:
snapshotRepo: alpha-snapshots
releaseRepo: alpha-release
deployer:
snapshotRepo: alpha-snapshots
releaseRepo: alpha-release
  
EOL
                   export M2_HOME=/opt/maven
                   ./jfrog rt c --url=${baseUrl} --apikey=${this.dsl.env.ApiToken}
                   ./jfrog rt mvn "clean install -Dartifactory.publish.artifacts=flase" configuration.yml --build-name=${buildName} --build-number=${buildVer}
                   ./jfrog rt u "*/jar" healthcloud-snapshot
                   ./jfrog rt bce ${buildName} ${buildVer}
                   ./jfrog rt bp ${buildName} ${buildVer}
				   
				  
The problem is if I use the flag "Dartifactory.publish.artifacts=flase" my job get succesfully executed but in Jfrog under published module the repo path does not show Jar (No path found (externally resolved or deleted/overwritten)). 

So to avoid it I am using flag 	Dartifactory.publish.artifacts=true but it gives me the error I pasted in my last comment. 

Thanks for your help..

**Comment by Arun1111** [comment]
@Or-Gabay 

still the same , I am getting the same error.

I am using the jenkins to trigger the mvn job and jfrog cli to upload the artifacts

here is the command I am using 

curl -fL https://getcli.jfrog.io | sh
            
            cat > configuration.yml <<EOL
version: 1
type: maven
resolver:
snapshotRepo: alpha-snapshots
releaseRepo: alpha-release
deployer:
snapshotRepo: alpha-snapshots
releaseRepo: alpha-release
  
EOL

                   export M2_HOME=/opt/maven
                   ./jfrog rt c --url=${baseUrl} --apikey=${this.dsl.env.ApiToken}
                   ./jfrog rt mvn "clean install -Dartifactory.publish.artifacts=flase" configuration.yml --build-name=${buildName} --build-number=${buildVer}
                   ./jfrog rt bce ${buildName} ${buildVer}
                   ./jfrog rt bp ${buildName} ${buildVer}
				   
				  
The problem is if I use the flag "Dartifactory.publish.artifacts=flase" my job get succesfully executed but in Jfrog under published module the repo path does not show Jar (No path found (externally resolved or deleted/overwritten)). 

So to avoid it I am using flag 	Dartifactory.publish.artifacts=true but it gives me the error I pasted in my last comment.

**Comment by Or-Gabay** [comment]
First of all, there is [Jenkins Artifactory Plug-in](https://www.jfrog.com/confluence/display/RTF/Jenkins+Artifactory+Plug-in), which does all of this  much simpler [(Example)](https://github.com/jfrog/project-examples/blob/master/jenkins-examples/pipeline-examples/scripted-examples/maven-example/Jenkinsfile).
On the other hand, your script is missing the artifactory server configuration in `configuration.yml`.
In order to fix this you need to:

1) Add a serverId to resolver/deployer (i.e. `serverId: *SERVER_ID*`)
2) Add the same serverId to the command jfrog rt c like this: 
`./jfrog rt c *SERVER_ID* --url=${baseUrl} --apikey=${this.dsl.env.ApiToken}`.

Could you please give it a try and let me know?

**Comment by Arun1111** [comment]
@Or-Gabay 

I tried as per your suggestion and its giving "Server ID test API key authentication is not supported" .

**Comment by Or-Gabay** [comment]
Please send me the full error message.

**Comment by Or-Gabay** [comment]
It is recommended to use API key with username only.
Actually, when using the interactive mode of the `jfrog rt c` command (without any flags),
the command no longer accepts an API key without a username.
Since in the past, API key without a username used to be supported, the command can still be provided with an API key without a user, but only if the API key is sent as a flag. The reason why this is still supported is backward compatibility.

Despite the above. the maven integration of JFrog CLI never supported an API key without a username.
Here’s my recommendation for resolving the issue:
1. Configure your Artifactory server details with either username/API key or username/password or access token using the `jfrog rt c` command. Notice that this command is interactive if it is not provided with all the details as flags.
2. Run the following command from the root dir of your project: `jfrog rt mvnc`
    Notice that the above command creates a `.jfrog` dir. I recommend pushing this dir to the source control, so that it is available for your build automation.
3, Run mvn as follows (notice that the command does not includes quotes): jfrog rt mvn clean install --build-name=${buildName} --build-number=${buildVer}
4. Publish the build-info: jfrog rt bp ${buildName} ${buildVer}

One last thing, as a result of your last [comment](https://github.com/jfrog/jfrog-cli/issues/554#issuecomment-573409053), I committed a better error message.
Thanks so much for reporting this!

**Comment by Arun1111** [comment]
@Or-Gabay 

Thanks a lot it worked for me using the username/API key.

**Comment by Or-Gabay** [comment]
Happy to hear it worked for you!!
