### ISSUE TITLE
Upgrade build-info-extractor-gradle

### ISSUE THREAD

**Issue by jvalkeal** [jfrog/jfrog-cli#563]
Version used in

https://github.com/jfrog/jfrog-cli/blob/5dbadad92f4b6fab6d034532b4f49dabf8a2226a/artifactory/commands/gradle/gradle.go#L21

is causing issue fixed in jfrog/build-info#276. It'd be nice to get this version bumped up.

**Comment by jvalkeal** [comment]
@Or-Gabay this was fixed, right?

**Comment by eyalbe4** [comment]
@jvalkeal, 
Yes, the *build-info-extractor-gradle* was upgraded as part of the latest release.
