### ISSUE TITLE
Non-interactive mode for jfrog cli for use in Continuous Integration

### ISSUE THREAD

**Issue by tegataiprime** [jfrog/jfrog-cli#569]
We're using jfrog cli in the context a headless, non-interactive CI process.
Just recently we noticed that jfrog cli 1.33.1 had started to ask interactive questions, where it had not before. e.g.

```
$ jfrog rt config --url https://art.tools.company.us/artifactory --user <username> --password <password> artifactory 
Is the Artifactory HTTP proxy configured to accept a client certificate? [no]:
```

We are working around this like so:
```
$ echo | jfrog rt config --url https://art.tools.company.us/artifactory --user <username> --password <password> artifactory 
Is the Artifactory HTTP proxy configured to accept a client certificate? [no]:
$
```

Passing `--interactive false` as a parameter does not work on all permutations of the config command.  e.g.
```
$ jfrog rt config --url https://art.tools.company.us/artifactory --interactive false --user <username> --password <password> artifactory 
...
...
[Error] Wrong number of arguments.
```

Observation:  It would be useful if setting the CI environment variable to "true" would cause jfrog cli to suppress user interaction and simply accept the default.

**Comment by jvalkeal** [comment]
Seems to work if you use `--interactive=false`

```
$ jfrog rt c rt-server-1 --url=http://localhost:8081/artifactory --user=admin --password=password --interactive false
Is the Artifactory HTTP proxy configured to accept a client certificate? [no]: ^C

$ jfrog rt c rt-server-1 --url=http://localhost:8081/artifactory --user=admin --password=password --interactive=false

[Info] Encrypting password...
```

**Comment by eyalbe4** [comment]
@tegataiprime - thank you so much for reporting this issue!
We did not intend this to be a breaking change. We're working on a fix for this as we speak. We'll update here as soon as the fix is released.
@jvalkeal - thanks for providing the workaround. Setting a the non interactive mode when the CI env var is set to true is a good idea. There's a chance though that this won't be necessary with the implemented fix. We will update here soon.

**Comment by eyalbe4** [comment]
@tegataiprime,
After giving this more thought, having the CI environment variable automatically set the ```rt config``` command to non-interactive mode, may cause confusion. Here's why - If someone sets the CI env var (for example, to disable the progress bar) then the  ```rt config``` command will stop working interactively. The default value of the ```--interactive``` flag is true though. Adding CI into the decision whether to be interactive or not makes the default value of ```--interactive``` hard to explain.
I think that the best and safest approach would be specify explicitly whether you'd like to use the non interactive mode, by adding ```--interactive=false```.
I really apologies for the fact the fucntionality broke as a result of adding the client certificates support to the config.

While looking into this, we also realised that the client certificates flags should be added to the to the ```rt config``` command,. to allow setting them non-interactively. I created https://github.com/jfrog/jfrog-cli/pull/572 to add that.

Let me know what you think.

**Comment by tegataiprime** [comment]
@eyalbe4 This is fine by me, provided that the documentation (provided by the CLI --help and [on-line](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory)) is correct for the most up-to-date, release version of the CLI.  Alternatively, you may wish to consider releasing "bleeding edge" builds via a different channel.

Not wanting to conflate multiple issues, but we also noticed that commands like "npmc" were always interactive.  We would prefer a common CLI policy/convention of ensuing that every command can operate in a non-interactive / batch mode, so that we can automate the heck out of our build process.

Best Regards,
Your friends at Deloitte :)

**Comment by tegataiprime** [comment]
Thank you, that would be a great help.   Ensuring consistency across all CLI commands is important for consumers.  For example some commands expect "--build-name <build-name> --build-number <build-number>" while others expect "<build-name> <build-number>".  Stuff like this tickles my OCD ;)

**Comment by jvalkeal** [comment]
I could not even put any of these config files to a git as we push snapshots, milestones and releases into different artifactory repos meaning config needs to be customised at build time. Now you need to craft these files(i.e. maven/gradle) manually as jfrog config commands are interactive.

**Comment by tegataiprime** [comment]
Same here.  We're using Concourse CI and our build task is written in Python.  So we added a little function to generate the npm config file for the correct resolver/deployer repos based on the branch (feature/bugfix/master).  When npmc can be run in batch mode, we'll switch back to that.

**Comment by eyalbe4** [comment]
Thank you all for the feedback! This really helps.
We will definitely go for non interactive mode for all config commands.

**Comment by eyalbe4** [comment]
@tegataiprime and @jvalkeal, 
@yahavi created https://github.com/jfrog/jfrog-cli/pull/591 to support a non-interactive mode for the various config commands.
We're trying to get this out quickly for you guys. Please follow https://github.com/jfrog/jfrog-cli/pull/591 for updates.

**Comment by eyalbe4** [comment]
@tegataiprime and @jvalkeal,
Version 1.34.0 is released. With this release, all config commands can be used with flags (non-interactive mode).
Also, following your suggestion, when the CI environment variable is set to true, the CLI will run without prompts.
Looking forward to your feedback.
