### ISSUE TITLE
Improvement: add override flag to rt upload

### ISSUE THREAD

**Issue by taormania** [jfrog/jfrog-cli#571]
The rt upload command does not have a flag to overwrite the files if they already exist in the target path. In order to replace the files, the delete command needs to be run first before uploading the new versions.

**Comment by eyalbe4** [comment]
@taormania,
The rt upload command overrides existing files. The command will also check if the files already exist in Artifactory (by sending only the checksum) and if the files exist, Artifactory will only update the path of the files (the content of the files doesn't need to be transferred in this case).
If an existing file in Artifactory does need to be replaced with a different file with the same name and path, this requires delete permissions to be set.
Please let me know if you have any questions or comments.

**Comment by taormania** [comment]
Oh hey this was my fault with a misconfiguration. Sorry about that
