### ISSUE TITLE
CLI doesn't provide feedback when referencing a non existing server id

### ISSUE THREAD

**Issue by itamarb** [jfrog/jfrog-cli#574]
in earlier versions, CLI would return an indicative message saying that you are pointing to a server id that does not exist in the config:

export JFROG_CLI_LOG_LEVEL=DEBUG
jfrog rt dl path/to/folder/ repo/path/in/artifactory/ --server-id test
[Error] Server ID 'test' does not exist.

In the latest version 1.33.1, this message isn't thrown even in debug log level

**Comment by yahavi** [comment]
Fixed by https://github.com/jfrog/jfrog-cli/pull/586.
Will be available in the next version.
