### ISSUE TITLE
1.31.2 illegal file path error

### ISSUE THREAD

**Issue by AdityaGovardhan** [jfrog/jfrog-cli#597]
I am running the following CLI command:
`jfrog rt download some-path/*tar-name.tar.gz --flat=true --explode=true --user=**** --password=**** --url=artifactory-url`

I am getting the following error:

```
[Info] Searching items to download...
[Info] [Thread 2] Downloading some-other-path/tar-name.tar.gz
[Info] [Thread 2] [1]: 206 Partial Content...
[Info] [Thread 2] [0]: 206 Partial Content...
[Info] [Thread 2] [2]: 206 Partial Content...
[Info] [Thread 2] Extracting archive: tar-name.tar.gz to 
[Error] [Thread 2]  Received an error: tar-name/: illegal file path
[Error] tar-name/: illegal file path
{
  "status": "failure",
  "totals": {
    "success": 0,
    "failure": 1
  }
}
[Error] Download finished with errors, please review the logs.
```

However after looking at #298 I tried the following command:
`jfrog rt download some-path/*tar-name.tar.gz all_my_frogs/ --flat=true --explode=true --user=**** --password=**** --url=artifactory-url`

Then it's working fine and downloading as well as extracting in all_my_frogs/ folder.

**Comment by eyalbe4** [comment]
@AdityaGovardhan,
Can you try this with the latest release (currently 1.33.2)?

**Comment by AdityaGovardhan** [comment]
I downloaded the 1.33.2 version using following command:
`curl -fL https://getcli.jfrog.io | sh`

And ran the failing command, but it is still failing.

**Comment by yahavi** [comment]
@AdityaGovardhan,
JFrog CLI 1.35.1 is released. This version includes a fix for this issue.
Feel free to upgrade.
We'll appreciate your feedback for that!
