### ISSUE TITLE
Jfrog cli can work only with local user's

### ISSUE THREAD

**Issue by mfominov** [jfrog/jfrog-cli#599]
Our Artifactory instance connected to Atlassian Crowd and we don't have any local Artifactory user.
When i'm trying to  perform npmi with external user 
```bash
jfrog rt npmi --build-name=my_project --build-number=1.0.0
```
i see this error
```
[Error] Artifactory response: 400 Bad Request
{
  "errors": [
    {
      "status": 400,
      "message": "User 60061914 couldn't be found"
    }
  ]
}
```
but when i perform same operation with local admin, there is no problems.

**Comment by mfominov** [comment]
https://www.jfrog.com/jira/browse/RTFACT-21308 maybe problem not in cli it self

**Comment by eyalbe4** [comment]
@mfominov,
You are correct. Since the above JIRA already tracks this issue. I suggest we close this one.

**Comment by mfominov** [comment]
maybe fix in cli is easy to implement, rather than in artifactory instance

**Comment by eyalbe4** [comment]
I'm not sure it is possible @mfominov, but please share any suggestions or ideas you may have.

**Comment by eyalbe4** [comment]
@mfominov,
Since [RTFACT-21308](https://www.jfrog.com/jira/browse/RTFACT-21308) already tracks this issue, I'm closing this one.
