### ISSUE TITLE
Dependency not publishing for NPM repo

### ISSUE THREAD

**Issue by Arun1111** [jfrog/jfrog-cli#614]
Hello Team,

I am using jfrog cli to publish artifact for a NPM repo. I am able to publish the artifacts while the dependency is not getting published. Could you please advice. 

below pasted is the command I am using.

./jfrog rt c --url=${repoUrl} --apikey=${this.dsl.env.ApiToken}
mkdir .jfrog
cd .jfrog
mkdir projects
cd projects

cat > npm.yaml <<EOL
version: 1
type: npm
resolver:
  repo: npm-int
  serverid: Default-Server
deployer:
  repo: npm-int
  serverid: Default-Server
  
EOL
cd ../..
npm -version
npm install npm@latest -g
                        ./jfrog rt npmi common --build-name=${buildName} --build-number=${buildVersion}
                        ./jfrog rt bag ${buildName} ${buildVersion}
                        ./jfrog rt bce ${buildName} ${buildVersion}
                        ./jfrog rt npmp --build-name=${buildName} --build-number=${buildVersion}
                        ./jfrog rt bp ${buildName} ${buildVersion}

**Comment by yahavi** [comment]
@Arun1111, 
JFrog CLI does not upload the dependencies to Artifactory. 
The dependencies are already there in the remote repository cache. You should see the path for each one of them in the build-info page.

For more information see [Building npm packages](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-BuildingNpmPackages).
If you have more questions, please ask.

**Comment by eyalbe4** [comment]
@Arun1111,
I'm closing this issue for now, but please let us know if you have follow up questions.
