### ISSUE TITLE
Would it be possible to call 'maven_central_sync' endpoint via 'jfrog bt'

### ISSUE THREAD

**Issue by marandaneto** [jfrog/jfrog-cli#620]
Hey :) I'd like to know if it's possible to perform a `maven central sync` command via `jfrog-cli` on bintray's repo, I could not find on help nor on source code.
If not, would it be possible doing a plain http request? if you could point me out to any sort of docs, thanks a lot.

**Comment by marandaneto** [comment]
hey @yahavi any thoughts about it? thanks :)

**Comment by eyalbe4** [comment]
@marandaneto,
*Maven central sync* is currently not supported in JFrog CLI. 
As for some source pointers, JFrog CLI relies heavily on the [jfrog-client-go](https://github.com/jfrog/jfrog-client-go) package. See its README and the source code for integrating with Binary's REST APIs.
Let me know if you need more information.

**Comment by marandaneto** [comment]
I'll have a look at it, thanks @eyalbe4

**Comment by bootstraponline** [comment]
hey, if a pull request were submitted to add maven_central_sync  to jfrog-cli would jfrog merge it?

**Comment by eyalbe4** [comment]
Sure @bootstraponline,
I see that you've already opened https://github.com/jfrog/jfrog-client-go/issues/148.
Feel free to start implementing this on the [jfrog-client-go](https://github.com/jfrog/jfrog-client-go) project. We can first expose this as an additional [service](https://github.com/jfrog/jfrog-client-go/blob/master/README.md).

**Comment by bootstraponline** [comment]
we've submitted a pull request here: https://github.com/jfrog/jfrog-client-go/pull/154 😄

**Comment by marandaneto** [comment]
it seems that the PR got accepted and released https://github.com/jfrog/jfrog-client-go/releases/tag/v0.10.0 :)
thanks for doing this @bootstraponline
now it's a matter of getting this into `jfrog-cli`

**Comment by kowalczykp** [comment]
@marandaneto @eyalbe4 I've raised https://github.com/jfrog/jfrog-cli/pull/690 to include that in `jfrog-cli` today
