### ISSUE TITLE
AzureDevOops [Error] couldn't find plexus-classworlds-x.x.x.jar in Maven installation path, please check M2_HOME environment variable

### ISSUE THREAD

**Issue by dirien** [jfrog/jfrog-cli#625]
**Describe the bug**
When using the a hosted agent (ubuntu) from Azure DevOps we get the error:

`[Info] Running Mvn...
[Info] Downloading build-info-extractor from https://schwarzit.jfrog.io/schwarzit/jcenter-maven-remote/org/jfrog/buildinfo/build-info-extractor-maven3/2.13.13/build-info-extractor-maven3-2.13.13-uber.jar
[Error] couldn't find plexus-classworlds-x.x.x.jar in Maven installation path, please check M2_HOME environment variable
##[error]Error: Command failed: /opt/hostedtoolcache/jfrog/1.31.2/x64/jfrog rt mvn "clean install -f /home/vsts/work/1/s/backend/pom.xml -e --batch-mode" /home/vsts/work/1/s/config --build-name="myaccount-backend-CI" --build-number="195900"
Collecting environment variables...
[Info] Collecting environment variables...
`

**To Reproduce**
Use ArtifactoryMaven Plugin in an Azure Devops Pipline

**Expected behavior**
The Maven Build should run through.

**Versions**
- JFrog CLI version: 1.31.2 
- JFrog CLI operating system: ubuntu 18.04
- Artifactory Version: SaaS and 6.18.0

**Additional context**
The hosted agents from Microsoft use 
Maven 3.6.3
with Maven 3.6.2 everything works fine

This is hard blocking us, and we need to costly provide Agents with 3.6.2 on it.

**Comment by eyalbe4** [comment]
Thanks for reporting this @dirien.
The root cause of this issue is described here -
https://github.com/jfrog/jfrog-cli/issues/511
This issue also includes a temporary workaround (deleting a file on the agent).
The upcoming release of the JFrog Azure DevOps Extension will resolve this issue.

**Comment by dirien** [comment]
Hi @eyalb4doc , thanks for the feedback. 

When will be the release of the new Extension?

**Comment by eyalbe4** [comment]
@dirien,
It is planned to be released by the end of this month.

**Comment by dirien** [comment]
ok looking forward :) 
Thanks
