### ISSUE TITLE
Restrict size of /tmp folder usage

### ISSUE THREAD

**Issue by Snapstromegon** [jfrog/jfrog-cli#653]
We use the CLI to clone some remote Artifactory Repos to local server, but we hit a storage limit since the Artifactory CLI Clutters the /tmp folder (>1TB in our case of /tmp/jfrog.cli.* folders with single folders beeing multiple hundret gigs.).

Is there a way to restrict the size the CLI uses in the tmp folder?

Also it doesn't seem to reuse old tmp folders, so why aren't they deleted?

**Comment by Snapstromegon** [comment]
It seems like the tmp folders don't get deleted reliably (like they stay when the process aborts).

**Comment by yahavi** [comment]
@Snapstromegon can you please be more specific - What is the use case that the `tmp` folder doesn't delete? 
Thanks.

**Comment by Snapstromegon** [comment]
If you have a long running system, which doesn't reboot and e.g. run the cli to clone an Artifactory repo, it creates a folder in the /tmp directory. This folder can grow a lot with a big repo as it seems like it doesn't remove temporary files from that directory after downloading, but deletes the created folder when done.
If it now happens, that you terminate the jfrog cli process (e.g. by hanging up your ssh connection) the created /tmp/jfrog.cli.... folder never gets deleted.

In my opinion it should be possible to limit the maximum size of the /tmp/jrog.cli.* or to enable that the cli deletes temp files immidiatly when done with them.

**Comment by guiramos** [comment]
Do we have an update in this? 

My /temp keeps getting bigger and bigger eating all the available storage.

**Comment by Or-Geva** [comment]
Thanks for reporting this issue @shaybagants & @guiramos.
I believe I found the cause for this issue. I would like to make sure I have it all, do you mind sharing your full CLI download command?

**Comment by Or-Geva** [comment]
@Snapstromegon & @guiramos, JFrog CLI v1.48.0 is released, feel free to upgrade and share your feedback.

**Comment by Snapstromegon** [comment]
We moved away from using JFrog CLI, so I can no longer report on this issue.
If others no longer encounter this issue, feel free to close it.

**Comment by Snapstromegon** [comment]
I will close this issue, since I never heard a similar issue from our side again and also to my team it's no longer needed.

On the same niote, the issue is probably fixed as mentioned above.

**Comment by werdck** [comment]
This question is very relevant to me now.
Situation: Downloading a big repo (>600GB) with some big files (>10GB) to a machine with litte RAM.
My machine has 8GB of RAM for its 2.5TB of storage, because it does not need much RAM for normal operation. Now jfrog clutters all the RAM with temp-files (my /tmp is a ramdisk, as is standard on many distros), and therefore I can expand it to 6GB max.

Is there a way to make it use either another folder or no temp files at all, writing directly to disk?
