### ISSUE TITLE
--model-name and --model-number not filtering jfrog rt download results

### ISSUE THREAD

**Issue by csaska** [jfrog/jfrog-cli#675]
**Describe the bug**

Specifying `buildname/buildnumber` via spec file or `--build-name` and `--build-number` for `jfrog rt download` does not result in dowloading only arftifacts belonging to the specified build as Example 7 below suggests. Instead, it downloads everything.

> Example 7: Download the artifacts from the generic-local repository, which belong to the following build, which had been published to Artifactory - Build name: my-build and build number: 10.

https://www.jfrog.com/confluence/display/JFROG/Using+File+Specs#UsingFileSpecs-UsingPlaceholders

**To Reproduce**

```
jfrog rt upload foo/ sys-pcore-generic-local/tag123/foo/ --build-name=bar --build-number=1
jfrog rt bp bar 1

jfrog rt upload foo/ sys-pcore-generic-local/tag456/foo/ --build-name=bar --build-number=2
jfrog rt bp bar 2

jfrog rt download --build-name=bar --build-number=2  sys-pcore-generic-local
```

**Expected behavior**

Download only artifacts `sys-pcore-generic-local/tag456/foo/`

Instead, both artifacts `sys-pcore-generic-local/tag123/foo/` and `sys-pcore-generic-local/tag456/foo/` are downloaded.

**Versions**
- JFrog CLI version: 1.35.1
- JFrog CLI operating system: ppc64le_linux26_RH7 and amd64_linux26_RH7
- Artifactory Version: Artifactory Enterprise Plus 6.17.0 rev 61700900

**Comment by eyalbe4** [comment]
@csaska,
Filtering out artifacrs by build is done using tbe *--build* option, and not the *--build-name" and *--build-number* options. 
Did that work for you?

**Comment by csaska** [comment]
> Did that work for you?

Yes it did. I misunderstood the documentation.
