### ISSUE TITLE
How to use jfrog cli set properties with filename include #

### ISSUE THREAD

**Issue by Tizeen** [jfrog/jfrog-cli#683]
Sorry.
I have a problem with jfrog cli set properties with filename include #.

My command is:
`
jfrog rt sp "snapshot/feature/abcd/efg#_8.90_ddd.apk" "zone=zone"
`

but it return 400 bad request.
Can anyone help,thanks a lot.

**Comment by Tizeen** [comment]
Following the [official document](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-SettingPropertiesonFiles), I can't find answer.

**Comment by RobiNino** [comment]
Hi @Tizeen ,
Thank you for reporting this issue.
Version 1.38.0 was recently and includes a fix for this issue.
We'd appreciate your feedback for it.

**Comment by Tizeen** [comment]
@RobiNino 
Thx~
