### ISSUE TITLE
--retries has no effect

### ISSUE THREAD

**Issue by mbrancato** [jfrog/jfrog-cli#689]
**Describe the bug**

Retries is not being passed to the http client

**To Reproduce**

`jfrog rt dl --retries=1`

**Expected behavior**

Will retry --retries times for each segment 

**Versions**
- JFrog CLI version: 1.35.3
- JFrog CLI operating system: Mac  and Linux
- Artifactory Version: 🤷‍♂️

**Additional context**

I believe retries is hardcoded to 3 here:
https://github.com/jfrog/jfrog-cli/blob/bfdeea29d204426a38a47897357112e69a20b889/artifactory/utils/dependenciesutils.go#L122

And here:
https://github.com/jfrog/jfrog-cli/blob/bfdeea29d204426a38a47897357112e69a20b889/xray/commands/offlineupdate.go#L156

**Comment by eyalbe4** [comment]
@mbrancato,

Thanks for reporting this issue.

The code in *dependenciesutils.go* downloads the build-info-extractor jars used to integrate with the maven and gradle package managers. The code in *offlineupdate.go* downloads the files for JFrog Xray's offline database sync.
In both scenarios above the total retries is indeed hardcoded to 3 and cannot be configured currently.

As for setting **--retries=1** for the ```jfrog rt dl``` command, can you please share with us the logs showing 3 reties, when you're setting **--retries=1**?
(You can set debug logging with ```export JFROG_CLI_LOG_LEVEL=DEBUG```).

Thanks

**Comment by mbrancato** [comment]
Sure - below is the output from the Azure DevOps task that is using the CLI (version 1.35.3) in its execution. Ignore the obvious network errors, we're working with JFrog support on this. The same holds true if I try `--retries=12` which was my workaround goal to get past the network issues. You can see the CLI command run at the very bottom.

```
Starting: Download Artifacts
==============================================================================
Task         : Artifactory Generic Download
Description  : Download artifacts from Artifactory using FileSpecs, while allowing to collect build-info. The collected build-info can be later published to Artifactory by the "Artifactory Publish Build Info" task.
Version      : 3.9.2
Author       : JFrog
Help         : 
==============================================================================
Found tool in cache: jfrog 1.35.3 x64
Running jfrog-cli from /__t/jfrog/1.35.3/x64/jfrog.
JFrog CLI version: 1.35.3
Generic download...
Using file spec located at /__w/21/s/images/artifacts.json
Using file spec:
{
  "files": [
    {
      "pattern": "myrepo/app1/1.3.4/app1",
      "target": "images/app1-app2/",
      "flat": "true"
    },
    {
      "pattern": "myrepo/app2/1.5.2/app2",
      "target": "images/app1-app2/",
      "flat": "true"
    }
  ]
}

[Info] Searching items to download...
[Info] Searching items to download...
[Info] [Thread 0] Downloading myrepo/app1/1.3.4/app1
[Info] [Thread 0] [0]: 206 Partial Content...
[Info] [Thread 0] [1]: 206 Partial Content...
[Info] [Thread 0] [2]: 206 Partial Content...
[Warn] [Thread 0] [0]: Attempt 0 - Failure occurred while downloading part 0 of https://mydomain.jfrog.io/mydomain/myrepo/app1/1.3.4/app1 - unexpected EOF
[Info] [Thread 0] [0]: 206 Partial Content...
[Warn] [Thread 0] [1]: Attempt 0 - Failure occurred while downloading part 1 of https://mydomain.jfrog.io/mydomain/myrepo/app1/1.3.4/app1 - unexpected EOF
[Info] [Thread 0] [1]: 206 Partial Content...
[Warn] [Thread 0] [0]: Attempt 1 - Failure occurred while downloading part 0 of https://mydomain.jfrog.io/mydomain/myrepo/app1/1.3.4/app1 - unexpected EOF
[Info] [Thread 0] [0]: 206 Partial Content...
[Warn] [Thread 0] [1]: Attempt 1 - Failure occurred while downloading part 1 of https://mydomain.jfrog.io/mydomain/myrepo/app1/1.3.4/app1 - unexpected EOF
[Info] [Thread 0] [1]: 206 Partial Content...
[Info] [Thread 0] Done downloading.
[Info] [Thread 0] Downloading myrepo/app2/1.5.2/app2
[Info] [Thread 0] [0]: 206 Partial Content...
[Info] [Thread 0] [1]: 206 Partial Content...
[Info] [Thread 0] [2]: 206 Partial Content...
[Warn] [Thread 0] [0]: Attempt 0 - Failure occurred while downloading part 0 of https://mydomain.jfrog.io/mydomain/myrepo/app2/1.5.2/app2 - unexpected EOF
[Info] [Thread 0] [0]: 206 Partial Content...
[Warn] [Thread 0] [0]: Attempt 1 - Failure occurred while downloading part 0 of https://mydomain.jfrog.io/mydomain/myrepo/app2/1.5.2/app2 - unexpected EOF
[Info] [Thread 0] [0]: 206 Partial Content...
[Warn] [Thread 0] [0]: Attempt 2 - Failure occurred while downloading part 0 of https://mydomain.jfrog.io/mydomain/myrepo/app2/1.5.2/app2 - unexpected EOF
[Info] [Thread 0] [0]: 206 Partial Content...
[Warn] [Thread 0] [0]: Attempt 3 - Failure occurred while downloading part 0 of https://mydomain.jfrog.io/mydomain/myrepo/app2/1.5.2/app2 - unexpected EOF
[Error] [Thread 0]  Received an error: unexpected EOF
{
[Error] unexpected EOF
[Error] Download finished with errors, please review the logs.
  "status": "failure",
  "totals": {
    "success": 1,
    "failure": 1
  }
}
##[error]Error: Command failed: /__t/jfrog/1.35.3/x64/jfrog rt dl --url="https://mydomain.jfrog.io/mydomain/" --user=*** --password=*** --fail-no-op=true --dry-run=false --insecure-tls=false --threads=1 --retries=1 --validate-symlinks=false --split-count=3 --min-split=5120
Finishing: Download Artifacts
```

**Comment by eyalbe4** [comment]
@mbrancato - thanks a lot for providing the above info.
@Or-Gabay identified the issue and fixed it (see the above pull request).
1.35.4 has been released and includes the fix.
A patch version for Artifactory AzureDevOps Extension with the new release of JFrog CLI will be also be released soon.

**Comment by eyalbe4** [comment]
@mbrancato,
The latest release of the Artifactory Azure DevOps Extension uses JFrog CLI 1.35.5 which includes this fix. Looking forward to your feedback for it.

**Comment by mbrancato** [comment]
Sorry, I'm not working on that problem anymore. Once our connectivity issues were resolved, it was difficult to reproduce the retries problem. Glad to know it is resolved for the next flakey network...
