### ISSUE TITLE
Offer a way to timestamp output

### ISSUE THREAD

**Issue by jblaine** [jfrog/jfrog-cli#698]
Paying customer if that matters at all...

There is no timestamping of operations being performed in `jfrog-cli` and that makes the tool difficult to use to debug or test performance measures. Perhaps a `JFROG_CLI_TIMESTAMP` environment variable could default to off but be toggled on so that this turns into what is shown further down below:
```[Debug] Usage Report: Sending info...
[Info] Searching artifacts...
[Debug] Searching Artifactory using AQL query:
```
Either seconds since UNIX epoch timestamps or ISO 8601 time formatting or whatever...
```
1589573951 [Debug] Usage Report: Sending info...
1589573952 [Info] Searching artifacts...
1589573953 [Debug] Searching Artifactory using AQL query:
```

**Comment by amitron72** [comment]
I join this request. Thank you,  Amit

**Comment by RobiNino** [comment]
Hi @jblaine @amitron72 ,
Thanks for raising this request.
JFrog CLI version 2.12.0 was just released and includes logs timestamp support.

The timestamp can be modified by the following environment variable:
```
JFROG_CLI_LOG_TIMESTAMP
	[Default: TIME]
	Controls the log messages timestamp format.
	Possible values are: TIME, DATE_AND_TIME, and OFF.
```

We'd appreciate your feedback for that.

**Comment by jblaine** [comment]
Looks good to me!
