### ISSUE TITLE
Upload not working due to missing VCS information

### ISSUE THREAD

**Issue by cschyma** [jfrog/jfrog-cli#704]
**Describe the bug**
Starting with 1.35.4, most likely due to fix "Bug fix - VCS props are not added when uploading only one file.", files cannot be uploaded anymore due to missing VCS information:

```
[10:06:03]W:	 [Step 1/1] [Debug] Usage info is disabled.
[10:06:03]W:	 [Step 1/1] [Debug] Saving build general details at: /tmp/jfrog/builds/U21hcnRlbmFuY2UgV2ViXzQuMTEuMC01Ng==/partials
[10:06:03] :	 [Step 1/1] {
[10:06:03] :	 [Step 1/1]   "status": "failure",
[10:06:03] :	 [Step 1/1]   "totals": {
[10:06:03] :	 [Step 1/1]     "success": 0,
[10:06:03] :	 [Step 1/1]     "failure": 0
[10:06:03] :	 [Step 1/1]   }
[10:06:03] :	 [Step 1/1] }
[10:06:03]W:	 [Step 1/1] [Error] open /app/tcbuild/work/c9360888d2aace4e/.git/refs/heads/master: no such file or directory
[10:06:03]W:	 [Step 1/1] [Debug] Uploaded 0 artifacts.
````

**To Reproduce**

```
jfrog rt upload \
    --build-name "test" \
    --build-number 42 \
    artifact.zip \
    generic-development/ApplicationA/
```

**Expected behavior**

```
[11:28:33]W:	 [Step 1/1] [Debug] Usage info is disabled.
[11:28:33]W:	 [Step 1/1] [Debug] Saving build general details at: /tmp/jfrog/builds/U21hcnRlbmFuY2UgV2ViXzQuMTEuMC01OA==/partials
[11:28:33]W:	 [Step 1/1] [Info] [Thread 2] Uploading artifact: artifact.zip
[11:28:33]W:	 [Step 1/1] [Debug] Sending HTTP PUT request to: https://artifactory/artifactory/generic-development/ApplicationA/artifact.zip;build.name=buildname;build.number=4.11.0-58;build.timestamp=1589966595556
[11:28:34]W:	 [Step 1/1] [Debug] [Thread 2]  Artifactory response: 201 Created 
[11:28:34]W:	 [Step 1/1] [Debug] Uploaded 1 artifacts.
```

**Versions**
- JFrog CLI version: >= 1.35.4 
- JFrog CLI operating system: Linux
- Artifactory Version: 6.18.1

**Additional context**
I am using Git as VCS and I do have the .git directory but it is not a normal Git repository containing all the VCS metadata as it is a Git alternate repository.

**Comment by eyalbe4** [comment]
Thanks for reporting thsi issue @cschyma!
Can you please share with us why your local ```.git``` directory is not normal, and maybe share with us its content? Is this something we should support?

**Comment by cschyma** [comment]
We are using TeamCity as build server. There is a mechanism mirroring Git repositories at the build agents.

"TeamCity clones the repository under the agent's system\git directory and uses the mirror as an alternate repository when updating the checkout directory for the build. As a result, this speeds up clean checkout (because only the working directory is cleaned), and saves disk space (as there is only one clone of the given Git repository on an agent)." [TeamCity documentation](https://www.jetbrains.com/help/teamcity/git.html#Git-AgentSettings)

Due to those Git alternate repositories not all files are included at <checkout dir>/.git/refs/ .

Is looking for those files the only way to get the meta info needed by the JFrog CLI?

**Comment by RobiNino** [comment]
Hi @cschyma ,
Im assuming the issue here occurs because the refs are packed.

Additional information will help us make sure the fix we are working on really suits your case.
1. Can you please verify that a `packed-refs` file really exists in your .git directory?
2. Can you please run `git rev-parse HEAD` and verify it successfully prints your revision?

Thanks!

**Comment by cschyma** [comment]
Hi @RobiNino ,

see below.

Thanks!

```
ls -all
total 64
drwxr-xr-x 8 tcbuildagent gde_festo_ux_technical-users 4096 Jun 19 11:26 .
drwxr-xr-x 8 tcbuildagent gde_festo_ux_technical-users 4096 Jun 19 11:26 ..
drwxr-xr-x 2 tcbuildagent gde_festo_ux_technical-users 4096 Jun 19 11:26 branches
-rw-r--r-- 1 tcbuildagent gde_festo_ux_technical-users  500 Jun 19 11:26 config
-rw-r--r-- 1 tcbuildagent gde_festo_ux_technical-users   73 Jun 19 11:26 description
-rw-r--r-- 1 tcbuildagent gde_festo_ux_technical-users  121 Jun 19 11:26 FETCH_HEAD
-rw-r--r-- 1 tcbuildagent gde_festo_ux_technical-users   23 Jun 19 11:26 HEAD
drwxr-xr-x 2 tcbuildagent gde_festo_ux_technical-users 4096 Jun 19 11:26 hooks
-rw-r--r-- 1 tcbuildagent gde_festo_ux_technical-users 6158 Jun 19 11:26 index
drwxr-xr-x 2 tcbuildagent gde_festo_ux_technical-users 4096 Jun 19 11:26 info
drwxr-xr-x 3 tcbuildagent gde_festo_ux_technical-users 4096 Jun 19 11:26 logs
drwxr-xr-x 4 tcbuildagent gde_festo_ux_technical-users 4096 Jun 19 11:26 objects
-rw-r--r-- 1 tcbuildagent gde_festo_ux_technical-users   41 Jun 19 11:26 ORIG_HEAD
-rw-r--r-- 1 tcbuildagent gde_festo_ux_technical-users   98 Jun 19 11:28 packed-refs
drwxr-xr-x 5 tcbuildagent gde_festo_ux_technical-users 4096 Jun 19 11:26 refs
[tcbuildagent@sdeu0022 .git]$ cd ..
[tcbuildagent@sdeu0022 f23d79a197916b91]$ git rev-parse HEAD
4d09a5c16e5647846953b77e4cfb477658e1db1f
```

**Comment by RobiNino** [comment]
Thanks @cschyma ,
The fix should suit your case. We'll update you once it is released.

**Comment by RobiNino** [comment]
Hi @cschyma ,
Version 1.38.0 is released and includes the fix.
We'd appreciate your feedback for it.

**Comment by cschyma** [comment]
Hi @RobiNino,
I've tested 1.38.0 and it is working as expected.
Thank you very much!
