### ISSUE TITLE
jfrog rt build-publish --dry-run deletes local build information

### ISSUE THREAD

**Issue by 7DataBits** [jfrog/jfrog-cli#722]
**Describe the bug**
When executing a `jfrog rt build-publish` command with `--dry-run` flag the gathered local build information is deleted
This leads to
`[Error] open ...\AppData\Local\Temp\jfrog\builds\...\partials\details: The system cannot find the file specified.` when following up with a real publish after the dry run

**To Reproduce**
1. Gather build information: `jfrog rt <command> --build-name=bn1 --build-number=5`
2. Check in temp folder that build information has been gathered (%userprofile%/AppData/Local/Temp/jfrog/builds)
3. Execute dry-run `jfrog rt build-publish --dry-run bn1 5`
4. Check temp folder again to see that gathered information is gone
5. Also execution of build-publish without --dry-run afterwards fails since expected files are not existing anymore

**Expected behavior**
`jfrog rt build-publish --dry-run` does not delete gathered local build information

**Versions**
- JFrog CLI version: 
jfrog version 1.36.0
- JFrog CLI operating system:
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362
- Artifactory Version: (should be irrelevant)
Artifactory Enterprise 
6.18.0 rev 61800900

**Comment by RobiNino** [comment]
Hi @7DataBits,
Thank for reporting this issue.
We recently released version 1.38.0 which includes a fix.
We'd appreciate your feedback for it.
