### ISSUE TITLE
Upload spec placeholders, weird behaviour

### ISSUE THREAD

**Issue by reenberg** [jfrog/jfrog-cli#727]
**Describe the bug**

Depending on how you construct the upload specification (i.e., different uses of placeholders) will result in very different directory layout in the uploaded repository.

**To Reproduce**

1. Setup a remote of docker hub, and download a few images easy testing purposes (e.e. library/debian:{9,10} and library/hello-world)

1. Use the cli to download the remote repository, resulting in a directory structure something like this (module newer images and thus sha256 hashes)

    ```
    dck-docker-local/
    └── library
        ├── debian
        │   ├── 10
        │   │   └── list.manifest.json
        │   ├── 9
        │   │   └── list.manifest.json
        │   ├── sha256__18f374fa88f9230a5c860f986dc83d3d03a056708164ff30c98d0e789e90946d
        │   │   ├── manifest.json
        │   │   ├── sha256__376057ac6fa17f65688c56977118e2e764b27c348b3f70637fa829cd2a12b200
        │   │   └── sha256__5971ee6076a06b695a62d8dbb5e4c977f2db1e45902f5bb8d4b74511d9649dde
        │   └── sha256__d5fee78cade878cd56ae63754a0f923784648b4ad834b7f2f770ad4ff1bda2c6
        │       ├── manifest.json
        │       ├── sha256__1c6172af85ee14a8db5a3a51d406b768dfa94d196c06d0d06d591507cf8199f0
        │       └── sha256__614bb74b620e2f9b393e1a1891cba13193486792ec2c59f7c3ceabee9e6507dd
        └── hello-world
            ├── latest
            │   └── list.manifest.json
            └── sha256__90659bf80b44ce6be8234e6ff90a1ac34acbeb826903b02cfa0da11c82cbc042
                ├── manifest.json
                ├── sha256__0e03bdcc26d7a9a57ef3b6f1bf1a210cff6239bff7c8cac72435984032851689
                └── sha256__bf756fb1ae65adf866bd8c456593cd24beb6a0a061dedf42b26a993176745f6b
    ```

    Note: The root folder name is the same a my local repository, that intend to upload to, such that a wildcard placeholder may be used.

1. Use the cli to upload to another local repository.  Depending on the upload specification used, then various results happen.  Every invocation below is issued alongside of the above folder structure.

```
$  ls -Al
drwxr-xr-x  3 user user 4096 Jun  5 12:49 dck-docker-local
```

With the following upload spec, I get the same behaviour as if I had run `jfrog rt upload --flat=false dck-docker-local/ dck-docker-local`
```
{
    "files": [
        {
            "pattern": "(dck-docker-local)/",
            "target": "{1}",
            "flat": "false"
        }
    ]
}
```
which results in a top level folder named the same as the repository name (I redacted some of the lower level structure for brevity):

```
dck-docker-local   <-- This is the Artifactory repository level
└── dck-docker-local
    └── library
        ├── debian
        │  [...]
        └── hello-world
           [...]
```
This kinda makes sense, though it was not entirely what I expected.  I found out that you need to be inside the folder and run the upload command with `./` as the "source pattern".

**However** the above isn't consistent with the following upload specification, where I just changed the specifc folder name in a placeholder, with a wildcard placeholder
```
{
    "files": [
        {
            "pattern": "(*)/",
            "target": "{1}",
            "flat": "false"
        }
    ]
}
``` 

This results in a directory layout in Artifactory, that doesn't have the  "dck-docker-local" as a root level folder, as above.  And where the files should have been, a "copy" of the directory structure is added, which just kinda blows my mind

```
dck-docker-local   <-- This is the Artifactory repository level
└── library
    ├── debian
    │   ├── 10
    │   │   └── dck-docker-local   <-- This is where the duplicate strucute starts
    │   │       └── library
    │   │           └── debian
    │   │               └── 10
    │   │                   └── list.manifest.json
    │   ├── 9
    │   │   └── dck-docker-local  <-- This is where the duplicate strucute starts
    │   │       └── library
    │   │           └── debian
    │   │               └── 9
    │   │                   └── list.manifest.json
    │   ├── sha256__18f374fa88f9230a5c860f986dc83d3d03a056708164ff30c98d0e789e90946d
    │   │   └── dck-docker-local  <-- This is where the duplicate strucute starts
    │   │       └── library
    │   │           └── debian
    │   │               └── sha256__18f374fa88f9230a5c860f986dc83d3d03a056708164ff30c98d0e789e90946d
    │   │                   ├── manifest.json
    │   │                   ├── sha256__376057ac6fa17f65688c56977118e2e764b27c348b3f70637fa829cd2a12b200
    │   │                   └── sha256__5971ee6076a06b695a62d8dbb5e4c977f2db1e45902f5bb8d4b74511d9649dde
    │   └── sha256__d5fee78cade878cd56ae63754a0f923784648b4ad834b7f2f770ad4ff1bda2c6
    │       └── dck-docker-local  <-- This is where the duplicate strucute starts
    │           └── library
    │               └── debian
    │                   └── sha256__d5fee78cade878cd56ae63754a0f923784648b4ad834b7f2f770ad4ff1bda2c6
    │                       ├── manifest.json
    │                       ├── sha256__1c6172af85ee14a8db5a3a51d406b768dfa94d196c06d0d06d591507cf8199f0
    │                       └── sha256__614bb74b620e2f9b393e1a1891cba13193486792ec2c59f7c3ceabee9e6507dd
    └── hello-world
        ├── latest
        │   └── dck-docker-local  <-- This is where the duplicate strucute starts
        │       └── library
        │           └── hello-world
        │               └── latest
        │                   └── list.manifest.json
        └── sha256__90659bf80b44ce6be8234e6ff90a1ac34acbeb826903b02cfa0da11c82cbc042
            └── dck-docker-local  <-- This is where the duplicate strucute starts
                └── library
                    └── hello-world
                        └── sha256__90659bf80b44ce6be8234e6ff90a1ac34acbeb826903b02cfa0da11c82cbc042
                            ├── manifest.json
                            ├── sha256__0e03bdcc26d7a9a57ef3b6f1bf1a210cff6239bff7c8cac72435984032851689
                            └── sha256__bf756fb1ae65adf866bd8c456593cd24beb6a0a061dedf42b26a993176745f6b
```

It is somewhat visible in this image (somewhat in the sense that the web UI collapses single folder paths)

![Artifactory screenshot](https://i.imgur.com/PILVozv.png)

Adding one more wildcard placeholder, seems to fix this weird behaviour, and also seems to not add the root folder 
```
{
    "files": [
        {
            "pattern": "(*)/(*)",
            "target": "{1}/{2}",
            "flat": "false"
        }
    ]
}

``` 
Which results in the following correct structure

```
dck-docker-local   <-- This is the Artifactory repository level└── library
    ├── debian
    │   ├── 10
    │   │   └── list.manifest.json
    │   ├── 9
    │   │   └── list.manifest.json
    │   ├── sha256__18f374fa88f9230a5c860f986dc83d3d03a056708164ff30c98d0e789e90946d
    │   │   ├── manifest.json
    │   │   ├── sha256__376057ac6fa17f65688c56977118e2e764b27c348b3f70637fa829cd2a12b200
    │   │   └── sha256__5971ee6076a06b695a62d8dbb5e4c977f2db1e45902f5bb8d4b74511d9649dde
    │   └── sha256__d5fee78cade878cd56ae63754a0f923784648b4ad834b7f2f770ad4ff1bda2c6
    │       ├── manifest.json
    │       ├── sha256__1c6172af85ee14a8db5a3a51d406b768dfa94d196c06d0d06d591507cf8199f0
    │       └── sha256__614bb74b620e2f9b393e1a1891cba13193486792ec2c59f7c3ceabee9e6507dd
    └── hello-world
        ├── latest
        │   └── list.manifest.json
        └── sha256__90659bf80b44ce6be8234e6ff90a1ac34acbeb826903b02cfa0da11c82cbc042
            ├── manifest.json
            ├── sha256__0e03bdcc26d7a9a57ef3b6f1bf1a210cff6239bff7c8cac72435984032851689
            └── sha256__bf756fb1ae65adf866bd8c456593cd24beb6a0a061dedf42b26a993176745f6b
```

**Expected behavior**
A consistent directory layout is expected, that matches the one on local disk.

**Versions**
- JFrog CLI version: 1.36.0
- JFrog CLI operating system: Linux
- Artifactory Version: Jfrog Cloud (7.5.2)

**Comment by reenberg** [comment]
From some quick investigation, the culprit seems to be around [getUploadTarget()](https://github.com/jfrog/jfrog-client-go/blob/cdc516390db55682e40d7eba4279f1ad1ae1c200/artifactory/services/upload.go#L284), and whether or not the `target` variable has '/' as a suffix.

In the case of pattern `"(*)/(*)"` and target `"{1}/{2}"`, the resulting target after replacing `{n}` groups ends up being a proper file path, without ending in a '/', as an example target is 
```
dck-docker-local/library/hello-world/sha256__90659bf80b44ce6be8234e6ff90a1ac34acbeb826903b02cfa0da11c82cbc042/sha256__bf756fb1ae65adf866bd8c456593cd24beb6a0a061dedf42b26a993176745f6b
```

In the case of a pattern `"(*)/"` and target `"{1}"`, the resulting target (the same target as above) after replacing `{n}` groups ends up being 
```
dck-docker-local/library/hello-world/sha256__90659bf80b44ce6be8234e6ff90a1ac34acbeb826903b02cfa0da11c82cbc042/
```

Clearly something has happened prior to calling this function, since the target is not the entire path, but everything up until the filename.

**Comment by reenberg** [comment]
I think I have figure out what happens.  As the pattern is `"(*)/"` it obviously only matches the directory part of the path (minus the filename).
However using `"(*)"` as a pattern, which matches the entire file path (including the filename) doesn't work, as [collectFilesForUpload()](https://github.com/jfrog/jfrog-client-go/blob/cdc516390db55682e40d7eba4279f1ad1ae1c200/artifactory/services/upload.go#L137) checks the `target` variable, and if it doesn't contain a '/', then one is added at the end.

This results in the following target `"{1}/"`, which when replaced with the match from the pattern regex being "wrong".  Well wrong in the sense, that it is now no longer being treated as a file, but it is now being treated as a directory.  This results in [getUploadTarget()](https://github.com/jfrog/jfrog-client-go/blob/cdc516390db55682e40d7eba4279f1ad1ae1c200/artifactory/services/upload.go#L285) now adding the local file path to the target, ending up in this "double" path in Artifactory.

If there is truly a reason for adding a '/' to the end of the target, if it didn't contain any, then I would argue that the docs needs some substantional additions details how wildcard patterns is supposed to work.

Unless I'm missing a really good reason for adding '/' as a suffix if the target doesn't contain any in the first place, then it seems just as weird a default behavior as the `--flat=true` default for uploads.  And as such really ought to be heavily documented in [the docs.](https://www.jfrog.com/confluence/display/JFROG/Using+File+Specs#UsingFileSpecs-UsingPlaceholders).

At the very least it would have been decent to have an info log entry, when the code is changing some of my input to something else.

I'm choosing no to close this issue, even though there doesn't seem to be an "error" in the code, as I beliewe the docs are insufficient and the log entry would have been somewhat helpful, as would some more debug logging.

**Comment by eyalbe4** [comment]
@reenberg,
Thank you the through drill down into this!
I believe that the placeholders functionality should be improved to pick up the repository section as part of the path. We will look into everything you wrote above omce we get to working on this, and add we'll updates here.
BTW, if you have the time and would like to get involved in improving the code, you're welcome to of course.

**Comment by barbelity** [comment]
@reenberg please take a look at the [Uploading Files documentation](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-UploadingFiles), and specifically the 'Source path' and 'Target path' command arguments.
Does this part of the documentation give a good explanation for how to use the command?

**Comment by reenberg** [comment]
@eyalbe4, point taken :)  I could just as easily have made a patch for the logging part instead of "complaining" about it, hehe.  I haven't spend nearly as much time looking at the cli code, as I have on the Jenkins plugin, so I guess i just didn't feel as comfortable to make a meaningfull contribution.

@barbelity, mm.  In the general case, yes.  But when it gets a bit more "complex" then you hit a lot of special cases.

The Source Path refers to the `--regexp` argument, which details that the regular expression "must be enclosed in parenthesis".  I may be mixing up the upload and download code/functionality now, but as I remember the parentheses is solely used in combination with placeholders.  The facts that there needs to be a one to one mapping with the number of parenthesis and placeholders (else parenthesis will end up staying in the pattern) is not fully documented anywhere (that I have found).

A note about difference when dealing with local and remote repos would perhaps also be great.  Specifically you need to use the -cache repo when downloading from a remote repository, and then you end up having to deal with expired meta data files resulting in reported "failures" count. 

Perhaps the part of how the source path is going to be reflected in the repository, could be a bit more clear.  i.e. that i have to be inside the directory, using './' or else the directory will also be uploaded to the repository, when downloading and uploading entire repositories, instead of single files.  When reading [this blog post](https://jfrog.com/blog/using-artifactory-with-an-air-gap/), i got the impression that I didn't need to be inside the directory when executing the upload command.

I would argue that the "lack" of docs is in the  [Using Placeholders](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-UsingPlaceholders).  When I read it the first time it seemed quite simple.  But then I encountered all the above issues.  Perhaps because the examples are simple, and my use case is relative complex, to the point of trying to "template" the repository name. 
Having just "*" as a pattern seems like a special corner case, and most likely should be documented, as this had be fooled for quite some time, until i figured that it added the '/', so it should be "*/*" instead (you need a '/' in the pattern, else it will be treated as a directory).

Hope it makes sense, and aren't just a bunch of rambling :)

**Comment by barbelity** [comment]
@reenberg sorry for the late 'awakening', but actually your described issue is known and rather easily resolvable.
Please change your original file-spec to have a **flat=true** value. 

**It should be like:**

```xml
    "files": [
        {
            "pattern": "(*)/",
            "target": "{1}",
            "flat": "true"
        }
    ]
```

Hopefully this will get you the result you expect, please keep us updated.

**Comment by reenberg** [comment]
@barbelity, I also somehow missed basically most notification from github as of late.

I am aware of `flat=true` which I also noted above, and as far as I remember this, then Eyal explained that it has issues with backwards compatability making it hard to do much about, and then me complaining about the docs lacking some better explanation and examples :) 

I guess this issue could be closed with regards to the cli, however I still believe the docs could use some additions with respect to the comments i made above (I didn't check if they changed).
We ended up implementing our sync through some NiFi flows, partly because of the issues with the docker image metadata when using the cli.  So I most likely won't end up getting back to this anytime soon.
