### ISSUE TITLE
Gradle Proxy Enablement ignores no_proxy rules

### ISSUE THREAD

**Issue by Enquier** [jfrog/jfrog-cli#728]
**Describe the bug**
The changes introduced in #359 while important disable the ability to specify a proxy for resolving external dependencies while publishing to an internal repository. For example you might be pulling from an external repository such as external jcenter() or in my case a non-ivy non-maven source that needs manipulation before it can be added to artifactory

**To Reproduce**

1. Configure jfrog/gradle to use http/https_proxy with no_proxy for internal sites (ive tried both IP's and DNS names)
1. Configure a dependency resolution repository that requires a proxy to access
1. Perform gradle tasks including dependency resolution via proxy
1.  Publish Artifacts to internal Artifactory

**Expected behavior**
Gradle/Artifactory plugin to respect no_proxy rules

**Versions**
- JFrog CLI version: Latest
- JFrog CLI operating system: debian/docker
- Artifactory Version: 6.17.0

**Additional context**
Gradle: 4.10.2

**Comment by eyalbe4** [comment]
@Enquier,
Thanks for reporting this. We should probability add a "bypass http proxy" option when configuring an Artifactory server through the *jfrog rt c* command.  What do you think?

**Comment by Enquier** [comment]
That would be a great way to manage internal vs external rt servers/repositories

**Comment by Enquier** [comment]
I have added a PR with a fix for this. CLA is not available via link anymore

**Comment by joanna-polec** [comment]
Hi, do you have any update about this issue?
I have similar problem with gradle deployment, it ignores NO_PROXY env (there is no such issue for mvn or npm). Only one workaround which works is to unset HTTP_PROXY env before running  `jf gradle artifactoryPublish...`
jfrog cli version: 2.59.1

**Comment by yahavi** [comment]
@joanna-polec  
JFrog CLI version 2.65.0 has been released, and it includes a fix for the no-proxy issue during deployment. Please give it a try and let us know your feedback.
