### ISSUE TITLE
Deleted --server-id-deploy option from pip-config parameter 

### ISSUE THREAD

**Issue by iwashitah** [jfrog/jfrog-cli#736]
**Describe the bug**
**--server-id-deploy** option from pip-config parameter is deleted since 1.36.0.

**To Reproduce**
```
$ jfrog -v
jfrog version 1.35.5
iwashita:Downloads iwashita$ jfrog rt pipc -h

Name:
  jfrog rt pipc - Generate pip build configuration.

Usage:
  jfrog rt pip-config

Options:
  --global               [Default: false] Set to true if you'd like the configuration to be global (for all projects). Specific projects can override the global configuration.
  --server-id-resolve    [Optional] Artifactory server ID for resolution. The server should configured using the 'jfrog rt c' command.
  --server-id-deploy     [Optional] Artifactory server ID for deployment. The server should configured using the 'jfrog rt c' command.
  --repo-resolve         [Optional] Repository for dependencies resolution.
  --repo-deploy          [Optional] Repository for artifacts deployment.

$ ./jfrog1.36 rt pipc -h

Name:
  jfrog rt pipc - Generate pip build configuration.

Usage:
  jfrog rt pip-config

Options:
  --global               [Default: false] Set to true if you'd like the configuration to be global (for all projects). Specific projects can override the global configuration.
  --server-id-resolve    [Optional] Artifactory server ID for resolution. The server should configured using the 'jfrog rt c' command.
  --repo-resolve         [Optional] Repository for dependencies resolution.

$ ./jfrog1.36 rt pipc --server-id-resolve=rt-server --server-id-deploy=rt-server --repo-resolve=pypi --repo-deploy=pypi
                                     :
[Error] flag provided but not defined: -server-id-deploy
$
```

**Expected behavior**
Since the option is also written in [Building Python Packages](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-BuildingPythonPackages) and not written in [Release Notes](https://bintray.com/jfrog/jfrog-cli-go/jfrog-cli-linux-amd64#release), please support it again.
In addition, **--repo-deploy** option is also deleted.

**Screenshots**
Please see the above Reproduce steps.

**Versions**
- JFrog CLI version: 1.36.0, 1.37.0
- JFrog CLI operating system: Mac
- Artifactory Version: 7.5.5

**Comment by dvogel** [comment]
This just broke a production database maintenance job for my team. Very disappointing.

**Comment by liron-shalom** [comment]
@iwashitah @dvogel 
Thanks for reporting the issue, we are truly sorry for the inconvenience.
This change actually came to fix a bug of adding these unnecessary flags for the command.
We opened  a [PR](https://github.com/jfrog/jfrog-cli/pull/738) to update the relevant release notes.

**Comment by iwashitah** [comment]
@liron-shalom 
Please update not only Release Note but also [Wiki](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-BuildingPythonPackages)

**Comment by eyalbe4** [comment]
@iwashitah,
Thanks for letting us know these options are still included in the documentation. We removed them now.
Please let us know if you have additional feedback for the pip functionality in JFrog CLI. We'd like to make sure all scenarios and project structures are supported.

**Comment by eyalbe4** [comment]
I'm closing this issue @iwashitah.
Thanks again for your feedback.
