### ISSUE TITLE
jfrog cli(1.35.4) mvn can not resolve snapshot parent pom

### ISSUE THREAD

**Issue by lyqwaterway** [jfrog/jfrog-cli#745]
**Describe the bug**
We can not resolve an snapshot parent pom when we do the maven build

By the way, We can resolve an released parent pom

**To Reproduce**
reproduce steps:(Linux)

1.set up the first maven project. The first is an parent pom project. The version is 1.0.0-SNAPSHOT

Ex: GAVC: org.waterway.oss:parent:pom:1.0.0-SNAPSHOT

2.set up the second maven project and modify the parent field as below

 

<parent>
<groupId>org.waterway.oss</groupId>
<artifactId>parent</artifactId>
<version>1.0.0-SNAPSHOT</version>
<relativePath/>
</parent>

3.install jfrog cli(the version is 1.35.4) and intergrate with jfrog Artifactory (jfrog rt c )

install apache maven (3.6.3)

4.execute jfrog rt mvnc as below:

[root@iz2ze1x83ahtbar67ty7p1z flyway-db]# cat .jfrog/projects/maven.yaml
version: 1
type: maven
resolver:
serverId: Default-Server
snapshotRepo: libs-snapshot
releaseRepo: libs-release

5. execute mvn build as below:

./jfrog rt mvn clean install -U

**Expected behavior**
We want to install an parent pom with snapshot verion

**Screenshots**

**Versions**
- JFrog CLI version: 1.35.4
- JFrog CLI operating system: Linux
- Artifactory Version: Artifactory 6.x and 7.x

**Additional context**
The error message:

[Info] Running Mvn...
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - Scanning for projects...
[main] ERROR org.apache.maven.DefaultMaven - [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.waterway.oss:flyway-db:1.0.0-SNAPSHOT: Could not find artifact org.waterway.oss:parent:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at no local POM @ line 14, column 17
@
[main] ERROR org.apache.maven.cli.MavenCli - The build could not read 1 project -> [Help 1]
[main] ERROR org.apache.maven.cli.MavenCli -
[main] ERROR org.apache.maven.cli.MavenCli - The project org.waterway.oss:flyway-db:1.0.0-SNAPSHOT (/root/code/flyway-demo/flyway-db/pom.xml) has 1 error
[main] ERROR org.apache.maven.cli.MavenCli - Non-resolvable parent POM for org.waterway.oss:flyway-db:1.0.0-SNAPSHOT: Could not find artifact org.waterway.oss:parent:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at no local POM @ line 14, column 17 -> [Help 2]
[main] ERROR org.apache.maven.cli.MavenCli -
[main] ERROR org.apache.maven.cli.MavenCli - To see the full stack trace of the errors, re-run Maven with the -e switch.
[main] ERROR org.apache.maven.cli.MavenCli - Re-run Maven using the -X switch to enable full debug logging.
[main] ERROR org.apache.maven.cli.MavenCli -
[main] ERROR org.apache.maven.cli.MavenCli - For more information about the errors and possible solutions, please read the following articles:
[main] ERROR org.apache.maven.cli.MavenCli - [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[main] ERROR org.apache.maven.cli.MavenCli - [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
[Error] exit status 1

**Comment by lyqwaterway** [comment]
Is there any update for this error？Thanks

**Comment by eyalbe4** [comment]
Thank you for reporting this issue @lyqwaterway.
Do you see the same issue with version 1.38.0?

**Comment by lyqwaterway** [comment]
Thanks. It work on 1.38.0
