### ISSUE TITLE
Does Jfrog CLI support pip3

### ISSUE THREAD

**Issue by Iril** [jfrog/jfrog-cli#758]
We are having problems on Redhat with Python3-pip ( pip3 ) and Jfrog CLI.
Does it support pip3 and how do you tell the cli to use "pip3" instead of "pip" ?

Thanks

**Comment by barbelity** [comment]
@Iril the JFrog CLI indeed executes 'pip' in a new process, it can be any version of pip under that alias.
We understood that the best-practice for building python projects is inside a virtual-environment, which when enabled -> 'pip' executes the corresponding pip executable to the environment's python version.

May using a virtual-environment for building the project with JFrog CLI be a solution for you?
