### ISSUE TITLE
support go get command without needing a local go.mod file

### ISSUE THREAD

**Issue by sophietait** [jfrog/jfrog-cli#763]
Since Artifactory supports go get commands and as of go 1.12, a go.mod file isn't necessary if GO111MODULE="on" and the commands do not need to resolve import paths relative to the current directory or explicitly edit the go.mod file. https://golang.org/doc/go1.12#modules

**Comment by talarian1** [comment]
Hi @sophietait thanks for reporting this issue.
The new feature is included in the [1.40.0](https://github.com/jfrog/jfrog-cli/releases/tag/v1.40.0) release.
We would appreciate any feedback from you.
