### ISSUE TITLE
Is it possible to download the artifacts of a build + dependencies?

### ISSUE THREAD

**Issue by saggl** [jfrog/jfrog-cli#765]
with ``jfrog rt dl --build abc/1`` it is possible to download the artifacts of a build abc/1.

but how is it possible to additionally download the dependencies of build abc/1?

**Comment by Or-Gabay** [comment]
Hey @saggl, could you please share more details about your scenario?

**Comment by saggl** [comment]
I'm still very new to the subject CD. So maybe I want to do something that is actually solved quite differently =) 
but that would be my way of thinking:
1. the development-ci upload artifacts and published the build information under: "develop/1".
2. by publishing or promotion of the build information "develop/1" the test-ci is triggered via webhook. 
 the test-ci should:
- downloads the artifacts belonging to "develop/1": 
``jfrog rt dl --build develop/1``
- tests them
- uploads test results to artifactory and
- publishes its build information under: "test/1"
3. by publishing or promotion of the build information "test/1" the qa-ci is triggered via webhook. 
the qa-ci should:
- download all artifacts and dependencies that belong to "test/1":
maybe ``jfrog rt dl --build --dependency=true test/1``
- verifies the test results generated by "test/1" and does additional stuff with the tested artifacts from "develop/1"

**Comment by Or-Gabay** [comment]
Add at the end of step 2:
   - Promot the build `test/1` to a clean repo, e.g. `jfrog rt bpr test 1 clean-target-repository --include-dependencies`.

3. by the promotion of the build information "test/1" the QA-CI is triggered via webhook.

  - download all artifacts and dependencies from `clean-target-repository`

  - Verifies the test results generated by "test/1".
Let me know if this works for you.

**Comment by saggl** [comment]
first of all thanks for your help =) yes it works. but I would like, if possible, not to move the artifacts during the promotion in order to follow the recommendations in this article Pipeline "[Antipattern: Artifact Promotion](https://www.continuousdeliveryconsulting.com/blog/pipeline-antipattern-artifact-promotion/)". is there another way without moving the artifacts?

**Comment by eyalbe4** [comment]
@saggl,

Here's how you do it. A more or less similar solution is also offered [here](https://stackoverflow.com/questions/51205625/artifactory-query-language-find-dependencies-of-build).
1. Create the following [file spec](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-UsingFileSpecs). Let's name it **my-file-spec** for the sake of this example.
```
{
  "files": [
    {
      "aql": {
        "items.find": {
            "dependency.module.build.name": "my-build-name",
            "dependency.module.build.number":"my-build-number"   
        }
      },
      "target": "my-output-dir/"
    }
  ]
}
```
2. Replace **my-build-name**, **my-build-number** and **my-output-dir** with the right values.
3. Make sure not to delete the slash after **my-output-dir**, to indicate that **my-output-dir** is a directory.
4. Run ```jfrog rt s --spec my-file-spec```
5. If you're satisfied with the result, download the dependencies by running ```jfrog rt dl --spec my-file-spec```.

Let us know if this helps.

**Comment by saggl** [comment]
okay thank you for the quick solution . then I try it like this.

would it still be a cool extension for the CLI to solve it like this?
`` jfrog rt dl --build="test/1" --include-dependencies``

**Comment by eyalbe4** [comment]
Agree @saggl.
We'll include this in a future release.
Thanks for the feedback and for using JFrog CLI!

**Comment by saggl** [comment]
that makes me happy =) many thanks =)
