### ISSUE TITLE
Is there any way we can download the current (N) and previous (N-1) builds using Jfrog Cli

### ISSUE THREAD

**Issue by cloudengineers** [jfrog/jfrog-cli#774]
Hi All, 
Can you please Help me on the below query:
Is there any way we can download the current (N) and previous (N-1) builds using Jfrog Cli ?
Please Note: by using the below command I am able to download the current build  (N)
jfrog rt dl "microservices-release-local/xyz/abcd/*.tgz" --sort-by=created --sort-order=desc --limit=1

I need a command to download my N-1 build

Thank you

**Comment by Or-Gabay** [comment]
You can use `--build` to download artifacts of the specified build, the property format is build-name/build-number.
For more information [click here].(https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-DownloadingFiles)

**Comment by cloudengineers** [comment]
Thank you Gabay, is there any other way we can download N-1 build,

**Comment by Or-Gabay** [comment]
Since you use ` --limit=1` to get the latest `*.tgz`, add `--offset=1` and you will jump to the next `*.tgz`(N-1).
Tell me if this works for you.

**Comment by cloudengineers** [comment]
Thank you @Or-Gabay , I am able to download (N-1)  build with the below command, Thanks for your help. 

jfrog rt dl "microservices-release-local/xyz/abcd/*.tgz" --sort-by=created --sort-order=desc --limit=1 --offset=1
