### ISSUE TITLE
Username must be lowercase when version 1.38

### ISSUE THREAD

**Issue by nicholasdille** [jfrog/jfrog-cli#780]
**Describe the bug**
In version 1.38 access tokens are used instead of basic authentication. Getting the access token from the Artifactory API fails when the username is mixed case because the API expects lowercase usernames. On the other hand, the web UI of Artifactory accepts mixed case usernames. The behaviour should be identical. And the behaviour of jfrog-cli should not break with 1.38.

**To Reproduce**
Configure jfrog-cli using a mixed case username:

```bash
jfrog rt config --url rt.my-domain.com --username MyUser --password 'REDACTED'
jfrog rt search .
```

jfrog-cli fails with the following error:

```
[Error] Artifactory response: 400 Bad Request
{
  "error": "invalid_request",
  "error_description": "User myuser can only create user token(s) for themselves (requested: MyUser)"
}
```

**Expected behavior**
Search should work without error. Username should be converted to lowercase in request for access token.

**Versions**
- JFrog CLI version: 1.38.0
- JFrog CLI operating system: Linux Ubuntu 18.04
- Artifactory Version: 6.17.0

**Additional context**
There is also a [Jira issue for harmonizing the behaviour of the web UI and the API](https://www.jfrog.com/jira/browse/RTFACT-19141).

**Comment by eyalbe4** [comment]
Thanks for reporting this issue @nicholasdille!
We're looking into it now.

**Comment by eyalbe4** [comment]
Great work @@nicholasdille! figuring out the root cause of the issue. That really helped!
The above PR fixes the issue. We plan to release a patch soon.

**Comment by eyalbe4** [comment]
@nicholasdille,
Version 1.38.1 was released and includes this fix.
Looking forward to your feedback for it.

**Comment by nicholasdille** [comment]
Thanks for the update. I will test 1.38.1 in the morning and let you know.

**Comment by nicholasdille** [comment]
@eyalbe4 The patch fixes the issue :-) It works for existing credentials as well as newly configured credentials.

Thanks a lot for fixing this so quickly!
