### ISSUE TITLE
"jfrog rt bdi" return "[Info] Builds discarded". But the Builds are not discarded in Artifactory 

### ISSUE THREAD

**Issue by saggl** [jfrog/jfrog-cli#784]
**Describe the bug**
I have about 60 builds: "abc" and would like to delete all builds except the last 10 with:
``jfrog rt bdi abc --max-builds=10``
after executing the commando I get the following return:
``[Info] Discarding builds ...
[Info] Builds discarded``
a look at the artifactory itself shows that nothing has been deleted.
I think the problem is that I have no delete permission in the repo ``artifactory-build-info`` but I would expect to get an error message and not ``[Info] Builds discarded``.

**To Reproduce**
- publish more than 10 builds to artifactory
- try to discard builds without delete permission in the repo ``artifactory-build-info``

**Expected behavior**
I have about 60 builds: "abc" and would like to delete all builds except the last 10 with 
``jfrog rt bdi abc --max-builds = 10``
after executing the commando I should get the following return:
``[Info] Discarding builds ...
[Error] No Permission to discard Builds``

**Screenshots**

**Versions**
- JFrog CLI version: 1.38.0
- JFrog CLI operating system: Windows 10
- Artifactory Version: 6.19.0

**Additional context**

**Comment by eyalbe4** [comment]
@saggl,

Thanks for reporting this issue.
Is the problem you're seeing is that the builds don't get discarded in Artifactory, or is it that the builds do get discarded, but the build artifacts are not deleted?
If it is the later, then could it be that the artifacts aren't deleted, because the ```--delete-artifacts``` command option wasn't added to the the ```jfrog rt bdi``` command?

I've just tried running the ```jfrog rt bdi``` with a user without delete permissions and got the following output:
```
$ jfrog rt bdi a1 --max-builds=1 --delete-artifacts
[Info] Discarding builds...
[Error] Artifactory response: 500 Internal Server Error
{
  "errors": [
    {
      "status": 500,
      "message": "Errors have occurred while maintaining build retention. Please review the system logs for further information."
    }
  ],
  "error massages": [
    {
      "level": "ERROR",
      "message": "Deleting build a1 #2 failed: User 'a1' is not authorized to delete build info. Delete permission is needed."
    },
    {
      "level": "ERROR",
      "message": "Deleting build a1 #1 failed: User 'a1' is not authorised to delete build info. Delete permission is needed."
    }
  ]
```
Please let me know. Thanks.

**Comment by saggl** [comment]
the problem is that the builds don't get discarded in Artifactory.

**Comment by saggl** [comment]
with ``--delete-artifacts`` i get the same output like you.

**Comment by saggl** [comment]
crazy and also with ``jfrog rt bdi a1 --max-builds=1`` but with ``jfrog rt bdi a1 --max-builds=10`` not

**Comment by saggl** [comment]
ah okay i think i have the problem. I have 60 build information. but when i run ``jfrog rt bdi a1 --max-builds=1`` the error warning comes only for 9 builds and not for 50. then when i run ``jfrog rt bdi a1 --max-builds=10`` everything is okay.

**Comment by saggl** [comment]
what i noticed, the 9 he wants to delete are the only builds i didn't promote. are there any side effects between delete builds and promote?
