### ISSUE TITLE
go get is broken

### ISSUE THREAD

**Issue by christophermancini** [jfrog/jfrog-cli#785]
**Describe the bug**

I have a library of code that is attempting to import a specific package from this project. It currently is incapable of updating to the latest version. Go get responds with `server response: not found: create zip: malformed file path "testsdata/unicode/dirλrec၇tory/aȩ.ȥ1": invalid char '၇'`

**To Reproduce**

```bash
$ go get github.com/jfrog/jfrog-cli@master
go: github.com/jfrog/jfrog-cli master => v1.22.1-0.20200720082616-f4392723b71b
go get: github.com/jfrog/jfrog-cli@v1.22.1-0.20200720082616-f4392723b71b/go.mod: verifying module: github.com/jfrog/jfrog-cli@v1.22.1-0.20200720082616-f4392723b71b/go.mod: reading https://sum.golang.org/lookup/github.com/jfrog/jfrog-cli@v1.22.1-0.20200720082616-f4392723b71b: 410 Gone
        server response: not found: create zip: malformed file path "testsdata/unicode/dirλrec၇tory/aȩ.ȥ1": invalid char '၇'
```

**Expected behavior**

I expect go get to work

**Comment by sam-github** [comment]
It looks like the release tags are of the form `1.2.3`, but go expects `v1.2.3` (its Node.js convention, as well). Adding tags with the leading v might fix this.

**Comment by barbelity** [comment]
@christophermancini we applied a fix for the unsupported characters which failed the module verification (d4c3f08ee9e04fcdf6e3de4b57dcf680537e8a6b).
'go get github.com/jfrog/jfrog-cli@master' should work now.

**Comment by christophermancini** [comment]
Confirmed that it is fixed now, thank you so much!

**Comment by eyalbe4** [comment]
@sam-github and @christophermancini,
We added tag **v1.38.2** to the GitHub project. New releases will include a tag in this format.
See also https://github.com/jfrog/jfrog-cli/pull/792 which adds a new "go get" installation script. We may add this script to the download page of JFrog CLI.
Please let us know if you have any feedback for this script.
