### ISSUE TITLE
Upload command does not respect escaping of commas in build-name and/or props values

### ISSUE THREAD

**Issue by santhonisz** [jfrog/jfrog-cli#786]
**Describe the bug**
When running the `jfrog rt u` command with the `--build-name` and/or `--props` options, escaping of commas in the supplied values is not taken into account and results in multi-valued properties on the artifact(s).
This seems strange as if you use the `jfrog rt sp` command to explicitly set the properties on an existing artifact, the escaping of commas is supported and works as expected.

Note that for the `--build-name` option this causes a problem when later using the `jfrog rt bp` command as the build is not correctly matched up on the expected `build.name` property value on the artifact(s). Instead, when navigating to the artifact(s) of a build you see the text `No path found (externally resolved or deleted/overwritten)` under the *Repo Path* for each artifact.

**To Reproduce**
Run `jfrog rt u <source pattern> <target pattern> --build-name="My\, Build" --props="demo=test\,value"`
When browsing to the *Properties* tab in the Artifactory UI for the uploaded artifact(s) you can see that there are:
- two values for the `build.name` property - `My\` and `Build`
- two values for the `demo` property - `test\` and `value`

**Expected behavior**
The artifacts should have the following property values:
- `build.name` should be `My, Build`
- `demo` should be `test,value`

**Versions**
- JFrog CLI version: 1.38.2
- JFrog CLI operating system: Windows 10
- Artifactory Version: 6.20.0

**Comment by talarian1** [comment]
Hi @santhonisz, thanks for reporting this issue. 
The fix is included in [v1.39.6](https://github.com/jfrog/jfrog-cli/releases/tag/v1.39.6).
Please notice that comma escaping is not needed when using the "--build-name" or "--build-number" .
So `jfrog rt u <source pattern> <target pattern> --build-name="My, Build" --props="demo=test\,value"`
should work for you.
We will appreciate any feedback from you.

**Comment by talarian1** [comment]
I'm closing this issue. @santhonisz, please feel free to re-open it if the fix is not sufficient.
