### ISSUE TITLE
Unable to upload with build name and number

### ISSUE THREAD

**Issue by gjmorgan91** [jfrog/jfrog-cli#789]
I am working to publish a build, but at this time I cannot get my artifacts to be associated to the build.
I set up my config with my url, username, and password and I have verified the artifacts to upload exist and the paths work. I have a dev server id in my config.

When I run: 
`C:\gitlab-runner\jfrog.exe rt u "$CI_PROJECT_DIR/$CI_PIPELINE_IID/Test.txt" "build/$CI_PIPELINE_IID/" --server-id=dev`,
I am able to successfully upload the file.
`{
  "status": "success",
  "totals": {
    "success": 1,
    "failure": 0
  }
}`

However, when I then try to add a --build-name and --build-number, 
`C:\gitlab-runner\jfrog.exe rt u "$CI_PROJECT_DIR/$CI_PIPELINE_IID/" "vsso-main-build/$CI_PIPELINE_IID" --server-id=dev --build-name="main-build" --build-number=$CI_PIPELINE_IID` 
(where $CI_PIPELINE_IID will resolve properly), the upload fails:
`{
  "status": "failure",
  "totals": {
    "success": 0,
    "failure": 1
  }
}`

The logs and the response show that the file for uploading was found but it then registers a 404.
[Info] [Thread 2] Uploading artifact: "path to build"\main-build\997\Test.txt
[Error] [Thread 2] Artifactory response: 404 Not Found

[Error] Failed uploading 1 artifacts.

Am I missing a step here? Is there supposed to be a step to define the job in the first place?

I have the calls for uploading environment data and publishing the build working with the --build-name and --build-number tags working, I can see the builds in the UI with the environment data. What I need is to see the artifacts in that view to know they are associated.

**Comment by eyalbe4** [comment]
@gjmorgan91,
Thanks for reporting this issue. 
Which version of JFrog CLI are you using? If it is not the latest release, can you please try upgrading and let us know if you see anything different?
Can you please share the log messages after setting the *JFROG_CLI_LOG_LEVEL* environment variable to *DEBUG*?
Thanks

**Comment by gjmorgan91** [comment]
I am using CLI version 1.36.0
With Debug turned on I am receiving this response in the logs:

[Debug] Saving build general details at: C:\Users\ADMINI~1\AppData\Local\Temp\2\jfrog\builds\dnNzby1tYWluLWJ1aWxkXzk5Nw==\partials
[Debug] Sending HTTP GET request to: http://{artifactoryserver}/artifactory/{dev directory}/api/system/version
[Info] [Thread 2] Uploading artifact: C:\gitlab-runner\builds\dUqsre6_\0\project\997\Test.txt
[Error] [Thread 2] Artifactory response: 404 Not Found

[Debug] Uploaded 0 artifacts.
[Error] Failed uploading 1 artifacts.
[Debug] Usage Report: Usage Report: Artifactory response: 404 Not Found
{
  "errors": [
    {
      "status": 404,
      "message": "File not found."
    }
  ]
}

**Comment by gjmorgan91** [comment]
The directory in artifactory I am pushing to does exist: http://{artifactoryserver}/artifactory/{dev directory}
and, again, I am able to push just the artifacts to this location but not once I declare the build and build number.

**Comment by eyalbe4** [comment]
@gjmorgan91,
I suspect that the issue is related to the fact the JFrog CLI attaches the Git URL and revision as properties to the deployed artifscts. These properties are attached only in the context of a build. We fixed an issue recently related to the format of the local .git folder, from which this info is fetched. Can you please try using version 1.38.2 and let us know if this resolves the issue?
In case it doesn't, we'll need to check the local .git folder to figure out if this is related to it somehow.

**Comment by RobiNino** [comment]
Hi @gjmorgan91 ,
In addition to what @eyalbe4 mentioned, from the logs you provided it seems that the Artifactory url in your server configuration contains a path. The url should only contain the base Artifactory url (i.e. `http://{artifactoryserver}/artifactory/`), and the repository should be added to the target path in the command (i.e. `"{dev directory}/vsso-main-build/$CI_PIPELINE_IID/"`). Also make sure that the target path has a separator suffix if it should be treated as a directory.

Updated logs would be much appreciated once you fix this. I believe these do not directly cause the issue you described here, but they do mask it.
Thanks!

**Comment by gjmorgan91** [comment]
Ok, updated the cli version I am using 1.38.2 and modified the call to take @RobiNino 's advice as well.
So, I am now calling this: 

`C:\gitlab-runner\jfrog.exe rt u "$CI_PROJECT_DIR/$CI_PIPELINE_IID/" "{dev directory}/main-build/$CI_PIPELINE_IID/"  --build-name="main-build" --build-number=$CI_PIPELINE_IID`

My base artifactory server configured looks as such: `"url": "http://{artifactory server}.com/artifactory"`

With debug still enbaled, my logs look as such:

[Debug] Sending HTTP GET request to: http://{artifactory server}/artifactory/api/system/version
[Debug] Saving build general details at: C:\Users\ADMINI~1\AppData\Local\Temp\2\jfrog\builds\dnNzby1tYWluLWJ1aWxkXzk5Nw==\partials
[Info] [Thread 2] Uploading artifact: C:\gitlab-runner\builds\dUqsre6_\0\build\997\Test.txt
[Error] [Thread 2] Artifactory response: 404 Not Found

[Debug] Uploaded 0 artifacts.
[Error] Failed uploading 1 artifacts.
[Debug] The Artifactory version is: 6.17.0
[Debug] Sending HTTP POST request to: http://{artifactory server}/artifactory/api/system/usage
[Debug] Usage Report: Artifactory response: 200 OK
[Debug] Usage Report: Usage info sent successfully.

I am still receiving some 404, but I cannot see where the issue lies.

**Comment by gjmorgan91** [comment]
Just to point out a discrepancy between when I put up and @RobiNino's comment, I tried with and without the trailing slash on the base artifactory url.

**Comment by eyalbe4** [comment]
@gjmorgan91,

Since you're saying that the upload works well without the ```--build-name``` and ```--build-number``` options, and with those options the upload request fails, I suspect that the issue has to do with one of the values added to the upload URL when adding these options.

What is added to the URL with these options?
The following matrix params are added:
build.name=[the build name];build.number=[the build number];build.timestamp=[the build timestamp];vcd.url=[the build vcd.url];vcd.revision=[the build vcd.revision];

One of the above values added to the URL may cause the upload PUT request to fail. I find it hard to belive that the timestamp causes any issue, because it is just a long number, so we're left with one of one of the following values:
build name
build number
vcs url 
vcs revision

Can you please share with us the build name and number values you add as options to the command?
As for the VCS URL and VCS revision, can you please share with us your local .git folder?
BTW, if you run the command from a location which does not have a .git folder in an upstream directory, and all works, we know for sure that the issue is with the VCS values.

**Comment by eyalbe4** [comment]
@gjmorgan91,
Will you help us fix this issue by sharing with us your **.git** directory? If you can't share it, we can share with you a JFrog CLI version with more debug logging.
Thanks in advance for helping us improve!

**Comment by gjmorgan91** [comment]
Is there any specific information I can get from it? I do not intend to give out the entire .git folder as I do not want to release too much on a public forum.
I have now added the working calls into our gitlab pipeline, and running into issues again. This is one of the calls from the logs;

http://artifactory-server/artifactory/release/build/231/build_14.1.0.231_deploy.zip;build.name=build;build.number=231;build.timestamp=1596813125972;vcs.revision=93f987fd700932cea1d28f4e3c57bcdb4916d671;vcs.url=https%3A%2F%2F%2A%2A%2A.%2A%2A%2A%40git.util.gitlab.com%2Fvsso%2FVIM.git

**Comment by H3npi** [comment]
@eyalbe4 i am getting the same error.

Currently i am using gitlab-ci with the docker image `docker.bintray.io/jfrog/jfrog-cli-go:latest` and as soon as i add `build-name` and `build-number` to `jfrog rt u` i get the 404 error. The URL which was not found:

`/artifactory/*MASKED*/kotlin-client-1.0.0-51f5217b.jar;;;build.number=18077;build.timestamp=1617198899706;vcs.revision=51f5217b4ee5eb6df3cf928bd0212e7c168ed3a0;vcs.url=https://**MASKED**/aws/sam/**reponame-masked**.git;build.name=gitlabci-gradle-artifactory `
