### ISSUE TITLE
global-options  --ssh-key-path not defined

### ISSUE THREAD

**Issue by shivaraman83** [jfrog/jfrog-cli#794]
**Describe the bug**
If you try to use -ssh-key path as an option, it always throws an error as flag provided but not defined: --ssh-key-path
**To Reproduce**
Steps to reproduce the behavior
1. jfrog rt bce --ssh-key-path='somepath' --url-'ssh://maven'

**Expected behavior**
Command should accept the ssh key path and should be able to proceed

**Screenshots**

**Versions**
- JFrog CLI version: 1.35
- JFrog CLI operating system:mac
- Artifactory Version:7.6.2

**Additional context**

**Comment by yahavi** [comment]
@shivaraman83 
`build-collect-env` is a local command. This command collects the environment variables and attaches them to the local build, before publishing it with `build-publish`. This command does not communicate with Artifactory. As a local command it should not accept the server flags.

For more information see [Collecting Environment Variables](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-CollectingEnvironmentVariables).
Please let me know if it helped.
