### ISSUE TITLE
1.38.3 release: "panic: Logger not initialized. See API documentation." error

### ISSUE THREAD

**Issue by salcock** [jfrog/jfrog-cli#800]
**Describe the bug**
Attempting to use the most recent release of jfrog-cli to create a package on Bintray fails, with the program reporting an error: `panic: Logger not initialized. See API documentation.`

**To Reproduce**
Download most recent jfrog-cli release on a fresh install of Ubuntu 16.04, e.g. the `ubuntu:xenial` public Docker image:

    apt-get install curl
    curl --silent -fL -XGET  "https://api.bintray.com/content/jfrog/jfrog-cli-go/\$latest/jfrog-cli-linux-amd64/jfrog?bt_package=jfrog-cli-linux-amd64" > /usr/local/bin/jfrog
    chmod +x /usr/local/bin/jfrog

Configure jfrog with bintray API credentials:

    mkdir -p ~/.jfrog/
    cat << EOF > ~/.jfrog/jfrog-cli.conf
    {
      "artifactory": null,
      "bintray": {
        "user": "${BINTRAY_USERNAME}",
        "key": "${BINTRAY_API_KEY}"
      },
      "Version": "1"
    } 
    EOF

Attempt to create a new package in a bintray repo:

    jfrog bt package-create --licenses "LGPL-3.0" --vcs-url "https://github.com/salcock/libtrace" "wand/libtrace/libtrace4-dev"

Observe error:

    panic: Logger not initialized. See API documentation.

    goroutine 1 [running]:
    github.com/jfrog/jfrog-client-go/utils/log.validateLogInit(...)
	/var/lib/jenkins/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.12.0/utils/log/logger.go:69
    github.com/jfrog/jfrog-client-go/utils/log.Debug(...)
	/var/lib/jenkins/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.12.0/utils/log/logger.go:74
     github.com/jfrog/jfrog-cli/utils/config.createHomeDirBackup(0x14f8d51, 0xdb112a)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli/utils/config/config.go:392 +0x3b4
    github.com/jfrog/jfrog-cli/utils/config.convertIfNeeded(0xc000182000, 0x5e, 0x25e, 0x5e, 0x25e, 0x0, 0x0, 0x7f4e89bff0f8)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli/utils/config/config.go:344 +0xe8
    github.com/jfrog/jfrog-cli/utils/config.readConf(0x0, 0xcf6120, 0x17f4eb088e701)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli/utils/config/config.go:243 +0x127
    github.com/jfrog/jfrog-cli/utils/config.GetAllArtifactoryConfigs(0xcf6120, 0x0, 0x0, 0x15849a0, 0xc00013fe58)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli/utils/config/config.go:137 +0x26
    github.com/jfrog/jfrog-cli/artifactory/commands/replication.getArtifactoryServerIds(0xcb84e0, 0xc00014b140, 0xdb756e)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli/artifactory/commands/replication/template.go:64 +0x48
    github.com/jfrog/jfrog-cli/artifactory/commands/replication.init()
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli/artifactory/commands/replication/template.go:141 +0xc5b

**Expected behavior**
Either the successful creation of a new package in the bintray repository, or an error if the package already exists. In my example, libtrace4-dev already existed so I was expecting output like:

    [Info] Creating package...
    [Error] Bintray response: 409 Conflict
    {
      "message": "Package libtrace4-dev exists for repository 'wand/libtrace'"
    }

Note that downgrading to jfrog CLI 1.38.0 resolves the issue.

**Versions**
- JFrog CLI version: 1.38.0
- JFrog CLI operating system: Ubuntu Xenial (16.04 LTS), but also observed on 18.04 as well.
- Artifactory Version: N/A

**Comment by eyalbe4** [comment]
@salcock,

Than you so much for reporting this issue!
Version 1.38.4 was released and includes the above PR which resolves this issue. We would appreciate your feedback for it.

As a side note, we recommend avoiding editing the config file directly, but using the ```jfrog bt c``` command instead. The command includes the ```--interactive=false``` option, which allows running it with no user prompts as follows:
```
jfrog bt c --interactive=false --user=<your bintray username> --key=<your bintray key>
```

**Comment by salcock** [comment]
Thanks for fixing this issue so quickly. The latest release appears to be working well for us in our packaging and release scripts, so I'm very happy with it.

**Comment by eyalbe4** [comment]
Thanks for the feedback @salcock.
