### ISSUE TITLE
Inconsistent tagging

### ISSUE THREAD

**Issue by dvzrv** [jfrog/jfrog-cli#806]
**Describe the bug**
The tags of this repository are inconsistent. Some are with, some without a `v` prefix.
For downstreams this is very hard to track. Please stick to the ones with `v` prefix now, as `v1.38.4` orders e.g. before (a potential) `1.38.5`.

**To Reproduce**

`git ls-remote -t https://github.com/jfrog/jfrog-cli/`

**Expected behavior**
Only tags with or without `v` prefix.

**Screenshots**
n/a

**Versions**
n/a

**Additional context**
Downstream Linux distributions use tooling to track upstreams (such as this). The ordering of tags is important to figure out what the current latest release is. With changing prefixes this is impossible.

**Comment by eyalbe4** [comment]
@dvzrv,
Up until recently, JFrog CLI release tags did not have the v prefix. Following requests we received, we started adding an additional tag with the v prefix, in addition to the one without it. This should allow tools like "go get", which expects the v prefix to find the version, while other installers, which have received a version without the prefix, can continue working as they always did.
Do you see an issue with having two tags for each release?

**Comment by dvzrv** [comment]
@eyalbe4 as long as the tagging remains consistent, I don't mind either way.

I would probably only use one tagging scheme though, as this gets quite confusing otherwise (e.g. stick to `v` prefix).

**Comment by eyalbe4** [comment]
So we're all good @dvzrv.
Can you please share with us which tools / methods you use to install JFrog CLI?

**Comment by dvzrv** [comment]
I'm building a package using [this PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=jfrog-cli-go).
