### ISSUE TITLE
Regression in 5.39.0 - Wildcards not working for `rt copy --flat`

### ISSUE THREAD

**Issue by carlsmedstad** [jfrog/jfrog-cli#807]
**Describe the bug**
Using wildcards together with `jfrog-cli rt copy --flat` only finds one artifact, regardless of how many artifacts matches the pattern. Using the same pattern and running `jfrog-cli rt download` or `jfrog-rt search` correctly finds all matching artifacts. Using version 5.38.4 and running `jfrog-cli rt copy --flat` correctly finds and copies all matching artifacts.

**To Reproduce**
1. Have a folder with more than one artifact and a destination folder.
2. Run `jfrog-cli rt copy --flat "source_folder/*" "destination_folder/"`
3. Observe `[Info] Found 1 artifact.`
4. Optionally: Use the same pattern and run `jfrog-cli rt search "source_folder/*"` and observe `[Info] Found 2 artifacts.`.

**Expected behavior**
If multiple files match the pattern provided, `jfrog rt copy --flat` should copy all matching files.

**Screenshots**
N/A.

**Versions**
- JFrog CLI version: 5.39.0
- JFrog CLI operating system: Linux
- Artifactory Version: 6.20.0

**Additional context**
The specific files that caused issues for us was an RPM and an md5sum.

**Comment by eyalbe4** [comment]
@carlsmedstad,
Thanks for reporting this issue.
I couldn't however reproduce it. Can you perhaps share the exact folder structure in Artifactory, which is not copied properly?

**Comment by carlsmedstad** [comment]
Masked some stuff but this is the general structure:
```
jfrog rt copy --url URL --user USER --apikey APIKEY --flat 'company-smoketest-rhel7/com/company/product/company-product/3.0.1080/*' company-promoted-rhel7/com/company/product/company-product/3.0.1080/
```

The files are:
```
company-product-3.0.1080-1.noarch.rpm-md5sum
company-product-3.0.1080-1.noarch.rpm
```

I should mention that this is running in the official docker container.

**Comment by carlsmedstad** [comment]
This regressions was introduced in 8ca0cf26.

**Comment by Or-Gabay** [comment]
Thank you @carlsmedstad for sharing your files structure.
As a result, I managed to fix this issue and soon will release a patch.

**Comment by carlsmedstad** [comment]
@Or-Gabay Great news, thanks!
