### ISSUE TITLE
Cannot execute AQL using Creating or updating an unsigned Release Bundle

### ISSUE THREAD

**Issue by iwashitah** [jfrog/jfrog-cli#809]
**Describe the bug**
When AQL is specified in the spec file, the POST method contains a bad payload as below.
`{"name":"cliTest","version":"1.0.0","dry_run":false,"spec":{"queries":null}}`

**To Reproduce**
```
$ cat aql.json 
{
  "files": [
    {
      "aql": {
        "items.find" : {"repo" : "generic-local"}
      },
      "target": "generic-local/data/"
    }
  ]
}
$ jfrog rt rbc --dist-url=http://localhost:8182/distribution --user=admin --password=P@ssw0rd123 --spec=aql.json cliTest 1.0.0
[Error] Distribution response: 400 Bad Request
{
  "detail": "Missing queries",
  "message": "Invalid parameters for release bundle creation",
  "status_code": 400
}
$
```
**Expected behavior**
Can execute the same as REST API ([Create Release Bundle Version](https://www.jfrog.com/confluence/display/JFROG/Distribution+REST+API#DistributionRESTAPI-CreateReleaseBundleVersion))

**Screenshots**
None

**Versions**
- JFrog CLI version: 1.39.0
- JFrog CLI operating system: Mac
- Artifactory Version: 7.7.3

**Additional context**
None

**Comment by iwashitah** [comment]
I posted a basic AQL for explaining the issue. We cannot use the element **pattern** when we want to use complex queries.

**Comment by eyalbe4** [comment]
Got it @iwashitah.
We're working on fixing this issue. We'll send out another update soon.

**Comment by eyalbe4** [comment]
@iwashitah,
Version 1.39.1 is released and includes the fix. Looking forward to your feedback for it.
Thanks for fixing this @yahavi!

**Comment by iwashitah** [comment]
I confirmed the issue was solved. Please close this issue.
Thank you for the quick fix.
