### ISSUE TITLE
`jfrog rt build-publish --dry-run` no longer prints only the JSON to stdout

### ISSUE THREAD

**Issue by byohay** [jfrog/jfrog-cli#820]
**Describe the bug**

The command `jfrog rt build-publish --dry-run` prints the following log message in addition to printing the JSON to stdout: `[Info] [Dry run] Logging Build info preview...`

**To Reproduce**

Upload some build artifacts and run this command: 

`jfrog rt build-publish --dry-run <build-name> <build-number>`

**Expected behavior**

I would expect the command not to print a log message because I rely on the output to stdout to be a clean JSON.

**Versions**
- JFrog CLI version: 1.39.3
- JFrog CLI operating system: Mac OSX
- Artifactory Version: 6.16.0

**Additional context**

This can be bypassed by changing the log level, however it does seem to me like the command should output a pure JSON in any situation.

**Comment by eyalbe4** [comment]
@byohay,
All of JFrog CLI's log messages are printed into *stderr*, so they should cause any issue for you.
Try the following:
```
$ jfrog rt bce test-build-name 1
[Info] Collecting environment variables...
[Info] Collected environment variables for test-build-name/1.
$ 
$ jfrog rt bp test-build-name 1 --dry-run > output
[Info] [Dry run] Logging Build info preview...
$ 
$ cat output 
{
  "name": "test-build-name",
  "number": "1",
  "agent": {
    "name": "jfrog-cli-go",
    "version": "1.39.3"
  },
  "buildAgent": {
    "name": "GENERIC",
    "version": "1.39.3"
  },
  "started": "2020-09-08T12:05:16.695+0300",
  "properties": {
...
```
As you can see above, only the JSON is included as part of the *stdout*.
Please let me know what you think and if this helps.

**Comment by byohay** [comment]
@eyalbe4 thanks! Closing.
