### ISSUE TITLE
"used by" and dependency don't get update when using jenkins rtdownload and publish build info

### ISSUE THREAD

**Issue by levdor** [jfrog/jfrog-cli#828]
"used by" and dependency doesn't get updated when using jenkins rtdownload and publish build info.

I created jenkinsfile with 4 stages:

rtdownload of files from artifactory to specific local locations
maven install which creates an rpm.
rtupload which uploads the new rpm to the artifactory.
rtPublishBuildInfo - as described above.
The rpm uploaded can be seen under "artifacts" of the build in the artifactory builds page. BUT - The files that were downloaded in step 1 are not being added as dependencies of the build (and the build not added to the "used by" list).

**Comment by eyalbe4** [comment]
@levdor,
This is JFrog CLI's GitHub repository.
I assume that you intended to open this issue for the Jenkins Artifactory Plugin.
Is this is the case, can you please open it in the below repository?
https://github.com/jfrog/jenkins-artifactory-plugin
In addition, it is pretty hard to understand the issue from your description. After reopening the issue, can you please try to elaborate more? I'm not sure what **"used by" and dependency** mean.
Thanks!

**Comment by levdor** [comment]
yes, sorry
thank you
