### ISSUE TITLE
rt mvn - server misbehaving

### ISSUE THREAD

**Issue by bolrock** [jfrog/jfrog-cli#829]
I'm testing my gitlab pipeline on a local gitlab server.
In my pipeline I have

    - jfrog rt config myserver --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --password $ARTIFACTORY_PASSWORD --enc-password --interactive=false
    - jfrog rt mvnc --server-id-deploy myserver --repo-deploy-snapshots libs-snapshot-local --repo-deploy-releases libs-release-local
    - jfrog rt mvn clean install --build-name=gitlabci-maven-artifactory --build-number=$CI_JOB_ID

It is working and I for the `rt mvn` command I have

    $ jfrog rt mvn clean install --build-name=gitlabci-maven-artifactory --build-number=$CI_JOB_ID
    [Info] Running Mvn...
    [Debug] Checking prerequisites.
    [Info] Downloading bintray/jcenter/org/jfrog/buildinfo/build-info-extractor-maven3/2.17.0/build-info-extractor-maven3-2.17.0-uber.jar
    [Debug] Sending HTTP HEAD request to: https://dl.bintray.com/bintray/jcenter/org/jfrog/buildinfo/build-info-extractor-maven3/2.17.0/build-info-extractor-maven3-2.17.0-uber.jar
    [Debug] Usage Report: Sending info...
    [Debug] Sending HTTP GET request to: http://artifact.local.intra:8081/artifactory/api/system/version
    [Debug] The Artifactory version is: 6.18.1
    [Debug] Sending HTTP POST request to: http://artifact.local.intra:8081/artifactory/api/system/usage
    [Debug] Usage Report: Artifactory response: 200 OK
    [Debug] Usage Report: Usage info sent successfully.
    [Debug] Sending HTTP GET request to: https://dl.bintray.com/bintray/jcenter/org/jfrog/buildinfo/build-info-extractor-maven3/2.17.0/build-info-extractor-maven3-2.17.0-uber.jar
    [Debug]  Bintray response: 200 OK
    [Info] Downloaded 1 artifact.
    ....

When I'm testing the same pipeline on the 'real' gitlab it is not working.  I have

    $ jfrog rt mvn clean install --build-name=gitlabci-maven-artifactory --build-number=$CI_JOB_ID
    [Info] Running Mvn...
    [Debug] Checking prerequisites.
    [Info] Downloading bintray/jcenter/org/jfrog/buildinfo/build-info-extractor-maven3/2.17.0/build-info-extractor-maven3-2.17.0-uber.jar
    [Debug] Sending HTTP HEAD request to: https://dl.bintray.com/bintray/jcenter/org/jfrog/buildinfo/build-info-extractor-maven3/2.17.0/build-info-extractor-maven3-2.17.0-uber.jar
    [Debug] Usage Report: Sending info...
    [Debug] Sending HTTP GET request to: http://artifact.prod.intra:8081/artifactory/api/system/version
    [Debug] The Artifactory version is: 6.18.1
    [Debug] Sending HTTP POST request to: http://artifact.prod.intra:8081/artifactory/api/system/usage
    [Debug] Usage Report: Artifactory response: 200 OK
    [Debug] Usage Report: Usage info sent successfully.
    [Error] Bintray Head "https://dl.bintray.com/bintray/jcenter/org/jfrog/buildinfo/build-info-extractor-maven3/2.17.0/build-info-extractor-maven3-2.17.0-uber.jar": dial tcp: lookup dl.bintray.com on 10.100.200.2:53: server misbehaving
    ERROR: Job failed: command terminated with exit code 1

What's the problem ?

**Comment by eyalbe4** [comment]
@bolrock,
My guess is that your build agent doesn't have access to the internal. Therefore JFrog CLI fails to download the maven extractor jar, used to integrate with maven.
You have the option of having JFrog CLI download the jar directly from Artifactory. See [this link](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-DownloadingtheMavenandGradleExtractorJARs) for instructions for how to do this. 
Please let us know if this resolves the issue or if you have additional questions.

**Comment by bolrock** [comment]
@eyalbe4 Thanks.  It is now going further but ... not working.

I now have

    - export JFROG_CLI_JCENTER_REMOTE_SERVER=myserver
    - export JFROG_CLI_JCENTER_REMOTE_REPO=myrepo
    - jfrog rt config myserver --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --password $ARTIFACTORY_PASSWORD --enc-password --interactive=false
    - jfrog rt mvnc --server-id-deploy myserver --repo-deploy-snapshots libs-snapshot-local --repo-deploy-releases libs-release-local
    - jfrog rt mvn clean install --build-name=gitlabci-maven-artifactory --build-number=$CI_JOB_ID

and

    $ jfrog rt mvn clean install --build-name=gitlabci-maven-artifactory --build-number=$CI_JOB_ID
    [Info] Running Mvn...
    [Debug] Checking prerequisites.
    [Info] Downloading build-info-extractor from http://artifact.prod.intra:8081/artifactory/fodfin/org/jfrog/buildinfo/build-info-extractor-maven3/2.17.0/build-info-extractor-maven3-2.17.0-uber.jar
    [Debug] Usage Report: Sending info...
    [Debug] Sending HTTP GET request to: http://artifact.prod.intra:8081/artifactory/fodfin/org/jfrog/buildinfo/build-info-extractor-maven3/2.17.0/build-info-extractor-maven3-2.17.0-uber.jar
    [Debug] Sending HTTP GET request to: http://artifact.finbel.intra:8081/artifactory/api/system/version
    [Debug] The Artifactory version is: 6.18.1
    [Debug] Sending HTTP POST request to: http://artifact.finbel.intra:8081/artifactory/api/system/usage
    [Debug] Usage Report: Artifactory response: 200 OK
    [Debug] Usage Report: Usage info sent successfully.
    [Error] 403 Forbidden received when attempting to download http://artifact.prod.intra:8081/artifactory/myrepo/org/jfrog/buildinfo/build-info-extractor-maven3/2.17.0/build-info-extractor-maven3-2.17.0-uber.jar
    ERROR: Job failed: command terminated with exit code 1

I don't understand why it is forbidden.  The previous step (maven compile) is working fine with retrieving all dependencies from the same artifactory repository.

**Comment by eyalbe4** [comment]
I'm not sure @bolrock,
The *jfrog rt mvnc* command does not include resolution server and repository (only deploy). In other words, it is not configured to download maven dependencies from myrepo.
As for the 403 HTTP error, in most cases this is caused by a permissions issue. I suggest you try downloading the file using curl. Use the same credentials you configured for myrepo in JFrog CLI.
If you'll get the same 403 forbidden, then you should look in the Artifactory logs (also available through the UI) to figure out what's wrong. You should also make sure that the remote repo you configured in Artifactory does indeed proxy jcenter.

**Comment by bolrock** [comment]
I don't have the had on the artifactory.  
But ... don't know what happend last week but now it is working !!
Sorry.  Thx for your help.
I'm closing the issue.
