### ISSUE TITLE
Support SSH-Keys with passphrase

### ISSUE THREAD

**Issue by Rondom** [jfrog/jfrog-cli#83]
I just tried to authenticate with Artifactory using my SSH-key and I got the following message, because my key has a passphrase.

    [Info] Performing SSH authentication...
    [Error] ssh: cannot decode encrypted private keys

I think it is not uncommon to protect SSH-Keys using a passphrase.

Expected: jfrog-cli should ask for a passphrase and ideally use the system ssh-agent to support more advanced scenarios than a simple passphrase as well. For a start asking for the passphrase instead of printing that message, would already help.

**Comment by jgeorgeson** [comment]
Please support encrypted keys!

https://stackoverflow.com/questions/42105432/how-to-use-an-encrypted-private-key-with-golang-ssh

**Comment by jgeorgeson** [comment]
Looks like this is fixed in 1.12! Thanks!

**Comment by eyalbe4** [comment]
1.12 does fixes this.
@Rondom, we'd also appreciate your feedback after you try this.

**Comment by Rondom** [comment]
I will try on Monday.

One thing I notice from the commits is that you accept a password from the command line. Many tools that support supplying passwords non-interactively, read them from stdin instead of from command line for security reasons. Especially on shared machines, supplying secrets via command line arguments is an issue, because everyone can see the cmdline including password by running `ps aux` while the tool is running!

**Comment by eyalbe4** [comment]
@Rondom,
If you don't add the passphrase as command option, and your RSA key is encrypted, the CLI will interactively prompt you to enter the passphrase. If you're using a SSH agent, the CLI will obtain the passphrase from it.

**Comment by Rondom** [comment]
The handling of encrypted keys works perfectly. Thank you!

The only thing I noticed: When you run `jfrog rt config` it will ask you whether you want to use SSH agent or not. So you need to know in advance whether you want to use an SSH agent or not. If no agent is available, you get `[Error] SSH agent requested but SSH_AUTH_SOCK not-specified`. But this is not always a given that the agent is always available. For example, in the default configuration of many Linux distribution an SSH-agent will be started automatically for GUI-sessions, but not for text-only sessions such as when logging in via SSH. SSH uses an agent if it is availabe, i.e. it falls back to a password-prompt and only uses the agent if it is available.
What is the rationale for having this configurable? I guess it will also fail, when one wants to use SSH-Agent for a Key that is in non-standard location, but I have not tried.

**Comment by yahavi** [comment]
@Rondom,
Thanks for your feedback.
We will implement your suggestions.

**Comment by jgeorgeson** [comment]
Any updates on this? I don't see any setting in the conf file for using the ssh-agent or not, and regardless of whether I select `y` or `n` I'm being prompted for the key passphrase.

I'm trying to setup SSH private key as a credential in Jenkins, to be opened in an `ssh-agent` step to expose the key to jfrog CLI. Ideally I would be able to do this without a conf file as it would have to be written during each build because as a credential, the key file path will be unique every build.

**Comment by eyalbe4** [comment]
@jgeorgeson,
We haven't implemented this yet. With the latest release, you still need to specify whether to use the SSH agent or not. We do however want to improve this behaviour and would like to see this as part of one of the upcoming releases.

**Comment by AlexeiVainshtein** [comment]
@Rondom, @jgeorgeson and all,

With the current impelementation, when configuring Artifactory with **jfrog rt c** and the URL starts with **ssh://**, you're then asked whether an SSH Agent exists. If the answer is **Yes** JFrog CLI will expect the agent to exist. Else, you'll be asked to provide an SSH Key path.

**We're considering changing the implementation as follows:**

You'll be **optionally** requested to provide the path to the SSH key file. By default this path, if kept empty, will point to **~/.ssh**. Then, you'll be prompted with *Fallback to SSH agent?*
The CLI will first try to look for the SSH key file in the provided path (if provided). If it can't find the key, or there's no valid key there, it will fallback to the SSH Agent (if fallback to SSH agent was requested).

We'd love to hear everyone's feedback for the above suggested implementation.

**Comment by jgeorgeson** [comment]
What about when  _not_ configuring the CLI*? If I use `jfrog rt <command> --url=ssh://art.example.com/artifactory <arguments>` will it go straight to using keys from the agent?

\* There had been #45 request for an arg to the config file, but the resolution was an env variable to the parent dir of the config file instead. But even with that there's not much convenience to trying to put a config file in Jenkins unless the Artifactory Jenkins plugin is expanded to add support for a managed config file for the CLI, complete with credentials substitution. Without that we would need to put CLI config files as secret file credentials, meaning we can't edit them once configured.

**Comment by Rondom** [comment]
Can you please outline what your motivation is for having the requirement to configure things? I am not familar with any constraints that you may have, but I do not see the why behind it.

When I use OpenSSH (to login to a server, clone a git repo...), it works as follows (please double-check, have not checked documentation or source of OpenSSH):
* If ssh-agent is available, it is used (SSH_AUTH_SOCK is set and connection succeeds)
* If key is not in agent (or agent is not running, connection failed or whatever), key is taken from default paths such as `~/.ssh/id_rsa` (if nothing else is specified)

Ideally, I would prefer not to do much configuration, if sane defaults work fine for the majority of the cases:
* ssh-agent is automatically used if available
* key is in ~/.ssh/id_rsa

**Comment by RobiNino** [comment]
Hi @Rondom @jgeorgeson,
On JFrog CLI version 1.21.0 the behaviour of SSH authentication to Artifactory was updated to the following:
1. Try authenticating via ssh-agent.
If failed due to any reason (No agent / connection failed / no key in agent):
2. Try authenticating via ssh-key.
If the key is encrypted, passphrase has to be passed via the --ssh-passphrase flag.

We'll appreciate your feedback regarding this matter.
Thanks
