### ISSUE TITLE
vNext task Artifactory Nuget Restore warning invalid UTF-8

### ISSUE THREAD

**Issue by kw80** [jfrog/jfrog-cli#840]
**Describe the bug**
In Azure DevOps Server 2019 build pipeline, we use task "Artifactory Nuget v2.10.0" from jFrog. During the nuget package restore, a warning message is displayed for some packages that have UTF-16 encoding.

**To Reproduce**
Run build including nuget package restore of "Microsoft.Web.Infrastructure.1.0.0"

**Expected behavior**
No warning message, package dependencies are not skipped

**Versions**
- JFrog CLI version: 1.39.0
- JFrog CLI operating system: Windows 2008 server
- Artifactory Version:  6.18.1

 **Build log of task "Artifactory Nuget restore"**
[Section]Starting: Artifactory NuGet restore

Task         : Artifactory Nuget
Description  : Restore and push NuGet packages from and to Artifactory while allowing to collect build-info. The collected build-info can be later published to Artifactory by the "Artifactory Publish Build Info" task.
Version      : 2.10.0
Author       : JFrog
Help         : [More Information](https://www.jfrog.com/confluence/display/RTF/NuGet+Repositories)

Running jfrog-cli from C:\AGENT\_tool\_jfrog\current\jfrog.exe.
JFrog CLI version: 1.39.0
The following version/s 3.3.0,4.0.0,4.1.0 were found on the build agent
Found tool in cache: NuGet 4.1.0 x64
...
Restoring NuGet package Microsoft.Web.Infrastructure.1.0.0.
...
GET https://server/artifactory/api/nuget/nuget/Packages(Id='Microsoft.Web.Infrastructure',Version='1.0.0')
...
Added package 'Microsoft.Web.Infrastructure.1.0.0' to folder 'C:\AGENT\1234\s\APP_DEV\Src\packages'
Added package 'Microsoft.Web.Infrastructure.1.0.0' to folder 'C:\AGENT\1234\s\APP_DEV\Src\packages' from source 'https://server/artifactory/api/nuget/nuget/'
...
Installed:
    26 package(s) to packages.config projects
[Warn] Package: microsoft.web.infrastructure:1.0.0 couldn't be parsed due to: XML syntax error on line 1: invalid UTF-8 . Skipping the package dependency.
Collecting environment variables...
[Info] Collected environment variables for APP/20200101.1.
##[section]Finishing: Artifactory NuGet restore

**Question**
Does anybody know a UTF-16 package with dependencies (can be UTF-8 depencies, but the nuget package itself should be UTF-16. This will allow us to test the dependencies. Thank you.

**Comment by fourpastmidnight** [comment]
I opened a similar bug for the same exact package over on the GitHub project for the JFrog Azure DevOps Server extension repository: https://github.com/jfrog/jfrog-azure-devops-extension/issues/464

**Comment by sverdlov93** [comment]
Hi @fourpastmidnight and @kw80 
Thanks for reporting this issue.
This PR - https://github.com/jfrog/build-info-go/pull/226 should fix it.
I will update this thread once the next release will be out.

**Comment by fourpastmidnight** [comment]
Awesome, thanks for resolving this quickly. I just had our Azure DevOps Server admin updatè the plugin yesterday, so I still need to test a build using the updated task. I'll report back here soon.

**Comment by sverdlov93** [comment]
Hi @fourpastmidnight,
It will be included in the next ADO JFrog Extension version.

**Comment by sverdlov93** [comment]
@fourpastmidnight 
https://github.com/jfrog/jfrog-azure-devops-extension/releases/tag/2.9.2 is Released!
Looking forward to your feedback on it.
