### ISSUE TITLE
modules in testdata/go make IntelliJ go nuts with trying to request github login information

### ISSUE THREAD

**Issue by 7DataBits** [jfrog/jfrog-cli#841]
**Describe the bug**
Modules in testdata/go seem to be corrupt by design but since the git repo under the specified dependencies are not existing or private, IntelliJ tries to request login information for those repositories.

**To Reproduce**
Checkout jfrog-cli repo with intellij with go plugin installed.

**Expected behavior**
Not have corrupted projects in testdata or fix with replace statements in go.mod files

**Screenshots**
![intellij-github-login-requests](https://user-images.githubusercontent.com/6513731/93991912-2a4b1080-fd8d-11ea-9393-20fa5620dfd0.jpg)

**Versions**
- JFrog CLI version: project source code
- JFrog CLI operating system: Windows

**Comment by RobiNino** [comment]
Hi @7DataBits ,
Thanks for reporting this issue.
This was resolved with the merge of #916.
Would appreciate your feedback, thanks.
