### ISSUE TITLE
Published Modules not available for .vbproj files after nuget restore and build info publish using JFrog-CLI

### ISSUE THREAD

**Issue by vigneshs09jfrog** [jfrog/jfrog-cli#868]
**Describe the bug**
When performing a Nuget restore and build info publish for a .vbproj, the published modules are empty and however, when using a project which has a .csproj files the published modules are having the artifacts shown in the JFrog CLI version above 1.39.0. However, the issue is not reproducible in 1.35.3v of JFrog CLI

**To Reproduce**
Create a sample .NET project which contains only .vbproj files and use the latest version of JFROG-CLI in Azure DevOps pipeline

Reproduction steps: Followed the exact same steps to set up the Azure DevOps pipeline
https://jfrog.com/blog/accelerate-azure-devops-or-tfs-with-jfrog-artifactory-and-nuget/
During the build info publish task, we could notice the below debug message

**Debug message**
2020-10-20T08:29:09.1387387Z All packages listed in packages.config are already installed.
2020-10-20T08:29:09.3389407Z [Debug] Skipping a project "TestProjectVB", since it doesn't have a csproj file path.
2020-10-20T08:29:09.3389407Z [Debug] Skipping a project "TestProjectVB", since it doesn't have a csproj file path.

**Sample azure-pipelines.yaml file:**
`
trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script
- task: ArtifactoryNuGet@2
  inputs:
    command: 'restore'
    artifactoryService: 'vigneshs-saas'
    targetResolveRepo: 'nuget'
    solutionPath: '**/*.sln'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'vigneshs-saas'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'`

**Expected behavior**
If we perform a nuget restore and build publish for a .csproj files proj, then we could get the expected behaviour

**Screenshots**
Screenshot of .vbproj build info- Not working
![image](https://user-images.githubusercontent.com/52813768/96880623-03225480-149b-11eb-80be-5447972f260f.png)

Screenshot of .csproj build info - Working
![image](https://user-images.githubusercontent.com/52813768/96880884-53011b80-149b-11eb-979c-64d6bdb5298c.png)

**Versions**
- JFrog CLI version:  This behaviour is seen observed in 1.39.5, 1.39.0, It works with 1.35.3
- JFrog CLI operating system: Azure DevOps pipeline
- Artifactory Version: 6.18.1, 7.9.0

**Githubproject**
Example project with .vbproj files -> https://github.com/vigneshs09jfrog/vbproj.git
Example project with .csproj files -> https://github.com/vigneshs09jfrog/Nuget.git

Steps to reproduce: 
1. create a new pipeline in Azure DevOps pointing to the above github projects
2. use the provided azure-pipelines yaml file which includes, nuget restore, build info publish and trigger the build. The example code has the exact azure-pipelines yaml file which was used to replicate the issue

**Comment by RobiNino** [comment]
Hi @vigneshs09jfrog ,
Thanks for reporting this issue.
JFrog CLI version 1.40.0 was just released and includes a fix for this issue.

Note that the vbproject you referred to has nothing to restore. I used [this](https://github.com/microsoft/vs-setup-samples) project to reproduce and test the fix.
Thanks!
