### ISSUE TITLE
xrayIndex=true when creating a remote repo with jfrog rt rc doesn’t work

### ISSUE THREAD

**Issue by valeriypj** [jfrog/jfrog-cli#877]
When creating a remote repository with **xrayIndex=true** with **$ jfrog rt rc** it doesn't enable Xray indexing checkbox in Artifactory.

**To Reproduce**
$ cat maven.json
{
        "blockMismatchingMimeTypes": "true",
        "enableTokenAuthentication": "true",
        "key": "atlassian-nonblocking-remote-cli",
        "packageType": "maven",
        "rclass": "remote",
        "repoLayoutRef": "maven-2-default",
        "url": "https://maven.atlassian.com/repository/public",
        **"xrayIndex": "true"**
}

$ jfrog rt rc maven.json

Repository created in Artifactory without Enable Indexing in Xray checkbox set.

**Expected behavior**
The repository will be created with Enable Indexing in Xray set.

**Versions**
- JFrog CLI version: 1.39.7
- JFrog CLI operating system: MacOS
- Artifactory Version: 7.10.2

**Comment by yahavi** [comment]
Hi, @valeriypj.
By looking into the repository configuration, I can see no `xrayIndex` key for remote repositories:
https://www.jfrog.com/confluence/display/JFROG/Repository+Configuration+JSON#RepositoryConfigurationJSON-RemoteRepository
There is an `xrayIndex` key only for local repositories. Furthermore, I'm not sure how this feature would work, but this is out of topic.
Please let me know what you think.

**Comment by yahavi** [comment]
Resolved by https://github.com/jfrog/jfrog-cli-core/pull/31
