### ISSUE TITLE
JFrog CLI doesn't support V3 Nugget packages while Artifactory does.

### ISSUE THREAD

**Issue by OrNaishtat1** [jfrog/jfrog-cli#881]

**Comment by RobiNino** [comment]
JFrog CLI 1.42.0 was released and includes NuGet V3 support:
NuGet v3 will now be the default protocol.
Using v2 can be configured in the project config file (by running nugetc or dotnetc, with --nuget-v2 or interactively), or by option for the legacy nuget command (--nuget-v2-protocol).
