### ISSUE TITLE
Lacks console tracing

### ISSUE THREAD

**Issue by rico-chet** [jfrog/jfrog-cli#885]
**Describe the bug**
When an error occurs, it's not directly visible to a user. She has to find out name of the log file and look there.

**To Reproduce**
Set log level to DEBUG and run a `jfrog-cli rt download` command which fails with an SSH Agent error, e.g. due to a mistyped host name.

**Expected behavior**
The SSH Agent error is printed to _stderr_ when verbosity is high.

**Screenshots**
You see the confusing error message below because the key is encrypted but SSH-Agent which failed, so the fallback to a different method is active
:
```
$ jfrog-cli rt download ...
 Log path: /tmp/jfh/logs/jfrog-cli.2020-11-04.09-55-50.27487.log
{
  "status": "failure",
  "totals": {
    "success": 0,
    "failure": 0
  }
}
[Error] SSH Key is encrypted but no passphrase was specified.

$ cat /tmp/jfh/logs/jfrog-cli.2020-11-04.09-55-50.27487.log
[Info] Performing SSH authentication...
[Info] Trying to authenticate via SSH-Agent...
[Debug] Usage info is disabled.
[Info] Authentication via SSH-Agent failed. Error:
 dial tcp: lookup artifactory.example.com on 10.20.30.40:53: no such host
[Info] Trying to authenticate via SSH Key...
[Info] Authentication via SSH key failed.
```

**Versions**
- JFrog CLI version: 1.40.1
- JFrog CLI operating system: Debian buster / Debian sid
- Artifactory Version: unknown, doesn't matter

**Comment by yahavi** [comment]
Thanks for reporting this issue, @rico-chet.
The JFrog CLI shows a progress bar when a human user downloads or uploads files. 
In order to show the progress bar neatly, we redirect all outputs to a file, except the command summary.

In CI servers we print the logs to the screen instead. Therefore, setting environment variable CI=TRUE will be an easy workaround for you. Simply run:
```
CI=TRUE jfrog-cli rt download
```

By the way, do you see this behavior in a CI server? I'd like to know.
Please let me know what you think.

**Comment by rico-chet** [comment]
Thank you for the response. I don't remember if I saw this in CI, I set it a year ago (and I am not sure we have the CI environment variable set...).

Now as a user, I run a script which caches a _git LFS_ Artifactory repository for faster cloning. It's done via SSH and my keys are passphrase-protected with an SSH agent active to save the typing. I will add `CI=TRUE` to my script to get to the reason of failure faster next time. Maybe a new CLI parameter would be handy for this to be available in a more straightforward way. I cannot come up with a nice name, though.

You can close this issue if you like.
