### ISSUE TITLE
docs missing certificate format info

### ISSUE THREAD

**Issue by kenyon** [jfrog/jfrog-cli#954]
The [documentation](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-NotUsingaPublicCA(CertificateAuthority)?) about using your own certificates in the `~/.jfrog/security/certs` directory doesn't say what format the certificates should be in.

**Comment by eyalbe4** [comment]
Thank you for reporting this @kenyon!
We updated the [documentation] and added the following to it:
```
The supported certificate format is PEM.
``` 
If you'd like us to add anything else, please let su know.

**Comment by kenyon** [comment]
Works for me, thanks.
