### ISSUE TITLE
Using sort-by results in artifactory response 400 (bad request)

### ISSUE THREAD

**Issue by tllngr** [jfrog/jfrog-cli#957]
**Describe the bug**
When using option --sort-by I always get error response 

> [Error] Artifactory response: 400 Bad Request

**To Reproduce**
Without using _--sort-by_ option, following example commands do succeed
```
jfrog rt s generic-local/
jfrog rt del "generic-local/mytest/*" --dry-run
```

Applying _--sort-by_ in the example commands above result in error "bad request"
```
jfrog rt s generic-local/ --sort-by created
jfrog rt del "generic-local/mytest/*" --dry-run --sort-by name
```

**Expected behavior**
Expecting that  --sort-by does not cause "bad request" and does sorting as described

**Screenshots**
none

**Versions**
- JFrog CLI version: 1.43.2
- JFrog CLI operating system: Linux Mint 18.1 (serena) x86_64
- Artifactory Version:  7.4.3 rev 70403900 (CE)

**Additional context**
none

**Comment by RobiNino** [comment]
Hi @tllngr ,
Can you please provide the full log while exporting `JFROG_CLI_LOG_LEVEL=DEBUG`?
Thanks

**Comment by tllngr** [comment]
Hi @RobiNino ,

here is a log from search query command `jfrog rt s generic-local/ --sort-by created` (as mentioned above)

~~~.sh
$ jfrog rt s generic-local/ --sort-by created
[Debug] Usage Report: Sending info...
[Info] Searching artifacts...
[Debug] Searching Artifactory using AQL query:
 items.find({"$or":[{"$and":[{"repo":"generic-local","path":{"$match":"*"},"name":{"$match":"*"}}]}]}).include("name","repo","path","actual_md5","actual_sha1","size","type","modified","created").sort({"$asc":["created"]})
[Debug] Sending HTTP POST request to: https://jfrogserver/artifactory/api/search/aql
[Debug] Sending HTTP GET request to: https://jfrogserver/artifactory/api/system/version
[Debug] The Artifactory version is: 7.4.3
[Debug] Sending HTTP POST request to: https://jfrogserver/artifactory/api/system/usage
[Error] Artifactory response: 400 Bad Request

[Debug] Usage Report: Artifactory response: 200 OK
[Debug] Usage Report: Usage info sent successfully.
[Error] Artifactory response: 400 Bad Request
~~~

**Comment by RobiNino** [comment]
Thanks for the logs @tllngr .
I couldn't reproduce this issue on my environment. The AQL generated is correct, and works when I run the request via cURL, so this is unlikely an issue with the CLI.
(I tested against Artifactory 7.10.2, but I'm unaware of such issue in the previous versions).

I suggest you try running the [AQL](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-ArtifactoryQueryLanguage(AQL)) via cURL as well to verify this assumption.
If the issue persists, checking the Artifactory logs for more details could be helpful.

**Comment by tllngr** [comment]
Hi @RobiNino,

i did a search request using AQL via cURL as you suggested:
~~~
curl -u user:pw -X POST -k -H 'Content-Type:text/plain' -i 'https://jfrogserver/artifactory/api/search/aql' --data 'items.find({"repo":{"$eq":"generic-local"}}).sort({"$asc" : ["repo","name"]})'
HTTP/1.1 200 Connection established
Proxy-Connection: keep-alive
Connection: close

HTTP/1.1 400 Bad Request
Date: Mon, 25 Jan 2021 14:28:45 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Server: Artifactory/7.4.3 70403900
...

Sorting is not supported by AQL in the open source version
~~~

So it turns out that Artifactory CE does not allow sorting? I didn't find any note on this at the documentation, neither at jfrog cli nor artifactory and aql

**Comment by RobiNino** [comment]
Hi @tllngr ,
I'm afraid you are correct and sorting is not support in Artifactory OSS and CE.
This has been added to the [Artifactory Comparison Matrix](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Comparison+Matrix).
We are sorry for the inconvenience caused to you by this.
Thanks for reporting this issue

**Comment by tllngr** [comment]
Hi @RobiNino ,

thanks for pointing this out and for adding it to the Artifactory Comparison Matrix. I guess i can close this ticket right now

**Comment by itsmejoeeey** [comment]
It is disappointing to see how opaque and misleading JFrog makes the evaluation process between versions.

- The current [Artifactory Comparison Matrix](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Comparison+Matrix) is very unclear (especially since AQL is mostly supported even on the CE)
- Other API's ([such as these](https://jfrog.com/help/r/jfrog-rest-apis/artifact-latest-version-search-based-on-layout)) make it clear when a feature requires "Pro", Why is none of this made clear [on any](https://jfrog.com/help/r/jfrog-rest-apis/artifactory-query-language-aql). [of the](https://jfrog.com/help/r/jfrog-rest-apis/artifactory-query-language). [other pages](https://jfrog.com/help/r/jfrog-rest-apis/sorting-in-aql) related to AQL.

While nothing is owed to the community-edition users, it is also a shame that such foundational functionality as AQL-sort had to be witheld from the barebones community edition.
