### ISSUE TITLE
CLI with ssh does not prompt for key passphrase

### ISSUE THREAD

**Issue by lorenyeung** [jfrog/jfrog-cli#980]
**Describe the bug**
When setting up the CLI to use SSH authentication, the CLI does not prompt for a passphrase. This means that when the user attempts to use the server-id later, it will error with 'empty password' but fail with a different error when a passphrase is manually set. 

**To Reproduce**
Set up the CLI as per normal:
```
% jfrog rt c
Artifactory server ID [loren]: ssh-test
JFrog Artifactory URL [http://localhost:8081/artifactory/]: ssh://localhost:1339
JFrog Distribution URL (Optional): 
SSH key file path (optional): /Users/loreny/.ssh/id_rsa_cli
loreny@loreny-mac logs %
```

Notice that it does not prompt for passphrase. Try to upload:
```
% jfrog rt upload log-test.log generic-local --server-id=ssh-test
 Log path: /Users/loreny/.jfrog/logs/jfrog-cli.2021-02-26.09-03-58.85835.log
{
  "status": "failure",
  "totals": {
    "success": 0,
    "failure": 0
  }
}
[Error] bcrypt_pbkdf: empty password
```

Fill in a password:
```
% jfrog rt upload log-test.log generic-local --server-id=ssh-test --ssh-passphrase XXXX
[Error] the --url option is mandatory
```

**Workaround**
In your jfrog-cli.conf, add in the passphrase as a key value pair in the appropriate section:
```
"sshPassPhrase": "<your password here>",
```

**Expected behaviour**
Upload to succeed when passing in just the server-id flag:
```
% jfrog rt upload log-test.log generic-local --server-id=ssh-test
 Log path: /Users/loreny/.jfrog/logs/jfrog-cli.2021-02-26.09-04-57.85843.log
{
  "status": "success",
  "totals": {
    "success": 1,
    "failure": 0
  }
}
```

**Versions**
- JFrog CLI version: 1.44.0
- JFrog CLI operating system: MacOS 11.2.1
- Artifactory Version: 7.12.8

**Comment by eyalbe4** [comment]
@lorenyeung,
Version 1.45.1 is released and includes @yahavi's fix for this issue. 
The fix was implemented as part of the new ```jfrog c add``` command. 
Looking forward to your feedback.

**Comment by lorenyeung** [comment]
sounds good, I tested it out and it works well for me; waiting for customer feedback.
