### ISSUE TITLE
getCli.sh bad globbing

### ISSUE THREAD

**Issue by G3zz** [jfrog/jfrog-cli#984]
The current version of `getCli.sh` fails with some implementations of curl when no version is specified because of the square brackets,`[RELEASE]`, in the URL to be fetched.

The internal call to `curl` needs to be amended to switch off the URL globbing parser by using the `-g, --globoff` flag.

**Comment by G3zz** [comment]
I see that a PR was merged today for this: https://github.com/jfrog/jfrog-cli/pull/983. Doesn't seem to have made its way to production yet though.

**Comment by eyalbe4** [comment]
Yes @G3zz - it is being deployed as we speak.

**Comment by yahavi** [comment]
@G3zz,
It should work now. 
Please let us know if you still see any issues with the getCli.

**Comment by eyalbe4** [comment]
@G3zz - 
Terribly sorry for inconvenience caused by this.
This should work now. Does it work on your end?

**Comment by G3zz** [comment]
@yahavi @eyalbe4 yes it works again now - thanks!
