### ISSUE TITLE
downloading from remote repo does not work

### ISSUE THREAD

**Issue by flupperdeflup** [jfrog/jfrog-cli#985]
We are trying to download a file from a remote repo using the CLI with the jfrog rt download command.
As a response we get:
{
  "status": "success",
  "totals": {
    "success": 0,
    "failure": 0
  }
}
But no file was downloaded. The CLI ping command works fine. When using curl we can download files from remote repos, just not when using the CLI.

**Versions**
- JFrog CLI version: latest version
- JFrog CLI operating system: Win10
- Artifactory Version: 7.10..2

**Comment by eyalbe4** [comment]
@flupperdeflup,
We're currently working on allowing the download command tondownlo

**Comment by bodziom777** [comment]
I also interested in. Is there any update?

**Comment by eyalbe4** [comment]
Yes @bodziom777 - 
This functionality requires changes on both Artifactory and JFrog CLI.
We're aiming to make the two releases available during April.

**Comment by eyalbe4** [comment]
@asafgabai has just created https://github.com/jfrog/jfrog-client-go/pull/320 which is currently being reviewed.

**Comment by Hellboy94520** [comment]
Hello ! I am also very interesting by this feature. Let us know when update will be availble.
Thank you

**Comment by asafgabai** [comment]
Hi,
Searching and downloading from remote repositories is now available on JFrog CLI 1.46.1.
It requires Artifactory 7.17 or higher.
To download artifacts also from remote repositories, set the following environment variable first:
JFROG_CLI_TRANSITIVE_DOWNLOAD_EXPERIMENTAL=true

**Comment by razeev1419** [comment]
Hi @asafgabai , When we are trying to download a folder or files from Artifactory using Jfrog CLI command 
`jf rt dl --url < > --access-token < > --target --output`. 
As a response we get  
`{
  "status": "success",
  "totals": {
    "success": 0,
    "failure": 0
  }
}`
But no files are being downloaded. 
It used to work for a while and suddenly it started showing the above response


- Versions
    - JFrog CLI version: 2.13
    - JFrog CLI operating system: Ubuntu
    - Artifactory Version: 6.23.41

**Comment by eyalbe4** [comment]
@razeev1419,
Do you have the *JFROG_CLI_TRANSITIVE_DOWNLOAD_EXPERIMENTAL* environment variable set to *true*?
Also, are you using Artifactory 7.17 or higher?
The above two are prerequisite for this functionality. Also note that the remote repository should proxy an Artifactory repository for this to work.

**Comment by razeev1419** [comment]
@eyalbe4 
- The above environment variable works with newer version of Artifactory, but we are having 6.23V. That's the reason why this functionality is not working for us?

- Also, could you please help me understand as we use enterprise version of jfrog artifactory repository, the downloading command should work for this repository right?

**Comment by eyalbe4** [comment]
@razeev1419,
The answer is yes to your two questions above.

**Comment by rpolocu** [comment]
Hello,

I'm running

 jf rt dl --spec Spec.json  --url <url-remote> --user <user> --password <password>

but i get an error

"message": "Could not find resource"

The JFROG_CLI_TRANSITIVE_DOWNLOAD_EXPERIMENTAL variable is set to true and the artifact version is 7.31.13 enterprice any ideas?

**Comment by eyalbe4** [comment]
Could it be that the repository path in your file spec isn't available or the user you used has no permissions to download from it @rpolocu?

**Comment by rpolocu** [comment]
Hello,

Regarding the above, I solved the problem. I was putting the repository name in --url for this reason it was failing

**Comment by eyalbe4** [comment]
Happy to hear this @rpolocu.
